<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 분할표 검정 | Statistical Analysis</title>
  <meta name="description" content="This is a Statistical Analysis" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 분할표 검정 | Statistical Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a Statistical Analysis" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 분할표 검정 | Statistical Analysis" />
  
  <meta name="twitter:description" content="This is a Statistical Analysis" />
  

<meta name="author" content="Jin Hyun Nam" />


<meta name="date" content="2023-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="nonpara.html"/>
<link rel="next" href="regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>머리말</a></li>
<li class="chapter" data-level="1" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>1</b> 평균차이 검정</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ttest.html"><a href="ttest.html#일표본-t-검정"><i class="fa fa-check"></i><b>1.1</b> 일표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ttest.html"><a href="ttest.html#with-r"><i class="fa fa-check"></i><b>1.1.1</b> With R</a></li>
<li class="chapter" data-level="1.1.2" data-path="ttest.html"><a href="ttest.html#with-sas"><i class="fa fa-check"></i><b>1.1.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ttest.html"><a href="ttest.html#독립표본-t-검정"><i class="fa fa-check"></i><b>1.2</b> 독립표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ttest.html"><a href="ttest.html#두-모분산-비의-검정"><i class="fa fa-check"></i><b>1.2.1</b> 두 모분산 비의 검정</a></li>
<li class="chapter" data-level="1.2.2" data-path="ttest.html"><a href="ttest.html#with-r-1"><i class="fa fa-check"></i><b>1.2.2</b> With R</a></li>
<li class="chapter" data-level="1.2.3" data-path="ttest.html"><a href="ttest.html#with-sas-1"><i class="fa fa-check"></i><b>1.2.3</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="ttest.html"><a href="ttest.html#대응표본-t-검정"><i class="fa fa-check"></i><b>1.3</b> 대응표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ttest.html"><a href="ttest.html#with-r-2"><i class="fa fa-check"></i><b>1.3.1</b> With R</a></li>
<li class="chapter" data-level="1.3.2" data-path="ttest.html"><a href="ttest.html#with-sas-2"><i class="fa fa-check"></i><b>1.3.2</b> with SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>2</b> 분산분석</a>
<ul>
<li class="chapter" data-level="2.1" data-path="anova.html"><a href="anova.html#분산분석"><i class="fa fa-check"></i><b>2.1</b> 분산분석</a></li>
<li class="chapter" data-level="2.2" data-path="anova.html"><a href="anova.html#일원배치-분산분석"><i class="fa fa-check"></i><b>2.2</b> 일원배치 분산분석</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="anova.html"><a href="anova.html#사후분석다중검정"><i class="fa fa-check"></i><b>2.2.1</b> 사후분석(다중검정)</a></li>
<li class="chapter" data-level="2.2.2" data-path="anova.html"><a href="anova.html#with-r-3"><i class="fa fa-check"></i><b>2.2.2</b> With R</a></li>
<li class="chapter" data-level="2.2.3" data-path="anova.html"><a href="anova.html#with-sas-3"><i class="fa fa-check"></i><b>2.2.3</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="anova.html"><a href="anova.html#이원배치-분산분석"><i class="fa fa-check"></i><b>2.3</b> 이원배치 분산분석</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="anova.html"><a href="anova.html#교호작용"><i class="fa fa-check"></i><b>2.3.1</b> 교호작용</a></li>
<li class="chapter" data-level="2.3.2" data-path="anova.html"><a href="anova.html#with-r-4"><i class="fa fa-check"></i><b>2.3.2</b> With R</a></li>
<li class="chapter" data-level="2.3.3" data-path="anova.html"><a href="anova.html#with-sas-4"><i class="fa fa-check"></i><b>2.3.3</b> With SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nonpara.html"><a href="nonpara.html"><i class="fa fa-check"></i><b>3</b> 비모수 검정</a>
<ul>
<li class="chapter" data-level="3.1" data-path="nonpara.html"><a href="nonpara.html#정규성-검정"><i class="fa fa-check"></i><b>3.1</b> 정규성 검정</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="nonpara.html"><a href="nonpara.html#with-r-5"><i class="fa fa-check"></i><b>3.1.1</b> With R</a></li>
<li class="chapter" data-level="3.1.2" data-path="nonpara.html"><a href="nonpara.html#with-sas-5"><i class="fa fa-check"></i><b>3.1.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="nonpara.html"><a href="nonpara.html#윌콕슨-부호순위-검정"><i class="fa fa-check"></i><b>3.2</b> 윌콕슨 부호순위 검정</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="nonpara.html"><a href="nonpara.html#with-r-6"><i class="fa fa-check"></i><b>3.2.1</b> With R</a></li>
<li class="chapter" data-level="3.2.2" data-path="nonpara.html"><a href="nonpara.html#with-sas-6"><i class="fa fa-check"></i><b>3.2.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="nonpara.html"><a href="nonpara.html#윌콕슨-순위합-검정"><i class="fa fa-check"></i><b>3.3</b> 윌콕슨 순위합 검정</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="nonpara.html"><a href="nonpara.html#with-r-7"><i class="fa fa-check"></i><b>3.3.1</b> With R</a></li>
<li class="chapter" data-level="3.3.2" data-path="nonpara.html"><a href="nonpara.html#with-sas-7"><i class="fa fa-check"></i><b>3.3.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="nonpara.html"><a href="nonpara.html#크루스칼-왈리스-검정"><i class="fa fa-check"></i><b>3.4</b> 크루스칼-왈리스 검정</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="nonpara.html"><a href="nonpara.html#with-r-8"><i class="fa fa-check"></i><b>3.4.1</b> With R</a></li>
<li class="chapter" data-level="3.4.2" data-path="nonpara.html"><a href="nonpara.html#with-sas-8"><i class="fa fa-check"></i><b>3.4.2</b> With SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="category.html"><a href="category.html"><i class="fa fa-check"></i><b>4</b> 분할표 검정</a>
<ul>
<li class="chapter" data-level="4.1" data-path="category.html"><a href="category.html#상대위험률과-오즈비"><i class="fa fa-check"></i><b>4.1</b> 상대위험률과 오즈비</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="category.html"><a href="category.html#상대위험률"><i class="fa fa-check"></i><b>4.1.1</b> 상대위험률</a></li>
<li class="chapter" data-level="4.1.2" data-path="category.html"><a href="category.html#오즈비"><i class="fa fa-check"></i><b>4.1.2</b> 오즈비</a></li>
<li class="chapter" data-level="4.1.3" data-path="category.html"><a href="category.html#with-r-9"><i class="fa fa-check"></i><b>4.1.3</b> With R</a></li>
<li class="chapter" data-level="4.1.4" data-path="category.html"><a href="category.html#with-sas-9"><i class="fa fa-check"></i><b>4.1.4</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="category.html"><a href="category.html#독립성-검정"><i class="fa fa-check"></i><b>4.2</b> 독립성 검정</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="category.html"><a href="category.html#with-r-10"><i class="fa fa-check"></i><b>4.2.1</b> With R</a></li>
<li class="chapter" data-level="4.2.2" data-path="category.html"><a href="category.html#with-sas-10"><i class="fa fa-check"></i><b>4.2.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="category.html"><a href="category.html#동질성-검정"><i class="fa fa-check"></i><b>4.3</b> 동질성 검정</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="category.html"><a href="category.html#with-r-11"><i class="fa fa-check"></i><b>4.3.1</b> With R</a></li>
<li class="chapter" data-level="4.3.2" data-path="category.html"><a href="category.html#with-sas-11"><i class="fa fa-check"></i><b>4.3.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="category.html"><a href="category.html#fisher의-정확-검정"><i class="fa fa-check"></i><b>4.4</b> Fisher의 정확 검정</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="category.html"><a href="category.html#with-r-12"><i class="fa fa-check"></i><b>4.4.1</b> With R</a></li>
<li class="chapter" data-level="4.4.2" data-path="category.html"><a href="category.html#with-sas-12"><i class="fa fa-check"></i><b>4.4.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="category.html"><a href="category.html#맥니마-검정"><i class="fa fa-check"></i><b>4.5</b> 맥니마 검정</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="category.html"><a href="category.html#이론적-배경"><i class="fa fa-check"></i><b>4.5.1</b> 이론적 배경</a></li>
<li class="chapter" data-level="4.5.2" data-path="category.html"><a href="category.html#with-r-13"><i class="fa fa-check"></i><b>4.5.2</b> With R</a></li>
<li class="chapter" data-level="4.5.3" data-path="category.html"><a href="category.html#with-sas-13"><i class="fa fa-check"></i><b>4.5.3</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="category.html"><a href="category.html#cochran-mantel-haenzel-test"><i class="fa fa-check"></i><b>4.6</b> Cochran-Mantel-Haenzel test</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="category.html"><a href="category.html#with-r-14"><i class="fa fa-check"></i><b>4.6.1</b> With R</a></li>
<li class="chapter" data-level="4.6.2" data-path="category.html"><a href="category.html#with-sas-14"><i class="fa fa-check"></i><b>4.6.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="category.html"><a href="category.html#진단법의-평가"><i class="fa fa-check"></i><b>4.7</b> 진단법의 평가</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="category.html"><a href="category.html#민감도와-특이도"><i class="fa fa-check"></i><b>4.7.1</b> 민감도와 특이도</a></li>
<li class="chapter" data-level="4.7.2" data-path="category.html"><a href="category.html#양성예측도와-음성예측도"><i class="fa fa-check"></i><b>4.7.2</b> 양성예측도와 음성예측도</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>5</b> 회귀분석</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression.html"><a href="regression.html#상관분석"><i class="fa fa-check"></i><b>5.1</b> 상관분석</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="regression.html"><a href="regression.html#상관계수"><i class="fa fa-check"></i><b>5.1.1</b> 상관계수</a></li>
<li class="chapter" data-level="5.1.2" data-path="regression.html"><a href="regression.html#스피어만-상관계수"><i class="fa fa-check"></i><b>5.1.2</b> 스피어만 상관계수</a></li>
<li class="chapter" data-level="5.1.3" data-path="regression.html"><a href="regression.html#켄달의-타우"><i class="fa fa-check"></i><b>5.1.3</b> 켄달의 타우</a></li>
<li class="chapter" data-level="5.1.4" data-path="regression.html"><a href="regression.html#편상관계수"><i class="fa fa-check"></i><b>5.1.4</b> 편상관계수</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="regression.html"><a href="regression.html#단순선형회귀분석"><i class="fa fa-check"></i><b>5.2</b> 단순선형회귀분석</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression.html"><a href="regression.html#최소제곱법"><i class="fa fa-check"></i><b>5.2.1</b> 최소제곱법</a></li>
<li class="chapter" data-level="5.2.2" data-path="regression.html"><a href="regression.html#회귀계수-추정"><i class="fa fa-check"></i><b>5.2.2</b> 회귀계수 추정</a></li>
<li class="chapter" data-level="5.2.3" data-path="regression.html"><a href="regression.html#회귀계수-가설검정"><i class="fa fa-check"></i><b>5.2.3</b> 회귀계수 가설검정</a></li>
<li class="chapter" data-level="5.2.4" data-path="regression.html"><a href="regression.html#결정계수"><i class="fa fa-check"></i><b>5.2.4</b> 결정계수</a></li>
<li class="chapter" data-level="5.2.5" data-path="regression.html"><a href="regression.html#예제"><i class="fa fa-check"></i><b>5.2.5</b> 예제</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression.html"><a href="regression.html#다중선형회귀분석"><i class="fa fa-check"></i><b>5.3</b> 다중선형회귀분석</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="regression.html"><a href="regression.html#변수-선택"><i class="fa fa-check"></i><b>5.3.1</b> 변수 선택</a></li>
<li class="chapter" data-level="5.3.2" data-path="regression.html"><a href="regression.html#결정계수-1"><i class="fa fa-check"></i><b>5.3.2</b> 결정계수</a></li>
<li class="chapter" data-level="5.3.3" data-path="regression.html"><a href="regression.html#표준화-회귀계수"><i class="fa fa-check"></i><b>5.3.3</b> 표준화 회귀계수</a></li>
<li class="chapter" data-level="5.3.4" data-path="regression.html"><a href="regression.html#다중공선성"><i class="fa fa-check"></i><b>5.3.4</b> 다중공선성</a></li>
<li class="chapter" data-level="5.3.5" data-path="regression.html"><a href="regression.html#더미변수가변수"><i class="fa fa-check"></i><b>5.3.5</b> 더미변수(가변수)</a></li>
<li class="chapter" data-level="5.3.6" data-path="regression.html"><a href="regression.html#회귀모형에-대한-가정-검토"><i class="fa fa-check"></i><b>5.3.6</b> 회귀모형에 대한 가정 검토</a></li>
<li class="chapter" data-level="5.3.7" data-path="regression.html"><a href="regression.html#예제-1"><i class="fa fa-check"></i><b>5.3.7</b> 예제</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>6</b> 일반화 선형모형</a>
<ul>
<li class="chapter" data-level="6.1" data-path="glm.html"><a href="glm.html#the-generalized-linear-models"><i class="fa fa-check"></i><b>6.1</b> The Generalized Linear models</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="glm.html"><a href="glm.html#the-general-linear-model"><i class="fa fa-check"></i><b>6.1.1</b> The General Linear Model</a></li>
<li class="chapter" data-level="6.1.2" data-path="glm.html"><a href="glm.html#generalized-linear-models-glms"><i class="fa fa-check"></i><b>6.1.2</b> Generalized Linear Models (GLMs)</a></li>
<li class="chapter" data-level="6.1.3" data-path="glm.html"><a href="glm.html#normal-glms-as-a-special-case"><i class="fa fa-check"></i><b>6.1.3</b> Normal GLMs as a Special Case</a></li>
<li class="chapter" data-level="6.1.4" data-path="glm.html"><a href="glm.html#modelling-binomial-data"><i class="fa fa-check"></i><b>6.1.4</b> Modelling Binomial Data</a></li>
<li class="chapter" data-level="6.1.5" data-path="glm.html"><a href="glm.html#modelling-poisson-data"><i class="fa fa-check"></i><b>6.1.5</b> Modelling Poisson Data</a></li>
<li class="chapter" data-level="6.1.6" data-path="glm.html"><a href="glm.html#transformation-vs.-glms"><i class="fa fa-check"></i><b>6.1.6</b> Transformation vs. GLMs</a></li>
<li class="chapter" data-level="6.1.7" data-path="glm.html"><a href="glm.html#exponential-family"><i class="fa fa-check"></i><b>6.1.7</b> Exponential Family</a></li>
<li class="chapter" data-level="6.1.8" data-path="glm.html"><a href="glm.html#canonical-links"><i class="fa fa-check"></i><b>6.1.8</b> Canonical Links</a></li>
<li class="chapter" data-level="6.1.9" data-path="glm.html"><a href="glm.html#estimation-of-the-model-parameters"><i class="fa fa-check"></i><b>6.1.9</b> Estimation of the Model Parameters</a></li>
<li class="chapter" data-level="6.1.10" data-path="glm.html"><a href="glm.html#distribution-and-link-function"><i class="fa fa-check"></i><b>6.1.10</b> Distribution and Link Function</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="glm.html"><a href="glm.html#medical-cost-data-analysis"><i class="fa fa-check"></i><b>6.2</b> Medical Cost Data Analysis</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="glm.html"><a href="glm.html#health-care-cost"><i class="fa fa-check"></i><b>6.2.1</b> health care cost</a></li>
<li class="chapter" data-level="6.2.2" data-path="glm.html"><a href="glm.html#regression-analysis-with-log-transformation"><i class="fa fa-check"></i><b>6.2.2</b> Regression analysis with log transformation</a></li>
<li class="chapter" data-level="6.2.3" data-path="glm.html"><a href="glm.html#gamma-generalized-linear-models"><i class="fa fa-check"></i><b>6.2.3</b> Gamma generalized linear models</a></li>
<li class="chapter" data-level="6.2.4" data-path="glm.html"><a href="glm.html#transformation-vs.-glms-1"><i class="fa fa-check"></i><b>6.2.4</b> Transformation vs. GLMs</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="glm.html"><a href="glm.html#binary-and-categorical-data-analysis"><i class="fa fa-check"></i><b>6.3</b> Binary and Categorical data Analysis</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="glm.html"><a href="glm.html#overview-of-logistic-regression-model"><i class="fa fa-check"></i><b>6.3.1</b> Overview of Logistic Regression Model</a></li>
<li class="chapter" data-level="6.3.2" data-path="glm.html"><a href="glm.html#binary-outcomes"><i class="fa fa-check"></i><b>6.3.2</b> Binary Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="glm.html"><a href="glm.html#poisson-regression"><i class="fa fa-check"></i><b>6.4</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="glm.html"><a href="glm.html#example-danish-lung-cancer-counts"><i class="fa fa-check"></i><b>6.4.1</b> Example: Danish Lung Cancer Counts</a></li>
<li class="chapter" data-level="6.4.2" data-path="glm.html"><a href="glm.html#what-about-accounting-for-population-size"><i class="fa fa-check"></i><b>6.4.2</b> What About Accounting for Population Size?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survival.html"><a href="survival.html"><i class="fa fa-check"></i><b>7</b> 생존분석</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survival.html"><a href="survival.html#생존분석"><i class="fa fa-check"></i><b>7.1</b> 생존분석</a></li>
<li class="chapter" data-level="7.2" data-path="survival.html"><a href="survival.html#비모수적-생존함수-추정"><i class="fa fa-check"></i><b>7.2</b> 비모수적 생존함수 추정</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="survival.html"><a href="survival.html#생명표-방법"><i class="fa fa-check"></i><b>7.2.1</b> 생명표 방법</a></li>
<li class="chapter" data-level="7.2.2" data-path="survival.html"><a href="survival.html#누적한계추정법"><i class="fa fa-check"></i><b>7.2.2</b> 누적한계추정법</a></li>
<li class="chapter" data-level="7.2.3" data-path="survival.html"><a href="survival.html#생존분포-비교"><i class="fa fa-check"></i><b>7.2.3</b> 생존분포 비교</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="survival.html"><a href="survival.html#모수적-생존함수-추정과-회귀모형"><i class="fa fa-check"></i><b>7.3</b> 모수적 생존함수 추정과 회귀모형</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="survival.html"><a href="survival.html#지수분포"><i class="fa fa-check"></i><b>7.3.1</b> 지수분포</a></li>
<li class="chapter" data-level="7.3.2" data-path="survival.html"><a href="survival.html#와이블분포"><i class="fa fa-check"></i><b>7.3.2</b> 와이블분포</a></li>
<li class="chapter" data-level="7.3.3" data-path="survival.html"><a href="survival.html#감마분포"><i class="fa fa-check"></i><b>7.3.3</b> 감마분포</a></li>
<li class="chapter" data-level="7.3.4" data-path="survival.html"><a href="survival.html#로그정규분포"><i class="fa fa-check"></i><b>7.3.4</b> 로그정규분포</a></li>
<li class="chapter" data-level="7.3.5" data-path="survival.html"><a href="survival.html#로그로지스틱분포"><i class="fa fa-check"></i><b>7.3.5</b> 로그로지스틱분포</a></li>
<li class="chapter" data-level="7.3.6" data-path="survival.html"><a href="survival.html#곰페르츠분포"><i class="fa fa-check"></i><b>7.3.6</b> 곰페르츠분포</a></li>
<li class="chapter" data-level="7.3.7" data-path="survival.html"><a href="survival.html#회귀모형aft"><i class="fa fa-check"></i><b>7.3.7</b> 회귀모형(AFT)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="survival.html"><a href="survival.html#cox-비례위험모형"><i class="fa fa-check"></i><b>7.4</b> Cox 비례위험모형</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="survival.html"><a href="survival.html#시간에-따라-변화하는-공변량이-있을-경우"><i class="fa fa-check"></i><b>7.4.1</b> 시간에 따라 변화하는 공변량이 있을 경우</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="survival.html"><a href="survival.html#경쟁위험모형"><i class="fa fa-check"></i><b>7.5</b> 경쟁위험모형</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="survival.html"><a href="survival.html#원인별-누적발생함수"><i class="fa fa-check"></i><b>7.5.1</b> 원인별 누적발생함수</a></li>
<li class="chapter" data-level="7.5.2" data-path="survival.html"><a href="survival.html#원인별-위험함수"><i class="fa fa-check"></i><b>7.5.2</b> 원인별 위험함수</a></li>
<li class="chapter" data-level="7.5.3" data-path="survival.html"><a href="survival.html#누적발생함수에-대한-회귀분석"><i class="fa fa-check"></i><b>7.5.3</b> 누적발생함수에 대한 회귀분석</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="survival.html"><a href="survival.html#sas-실습"><i class="fa fa-check"></i><b>7.6</b> SAS 실습</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="survival.html"><a href="survival.html#생명표-방법-1"><i class="fa fa-check"></i><b>7.6.1</b> 생명표 방법</a></li>
<li class="chapter" data-level="7.6.2" data-path="survival.html"><a href="survival.html#누적한계추정법-1"><i class="fa fa-check"></i><b>7.6.2</b> 누적한계추정법</a></li>
<li class="chapter" data-level="7.6.3" data-path="survival.html"><a href="survival.html#생존분포-비교-1"><i class="fa fa-check"></i><b>7.6.3</b> 생존분포 비교</a></li>
<li class="chapter" data-level="7.6.4" data-path="survival.html"><a href="survival.html#parametric-model"><i class="fa fa-check"></i><b>7.6.4</b> Parametric Model</a></li>
<li class="chapter" data-level="7.6.5" data-path="survival.html"><a href="survival.html#aft-model"><i class="fa fa-check"></i><b>7.6.5</b> AFT model</a></li>
<li class="chapter" data-level="7.6.6" data-path="survival.html"><a href="survival.html#cox-비례위험모형-1"><i class="fa fa-check"></i><b>7.6.6</b> Cox 비례위험모형</a></li>
<li class="chapter" data-level="7.6.7" data-path="survival.html"><a href="survival.html#cox-비례위험모형---time-dependent-covariate"><i class="fa fa-check"></i><b>7.6.7</b> Cox 비례위험모형 - time dependent covariate</a></li>
<li class="chapter" data-level="7.6.8" data-path="survival.html"><a href="survival.html#competing-risks"><i class="fa fa-check"></i><b>7.6.8</b> Competing Risks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="psm.html"><a href="psm.html"><i class="fa fa-check"></i><b>8</b> 성향점수(propensity score)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="psm.html"><a href="psm.html#observational-study"><i class="fa fa-check"></i><b>8.1</b> Observational Study?</a>
<ul>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#randomized-controlled-trials-gold-standard"><i class="fa fa-check"></i>Randomized Controlled Trials ("gold standard")</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#characteristics-of-rcts"><i class="fa fa-check"></i>Characteristics of RCTs</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#what-is-observational-data"><i class="fa fa-check"></i>What is Observational Data?</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#confounding-due-to-selection-bias"><i class="fa fa-check"></i>Confounding due to Selection Bias</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#impact-of-selection-bias-on-analytic-inferences"><i class="fa fa-check"></i>Impact of Selection Bias on Analytic Inferences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#statistical-adjustment-for-observational-data"><i class="fa fa-check"></i>Statistical Adjustment for Observational Data</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#addressing-selection-bias-with-exact-matching"><i class="fa fa-check"></i>Addressing Selection Bias with Exact Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-on-specific-variables"><i class="fa fa-check"></i>Matching on Specific Variables</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-on-specific-variables-1"><i class="fa fa-check"></i>Matching on Specific Variables</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="psm.html"><a href="psm.html#propensity-score"><i class="fa fa-check"></i><b>8.2</b> Propensity Score?</a>
<ul>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#general-procedure"><i class="fa fa-check"></i>General Procedure</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#choosing-variables-for-propensity-scores"><i class="fa fa-check"></i>Choosing Variables for Propensity Scores</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#calculate-propensity-score"><i class="fa fa-check"></i>Calculate Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#initial-checks-balance-across-groups"><i class="fa fa-check"></i>Initial Checks: Balance across Groups</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#check-balance-of-covariates"><i class="fa fa-check"></i>Check Balance of Covariates</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#assess-balance-with-standardized-differences"><i class="fa fa-check"></i>Assess Balance with Standardized Differences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#balance-of-covariates-caution"><i class="fa fa-check"></i>Balance of Covariates: Caution</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-and-weighting-strategies"><i class="fa fa-check"></i>Matching and Weighting Strategies</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#choices-when-matching-sample-by-propensity-score"><i class="fa fa-check"></i>Choices When Matching Sample by Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#which-strategy-to-chooose"><i class="fa fa-check"></i>Which Strategy to Chooose?</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#evaluate-balance-in-sample-matched-or-weighted"><i class="fa fa-check"></i>Evaluate Balance in Sample Matched or Weighted</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#visualization-of-standardized-differences"><i class="fa fa-check"></i>Visualization of Standardized Differences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#plots-of-covariates-between-groups"><i class="fa fa-check"></i>Plots of Covariates between Groups</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="psm.html"><a href="psm.html#propensity-score-methods"><i class="fa fa-check"></i><b>8.3</b> Propensity Score Methods</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="psm.html"><a href="psm.html#propensity-score-matching"><i class="fa fa-check"></i><b>8.3.1</b> Propensity Score Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#general-procedure-for-propensity-score-matching"><i class="fa fa-check"></i>General Procedure for Propensity Score Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#greedy-matching"><i class="fa fa-check"></i>Greedy Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#mahalanobis-metric-matching"><i class="fa fa-check"></i>Mahalanobis Metric Matching</a></li>
<li class="chapter" data-level="8.3.2" data-path="psm.html"><a href="psm.html#stratification-using-propensity-score"><i class="fa fa-check"></i><b>8.3.2</b> Stratification using Propensity Score</a></li>
<li class="chapter" data-level="8.3.3" data-path="psm.html"><a href="psm.html#inverse-probability-of-treatment-weighting"><i class="fa fa-check"></i><b>8.3.3</b> Inverse Probability of Treatment Weighting</a></li>
<li class="chapter" data-level="8.3.4" data-path="psm.html"><a href="psm.html#propensity-score-adjustment-as-covariate"><i class="fa fa-check"></i><b>8.3.4</b> Propensity Score Adjustment as Covariate</a></li>
<li class="chapter" data-level="8.3.5" data-path="psm.html"><a href="psm.html#property-of-propensity-score"><i class="fa fa-check"></i><b>8.3.5</b> Property of Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#property-of-observational-studies"><i class="fa fa-check"></i>Property of Observational Studies</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="psm.html"><a href="psm.html#practice---sas"><i class="fa fa-check"></i><b>8.4</b> Practice - SAS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="psm.html"><a href="psm.html#greedy-nearest-neighbor-matching"><i class="fa fa-check"></i><b>8.4.1</b> Greedy Nearest Neighbor Matching</a></li>
<li class="chapter" data-level="8.4.2" data-path="psm.html"><a href="psm.html#propensity-score-stratification"><i class="fa fa-check"></i><b>8.4.2</b> Propensity Score Stratification</a></li>
<li class="chapter" data-level="8.4.3" data-path="psm.html"><a href="psm.html#inverse-probability-treatment-weighting"><i class="fa fa-check"></i><b>8.4.3</b> Inverse Probability Treatment Weighting</a></li>
<li class="chapter" data-level="8.4.4" data-path="psm.html"><a href="psm.html#matching-with-existing-propensity-scores"><i class="fa fa-check"></i><b>8.4.4</b> Matching with Existing propensity scores</a></li>
<li class="chapter" data-level="8.4.5" data-path="psm.html"><a href="psm.html#matching-with-existing-propensity-scores-1"><i class="fa fa-check"></i><b>8.4.5</b> Matching with Existing propensity scores</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="category" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> 분할표 검정<a href="category.html#category" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ul>
<li><p>두 범주형(명목형, 순서형) 변수간의 연관 관계(association)를 볼 때
분할표(교차표)를 작성하여 변수들간 관계를 분석</p></li>
<li><p>독립성 검정, 동질성 검정, 교차 분석 혹은 카이제곱검정(chi-square test) 이라고 함</p></li>
<li><p>분할표(교차표)의 의미는 두 변수의 빈도 표(frequency table)를 교차시켰다는
의미이며, 교차 분석에 사용되는 검정 통계량이 <span class="math inline">\(\chi^2\)</span> 분포를 따르기
때문에 카이제곱검정이라 함</p></li>
<li><p>교차표(cross-tabulation, 분할표: contingency table)는 각 범주형
변수에 대한 빈도표를 행과 열로 결합시켜 놓은 형태</p></li>
<li><p>일반적으로 분할표는 행에는 설명(독립) 변수에 해당되는 변수를 열에는
반응(종속) 변수를 놓음</p></li>
<li><p><span class="math inline">\(r \times c\)</span> 분할표</p>
<p><img src="category/f1.jpg" style="width:90.0%" /></p></li>
<li><p>변수 <span class="math inline">\(A: r\)</span>개 범주, 변수 <span class="math inline">\(B: c\)</span>개 범주</p></li>
<li><p>전체 <span class="math inline">\(n\)</span>회의 독립적인 실험을 반복 결과 <span class="math inline">\(A\)</span>의 <span class="math inline">\(i\)</span>번째 범주와 <span class="math inline">\(B\)</span>의
<span class="math inline">\(j\)</span>번째 범주에 속하는 시행횟수는
<span class="math inline">\(n_{ij}(i=1,\ldots,r, j=1,\ldots,c)\)</span>, <span class="math inline">\(n_{i.}=\sum_{j=1}^cn_{ij}\)</span>,
<span class="math inline">\(n_{.j}=\sum_{i=1}^rn_{ij}\)</span>,
<span class="math inline">\(n=\sum_{i=1}^rn_{i.}=\sum_{j=1}^cn_{.j}\)</span>.</p></li>
<li><p><span class="math inline">\(A\)</span>의 <span class="math inline">\(i\)</span>번째 범주와 <span class="math inline">\(B\)</span>의 <span class="math inline">\(j\)</span>번째 범주의 결과가 발생할 확률은
<span class="math inline">\(p_{ij}(i=1,\ldots,r, j=1,\ldots,c)\)</span>, <span class="math inline">\(p_{i.}=\sum_{j=1}^cn_{ij}\)</span>,
<span class="math inline">\(p_{.j}=\sum_{i=1}^rp_{ij}\)</span>,
<span class="math inline">\(1=\sum_{i=1}^rp_{i.}=\sum_{j=1}^cp_{.j}\)</span>.</p></li>
</ul>
<div id="상대위험률과-오즈비" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> 상대위험률과 오즈비<a href="category.html#상대위험률과-오즈비" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>요인과 결과가 각각 두 개의 범주로 나누어진 분할표 (<span class="math inline">\(2\times 2\)</span> contingency
table) 자료의 경우, 연관성을 나타내는 측도로서 주로 사용되는 것은
상대 위험률(relative risk)과 오즈비(odds ratio, 교차비)임</p></li>
<li><p><span class="math inline">\(2\times 2\)</span> 분할표</p></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">그룹 / 결과</th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(n_{11}(p_{11})\)</span></td>
<td align="center"><span class="math inline">\(n_{12}(p_{12})\)</span></td>
<td align="center"><span class="math inline">\(n_{1+}(p_{1+})\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center"><span class="math inline">\(n_{21}(p_{21})\)</span></td>
<td align="center"><span class="math inline">\(n_{22}(p_{22})\)</span></td>
<td align="center"><span class="math inline">\(n_{2+}(p_{2+})\)</span></td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center"><span class="math inline">\(n_{+1}(p_{+1})\)</span></td>
<td align="center"><span class="math inline">\(n_{+2}(p_{+2})\)</span></td>
<td align="center"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Let <span class="math inline">\(X\)</span>: row classification variable and <span class="math inline">\(Y\)</span>: column classification variable.</p>
<div id="상대위험률" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> 상대위험률<a href="category.html#상대위험률" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>상대위험률(Relative Risk: RR)</li>
</ul>
<p><span class="math display">\[RR=\frac{\text{실험군에서의 위험률}}{\text{대조군에서의 위험률}}= \frac{\pi_{1|1}}{\pi_{1|2}}=\frac{\pi_{11}/\pi_{1+}}{\pi_{21}/\pi_{2+}}\]</span></p>
<ul>
<li>상대위험률 추정량</li>
</ul>
<p><span class="math display">\[
\hat{RR} = \frac{n_{11}/n_{1+}}{n_{21}/n_{2+}}
\]</span></p>
<p>Note: <span class="math inline">\(RR=1\)</span> then <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</p>
<ul>
<li><p>상대위험률은 <span class="math inline">\(\{n_{1+}\}\)</span>와 <span class="math inline">\(\{n_{2+}\}\)</span>처럼 행 합계가 고정(fixed)된 코호트 연구(cohort study)나 실험군과 대조군이 사전에 정해지고 난 후 그 결과를 관찰하게 되는 임상시험(clinical trials) 연구에서 사용됨</p></li>
<li><p>상대위험률의 신뢰구간</p>
<ul>
<li><p><span class="math inline">\(log RR\)</span>의 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간: <span class="math inline">\((log\hat{RR}-z_{\alpha/2}\hat{\sigma}(log\hat{RR}),log\hat{RR}+z_{\alpha/2}\hat{\sigma}(log\hat{RR}))\)</span></p></li>
<li><p>여기서 <span class="math inline">\(z_{\alpha/2}\)</span>는 정규분포의 상위 <span class="math inline">\({\alpha/2}\)</span>에 해당하는 임계값, <span class="math inline">\(\hat{\sigma}^2(log\hat{RR})\)</span>은 <span class="math inline">\(log\hat{RR}\)</span>의 분산추정량임</p></li>
<li><p><span class="math inline">\(log\hat{RR}\)</span>의 분산추정량</p></li>
</ul></li>
</ul>
<p><span class="math display">\[
\hat{\sigma}^2(log\hat{RR})=\frac{1-n_{11}/n_{1+}}{n_{1+}}+\frac{1-n_{21}/n_{2+}}{n_{21}}=\frac{1}{n_{11}}-\frac{1}{n_{1+}}+\frac{1}{n_{21}}-\frac{1}{n_{2+}}
\]</span></p>
<blockquote>
<p>따라서 <span class="math inline">\(RR\)</span>의 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간은 <span class="math inline">\(logRR\)</span>의 신뢰구간의 상한과 하한에 exp를 취하면 됨</p>
</blockquote>
<p>예제) 소량의 아스피린(aspirin) 복용이 심장병으로 인한 위험을 줄이는 데 효과가 있는지를 알아보고자 하였다. 22,071명의 남성을 확률화를 통해 두 그룹으로 나눈 후, 한 그룹에는 저용량(325 mg/일)의 아스피린을 복용시키고 다른 그룹에는 플라시보(placebo)를 복용하게 한 후 약 60개월간 관찰하여 심근경색(myocardial infarction)을 일으키는지 여부를 관찰하였다. 아스피린의 복용여부와 심근경색간의 연관성이 어느 정도인지 알아보자.</p>
<table>
<thead>
<tr class="header">
<th align="center">그룹 / 결과</th>
<th align="center">MI Yes</th>
<th align="center">MI No</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Aspirin</td>
<td align="center">139</td>
<td align="center">10,898</td>
<td align="center">11,037</td>
</tr>
<tr class="even">
<td align="center">Placebo</td>
<td align="center">239</td>
<td align="center">10,795</td>
<td align="center">11,034</td>
</tr>
</tbody>
</table>
<p>풀이)
<span class="math display">\[
\hat{RR}=\frac{139/11037}{239/11034}=\frac{0.0126}{0.0217}=0.581
\]</span></p>
<p>The proportion suffering heart attacks was 0.58 times higher for those taking aspirin than for those taking placebo. That is, the proportion suffering heart attacks was 1.72 times higher for those taking placebo than for those taking aspirin.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="category.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb1-2"><a href="category.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="category.html#cb1-3" aria-hidden="true" tabindex="-1"></a>aspirin <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">10795</span>,<span class="dv">10898</span>,<span class="dv">239</span>,<span class="dv">139</span>),<span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb1-4"><a href="category.html#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="category.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio.wald</span>(aspirin)</span></code></pre></div>
<pre><code>## $data
##           Outcome
## Predictor  Disease1 Disease2 Total
##   Exposed1    10795      239 11034
##   Exposed2    10898      139 11037
##   Total       21693      378 22071
## 
## $measure
##           risk ratio with 95% C.I.
## Predictor   estimate     lower     upper
##   Exposed1 1.0000000        NA        NA
##   Exposed2 0.5814319 0.4725282 0.7154346
## 
## $p.value
##           two-sided
## Predictor    midp.exact fisher.exact  chi.square
##   Exposed1           NA           NA          NA
##   Exposed2 1.858802e-07 1.878482e-07 2.09472e-07
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;Unconditional MLE &amp; normal approximation (Wald) CI&quot;</code></pre>
<p><br></p>
</div>
<div id="오즈비" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> 오즈비<a href="category.html#오즈비" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>오즈비(Odds ratio, OR, 승산비, 교차비)</p>
<p><span class="math display">\[OR=\frac{\text{처리 그룹에서 사건 발생 확률/처리 그룹에서 사건이 발생하지 않을 확률}}{\text{대조 그룹에서 사건 발생 확률/대조 그룹에서 사건이 발생하지 않을 확률}}\]</span></p></li>
<li><p>오즈(odds)</p>
<p><span class="math display">\[\frac{\text{처리 그룹에서 사건 발생 확률}}{\text{처리 그룹에서 사건이 발생하지 않을 확률}}\]</span></p>
<ul>
<li><p>그룹 1에서 2열에 대한 1열의 발생 odds는 <span class="math inline">\(\Omega_1 = \pi_{1|1}/\pi_{2|1}=\frac{\pi_{11}/\pi_{1+}}{\pi_{12}/\pi_{1+}}=\pi_{11}/\pi_{12}\)</span></p></li>
<li><p>그룹 2의 odds는 <span class="math inline">\(\Omega_2 = \pi_{1|2}/\pi_{2|2}=\pi_{21}/\pi_{22}\)</span></p></li>
</ul></li>
<li><p>Odds Ratio (OR)</p></li>
</ul>
<p><span class="math display">\[
OR = \Omega_1 / \Omega_2 = \frac{\pi_{11}/\pi_{12}}{\pi_{21}/\pi_{22}}
\]</span></p>
<ul>
<li>오즈비 추정량</li>
</ul>
<p><span class="math display">\[
\hat{OR}=\frac{n_{11}/n_{12}}{n_{21}/n_{22}}=\frac{n_{11}n_{22}}{n_{12}n_{21}}
\]</span></p>
<p>Note: <span class="math inline">\(OR=1\)</span> then <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</p>
<ul>
<li><p>오즈비는 사례-대조 연구(case-control study)에서 이용 됨</p></li>
<li><p><span class="math inline">\(1&lt;OR&lt;\infty\)</span>: subjects in row 1 are more likely to make the first response than are subjects in row 2.</p></li>
<li><p><span class="math inline">\(OR=4\)</span>: the odds of the first response are four times higher in row 1 than in row 2.</p></li>
<li><p><span class="math inline">\(0&lt;OR&lt;1\)</span>: the first response is less likely in row1 than in row 2.</p></li>
<li><p>상대위험률과 오즈비</p></li>
</ul>
<p><span class="math display">\[
OR = RR(\frac{1-\pi_{1|2}}{1-\pi_{1|1}})
\]</span></p>
<p><span class="math inline">\(OR \approx RR\)</span> whenever the probability of response 1 is colose to zero for both groups.</p>
<ul>
<li>오즈비의 신뢰구간
<ul>
<li><p><span class="math inline">\(log OR\)</span>의 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간: <span class="math inline">\((log\hat{OR}-z_{\alpha/2}\hat{\sigma}(log\hat{OR}),log\hat{OR}+z_{\alpha/2}\hat{\sigma}(log\hat{OR}))\)</span></p></li>
<li><p>여기서 <span class="math inline">\(z_{\alpha/2}\)</span>는 정규분포의 상위 <span class="math inline">\({\alpha/2}\)</span>에 해당하는 임계값, <span class="math inline">\(\hat{\sigma}^2(log\hat{OR})\)</span>은 <span class="math inline">\(log\hat{OR}\)</span>의 분산추정량임</p></li>
<li><p><span class="math inline">\(log\hat{OR}\)</span>의 분산추정량</p></li>
</ul></li>
</ul>
<p><span class="math display">\[
\hat{\sigma}^2(log\hat{OR})=\frac{1}{n_{11}}+\frac{1}{n_{12}}+\frac{1}{n_{21}}+\frac{1}{n_{22}}
\]</span></p>
<blockquote>
<p>따라서 <span class="math inline">\(OR\)</span>의 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간은 <span class="math inline">\(logOR\)</span>의 신뢰구간의 상한과 하한에 exp를 취하면 됨</p>
</blockquote>
<p>예제) 다음은 심장발작을 일으킨 환자와 그렇지 않은 사람들을 각각 214명씩 조사하여 그들이 과거에 약물남용을 한 경력이 있는지 여부를 조사한 사례-대조 연구로부터 얻은 자료이다. 약물남용과 심장발작의 연관성이 어느 정도인지 알아보자.</p>
<table>
<thead>
<tr class="header">
<th align="center">그룹 / 결과</th>
<th align="center">심장발작 Yes</th>
<th align="center">심장발작 No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">약물남용 Yes</td>
<td align="center">73</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">약물남용 No</td>
<td align="center">141</td>
<td align="center">196</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">214</td>
<td align="center">214</td>
</tr>
</tbody>
</table>
<p>풀이)</p>
<ul>
<li><p>약물남용인 그룹에서의 심장발작이 일어날 odds는 73/18=4.06이다.
odds 4.06의 의미는 약물남용그룹에서 심장발작이 일어나지 않은 100명에 대해 심장발작이 발생한 사람은 406명이 된다는 것이다. There were 406 “yes” (i.e., MI) outcomes for every 100 “no” outcomes.</p></li>
<li><p>약물남용하지 않은 그룹에서의 심장발작이 일어날 odds는 141/96=0.719.
마찬가지로 odds 0.719의 의미는 약물남용하지 않은 그룹에서 심장발작이 일어나지 않은 100명에 대해 심장발작이 발생 한 사람은 71.9명이 된다는 것이다.
따라서 OR=4.06/0.719=5.64이다.</p></li>
</ul>
<p><span class="math display">\[
\hat{RR}=\frac{73/18}{141/196}=\frac{73\times 196}{18\times 141}=5.64
\]</span></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="category.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(epitools)</span></span>
<span id="cb3-2"><a href="category.html#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="category.html#cb3-3" aria-hidden="true" tabindex="-1"></a>oddsr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">196</span>,<span class="dv">18</span>,<span class="dv">141</span>,<span class="dv">73</span>),<span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb3-4"><a href="category.html#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="category.html#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio.wald</span>(oddsr)</span></code></pre></div>
<pre><code>## $data
##           Outcome
## Predictor  Disease1 Disease2 Total
##   Exposed1      196      141   337
##   Exposed2       18       73    91
##   Total         214      214   428
## 
## $measure
##           odds ratio with 95% C.I.
## Predictor  estimate    lower    upper
##   Exposed1  1.00000       NA       NA
##   Exposed2  5.63751 3.222266 9.863094
## 
## $p.value
##           two-sided
## Predictor    midp.exact fisher.exact   chi.square
##   Exposed1           NA           NA           NA
##   Exposed2 3.393463e-11 5.794293e-11 8.164427e-11
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;Unconditional MLE &amp; normal approximation (Wald) CI&quot;</code></pre>
<p>예제) 다음은 당뇨 환자 <span class="math inline">\(25\)</span>명과 당뇨가 없는 정상인 <span class="math inline">\(75\)</span>명을 대상으로 비만
유무를 조사한 결과이다. 비만과 정상 체중에 대해 당뇨의 상대위험률과
오즈비를 산출하라.</p>
<p><img src="category/ex2.jpg" style="width:100.0%" /></p>
</div>
<div id="with-r-9" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> With R<a href="category.html#with-r-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="category.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(epitools)</span></span>
<span id="cb5-2"><a href="category.html#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="category.html#cb5-3" aria-hidden="true" tabindex="-1"></a>example <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">10</span>),<span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb5-4"><a href="category.html#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="category.html#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio.wald</span>(example)</span></code></pre></div>
<pre><code>## $data
##           Outcome
## Predictor  Disease1 Disease2 Total
##   Exposed1       65       15    80
##   Exposed2       10       10    20
##   Total          75       25   100
## 
## $measure
##           risk ratio with 95% C.I.
## Predictor  estimate    lower    upper
##   Exposed1 1.000000       NA       NA
##   Exposed2 2.666667 1.416591 5.019874
## 
## $p.value
##           two-sided
## Predictor   midp.exact fisher.exact  chi.square
##   Exposed1          NA           NA          NA
##   Exposed2 0.007513782  0.007783054 0.003892417
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;Unconditional MLE &amp; normal approximation (Wald) CI&quot;</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="category.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio.wald</span>(example)</span></code></pre></div>
<pre><code>## $data
##           Outcome
## Predictor  Disease1 Disease2 Total
##   Exposed1       65       15    80
##   Exposed2       10       10    20
##   Total          75       25   100
## 
## $measure
##           odds ratio with 95% C.I.
## Predictor  estimate    lower    upper
##   Exposed1 1.000000       NA       NA
##   Exposed2 4.333333 1.530248 12.27107
## 
## $p.value
##           two-sided
## Predictor   midp.exact fisher.exact  chi.square
##   Exposed1          NA           NA          NA
##   Exposed2 0.007513782  0.007783054 0.003892417
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;Unconditional MLE &amp; normal approximation (Wald) CI&quot;</code></pre>
</div>
<div id="with-sas-9" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> With SAS<a href="category.html#with-sas-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data odds;
input fat diabet count @@;
cards;
1   1   10
1   2   10
2   1   15
2   2   65
;
run;

proc freq data=odds;
weight count;
table fat*diabet/norow nopercent measures;
run;</code></pre>
<p><img src="category/ex4.jpg" style="width:30.0%" /></p>
<p><img src="category/ex5.jpg" style="width:50.0%" /></p>
<p>결과를 살펴보면 오즈비는 4.3, 상대위험률은 2.7로 정상체중보다 비만에서 당뇨가 더 높게 나타난다는 것을 알 수 있다.</p>
</div>
</div>
<div id="독립성-검정" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> 독립성 검정<a href="category.html#독립성-검정" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>두 범주형 변수간 독립인지 아닌지(연관성이 있는지 없는지)를 살펴보는
검정을 독립성 검정(test of independence)이라 함</p></li>
<li><p><span class="math inline">\(p_{ij}\)</span>를 한 관측값이 범주 <span class="math inline">\((A_i, B_j)\)</span>에 속할 확률이라 하고,
<span class="math inline">\(p_{i.}\)</span>을 한 관측값이 변수 <span class="math inline">\(A\)</span>의 <span class="math inline">\(i\)</span>번째 범수에 속할 주변확률,
<span class="math inline">\(p_{.j}\)</span>를 변수 <span class="math inline">\(B\)</span>의 <span class="math inline">\(j\)</span>번째 범수에 속할 주변확률이라고 하면,
확률이론에 의해 두 변수 <span class="math inline">\(A\)</span>와 <span class="math inline">\(B\)</span>가 독립일 필요충분조건은 모든
<span class="math inline">\((i,j)\)</span>쌍에 대해 <span class="math inline">\(p_{ij}=p_{i.}p_{.j}\)</span> 임</p></li>
<li><p>독립성 검정 가설</p>
<ul>
<li><p><span class="math inline">\(H_0 : p_{ij}=p_{i.}p_{.j},\quad i=1,\ldots,r,\quad j=1,\ldots,c\)</span>
(두 변수는 독립이다)</p></li>
<li><p><span class="math inline">\(H_1 : p_{ij} \ne p_{i.}p_{.j},\quad i=1,\ldots,r,\quad j=1,\ldots,c\)</span>
(두 변수는 연관성이 있다)</p></li>
</ul></li>
<li><p>검정 통계량
<span class="math display">\[T=\sum_{i=1}^r\sum_{j=1}^c \frac{(n_{ij}-\hat{e}_{ij})^2}{\hat{e}_{ij}}\sim \chi^2((r-1)(c-1))\]</span></p></li>
</ul>
<p>여기서 <span class="math inline">\(\hat{e}_{ij}=n_{i.}n_{.j}/n\)</span>이며, 이를 추정된
기대빈도(expected frequency)라 함</p>
<ul>
<li><p>검정통계량의 의미 : 만약 두 변수가 독립이라면 기대빈도 <span class="math inline">\(e_{ij}\)</span>는
관측빈도 <span class="math inline">\(n_{ij}\)</span>와 같아야하고 <span class="math inline">\(T\)</span> 값은 <span class="math inline">\(0\)</span>이 되어야 함. 즉 <span class="math inline">\(T\)</span>가
<span class="math inline">\(0\)</span>에 가까우면 두 변수는 관계가 없다고 결론 내릴 수 있음</p></li>
<li><p>기각역 <span class="math display">\[T &gt; \chi^2_{\alpha, (r-1)(c-1)}\]</span></p></li>
<li><p>기대 빈도 5 미만 문제</p>
<ul>
<li>교차분석 검정 통계량은 근사적으로 <span class="math inline">\(\chi^2\)</span> 분포를 따르지만, 근사
조건으로 각 셀의 기대 빈도가 5 이상이어야 함</li>
</ul></li>
</ul>
<ol style="list-style-type: decimal">
<li><p>기대 빈도가 5미만인 셀의 비율이 <span class="math inline">\(20\%\)</span>를 넘으면 계산된 검정
통계량은 <span class="math inline">\(\chi^2\)</span> 분포로 근사하지 않으므로 표본크기 <span class="math inline">\(n\)</span>을 키운다.</p></li>
<li><p>변수의 수준을 합쳐 셀의 수를 줄인다.</p></li>
<li><p>Fisher의 정확 검정(Fisher’s exact test)를 시행한다.</p></li>
</ol>
<p>예제) 소량의 아스피린(aspirin) 복용이 심장병으로 인한 위험률을 줄이는 데
효과가 있는지를 알아보고자 하였다. <span class="math inline">\(22,071\)</span>명의 남성을 확률화를 통해 두
그룹으로 나눈 후, 한 그룹에는 저용량(<span class="math inline">\(325mg\)</span>/일)의 아스피린을 복용시키고
다른 그룹에는 플라시보(placebo)를 복용하게 한 후 약 60개월간 관찰하여
심근경색(myocardial infarction)을 일으키는지 여부를 관찰하였다.
아스피린의 복용여부와 심근경색간의 연관성이 존재하는가?</p>
<p><img src="category/ex6.jpg" style="width:80.0%" /></p>
<div id="with-r-10" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> With R<a href="category.html#with-r-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="category.html#cb10-1" aria-hidden="true" tabindex="-1"></a>odds <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">139</span>,<span class="dv">239</span>,<span class="dv">10898</span>,<span class="dv">10795</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb10-2"><a href="category.html#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="category.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(odds, <span class="at">correct=</span>F)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  odds
## X-squared = 26.944, df = 1, p-value = 2.095e-07</code></pre>
<p>결과를 살펴보면, 아스피린 복용 유무와 심근경색 발생 유무에 대한 독립성 검정의 검정통계량은 26.94, P-value는 &lt;.0001로 유의수준 5%하에서 유의하다. 따라서 아스피린 복용 유무와 심근경색 발생 유무는 서로 관련이 있다고 할 수 있다.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="category.html#cb12-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="dv">139</span><span class="sc">*</span><span class="dv">10795</span><span class="sc">/</span><span class="dv">10898</span><span class="sc">/</span><span class="dv">239</span></span>
<span id="cb12-2"><a href="category.html#cb12-2" aria-hidden="true" tabindex="-1"></a>OR</span></code></pre></div>
<pre><code>## [1] 0.5760932</code></pre>
<p>OR 값은 0.58로 아스피린을 복용한 집단의 심근경색 발생율이 아스피린을 복용하지 않은 집단의 심금경색 발생율의 0.58배로 낮다는 것을 알 수 있다.</p>
</div>
<div id="with-sas-10" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> With SAS<a href="category.html#with-sas-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data odds;
input aspirin   mi  count @@;
cards;
1   1   139
1   0   10898
0   1   239
0   0   10795
;
run;

proc freq data=odds order=data;
weight count;
table aspirin*mi/norow nocol all;
run;</code></pre>
<p><img src="category/ex8.jpg" style="width:40.0%" /></p>
<p><img src="category/ex9.jpg" style="width:80.0%" /></p>
</div>
</div>
<div id="동질성-검정" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> 동질성 검정<a href="category.html#동질성-검정" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>독립성 검정 문제와 비슷한 개념으로 동질성 검정(test of
homogeneity)이 있음</p></li>
<li><p><span class="math inline">\(r \times c\)</span> 분할표에서 <span class="math inline">\(A_1, \ldots, A_r\)</span>은 요인 <span class="math inline">\(A\)</span>의
부차모집단(subpopulation)으로 간주하고, 각 부차모집단에서 <span class="math inline">\(B\)</span>의
범주인 <span class="math inline">\((B_1, \ldots, B_c)\)</span>가 동질적인지 검정하는 방법</p></li>
<li><p>실험의 경우 <span class="math inline">\(r\)</span>개의 비슷한 실험 <span class="math inline">\(A_1, \ldots, A_r\)</span>을 시행할 때
이들이 동질적인 실험의 형태로 나타나는가를 알아보기 위해 반응 <span class="math inline">\(B\)</span>의
각 수준에 대한 도수를 관측하여 동질성 여부를 검증할 때 시행</p></li>
<li><p>독립성 검정과 독립성 검정의 차이는 독립성 검정에서는 총 시행횟수
<span class="math inline">\(n\)</span>이 고정되는 반면, 동질성 검정은 <span class="math inline">\(A\)</span>의 각 부차모집단인
<span class="math inline">\(A_1, \ldots, A_n\)</span>에서의 표본크기인 <span class="math inline">\(n_1, \ldots, n_r\)</span>이 고정</p></li>
<li><p>동질성 검정 가설</p>
<ul>
<li><p><span class="math inline">\(H _{0} :(p _{11}, \ldots ,p _{1c} )= \cdots =(p _{r1} , \ldots ,p _{rc} )=(p _{1} ,\ldots ,p _{c} )\)</span>
(부차모집단의 분포는 동일하다)</p></li>
<li><p><span class="math inline">\(H_1 : \text{not} \hskip3pt H_0\)</span></p></li>
</ul></li>
</ul>
<p>여기서 <span class="math inline">\((p_{1},\ldots,p_{c})\)</span>는 <span class="math inline">\((B_1,\ldots, B_c)\)</span>의 확률을
나타내며, <span class="math inline">\(\sum_{i=1}^cp_{i}=1\)</span>.</p>
<ul>
<li><p>독립성 검정과 동질성 검정은 시작이 틀리지만 귀무가설 하에서
검정통계량의 형태와 자유도는 같음</p></li>
<li><p>검정 통계량
<span class="math display">\[T=\sum_{i=1}^r\sum_{j=1}^c \frac{(n_{ij}-\hat{e}_{ij})^2}{\hat{e}_{ij}}\sim \chi^2((r-1)(c-1))\]</span></p></li>
</ul>
<p>여기서 <span class="math inline">\(\hat{e}_{ij}=n_{i.}n_{.j}/n\)</span>이며, 이를 추정된
기대빈도(expected frequency)라 함</p>
<ul>
<li>기각역 <span class="math display">\[T &gt; \chi^2_{\alpha, (r-1)(c-1)}\]</span></li>
</ul>
<p>예제) 소량의 아스피린(aspirin) 복용이 심장병으로 인한 위험률을 줄이는 데
효과가 있는지를 알아보고자 하였다. <span class="math inline">\(22,071\)</span>명의 남성을 확률화를 통해 두
그룹으로 나눈 후, 한 그룹에는 저용량(<span class="math inline">\(325mg\)</span>/일)의 아스피린을 복용시키고
다른 그룹에는 플라시보(placebo)를 복용하게 한 후 약 60개월간 관찰하여
심근경색(myocardial infarction)을 일으키는지 여부를 관찰하였다.
아스피린의 복용여부와 심근경색간의 연관성이 존재하는가?</p>
<p><img src="category/ex6.jpg" style="width:80.0%" /></p>
<div id="with-r-11" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> With R<a href="category.html#with-r-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="category.html#cb15-1" aria-hidden="true" tabindex="-1"></a>rr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">139</span>,<span class="dv">239</span>,<span class="dv">10898</span>,<span class="dv">10795</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb15-2"><a href="category.html#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="category.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(rr, <span class="at">correct=</span>F)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  rr
## X-squared = 26.944, df = 1, p-value = 2.095e-07</code></pre>
<p>결과를 살펴보면, 아스피린 복용 유무와 심근경색 발생 유무에 대한 독립성 검정의 검정통계량은 26.94, P-value는 &lt;.0001로 유의수준 5%하에서 유의하다. 따라서 아스피린 복용 유무와 심근경색 발생 유무는 서로 관련이 있다고 할 수 있다.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="category.html#cb17-1" aria-hidden="true" tabindex="-1"></a>RR <span class="ot">&lt;-</span> (<span class="dv">139</span><span class="sc">/</span><span class="dv">11037</span>)<span class="sc">/</span>(<span class="dv">239</span><span class="sc">/</span><span class="dv">11034</span>)</span>
<span id="cb17-2"><a href="category.html#cb17-2" aria-hidden="true" tabindex="-1"></a>RR</span></code></pre></div>
<pre><code>## [1] 0.5814319</code></pre>
<p>RR 값은 0.58로 아스피린을 복용한 집단의 심근경색 발생율이 아스피린을 복용하지 않은 집단의 심금경색 발생율의 0.58배로 낮다는 것을 알 수 있다.</p>
</div>
<div id="with-sas-11" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> With SAS<a href="category.html#with-sas-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data rr;
input aspirin   mi  count @@;
cards;
1   1   139
1   0   10898
0   1   239
0   0   10795
;
run;

proc freq data=rr order=data;
weight count;
table aspirin*mi/nopercent nocol chisq;
run;</code></pre>
<p><img src="category/ex11.jpg" style="width:50.0%" /></p>
<p><img src="category/ex9.jpg" style="width:80.0%" /></p>
</div>
</div>
<div id="fisher의-정확-검정" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Fisher의 정확 검정<a href="category.html#fisher의-정확-검정" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>분할표에서 기대빈도가 <span class="math inline">\(5\)</span>보다 작은 셀이 전체의 <span class="math inline">\(20\%\)</span> 이상인
경우에는 카이제곱 검정 대신 Fisher의 정확 검정(Fisher’s exact
test)를 사용</li>
</ul>
<p>예제) 비만과 당뇨: 당뇨 <span class="math inline">\(5\)</span>, 당뇨가 없는 정상 <span class="math inline">\(15\)</span>명, 총 <span class="math inline">\(20\)</span>명을 대상으로 비만 여부를 조사한 자료</p>
<p><img src="category/f2.jpg" style="width:90.0%" /></p>
<ul>
<li>비만과 당뇨 예제의 기대빈도</li>
</ul>
<p><img src="category/f3.jpg" style="width:90.0%" /></p>
<ul>
<li><p>가설</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span> : 두 변수는 독립이다.</p></li>
<li><p><span class="math inline">\(H_1\)</span> : 두 변수는 독립이 아니다.</p></li>
</ul></li>
<li><p>Fisher의 정확 검정은 분할표의 주변합이 고정되었다는 가정하에 가능한
모든 경우에 대한 확률을 기반으로 가설을 검정하는 방법</p></li>
<li><p>위의 예제에서 총 <span class="math inline">\(20\)</span>명 중 비만인 사람은 <span class="math inline">\(4\)</span>명, 정상인 사람은 <span class="math inline">\(16\)</span>명
임. 따라서 <span class="math inline">\(20\)</span>명 중 <span class="math inline">\(4\)</span>명을 뽑는 가능한 모든 경우의 수는 <span class="math inline">\(_{20}C_4\)</span></p></li>
<li><p>여기서 비만 <span class="math inline">\(4\)</span>명은 당뇨와 정상으로 나뉘어지므로 선택될 수 있는 모든
조합은 <span class="math inline">\(5\)</span>가지 임</p></li>
</ul>
<p><img src="category/f4.jpg" style="width:90.0%" /></p>
<ul>
<li>가능한 조합의 형태</li>
</ul>
<p><img src="category/f5.jpg" style="width:90.0%" /></p>
<ul>
<li>P-value</li>
</ul>
<p><img src="category/f6.jpg" style="width:80.0%" /></p>
<div id="with-r-12" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> With R<a href="category.html#with-r-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="category.html#cb20-1" aria-hidden="true" tabindex="-1"></a>fisher <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">13</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb20-2"><a href="category.html#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="category.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(fisher)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  fisher
## p-value = 0.2487
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   0.2088683 77.8897313
## sample estimates:
## odds ratio 
##   3.955176</code></pre>
<p>P-value는 0.2487로 비만과 당뇨간에는 연관성이 없다고 할 수 있다.</p>
</div>
<div id="with-sas-12" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> With SAS<a href="category.html#with-sas-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data fisher;
input fat diabet count @@;
cards;
1   1   2
1   2   2
2   1   3
2   2   13
;
run;

proc freq data=fisher;
weight count;
table fat*diabet/norow nocol nopercent expected exact;
run;</code></pre>
<p><img src="category/ex13.jpg" style="width:34.0%" /></p>
<p><img src="category/ex14.jpg" style="width:50.0%" /></p>
</div>
</div>
<div id="맥니마-검정" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> 맥니마 검정<a href="category.html#맥니마-검정" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>맥니마 검정(McNemar test)은 짝지어진 범주형 자료의 경우 전/후 간
분포의 차이가 있는지 검정하는 방법</p></li>
<li><p>짝지어진 표본의 예</p>
<ul>
<li><p>새로운 이슈가 발생한 경우 이슈 전후의 <span class="math inline">\(A\)</span> 대통령 후보에 대한
지지 여부(동일 응답자, 패널(panel))</p></li>
<li><p>동일한 대상으로 교육전후 안전벨트 거부여부에 대한 조사</p></li>
</ul></li>
<li><p>전후 사이에 응답 대상이나 실험 대상이 바뀌는 경우, 혹은 전혀 다른
항목을 측정하는 경우 맥니마 검정을 사용할 수 없음</p></li>
<li><p>반드시 동일 실험 대상이 전후에 사용되어야 하고 같은 개념을 묻거나
실험 해야 함</p></li>
<li><p>맥니마 검정시 분할표</p></li>
</ul>
<p><img src="category/f7.jpg" style="width:100.0%" /></p>
<ul>
<li><p>가설</p>
<ul>
<li><p><span class="math inline">\(H_0 : p_1=p_2\)</span> (실험 전의 yes 확률과 실험 후의 yes 확률이 같다)</p></li>
<li><p><span class="math inline">\(H_1 : p_1 \ne p_2\)</span> (양측), <span class="math inline">\(p_1&gt;p_2\)</span> 혹은 <span class="math inline">\(p_1&lt;p_2\)</span> (단측)</p></li>
</ul></li>
<li><p>검정통계량 <span class="math display">\[T=\frac{B-C}{\sqrt{B+C}} \sim N(0,1)\]</span></p></li>
<li><p><span class="math inline">\(\hat{p}_1=\frac{A+B}{N}\)</span>, <span class="math inline">\(\hat{p}_2=\frac{A+C}{N}\)</span>,
<span class="math inline">\(\hat{p}_1 - \hat{p}_2=\frac{B-C}{N}\)</span> 그리고 귀무가설 하에서
<span class="math inline">\((B-C)/N=0\)</span></p></li>
</ul>
<div id="이론적-배경" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> 이론적 배경<a href="category.html#이론적-배경" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Inference for dependent proportions
<span class="math display">\[
d = \hat{p}_{1+} - \hat{p}_{+1}
\]</span></li>
<li>A large-sample <span class="math inline">\(100(1-\alpha)\%\)</span> confidence interval for p_{1+} - p_{+1} is</li>
</ul>
<p><span class="math display">\[
(\hat{p}_{1+} - \hat{p}_{+1}) \pm z_{\alpha/2}\hat{\sigma}(d)
\]</span>
where
<span class="math display">\[
\hat{\sigma}^2(d)=\hat{p}_{1+}(1-\hat{p}_{1+})+\hat{p}_{+1}(1-\hat{p}_{+1})-2(\hat{p}_{11}\hat{p}_{22}-\hat{p}_{12}\hat{p}_{21})/n
\]</span></p>
<p>Under <span class="math inline">\(H_0 : p_{1+}=p_{+1}\)</span>, another alternative estimate is</p>
<p><span class="math display">\[
\hat{\sigma}_0^2(d)= \frac{\hat{p}_{1+}+\hat{p}_{+1}-2\hat{p}_{11}}{n}=\frac{n_{12}+n_{21}}{n^2}
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
z=\frac{d}{\hat{\sigma}(d)}=\frac{n_{12}-n_{21}}{\sqrt{n_{12}+ n_{21}}}\sim N(0,1)
\]</span></p>
<p>This depends only on the observations classified in differentr categories at the two occasions. The <span class="math inline">\(n_{11}+n_{22}\)</span> observations on the main diagonal are irrelevant to inference whether <span class="math inline">\(p_{1+}\)</span> and $p_{+1} differ.</p>
<p>예제) 다음은 결혼한 지 <span class="math inline">\(3\)</span>년이 된 남성 <span class="math inline">\(60\)</span>명을 대상으로 결혼 전후의
경제생활의 만족도를 조사한 자료이다. 이 자료에 대해 결혼 전과 결혼 후의
경제생활의 만족도에 있어서 차이가 있는지 검정하라.</p>
<p><img src="category/ex15.jpg" style="width:100.0%" /></p>
</div>
<div id="with-r-13" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> With R<a href="category.html#with-r-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="category.html#cb23-1" aria-hidden="true" tabindex="-1"></a>mcnemar <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">23</span>,<span class="dv">18</span>,<span class="dv">7</span>,<span class="dv">12</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb23-2"><a href="category.html#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="category.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(mcnemar, <span class="at">correct=</span>F)</span></code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test
## 
## data:  mcnemar
## McNemar&#39;s chi-squared = 4.84, df = 1, p-value = 0.02781</code></pre>
<p>검정결과를 살펴보면 결혼 전의 경제생활 만족도와 결혼 후의 경제생활 만족도는 차이가 있는 것으로 나타났다(P-value: 0.0278). 결혼 전의 만족도는 <span class="math inline">\(30/60=0.5\)</span>이고 결혼 후의 만족도는 <span class="math inline">\(41/60=0.68\)</span>로 결혼 전보다 결혼 후에 경제생활에 대한 만족도가 더 높은 것으로 나타난다.</p>
</div>
<div id="with-sas-13" class="section level3 hasAnchor" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> With SAS<a href="category.html#with-sas-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code> DATA marriage;
 INPUT before $ after $ count @@;
CARDS;
 satisfy satisfy 23
satisfy unsatisfy 7
unsatisfy satisfy 18
unsatisfy unsatisfy 12
;
run;

ODS SELECT McNemarsTest;
PROC FREQ order=data;
WEIGHT count;
TABLES before*after/AGREE;
RUN;</code></pre>
<p><img src="category/ex17.jpg" style="width:60.0%" /></p>
</div>
</div>
<div id="cochran-mantel-haenzel-test" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Cochran-Mantel-Haenzel test<a href="category.html#cochran-mantel-haenzel-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>독립된 <span class="math inline">\(K\)</span>개의 층(sstrata)이 있을 때, 층효과를 제어(adjusting)한 후 처리와 반응의 독립성 검정</p></li>
<li><p><span class="math inline">\(H_0\)</span>: conditional independence of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></p></li>
<li><p>Mantal and Haenszel(1959) gave a test comparing two groups on a binary response, adjusting for control variables. This test of conditional independence applies to <span class="math inline">\(K\)</span> strata of 2×2 tables. Focusing on retrospective studies of disease, they treated response totals as fixed. They analyzed the data by conditioning, within each stratum, on both the group totals and the response totals. In stratum <span class="math inline">\(k\)</span>, given the marginal totals <span class="math inline">\((n_{1+k}, n_{2+k}, n_{+1k}, n_{+2k})\)</span>, the sampling model for cell counts is hypergeometric.</p></li>
<li><p>독립된 <span class="math inline">\(K\)</span>개의 그룹이 있을 때 그룹의 효과를 제어한 반응률의 차이가 있는지를 검정하는 방법</p></li>
<li><p><span class="math inline">\(k\)</span>번째 층(stratum)에서의 처리와 반응간의 관계</p></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">처리 / 반응여부</th>
<th align="center">반응</th>
<th align="center">반응 안함</th>
<th align="center">합계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(n_{11k}\)</span></td>
<td align="center"><span class="math inline">\(n_{12k}\)</span></td>
<td align="center"><span class="math inline">\(n_{1+k}\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center"><span class="math inline">\(n_{21k}\)</span></td>
<td align="center"><span class="math inline">\(n_{22k}\)</span></td>
<td align="center"><span class="math inline">\(n_{2+k}\)</span></td>
</tr>
<tr class="odd">
<td align="center">합계</td>
<td align="center"><span class="math inline">\(n_{+1k}\)</span></td>
<td align="center"><span class="math inline">\(n_{+2k}\)</span></td>
<td align="center"><span class="math inline">\(n_{++k}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>가설 형태</p>
<ul>
<li><p><span class="math inline">\(H_0: p_{11k}=p_{21k} \,\,\, vs \,\,\, H_1: p_{11k} \ne p_{21k}, \,\,\, k=1,\ldots, K\)</span></p>
<p>또는</p></li>
<li><p><span class="math inline">\(H_0: p_{ijk}=p_{i+k}\cdot p_{+jk} \,\,\, vs \,\,\, H_1: p_{ijk} \ne p_{i+k}\cdot p_{+jk}, \,\,\, k=1,\ldots, K\)</span></p></li>
</ul></li>
<li><p>Cochran-Mantel-Haenszel (CMH) 통계량</p></li>
</ul>
<p><span class="math display">\[
Q_{CMH}=\frac{(\sum_{k=1}^K n_{11k}-\sum_{k=1}^K E(n_{11k}|H_0))^2}{\sum_{i=1}^K Var(n_{11k}|H_0)}
\]</span>
또는</p>
<p><span class="math display">\[
Q_{CMH}=\frac{(|\sum_{k=1}^K n_{11k}-\sum_{k=1}^K E(n_{11k}|H_0)|-\frac{1}{2})^2}{\sum_{i=1}^K Var(n_{11k}|H_0)}
\]</span></p>
<p>Assuming conditional independence, the hypergeometric mean and variance of <span class="math inline">\(n_{11k}\)</span> are</p>
<p><span class="math display">\[
E(n_{11k}|H_0)=\frac{n_{1+k}n_{+1k}}{n_{++k}}, \,\,\, Var(n_{11k}|H_0)=\frac{n_{1+k}n_{2+k}n_{+1k}n_{+2k}}{n_{++k}^2(n_{++k}-1)}
\]</span></p>
<ul>
<li>기각역
<span class="math display">\[
Q_{CMH} &gt; \chi_{\alpha,1}^2
\]</span></li>
</ul>
<div id="note-1" class="section level4 unnumbered hasAnchor">
<h4>Note 1<a href="category.html#note-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>Breslow-Day test</p></li>
<li><p><span class="math inline">\(H_0\)</span>: Homogeneity of odds ratios</p></li>
<li><p>CMH 검정하기 전에 Breslow-Day를 사용하여 <span class="math inline">\(H_0\)</span>: Homogeneity of odds ratios를 검정하여 <span class="math inline">\(H_0\)</span>가 채택되면 CMH 검정을 한다.</p></li>
<li><p>Breslow-Day 검정에서 귀무가설을 기각하면 층별로 OR를 산출한다.</p></li>
</ul>
<p>예제) 4개의 병원으로부터 호흡기 곤란 환자들을 기존 치료제와 새로운 치료제에 랜덤하게 할당한 후 호전의 유무를 조사한 자료이다. 연구자가 알고 싶은 것은 치료제에 따라 호전도의 차이가 있는가이며, 병원의 효과를 제어하고 싶다.
Cochran-Mantel-Haenszel 검정을 이용하여 분석해보자.</p>
<table>
<thead>
<tr class="header">
<th align="center">병원</th>
<th align="center">치료제</th>
<th align="center">호전</th>
<th align="center">호전되지 않음</th>
<th align="center">합계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td align="center">기존 치료제</td>
<td align="center">9</td>
<td align="center">5</td>
<td align="center">14</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">새로운 치료제</td>
<td align="center">11</td>
<td align="center">6</td>
<td align="center">17</td>
</tr>
<tr class="odd">
<td align="center">합계</td>
<td align="center"></td>
<td align="center">20</td>
<td align="center">11</td>
<td align="center">31</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td align="center">기존 치료제</td>
<td align="center">7</td>
<td align="center">5</td>
<td align="center">12</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">새로운 치료제</td>
<td align="center">8</td>
<td align="center">3</td>
<td align="center">11</td>
</tr>
<tr class="even">
<td align="center">합계</td>
<td align="center"></td>
<td align="center">15</td>
<td align="center">8</td>
<td align="center">23</td>
</tr>
<tr class="odd">
<td align="center">C</td>
<td align="center">기존 치료제</td>
<td align="center">4</td>
<td align="center">6</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">새로운 치료제</td>
<td align="center">7</td>
<td align="center">5</td>
<td align="center">12</td>
</tr>
<tr class="odd">
<td align="center">합계</td>
<td align="center"></td>
<td align="center">11</td>
<td align="center">11</td>
<td align="center">22</td>
</tr>
<tr class="even">
<td align="center">D</td>
<td align="center">기존 치료제</td>
<td align="center">18</td>
<td align="center">11</td>
<td align="center">29</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">새로운 치료제</td>
<td align="center">26</td>
<td align="center">4</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center">합계</td>
<td align="center"></td>
<td align="center">44</td>
<td align="center">15</td>
<td align="center">59</td>
</tr>
<tr class="odd">
<td align="center">전체 합계</td>
<td align="center"></td>
<td align="center">90</td>
<td align="center">45</td>
<td align="center">135</td>
</tr>
</tbody>
</table>
</div>
<div id="with-r-14" class="section level3 hasAnchor" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> With R<a href="category.html#with-r-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="category.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb26-2"><a href="category.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Breslow-Day test</span></span>
<span id="cb26-3"><a href="category.html#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="category.html#cb26-4" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">5</span>,<span class="dv">6</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb26-5"><a href="category.html#cb26-5" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">5</span>,<span class="dv">3</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb26-6"><a href="category.html#cb26-6" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">5</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb26-7"><a href="category.html#cb26-7" aria-hidden="true" tabindex="-1"></a>d4 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">18</span>,<span class="dv">26</span>,<span class="dv">11</span>,<span class="dv">4</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb26-8"><a href="category.html#cb26-8" aria-hidden="true" tabindex="-1"></a>cmh <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="fu">c</span>(d1,d2,d3,d4), <span class="at">dim=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">4</span>))</span>
<span id="cb26-9"><a href="category.html#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="category.html#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="fu">BreslowDayTest</span>(cmh, <span class="at">OR=</span><span class="cn">NA</span>, <span class="at">correct=</span>F)</span></code></pre></div>
<pre><code>## 
##  Breslow-Day test on Homogeneity of Odds Ratios
## 
## data:  cmh
## X-squared = 1.8947, df = 3, p-value = 0.5946</code></pre>
<p>Breslow-Day 검정 결과, P-value가 0.5946으로 귀무가설을 기각하지 못하므로 층간 OR는 동질하다고 할 수 있다. 그러므로 CMH 검정을 통해 조건부 독립을 검정한다.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="category.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lawstat)</span>
<span id="cb28-2"><a href="category.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CMH test</span></span>
<span id="cb28-3"><a href="category.html#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="category.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cmh.test</span>(cmh)</span></code></pre></div>
<pre><code>## 
##  Cochran-Mantel-Haenszel Chi-square Test
## 
## data:  cmh
## CMH statistic = 4.039074, df = 1.000000, p-value = 0.044458, MH
## Estimate = 0.465868, Pooled Odd Ratio = 0.487179, Odd Ratio of level 1
## = 0.981818, Odd Ratio of level 2 = 0.525000, Odd Ratio of level 3 =
## 0.476190, Odd Ratio of level 4 = 0.251748</code></pre>
<p>CMH 검정 결과 P-value는 0.044로 유의수준 5%하에서 귀무가설을 기각한다. 즉, 치료제와 호전 유무간에 연관성이 존재한다고 할 수 있다. 이때 보정된 OR은 0.47로 층을 통합한 자료의 OR 0.49와는 약간의 차이가 있다.</p>
<p>만약 병원을 층변수로 제어하지 않고 병원에 대해 collapse 시키면 P-value가 0.0513으로 유의하지 않은 결과를 보여준다.</p>
</div>
<div id="with-sas-14" class="section level3 hasAnchor" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> With SAS<a href="category.html#with-sas-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>DATA hospital;
 INPUT hospital $ trt $ recovery $ count @@;
 CARDS;
 A old yes 9 A old no 5
 A new yes 11 A new no 6
 B old yes 7 B old no 5
 B new yes 8 B new no 3
 C old yes 4 C old no 6
 C new yes 7 C new no 5
 D old yes 18 D old no 11
 D new yes 26 D new no 4
 ;
 run;

 PROC FREQ;
 WEIGHT count;
 TABLES hospital*trt*recovery/CMH NOROW NOCOL;
RUN;</code></pre>
<p><img src="category/cmh.png" /></p>
</div>
</div>
<div id="진단법의-평가" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> 진단법의 평가<a href="category.html#진단법의-평가" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="민감도와-특이도" class="section level3 hasAnchor" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> 민감도와 특이도<a href="category.html#민감도와-특이도" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>어떤 진단기법이 얼마나 정확한가를 평가할 때 좋은 진단기법은 질병이 있는 사람을 양성으로, 질병이 없는 사람을 음성으로 판정할 확률이 높아야 함.</p>
<ul>
<li><p><strong>민감도(sensitivity)</strong> : 질병이 있는 경우 진단기법이 질병이 있다(양성)고 판단하는 기준</p></li>
<li><p><strong>특이도(specificity)</strong> : 질병이 없는 경우 진단기법이 질병이 없다(음성)고 판단하는 기준</p></li>
</ul></li>
<li><p>즉, 민감도가 높으면, 위음성률(false-negative rate)이 낮다. 반면, 특이도가 높으면 위양성률(false-positive rate)이 낮다. 질병 여부와 진단 결과를 2×2 분할표로 정리 가능</p>
<ul>
<li><p>위음성률 : 질병에 걸린 사람을 음성으로 잘못 진단</p></li>
<li><p>위양성률 : 질병에 걸리지 않은 사람을 양성으로 잘못 진단</p></li>
</ul></li>
<li><p>질병과 진단과의 관계를 보여주는 분할표</p></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">진단</th>
<th align="center">양성 D+</th>
<th align="center">음성 D-</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">양성 T+</td>
<td align="center">TP</td>
<td align="center">FP</td>
</tr>
<tr class="even">
<td align="center">음성 T-</td>
<td align="center">FN</td>
<td align="center">TN</td>
</tr>
</tbody>
</table>
<p>민감도=<span class="math inline">\(\frac{TP}{TP+FN}\)</span>, 특이도=<span class="math inline">\(\frac{TN}{FP+TN}\)</span></p>
<blockquote>
<p>TP: true positive, FP: false positive, TN: true negative, FN: false negative</p>
</blockquote>
<p>예제) 다음은 간의 화상(liver scan)과 병리적 진단 결과를 나타낸 표이다. 연구자의 관심은 간의 화상을 이용한 방법이 병리적인 비정상을 가려내는데 좋은 진단법인지 알아보는데 있다.</p>
<ul>
<li>간의 화상과 병리적 진단결과</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">진단/실제</th>
<th align="center">비정상 D+</th>
<th align="center">정상 D-</th>
<th align="center">계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">비정상 T+</td>
<td align="center">231</td>
<td align="center">32</td>
<td align="center">263</td>
</tr>
<tr class="even">
<td align="center">정상판정 T-</td>
<td align="center">27</td>
<td align="center">54</td>
<td align="center">81</td>
</tr>
<tr class="odd">
<td align="center">계</td>
<td align="center">258</td>
<td align="center">86</td>
<td align="center">344</td>
</tr>
</tbody>
</table>
<ul>
<li><p>민감도: 간의 화상을 이용한 방법이 병리적 진단결과 비정상인 사람을 얼마나 잘 비정상으로 판정했는가에 대한 기준, 231/258=0.90</p></li>
<li><p>특이도: 병리적 진단결과 정상인 사람들을 간의 화상방법에서 정상으로 옮게 판정하는 비율, 54/86=0.63</p></li>
</ul>
</div>
<div id="양성예측도와-음성예측도" class="section level3 hasAnchor" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> 양성예측도와 음성예측도<a href="category.html#양성예측도와-음성예측도" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>실제로 임상에서는 진단법이 옳은 진단을 내일 확률을 알고자 함</p>
<ul>
<li><p><strong>양성예측도(predicted value of positive test)</strong>: 양성으로 판전되었을 때 실제로 병에 걸렸을 확률, 231/263=0.88</p></li>
<li><p><strong>음성예측도(predicted value of negative test)</strong>: 음성으로 판정되었을 때 실제로도 병에 걸리지 않았을 확률, 54/81=0.67</p></li>
<li><p>이는 유병률(prevalence)을 고려하지 않아 양성예측도와 음성예측도가 정확하지 않게 계산되었음</p></li>
<li><p>344명이 전체집단에서 무작위로 추출되지 않았으므로, 258/344를 유병률이라고 할 수 없음</p></li>
<li><p>일반적으로, 관측된 도수에 의해 단순히 계산한다면 유병률이라는 중요한 부분을 고려하지 않게 됨. 그러므로 유병률을 고려한 양성예측도와 음성예측도는 베이즈 정리(Bayes’ theorem)에 근거하여 구할 수 있음</p></li>
</ul>
<div id="양성예측도" class="section level4 unnumbered hasAnchor">
<h4>양성예측도<a href="category.html#양성예측도" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>양성(T+)일 때, 실제로 병에 걸렸을(D+) 조건부 확률, 즉 <span class="math inline">\(P(D+|T+)\)</span>이 됨</li>
</ul>
<p><span class="math display">\[
P(D+|T+)=\frac{P(T+|D+)P(D+)}{P(T+|D+)P(D+)+P(T+|D-)P(D-)}
\]</span></p>
<p>여기서, <span class="math inline">\(P(T+|D+)\)</span>는 병에 걸렸을때 양성으로 판정할 확률, 즉 진단법의 민감도 의미, <span class="math inline">\(P(T+|D-)=1-P(T-|D-)\)</span>=1-특이도, <span class="math inline">\(P(D+)\)</span>는 질병의 유병률, <span class="math inline">\(P(D-)=1-P(D+)\)</span></p>
<p><span class="math display">\[
양성예측도=\frac{민감도\times 유병률}{(민감도\times 유병률)+(1-특이도)\times(1-유병률)}
\]</span></p>
</div>
<div id="음성예측도" class="section level4 unnumbered hasAnchor">
<h4>음성예측도<a href="category.html#음성예측도" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>같은 방식으로 음성(T-)일 때, 실제로 병에 걸리지 않았을(D-) 조건부 확률, 즉 <span class="math inline">\(P(D-|T-)\)</span>은 다음과 같음</li>
</ul>
<p><span class="math display">\[
P(D-|T-)=\frac{P(T-|D-)P(D-)}{P(T-|D-)P(D-)+P(T-|D+)P(D+)}
\]</span></p>
<p><span class="math display">\[
음성예측도=\frac{특이도\times (1-유병률)}{특이도\times (1-유병률)+(1-민감도)\times 유병률}
\]</span></p>
<p>즉, 예측도는 집단의 유병률에 의존하는 값임</p>
<p>예제) 아래 자료는 X-ray를 이용한 판정이 결핵(tuberculosis)을 진단하는데 얼마나 유용한가를 알아보기 위한 연구로부터 나온 결과이다. 민감도와 특이도, 양성예측도와 음성예측도를 구해보자.</p>
<ul>
<li>X-ray를 이용한 결핵 진단 자료</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">진단/결핵</th>
<th align="center">유 D+</th>
<th align="center">무 D-</th>
<th align="center">계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">양성 T+</td>
<td align="center">22</td>
<td align="center">51</td>
<td align="center">73</td>
</tr>
<tr class="even">
<td align="center">음성 T-</td>
<td align="center">8</td>
<td align="center">1739</td>
<td align="center">1747</td>
</tr>
<tr class="odd">
<td align="center">계</td>
<td align="center">30</td>
<td align="center">1790</td>
<td align="center">1820</td>
</tr>
</tbody>
</table>
<ul>
<li><p>민감도 = <span class="math inline">\(P(T+|D+)=22/30=0.7333\)</span></p></li>
<li><p>특이도 = <span class="math inline">\(P(T-|D-)=1739/1790=0.9715\)</span></p></li>
<li><p>1820명이 전체 집단에서 랜덤하게 뽑은 것이 아니므로 30/1820은 유병률이 아니다. 1987년도 연구에서 인구 100,000만명 당 9.3명 꼴로 결핵이 발생했으므로 이를 이용하여 사전확률인 유병률을 $P(D+)=0.000093으로 할 수 있다.</p></li>
<li><p>양성예측도 = <span class="math inline">\(\frac{0.7333\times 0.000093}{(0.7333\times 0.000093)+(0.0285\times 0.999907)}=0.00239\)</span>: X-ray 진단에 의해 양성으로 판단된 사람 중 0.239%만이 실제로 결핵환자 추정</p></li>
<li><p>음성예측도 = <span class="math inline">\(\frac{0.9715\times 0.999907}{(0.9715\times 0.999907)+(0.2667\times 0.000093)}=0.999974\)</span>: X-ray 진단에 의해 음성으로 판단된 사람 중 99.9%는 정상인으로 추정</p></li>
</ul>
</div>
<div id="참고-베이즈-정리" class="section level4 unnumbered hasAnchor">
<h4>참고: 베이즈 정리<a href="category.html#참고-베이즈-정리" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<blockquote>
<p>상호배반사상인 <span class="math inline">\(B_1, \ldots, B_n\)</span>가 표본공간 <span class="math inline">\(S\)</span>의 분할이며 모든 <span class="math inline">\(i\)</span>에 대해 <span class="math inline">\(P(B_i)&gt;0\)</span>이라 하면, <span class="math inline">\(P(A)&gt;0\)</span>인 사상 <span class="math inline">\(A\)</span>에 대해 다음이 성립한다.
<span class="math display">\[
P(B_k|A)-\frac{P(A|B_k)P(B_k)}{\sum_{i=1}^n P(A|B_i)P(B_i)}
\]</span>
이를 <strong>베이즈 정리(Bayes’ theorem)</strong>라고 한다.</p>
</blockquote>
<p>증명) 조건부 확률의 정의에 의하여
<span class="math display">\[
P(B_i|A)=\frac{P(B_i \cap A)}{P(A)}
\]</span></p>
<p>이 되고, 분모에 전확률의 정리를 이용하면,</p>
<p><span class="math display">\[
P(A)=\sum_{i=1}^n P(A|B_i)P(B_i)
\]</span></p>
<p>가 되므로 다음의 결과를 구할 수 있다.
<span class="math display">\[
P(B_k|A)-\frac{P(A|B_k)P(B_k)}{\sum_{i=1}^n P(A|B_i)P(B_i)}
\]</span></p>
<p><span class="math inline">\(n=2\)</span>인 경우 <span class="math inline">\(B(B1|A)\)</span>는 다음과 같이 정리할 수 있다.</p>
<p><span class="math display">\[
P(B_1|A)=\frac{P(A|B_1)P(B_1)}{P(A|B_1)P(B_1)+P(A|B_2)P(B_2)}
\]</span></p>
<p>예제) 통계학 과목이 A, B, C 3개 반으로 나누어져 수업을 받는다. A, B, C 반이 각각 50, 30, 20명씩 수강하고 있다. 학기가 끝난 후, 학점을 조사한 결과, F를 받은 사람은 A, B, C반에서 각각 10명씩이었다. 한 학생에게 학점을 물었을 때, 이 학생이 F를 받았다면, 그 학생이 A 반에서 수강한 학생이었을 확률을 구하시오.</p>
<p>풀이)</p>
<p><span class="math inline">\(P(A)=1/2, \,\,\, P(F|A)=\frac{P(A\cap F)}{P(A)}=\frac{0.1}{0.5}=\frac{1}{5}\)</span></p>
<p><span class="math inline">\(P(B)=3/10, \,\,\, P(F|B)=\frac{P(B\cap F)}{P(B)}=\frac{0.1}{0.3}=\frac{1}{3}\)</span></p>
<p><span class="math inline">\(P(C)=1/5, \,\,\, P(F|C)=\frac{P(C\cap F)}{P(C)}=\frac{0.1}{0.2}=\frac{1}{2}\)</span></p>
<p>따라서 $P(A|F)는</p>
<p><span class="math display">\[
P(A|F)=\frac{1/2\cdot 1/5}{1/2\cdot 1/5+3/10\cdot 1/3+1/5\cdot 1/2}=\frac{1}{3}
\]</span></p>
<!-------------------------------------->

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="nonpara.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Statistical Analysis.pdf", "Statistical Analysis.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
