<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 평균차이 검정 | Statistical Analysis</title>
  <meta name="description" content="This is a Statistical Analysis" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 평균차이 검정 | Statistical Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a Statistical Analysis" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 평균차이 검정 | Statistical Analysis" />
  
  <meta name="twitter:description" content="This is a Statistical Analysis" />
  

<meta name="author" content="Jin Hyun Nam" />


<meta name="date" content="2022-01-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="anova.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>머리말</a></li>
<li class="chapter" data-level="1" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>1</b> 평균차이 검정</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ttest.html"><a href="ttest.html#일표본-t-검정"><i class="fa fa-check"></i><b>1.1</b> 일표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ttest.html"><a href="ttest.html#with-r"><i class="fa fa-check"></i><b>1.1.1</b> With R</a></li>
<li class="chapter" data-level="1.1.2" data-path="ttest.html"><a href="ttest.html#with-sas"><i class="fa fa-check"></i><b>1.1.2</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ttest.html"><a href="ttest.html#독립표본-t-검정"><i class="fa fa-check"></i><b>1.2</b> 독립표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ttest.html"><a href="ttest.html#두-모분산-비의-검정"><i class="fa fa-check"></i><b>1.2.1</b> 두 모분산 비의 검정</a></li>
<li class="chapter" data-level="1.2.2" data-path="ttest.html"><a href="ttest.html#with-r-1"><i class="fa fa-check"></i><b>1.2.2</b> With R</a></li>
<li class="chapter" data-level="1.2.3" data-path="ttest.html"><a href="ttest.html#with-sas-1"><i class="fa fa-check"></i><b>1.2.3</b> With SAS</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="ttest.html"><a href="ttest.html#대응표본-t-검정"><i class="fa fa-check"></i><b>1.3</b> 대응표본 <span class="math inline">\(t\)</span>-검정</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ttest.html"><a href="ttest.html#with-r-2"><i class="fa fa-check"></i><b>1.3.1</b> With R</a></li>
<li class="chapter" data-level="1.3.2" data-path="ttest.html"><a href="ttest.html#with-sas-2"><i class="fa fa-check"></i><b>1.3.2</b> with SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>2</b> 분산분석</a>
<ul>
<li class="chapter" data-level="2.1" data-path="anova.html"><a href="anova.html#분산분석"><i class="fa fa-check"></i><b>2.1</b> 분산분석</a></li>
<li class="chapter" data-level="2.2" data-path="anova.html"><a href="anova.html#일원배치-분산분석"><i class="fa fa-check"></i><b>2.2</b> 일원배치 분산분석</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="anova.html"><a href="anova.html#사후분석다중검정"><i class="fa fa-check"></i><b>2.2.1</b> 사후분석(다중검정)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="anova.html"><a href="anova.html#이원배치-분산분석"><i class="fa fa-check"></i><b>2.3</b> 이원배치 분산분석</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="anova.html"><a href="anova.html#교호작용"><i class="fa fa-check"></i><b>2.3.1</b> 교호작용</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nonpara.html"><a href="nonpara.html"><i class="fa fa-check"></i><b>3</b> 비모수 검정</a>
<ul>
<li class="chapter" data-level="3.1" data-path="nonpara.html"><a href="nonpara.html#정규성-검정"><i class="fa fa-check"></i><b>3.1</b> 정규성 검정</a></li>
<li class="chapter" data-level="3.2" data-path="nonpara.html"><a href="nonpara.html#윌콕슨-부호순위-검정"><i class="fa fa-check"></i><b>3.2</b> 윌콕슨 부호순위 검정</a></li>
<li class="chapter" data-level="3.3" data-path="nonpara.html"><a href="nonpara.html#윌콕슨-순위합-검정"><i class="fa fa-check"></i><b>3.3</b> 윌콕슨 순위합 검정</a></li>
<li class="chapter" data-level="3.4" data-path="nonpara.html"><a href="nonpara.html#크루스칼-왈리스-검정"><i class="fa fa-check"></i><b>3.4</b> 크루스칼-왈리스 검정</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="category.html"><a href="category.html"><i class="fa fa-check"></i><b>4</b> 교차분석</a>
<ul>
<li class="chapter" data-level="4.1" data-path="category.html"><a href="category.html#상대위험률과-오즈비"><i class="fa fa-check"></i><b>4.1</b> 상대위험률과 오즈비</a></li>
<li class="chapter" data-level="4.2" data-path="category.html"><a href="category.html#독립성-검정"><i class="fa fa-check"></i><b>4.2</b> 독립성 검정</a></li>
<li class="chapter" data-level="4.3" data-path="category.html"><a href="category.html#동질성-검정"><i class="fa fa-check"></i><b>4.3</b> 동질성 검정</a></li>
<li class="chapter" data-level="4.4" data-path="category.html"><a href="category.html#fisher의-정확-검정"><i class="fa fa-check"></i><b>4.4</b> Fisher의 정확 검정</a></li>
<li class="chapter" data-level="4.5" data-path="category.html"><a href="category.html#맥니마-검정"><i class="fa fa-check"></i><b>4.5</b> 맥니마 검정</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>5</b> 회귀분석</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression.html"><a href="regression.html#상관분석"><i class="fa fa-check"></i><b>5.1</b> 상관분석</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="regression.html"><a href="regression.html#상관계수"><i class="fa fa-check"></i><b>5.1.1</b> 상관계수</a></li>
<li class="chapter" data-level="5.1.2" data-path="regression.html"><a href="regression.html#스피어만-상관계수"><i class="fa fa-check"></i><b>5.1.2</b> 스피어만 상관계수</a></li>
<li class="chapter" data-level="5.1.3" data-path="regression.html"><a href="regression.html#켄달의-타우"><i class="fa fa-check"></i><b>5.1.3</b> 켄달의 타우</a></li>
<li class="chapter" data-level="5.1.4" data-path="regression.html"><a href="regression.html#편상관계수"><i class="fa fa-check"></i><b>5.1.4</b> 1.3 편상관계수</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="regression.html"><a href="regression.html#단순선형회귀분석"><i class="fa fa-check"></i><b>5.2</b> 단순선형회귀분석</a></li>
<li class="chapter" data-level="5.3" data-path="regression.html"><a href="regression.html#다중선형회귀분석"><i class="fa fa-check"></i><b>5.3</b> 다중선형회귀분석</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="regression.html"><a href="regression.html#변수-선택"><i class="fa fa-check"></i><b>5.3.1</b> 변수 선택</a></li>
<li class="chapter" data-level="5.3.2" data-path="regression.html"><a href="regression.html#결정계수"><i class="fa fa-check"></i><b>5.3.2</b> 결정계수</a></li>
<li class="chapter" data-level="5.3.3" data-path="regression.html"><a href="regression.html#표준화-회귀계수"><i class="fa fa-check"></i><b>5.3.3</b> 표준화 회귀계수</a></li>
<li class="chapter" data-level="5.3.4" data-path="regression.html"><a href="regression.html#다중공선성"><i class="fa fa-check"></i><b>5.3.4</b> 다중공선성</a></li>
<li class="chapter" data-level="5.3.5" data-path="regression.html"><a href="regression.html#더미변수가변수"><i class="fa fa-check"></i><b>5.3.5</b> 더미변수(가변수)</a></li>
<li class="chapter" data-level="5.3.6" data-path="regression.html"><a href="regression.html#회귀모형에-대한-가정-검토"><i class="fa fa-check"></i><b>5.3.6</b> 회귀모형에 대한 가정 검토</a></li>
<li class="chapter" data-level="5.3.7" data-path="regression.html"><a href="regression.html#다중선형회귀분석---모든-변수를-다-사용하는-경우"><i class="fa fa-check"></i><b>5.3.7</b> 다중선형회귀분석 - 모든 변수를 다 사용하는 경우</a></li>
<li class="chapter" data-level="5.3.8" data-path="regression.html"><a href="regression.html#다중선형회귀분석---단계적-선택법을-사용하는-경우"><i class="fa fa-check"></i><b>5.3.8</b> 다중선형회귀분석 - 단계적 선택법을 사용하는 경우</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>6</b> 일반화 선형모형</a>
<ul>
<li class="chapter" data-level="6.1" data-path="glm.html"><a href="glm.html#the-generalized-linear-models"><i class="fa fa-check"></i><b>6.1</b> The Generalized Linear models</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="glm.html"><a href="glm.html#the-general-linear-model"><i class="fa fa-check"></i><b>6.1.1</b> The General Linear Model</a></li>
<li class="chapter" data-level="6.1.2" data-path="glm.html"><a href="glm.html#generalized-linear-models-glms"><i class="fa fa-check"></i><b>6.1.2</b> Generalized Linear Models (GLMs)</a></li>
<li class="chapter" data-level="6.1.3" data-path="glm.html"><a href="glm.html#normal-glms-as-a-special-case"><i class="fa fa-check"></i><b>6.1.3</b> Normal GLMs as a Special Case</a></li>
<li class="chapter" data-level="6.1.4" data-path="glm.html"><a href="glm.html#modelling-binomial-data"><i class="fa fa-check"></i><b>6.1.4</b> Modelling Binomial Data</a></li>
<li class="chapter" data-level="6.1.5" data-path="glm.html"><a href="glm.html#modelling-poisson-data"><i class="fa fa-check"></i><b>6.1.5</b> Modelling Poisson Data</a></li>
<li class="chapter" data-level="6.1.6" data-path="glm.html"><a href="glm.html#transformation-vs.-glms"><i class="fa fa-check"></i><b>6.1.6</b> Transformation vs. GLMs</a></li>
<li class="chapter" data-level="6.1.7" data-path="glm.html"><a href="glm.html#exponential-family"><i class="fa fa-check"></i><b>6.1.7</b> Exponential Family</a></li>
<li class="chapter" data-level="6.1.8" data-path="glm.html"><a href="glm.html#canonical-links"><i class="fa fa-check"></i><b>6.1.8</b> Canonical Links</a></li>
<li class="chapter" data-level="6.1.9" data-path="glm.html"><a href="glm.html#estimation-of-the-model-parameters"><i class="fa fa-check"></i><b>6.1.9</b> Estimation of the Model Parameters</a></li>
<li class="chapter" data-level="6.1.10" data-path="glm.html"><a href="glm.html#distribution-and-link-function"><i class="fa fa-check"></i><b>6.1.10</b> Distribution and Link Function</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="glm.html"><a href="glm.html#poisson-regression"><i class="fa fa-check"></i><b>6.2</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="glm.html"><a href="glm.html#example-danish-lung-cancer-counts"><i class="fa fa-check"></i><b>6.2.1</b> Example: Danish Lung Cancer Counts</a></li>
<li class="chapter" data-level="6.2.2" data-path="glm.html"><a href="glm.html#what-about-accounting-for-population-size"><i class="fa fa-check"></i><b>6.2.2</b> What About Accounting for Population Size?</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="glm.html"><a href="glm.html#logistic-regression"><i class="fa fa-check"></i><b>6.3</b> Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survival.html"><a href="survival.html"><i class="fa fa-check"></i><b>7</b> 생존분석</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survival.html"><a href="survival.html#생존분석"><i class="fa fa-check"></i><b>7.1</b> 생존분석</a></li>
<li class="chapter" data-level="7.2" data-path="survival.html"><a href="survival.html#비모수적-생존함수-추정"><i class="fa fa-check"></i><b>7.2</b> 비모수적 생존함수 추정</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="survival.html"><a href="survival.html#생명표-방법"><i class="fa fa-check"></i><b>7.2.1</b> 생명표 방법</a></li>
<li class="chapter" data-level="7.2.2" data-path="survival.html"><a href="survival.html#누적한계추정법"><i class="fa fa-check"></i><b>7.2.2</b> 누적한계추정법</a></li>
<li class="chapter" data-level="7.2.3" data-path="survival.html"><a href="survival.html#생존분포-비교"><i class="fa fa-check"></i><b>7.2.3</b> 생존분포 비교</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="survival.html"><a href="survival.html#모수적-생존함수-추정과-회귀모형"><i class="fa fa-check"></i><b>7.3</b> 모수적 생존함수 추정과 회귀모형</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="survival.html"><a href="survival.html#지수분포"><i class="fa fa-check"></i><b>7.3.1</b> 지수분포</a></li>
<li class="chapter" data-level="7.3.2" data-path="survival.html"><a href="survival.html#와이블분포"><i class="fa fa-check"></i><b>7.3.2</b> 와이블분포</a></li>
<li class="chapter" data-level="7.3.3" data-path="survival.html"><a href="survival.html#감마분포"><i class="fa fa-check"></i><b>7.3.3</b> 감마분포</a></li>
<li class="chapter" data-level="7.3.4" data-path="survival.html"><a href="survival.html#로그정규분포"><i class="fa fa-check"></i><b>7.3.4</b> 로그정규분포</a></li>
<li class="chapter" data-level="7.3.5" data-path="survival.html"><a href="survival.html#로그로지스틱분포"><i class="fa fa-check"></i><b>7.3.5</b> 로그로지스틱분포</a></li>
<li class="chapter" data-level="7.3.6" data-path="survival.html"><a href="survival.html#곰페르츠분포"><i class="fa fa-check"></i><b>7.3.6</b> 곰페르츠분포</a></li>
<li class="chapter" data-level="7.3.7" data-path="survival.html"><a href="survival.html#회귀모형aft"><i class="fa fa-check"></i><b>7.3.7</b> 회귀모형(AFT)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="survival.html"><a href="survival.html#cox-비례위험모형"><i class="fa fa-check"></i><b>7.4</b> Cox 비례위험모형</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="survival.html"><a href="survival.html#시간에-따라-변화하는-공변량이-있을-경우"><i class="fa fa-check"></i><b>7.4.1</b> 시간에 따라 변화하는 공변량이 있을 경우</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="survival.html"><a href="survival.html#경쟁위험모형"><i class="fa fa-check"></i><b>7.5</b> 경쟁위험모형</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="survival.html"><a href="survival.html#원인별-누적발생함수"><i class="fa fa-check"></i><b>7.5.1</b> 원인별 누적발생함수</a></li>
<li class="chapter" data-level="7.5.2" data-path="survival.html"><a href="survival.html#원인별-위험함수"><i class="fa fa-check"></i><b>7.5.2</b> 원인별 위험함수</a></li>
<li class="chapter" data-level="7.5.3" data-path="survival.html"><a href="survival.html#누적발생함수에-대한-회귀분석"><i class="fa fa-check"></i><b>7.5.3</b> 누적발생함수에 대한 회귀분석</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="survival.html"><a href="survival.html#sas-실습"><i class="fa fa-check"></i><b>7.6</b> SAS 실습</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="survival.html"><a href="survival.html#생명표-방법-1"><i class="fa fa-check"></i><b>7.6.1</b> 생명표 방법</a></li>
<li class="chapter" data-level="7.6.2" data-path="survival.html"><a href="survival.html#누적한계추정법-1"><i class="fa fa-check"></i><b>7.6.2</b> 누적한계추정법</a></li>
<li class="chapter" data-level="7.6.3" data-path="survival.html"><a href="survival.html#생존분포-비교-1"><i class="fa fa-check"></i><b>7.6.3</b> 생존분포 비교</a></li>
<li class="chapter" data-level="7.6.4" data-path="survival.html"><a href="survival.html#parametric-model"><i class="fa fa-check"></i><b>7.6.4</b> Parametric Model</a></li>
<li class="chapter" data-level="7.6.5" data-path="survival.html"><a href="survival.html#aft-model"><i class="fa fa-check"></i><b>7.6.5</b> AFT model</a></li>
<li class="chapter" data-level="7.6.6" data-path="survival.html"><a href="survival.html#cox-비례위험모형-1"><i class="fa fa-check"></i><b>7.6.6</b> Cox 비례위험모형</a></li>
<li class="chapter" data-level="7.6.7" data-path="survival.html"><a href="survival.html#cox-비례위험모형---time-dependent-covariate"><i class="fa fa-check"></i><b>7.6.7</b> Cox 비례위험모형 - time dependent covariate</a></li>
<li class="chapter" data-level="7.6.8" data-path="survival.html"><a href="survival.html#competing-risks"><i class="fa fa-check"></i><b>7.6.8</b> Competing Risks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="psm.html"><a href="psm.html"><i class="fa fa-check"></i><b>8</b> 성향점수(propensity score)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="psm.html"><a href="psm.html#observational-study"><i class="fa fa-check"></i><b>8.1</b> Observational Study?</a>
<ul>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#randomized-controlled-trials-gold-standard"><i class="fa fa-check"></i>Randomized Controlled Trials ("gold standard")</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#characteristics-of-rcts"><i class="fa fa-check"></i>Characteristics of RCTs</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#what-is-observational-data"><i class="fa fa-check"></i>What is Observational Data?</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#confounding-due-to-selection-bias"><i class="fa fa-check"></i>Confounding due to Selection Bias</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#impact-of-selection-bias-on-analytic-inferences"><i class="fa fa-check"></i>Impact of Selection Bias on Analytic Inferences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#statistical-adjustment-for-observational-data"><i class="fa fa-check"></i>Statistical Adjustment for Observational Data</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#addressing-selection-bias-with-exact-matching"><i class="fa fa-check"></i>Addressing Selection Bias with Exact Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-on-specific-variables"><i class="fa fa-check"></i>Matching on Specific Variables</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-on-specific-variables-1"><i class="fa fa-check"></i>Matching on Specific Variables</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="psm.html"><a href="psm.html#propensity-score"><i class="fa fa-check"></i><b>8.2</b> Propensity Score?</a>
<ul>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#general-procedure"><i class="fa fa-check"></i>General Procedure</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#choosing-variables-for-propensity-scores"><i class="fa fa-check"></i>Choosing Variables for Propensity Scores</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#calculate-propensity-score"><i class="fa fa-check"></i>Calculate Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#initial-checks-balance-across-groups"><i class="fa fa-check"></i>Initial Checks: Balance across Groups</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#check-balance-of-covariates"><i class="fa fa-check"></i>Check Balance of Covariates</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#assess-balance-with-standardized-differences"><i class="fa fa-check"></i>Assess Balance with Standardized Differences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#balance-of-covariates-caution"><i class="fa fa-check"></i>Balance of Covariates: Caution</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#matching-and-weighting-strategies"><i class="fa fa-check"></i>Matching and Weighting Strategies</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#choices-when-matching-sample-by-propensity-score"><i class="fa fa-check"></i>Choices When Matching Sample by Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#which-strategy-to-chooose"><i class="fa fa-check"></i>Which Strategy to Chooose?</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#evaluate-balance-in-sample-matched-or-weighted"><i class="fa fa-check"></i>Evaluate Balance in Sample Matched or Weighted</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#visualization-of-standardized-differences"><i class="fa fa-check"></i>Visualization of Standardized Differences</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#plots-of-covariates-between-groups"><i class="fa fa-check"></i>Plots of Covariates between Groups</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="psm.html"><a href="psm.html#propensity-score-methods"><i class="fa fa-check"></i><b>8.3</b> Propensity Score Methods</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="psm.html"><a href="psm.html#propensity-score-matching"><i class="fa fa-check"></i><b>8.3.1</b> Propensity Score Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#general-procedure-for-propensity-score-matching"><i class="fa fa-check"></i>General Procedure for Propensity Score Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#greedy-matching"><i class="fa fa-check"></i>Greedy Matching</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#mahalanobis-metric-matching"><i class="fa fa-check"></i>Mahalanobis Metric Matching</a></li>
<li class="chapter" data-level="8.3.2" data-path="psm.html"><a href="psm.html#stratification-using-propensity-score"><i class="fa fa-check"></i><b>8.3.2</b> Stratification using Propensity Score</a></li>
<li class="chapter" data-level="8.3.3" data-path="psm.html"><a href="psm.html#inverse-probability-of-treatment-weighting"><i class="fa fa-check"></i><b>8.3.3</b> Inverse Probability of Treatment Weighting</a></li>
<li class="chapter" data-level="8.3.4" data-path="psm.html"><a href="psm.html#propensity-score-adjustment-as-covariate"><i class="fa fa-check"></i><b>8.3.4</b> Propensity Score Adjustment as Covariate</a></li>
<li class="chapter" data-level="8.3.5" data-path="psm.html"><a href="psm.html#property-of-propensity-score"><i class="fa fa-check"></i><b>8.3.5</b> Property of Propensity Score</a></li>
<li class="chapter" data-level="" data-path="psm.html"><a href="psm.html#property-of-observational-studies"><i class="fa fa-check"></i>Property of Observational Studies</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="psm.html"><a href="psm.html#practice---sas"><i class="fa fa-check"></i><b>8.4</b> Practice - SAS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="psm.html"><a href="psm.html#greedy-nearest-neighbor-matching"><i class="fa fa-check"></i><b>8.4.1</b> Greedy Nearest Neighbor Matching</a></li>
<li class="chapter" data-level="8.4.2" data-path="psm.html"><a href="psm.html#propensity-score-stratification"><i class="fa fa-check"></i><b>8.4.2</b> Propensity Score Stratification</a></li>
<li class="chapter" data-level="8.4.3" data-path="psm.html"><a href="psm.html#inverse-probability-treatment-weighting"><i class="fa fa-check"></i><b>8.4.3</b> Inverse Probability Treatment Weighting</a></li>
<li class="chapter" data-level="8.4.4" data-path="psm.html"><a href="psm.html#matching-with-existing-propensity-scores"><i class="fa fa-check"></i><b>8.4.4</b> Matching with Existing propensity scores</a></li>
<li class="chapter" data-level="8.4.5" data-path="psm.html"><a href="psm.html#matching-with-existing-propensity-scores-1"><i class="fa fa-check"></i><b>8.4.5</b> Matching with Existing propensity scores</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ttest" class="section level1" number="1">
<h1><span class="header-section-number">Chapter 1</span> 평균차이 검정</h1>
<p>생명과학 분야의 연구에서는 실험군과 대조군을 비교한다거나 어떤 처리 전후의 변화가 있는지를 알아보는 분석을 해야 할 경우가 많다. 이 장에서는 반응이 연속형인 경우에 두 개의 독립적인 집단간에 차이가 있는가를 보는 방법과 짝지은 표본의 분석방법을 알아보자. 이러한 목적으로 시행되는 분석방법을 평균차이검정(t-test)이라 한다.</p>
<div id="일표본-t-검정" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> 일표본 <span class="math inline">\(t\)</span>-검정</h2>
<ul>
<li><p><span class="math inline">\(z\)</span>-test는 다음과 같은 두 가정 중 최소 하나의 가정을 요구함</p>
<ul>
<li><p>모집단의 분포는 정규(normal) 분포이고 모분산 <span class="math inline">\(\sigma^2\)</span>이 알려져
있다.</p></li>
<li><p>표본크기가 크다.</p></li>
<li><p>이때 표준화된 표본평균의 분포는 <span class="math inline">\(\frac{\bar{X}-\mu}{\sigma^2} \sim N(0,1)\)</span> 이다.</p></li>
</ul></li>
<li><p>현실적으로 모분산 <span class="math inline">\(\sigma^2\)</span>은 대부분 알려져 있지 않음</p></li>
<li><p><span class="math inline">\(X_1, \cdots, X_n\)</span>이 평균 <span class="math inline">\(\mu\)</span>, 분산 <span class="math inline">\(\sigma^2\)</span>인 정규분포를 따르는 모집단에서 나온 확률 표본이라고 하자.</p></li>
<li><p>만약 표본크기 <span class="math inline">\(n\)</span>이 크고 모집단의 분포가 평균이 <span class="math inline">\(\mu\)</span> 분산이
<span class="math inline">\(\sigma^2\)</span>(unknown)인 정규분포라면, 자유도가 <span class="math inline">\(n-1\)</span>인 <span class="math inline">\(t\)</span>분포를
따르는 검정통계량 <span class="math inline">\(T\)</span>를 정의할 수 있으며, 이러한 검정 통계량을
이용하여 모평균 <span class="math inline">\(\mu\)</span>에 대해 검정하는 방법을 일표본
<span class="math inline">\(t\)</span>-검정(one-sample t-test)이라고 함</p></li>
<li><p>가설의 형태</p>
<ul>
<li><p>양측검정 : <span class="math inline">\(H_0 : \mu=\mu_0 \quad vs. \quad H_1 : \mu \ne \mu_0\)</span></p></li>
<li><p>단측(좌측)검정 : <span class="math inline">\(H_0 : \mu=\mu_0 \quad vs. \quad H_1 : \mu &lt; \mu_0\)</span></p></li>
<li><p>단측(우측)검정 : <span class="math inline">\(H_0 : \mu=\mu_0 \quad vs. \quad H_1 : \mu &gt; \mu_0\)</span></p></li>
</ul></li>
<li><p>검정통계량 <span class="math display">\[T=\frac{\bar{X} - \mu_0}{S/\sqrt{n}} \sim t_{(n-1)}\]</span></p></li>
<li><p>유의수준 <span class="math inline">\(\alpha\)</span>에서 임계값
<span class="math display">\[\pm t_{\alpha/2,(n-1)} \quad \text{또는} \quad \pm t_{\alpha,(n-1)}\]</span></p></li>
<li><p>양측검정에서의 기각역</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if
<span class="math display">\[T \ge t_{\alpha/2,(n-1)} \quad \text{또는} \quad T \le -t_{\alpha/2,(n-1)}\]</span></li>
</ul></li>
<li><p>단측검정에서의 기각역</p>
<ul>
<li><p>In right-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \ge t_{\alpha,(n-1)}\]</span></p></li>
<li><p>In left-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \le -t_{\alpha,(n-1)}\]</span></p></li>
</ul></li>
</ul>
<p><img src="ttest/f10.jpg" style="width:100.0%" /></p>
<p>예제) Suppose the "average" cholesterol level in children is <span class="math inline">\(175mg/dl\)</span> and
the mean cholesterol level of <span class="math inline">\(10\)</span> children whose fathers died from
heart disease is <span class="math inline">\(200ml/dl\)</span> and the sample standard deviation is
<span class="math inline">\(50mg/dl\)</span>. Test the hypothesis that the mean cholesterol level is higher
in this group than in the general population.</p>
<p>풀이)</p>
<ol style="list-style-type: decimal">
<li><p>The hypothesis:
<span class="math inline">\(H_0 : \mu=175, \hskip5pt vs. \hskip5pt H_1 : \mu &gt; 175\)</span></p></li>
<li><p>Significance level: <span class="math inline">\(\alpha=0.05\)</span></p></li>
<li><p>Rejection region: <span class="math inline">\(t&gt;t_{(\alpha,n-1)}=t_{(0.05,9)}=1.833\)</span></p></li>
<li><p>Value of test statistic: <span class="math inline">\(t_0=\frac{200-175}{50\sqrt{10}}=1.58\)</span></p></li>
<li><p><span class="math inline">\(P\)</span>-value: <span class="math inline">\(P(t_9&gt;1.58)=0.074\)</span></p></li>
<li><p>Conclusion: Because the value of test statistic, <span class="math inline">\(1.58\)</span> is less than
the critical value <span class="math inline">\(1.833\)</span> or the P-value <span class="math inline">\(0.074\)</span> is greater than
the siganificance level <span class="math inline">\(0.05\)</span>, we conclude that our results are not
statistically significant and the null hypothesis is accepted.</p></li>
</ol>
<p>예제) 새로운 항우울제의 치료 효과를 증명하기 위해 40명의 우울증 환자에게
항우울제를 투여하였다. 1개월의 치료 뒤 측정한 우울증 점수를 통해
항우울제의 효과를 알아보고자 한다. 이때 우울증 점수가 25점 이하이면
항우울제가 효과가 있다고 판단한다. 항우울제가 효과가 있는지 검정하라.</p>
<p><img src="ttest/ex1.jpg" style="width:85.0%" /></p>
<div id="with-r" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> With R</h3>
<ol style="list-style-type: decimal">
<li>데이터 입력</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="ttest.html#cb1-1" aria-hidden="true" tabindex="-1"></a>score <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">16</span>,<span class="dv">27</span>,<span class="dv">15</span>,<span class="dv">21</span>,<span class="dv">14</span>,<span class="dv">16</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">23</span>,<span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">27</span>,<span class="dv">13</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">23</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">31</span>,<span class="dv">33</span>,<span class="dv">28</span>,<span class="dv">36</span>,<span class="dv">18</span>,<span class="dv">21</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">33</span>,<span class="dv">32</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">23</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>정규성 검정</li>
</ol>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="ttest.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(score)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  score
## W = 0.9763, p-value = 0.5546</code></pre>
<p>정규성 검정의 결과를 살펴보면 <span class="math inline">\(P\)</span>-value가 0.5546으로 유의수준 5% 하에서 데이터가 정규성을 만족한다는 귀무가설을 기각하지 못한다.</p>
<ol start="3" style="list-style-type: decimal">
<li>일표본 t-검정</li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="ttest.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">### t-test</span></span>
<span id="cb4-2"><a href="ttest.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(score,<span class="at">mu=</span><span class="dv">25</span>,<span class="at">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="at">conf.level=</span><span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  score
## t = -2.2664, df = 39, p-value = 0.01453
## alternative hypothesis: true mean is less than 25
## 90 percent confidence interval:
##     -Inf 24.0442
## sample estimates:
## mean of x 
##     22.75</code></pre>
<p>표본 평균은 22.75, <span class="math inline">\(t\)</span> 통계량은 -2.2664로 <span class="math inline">\(P\)</span>-value는 0.01453이다. <span class="math inline">\(P\)</span>-value가 유의수준 5%보다 작으므로 통계적으로 유의하다. 이는 표본평균이 귀무가설의 평균인 25보다 작으므로 항우울제는 유의미한 효과가 있다고 할 수 있다. 이때 신뢰구간은 단측 검정을 시행하였기 때문에 (<span class="math inline">\(-\infty, 24.0442\)</span>)로 나타나며, 25를 포함하지 않으므로 역시 통계적 유의성을 보장한다.
여기서 단측검정은 t.test의 인수 중 alternative=“less”이면 좌측, alternative=“greater”는 우측 검정, default는 양측검정인 alternative=“two.sided”로 지정되어 있다.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="ttest.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">### t-test : two sided test</span></span>
<span id="cb6-2"><a href="ttest.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(score,<span class="at">mu=</span><span class="dv">25</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  score
## t = -2.2664, df = 39, p-value = 0.02905
## alternative hypothesis: true mean is not equal to 25
## 95 percent confidence interval:
##  20.74195 24.75805
## sample estimates:
## mean of x 
##     22.75</code></pre>
<ul>
<li><span class="math inline">\(P\)</span>-value <span class="math inline">\(0.0291\)</span>은 유의수준 <span class="math inline">\(5\%\)</span>보다 작으므로 통계적으로
유의하다. 이때 표본평균은 <span class="math inline">\(22.75\)</span>로 <span class="math inline">\(25\)</span>보다 작으므로 항우울제는
효과가 있다고 할 수 있다.</li>
</ul>
</div>
<div id="with-sas" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> With SAS</h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data onettest;
input no score @@;
cards;
1   10  11  25  21  23  31  18
2   16  12  28  22  26  32  21
3   27  13  27  23  27  33  26
4   15  14  13  24  23  34  28
5   21  15  15  25  16  35  29
6   14  16  16  26  18  36  33
7   16  17  21  27  31  37  32
8   21  18  22  28  33  38  16
9   22  19  25  29  28  39  18
10  23  20  28  30  36  40  23
;
run;</code></pre>
<div id="one-sided-test" class="section level5 unnumbered">
<h5>One sided test</h5>
<pre><code>proc ttest data=onettest h0=25 sides=L;
var score;
run;</code></pre>
<ul>
<li>Results - one sided test</li>
</ul>
<p><img src="ttest/ex4.jpg" /></p>
<ul>
<li><span class="math inline">\(P\)</span>-value <span class="math inline">\(0.0145\)</span>는 유의수준 <span class="math inline">\(5\%\)</span>보다 작으므로 귀무가설을
기각한다. 따라서 항우울제는 효과가 있다고 할 수 있다.</li>
</ul>
</div>
<div id="two-sided-test" class="section level5 unnumbered">
<h5>Two sided test</h5>
<pre><code>proc ttest data=onettest h0=25;
var score;
run;</code></pre>
<ul>
<li>Results - two sided test</li>
</ul>
<p><img src="ttest/ex3.jpg" /></p>
<ul>
<li><span class="math inline">\(P\)</span>-value <span class="math inline">\(0.0291\)</span>은 유의수준 <span class="math inline">\(5\%\)</span>보다 작으므로 통계적으로
유의하다. 이때 표본평균은 <span class="math inline">\(22.75\)</span>로 <span class="math inline">\(25\)</span>보다 작으므로 항우울제는
효과가 있다고 할 수 있다.</li>
</ul>
</div>
</div>
</div>
<div id="독립표본-t-검정" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> 독립표본 <span class="math inline">\(t\)</span>-검정</h2>
<ul>
<li><p>확률표본 (<span class="math inline">\(X_1, X_2, \ldots , X_{n_1}\)</span>)과
(<span class="math inline">\(Y_1, Y_2, \ldots , Y_{n_2}\)</span>)이 서로 독립인 두 정규모집단
<span class="math inline">\(N(\mu_1, \sigma_1^2)\)</span>, <span class="math inline">\(N(\mu_2, \sigma_2^2)\)</span>으로부터 각각 표본크기
<span class="math inline">\(n_1\)</span>과 <span class="math inline">\(n_2\)</span>만큼 추출되고, 모분산 <span class="math inline">\(\sigma_1^2\)</span>과 <span class="math inline">\(\sigma_2^2\)</span>이
알려지지 않았을 때, 두 모평균 차 <span class="math inline">\(\mu_1 - \mu_2\)</span>에 대한 검정방법을
독립표본 <span class="math inline">\(t\)</span>-검정(independent two-sample <span class="math inline">\(t\)</span>-test)이라고 함</p></li>
<li><p>검정통계량은 두 모분산이 알려지지 않았지만, 두 모분산이 서로 같다고
가정했을 경우(<span class="math inline">\(\sigma_1^2=\sigma_2^2=\sigma^2\)</span>)와 그렇지 않은
경우(<span class="math inline">\(\sigma_1^2\ne\sigma_2^2\)</span>)로 구분하여 사용됨</p></li>
<li><p>가설의 형태</p>
<ul>
<li><p>양측검정 :
<span class="math inline">\(H_0 : \mu_1-\mu_2=d_0 \quad vs. \quad H_1 : \mu_1-\mu_2 \ne d_0\)</span></p></li>
<li><p>단측(좌측)검정 :
<span class="math inline">\(H_0 : \mu_1-\mu_2=d_0 \quad vs. \quad H_1 : \mu_1-\mu_2 &lt; d_0\)</span></p></li>
<li><p>단측(우측)검정 :
<span class="math inline">\(H_0 : \mu_1-\mu_2=d_0 \quad vs. \quad H_1 : \mu_1-\mu_2 &gt; d_0\)</span></p></li>
</ul></li>
<li><p><strong>검정통계량: 두 모집단의 분산이 같은 경우</strong>
<span class="math display">\[T=\frac{(\bar{X}-\bar{Y})-d_0}{S_p\sqrt{1/n_1+1/n_2}}\sim t_{(n_1+n_2-2)}\]</span>
여기서 사용되는 <span class="math inline">\(S_p\)</span>는 합동표준편차
<span class="math display">\[S_p=\sqrt{\frac{(n_1-1)S_1^2+(n_2-1)S_2^2}{n_1+n_2-2}}\]</span> 이고
<span class="math inline">\(S_1^2\)</span>과 <span class="math inline">\(S_2^2\)</span>은 각각 크기가 <span class="math inline">\(n_1\)</span>과 <span class="math inline">\(n_2\)</span>인 표본으로부터 구한
표본분산임</p></li>
<li><p><strong>검정통계량: 두 모집단의 분산이 다른 경우</strong>
<span class="math display">\[T=\frac{(\bar{X}-\bar{Y})-d_0}{\sqrt{S_1^2/n_1+S_2^2/n_2}}\sim t_{(\nu)}\]</span>
여기서 자유도 <span class="math inline">\(\nu\)</span>는 구간추정에서와 마찬가지로 새터스웨이트의
자유도를 이용함
<span class="math display">\[\nu=\frac{\left(\frac{S_1^2}{n_1}+\frac{S_2^2}{n_2} \right) ^2}{\frac{(S_1^2/n_1)^2}{n_1-1}+\frac{(S_2^2/n_2)^2}{n_2-1}}\]</span></p></li>
<li><p>양측검정에서의 기각역</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if
<span class="math display">\[T \ge t_{\alpha/2,(d.f)} \quad \text{또는} \quad T \le -t_{\alpha/2,(d.f)}\]</span></li>
</ul></li>
<li><p>단측검정에서의 기각역</p>
<ul>
<li><p>In right-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \ge t_{\alpha,(d.f)}\]</span></p></li>
<li><p>In left-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \le -t_{\alpha,(d.f)}\]</span></p></li>
</ul></li>
</ul>
<p><img src="ttest/f11.jpg" /></p>
<p>예제) Suppose a sample of eight <span class="math inline">\(35\)</span>- to <span class="math inline">\(39\)</span>-year-old nonpregnant,
premenopausal OC users who work in a company are identified who have
mean systolic blood pressure of <span class="math inline">\(132.86mmHG\)</span> and sample standard
deviation of <span class="math inline">\(15.34mmHg\)</span>. A sample of twenty-one <span class="math inline">\(35\)</span>- to <span class="math inline">\(39\)</span>-year-old
nonpregnant, premenopausal non-OC users are similarly identified who
have mean systolic blood pressure of <span class="math inline">\(127.44mmHg\)</span> and sample standard
deviation of <span class="math inline">\(18.23mmHg\)</span>. When the two variances are equal, assess the
statistical significance of mean difference in blood pressure between
the two group.</p>
<p>풀이)</p>
<ol style="list-style-type: decimal">
<li><p>The hypothesis:
<span class="math inline">\(H_0 : \mu_1=\mu_2 \quad vs. \quad H_1 : \mu_1 \ne \mu_2\)</span></p></li>
<li><p>Significance level: <span class="math inline">\(\alpha=0.05\)</span></p></li>
<li><p>Rejection region: <span class="math inline">\(|t|&gt;t_{(\alpha/2,n-1)}=t_{(0.025,27)}=2.052\)</span></p></li>
<li><p>Value of test statistic:</p></li>
</ol>
<p><span class="math display">\[s_p^2=\frac{7(15.34)^2+20(18.23)^2}{27}=307.18\]</span></p>
<p><span class="math display">\[t_0=\frac{132.86-127.44}{17.527\sqrt{1/8+1/21}}=0.74\]</span></p>
<ol start="5" style="list-style-type: decimal">
<li><p><span class="math inline">\(P\)</span>-value: <span class="math inline">\(2\times P(t_27&gt;0.74)=0.46\)</span></p></li>
<li><p>Conclusion: Because the value of test statistic is
<span class="math inline">\(-2.052&lt;0.74&lt;2.052\)</span> or the P-value <span class="math inline">\(0.46\)</span> is greater than the
siganificance level <span class="math inline">\(0.05\)</span>, we conclude that our results are not
statistically significant and the null hypothesis is accepted. Thus
the mean blood pressures of the two groups of OC users and non-OC
users do not significantly differ from each other.</p></li>
</ol>
<div id="두-모분산-비의-검정" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> 두 모분산 비의 검정</h3>
<ul>
<li><p>정규분포를 따르는 상호 독립인 두 모집단 <span class="math inline">\(N(\mu_1, \sigma_1^2)\)</span>,
<span class="math inline">\(N(\mu_2,\sigma_2^2)\)</span>으로부터의 표본크기가 <span class="math inline">\(n_1\)</span>과 <span class="math inline">\(n_2\)</span>인
확률표본을 각각 <span class="math inline">\(X_1, \ldots, X_{n_1}\)</span>과 <span class="math inline">\(Y_1, \ldots, Y_{n_2}\)</span>라고
할 때 이에 대한 표본분산을 각각
<span class="math inline">\(S_1^2=\frac{1}{n_1-1}\sum_{i=1}^{n_1}(X_i-\bar{X})^2\)</span>,
<span class="math inline">\(S_2^2=\frac{1}{n_2-1}\sum_{i=1}^{n_2}(Y_i-\bar{Y})^2\)</span>이라고 하자.</p></li>
<li><p>그러면 <span class="math inline">\(U=(n_1-1)S_1^2/\sigma_1^2\)</span>와 <span class="math inline">\(V=(n_2-1)S_2^2/\sigma_2^2\)</span>은
각각 자유도가 <span class="math inline">\(n_1-1\)</span>, <span class="math inline">\(n_2-1\)</span>인 <span class="math inline">\(\chi^2\)</span>분포를 따르고 <span class="math inline">\(F\)</span>분포의
정의에 의해 다음이 성립함
<span class="math display">\[F=\frac{U/(n_1-1)}{v/(n_2-1)}=\frac{S_1^2/\sigma_1^2}{S_2^2/\sigma_2^2}\sim F_{n_1-1,n_2-1}\]</span></p></li>
<li><p>귀무가설을 <span class="math inline">\(H_0 : \sigma_1^2/\sigma_2^2=1\)</span>(즉,
<span class="math inline">\(\sigma_1^2=\sigma_2^2\)</span>)이라고 정의하면 <span class="math inline">\(H_0\)</span>하에서의 검정통계량
<span class="math inline">\(F_0\)</span>는 다음과 같음 <span class="math display">\[F_0=\frac{S_1^2}{S_2^2}\sim F_{n_1-1,n_2-1}\]</span></p></li>
<li><p>따라서 유의수준 <span class="math inline">\(\alpha\)</span>하에서 <span class="math inline">\(\sigma_1^2\)</span>과 <span class="math inline">\(\sigma_2^2\)</span>의 동일성
여부에 대한 가설검정 절차를 요약하면 다음과 같음</p>
<p><img src="ttest/f18.jpg" style="width:90.0%" /></p></li>
<li><p>두 모분산 비의 검정에서 유의수준 <span class="math inline">\(\alpha\)</span>는 우측검정의 경우는
<span class="math inline">\(\alpha=P(F_0\ge F_{(\alpha,n_1-1,n_2-1)})\)</span>이고 좌측검정의 경우는
<span class="math inline">\(\alpha=P(F_0\le F_{(1-\alpha,n_1-1,n_2-1)})\)</span>임</p></li>
<li><p>여기서
<span class="math inline">\(F_{(1-\alpha,n_1-1,n_2-1)}=(F_{(\alpha,n_2-1,n_1-1)})^{-1}\)</span>이므로
좌측검정의 유의수준 <span class="math inline">\(\alpha\)</span>는
<span class="math inline">\(\alpha=P(F_0\le (F_{(\alpha,n_2-1,n_1-1)})^{-1})\)</span>과 같음</p></li>
<li><p>양측검정의 경우는
<span class="math inline">\(\alpha=P(F_0\ge F_{(\alpha/2,n_1-1,n_2-1)}) \hskip5pt \text{또는} \hskip5pt F_0\le (F_{(\alpha/2,n_2-1,n_1-1)})^{-1}\)</span></p></li>
</ul>
<p>예제) <span class="math inline">\(12\)</span>세의 남아와 여아 중에서 남아 <span class="math inline">\(25\)</span>명, 여아 <span class="math inline">\(23\)</span>명을 단순무작위
추출하여 폐활량을 조사한 결과, 남아의 분산은 <span class="math inline">\(0.145\)</span>, 여아의 분산은
<span class="math inline">\(0.0942\)</span>였다.(남녀 폐활량은 정규분포를 따른다고 가정) 두 모집단의 분산이
같은 지를 유의수준 <span class="math inline">\(5\%\)</span>에서 검정하라.(단, <span class="math inline">\(1\)</span>: 남아, <span class="math inline">\(2\)</span>: 여아)</p>
<p>풀이)</p>
<ol style="list-style-type: decimal">
<li><p>귀무가설과 대립가설:
<span class="math inline">\(H_0 : \sigma_1^2=\sigma_2^2, \hskip5pt vs. \hskip5pt H_1 : \sigma_1^2\ne \sigma_2^2\)</span></p></li>
<li><p>유의수준: <span class="math inline">\(\alpha=0.05\)</span></p></li>
<li><p>임계값: <span class="math inline">\(F_{(0.025,24,22)}=2.3315\)</span>,
<span class="math inline">\((F_{(0.025,22,24)})^{-1}=0.4356\)</span></p></li>
<li><p>기각역: <span class="math inline">\(F_0\ge 2.3315\)</span> 또는 <span class="math inline">\(F_0\le 0.4356\)</span></p></li>
<li><p>검정통계량값: <span class="math inline">\(s_1^2=0.145\)</span>, <span class="math inline">\(s_2^2=0.0942\)</span>,
<span class="math inline">\(f_0=\frac{0.145}{0.0942}=1.5393\)</span></p></li>
<li><p><span class="math inline">\(P\)</span>-값 계산: 검정통계량의 값 <span class="math inline">\(1.5393\)</span>은 중심에서 우측영역에
위치하므로 <span class="math inline">\(P\)</span>-값=<span class="math inline">\(2\times P(F\ge 1.5393)=0.3219\)</span>이다.</p></li>
<li><p><span class="math inline">\(f_0=1.5393\)</span>은 기각역에 속하지 않으므로 유의수준 <span class="math inline">\(\alpha=0.05\)</span>에서
귀무가설 <span class="math inline">\(H_0\)</span>를 기각할 수 없다. 또한 <span class="math inline">\(P\)</span>-값<span class="math inline">\(&gt;\alpha\)</span>이므로 귀무가설
<span class="math inline">\(H_0\)</span>를 기각할 수 없다. 따라서 유의수준 <span class="math inline">\(5\%\)</span>에서 두 모집단의 분산은
같다고 할 수 있다.</p></li>
</ol>
<p>예제) 새로운 항우울제의 치료 효과를 증명하기 위해 <span class="math inline">\(40\)</span>명의 우울증 환자를 군당 <span class="math inline">\(20\)</span>명씩 실험군과 대조군으로 무작위 배정하여 실험군에게는 항우울제를,
대조군에게는 위약을 투여하였다. <span class="math inline">\(1\)</span>개월의 치료 뒤 측정한 우울증 점수를
통해 두 군의 치료 효과의 크기를 비교하고자 한다. 두 군 사이에 우울증
점수의 차이가 있는지 검정하라.</p>
<p><img src="ttest/ex5.jpg" style="width:100.0%" /></p>
</div>
<div id="with-r-1" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> With R</h3>
<ol style="list-style-type: decimal">
<li>데이터 입력</li>
</ol>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="ttest.html#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">16</span>,<span class="dv">27</span>,<span class="dv">15</span>,<span class="dv">21</span>,<span class="dv">14</span>,<span class="dv">16</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">23</span>,<span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">27</span>,<span class="dv">13</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">25</span>,<span class="dv">28</span>)</span>
<span id="cb11-2"><a href="ttest.html#cb11-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">23</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">31</span>,<span class="dv">33</span>,<span class="dv">28</span>,<span class="dv">36</span>,<span class="dv">18</span>,<span class="dv">21</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">33</span>,<span class="dv">32</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">23</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>등분산 검정</li>
</ol>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="ttest.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(x,y)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  x and y
## F = 0.81402, num df = 19, denom df = 19, p-value = 0.6583
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.3221986 2.0565791
## sample estimates:
## ratio of variances 
##           0.814019</code></pre>
<p>두 집단의 분산이 같다는 귀무가설에 대해 <span class="math inline">\(P\)</span>-value는 0.66583으로 유의수준 5%하에서 귀무가설을 기각하지 못한다. 따라서 두 집단의 분산은 같다고 할 수 있다.</p>
<ol start="3" style="list-style-type: decimal">
<li>독립표본 T-검정</li>
</ol>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="ttest.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">var.equal=</span>T)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  x and y
## t = -2.7164, df = 38, p-value = 0.00988
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.726292 -1.273708
## sample estimates:
## mean of x mean of y 
##     20.25     25.25</code></pre>
<p>x의 표본평균은 20.25, y의 표본평균은 25.25로 차이는 5만큼 나타난다. 이에 대한 통계적 유의성을 살펴보면, <span class="math inline">\(P\)</span>-value가 0.00988로 유의수준 5%보다 작게 나타난다. 따라서 두 집단의 우울증 점수는 유의미한 차이가 있다고 할 수 있다. 여기서 두 집단의 분산이 같으면 t.test의 인수에서 var.equal=T로, 분산이 다르면 var.equal=F로 지정한다.</p>
</div>
<div id="with-sas-1" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> With SAS</h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data twottest;
input no group score @@;
cards;
1   1   10  11  1   25  21  2   23  31  2   18
2   1   16  12  1   28  22  2   26  32  2   21
3   1   27  13  1   27  23  2   27  33  2   26
4   1   15  14  1   13  24  2   23  34  2   28
5   1   21  15  1   15  25  2   16  35  2   29
6   1   14  16  1   16  26  2   18  36  2   33
7   1   16  17  1   21  27  2   31  37  2   32
8   1   21  18  1   22  28  2   33  38  2   16
9   1   22  19  1   25  29  2   28  39  2   18
10  1   23  20  1   28  30  2   36  40  2   23
;
run;

proc ttest data=twottest;
class group
var score;
run;</code></pre>
<ul>
<li>Results</li>
</ul>
<p><img src="ttest/ex7_1.jpg" /></p>
<p>x의 표본평균은 20.25, y의 표본평균은 25.25로 차이는 5만큼 나타난다.</p>
<p><img src="ttest/ex7_2.jpg" /></p>
<p>두 집단의 분산이 같다는 귀무가설에 대해 <span class="math inline">\(P\)</span>-value는 0.66583으로 유의수준 5%하에서 귀무가설을 기각하지 못한다. 따라서 두 집단의 분산은 같다고 할 수 있다.</p>
<p>두 집단의 평균 차이에 대한 통계적 유의성을 살펴보면, <span class="math inline">\(P\)</span>-value가 0.0099로 유의수준 5%보다 작게 나타난다. 따라서 두 집단의 우울증 점수는 유의미한 차이가 있다고 할 수 있다. 여기서 두 집단의 분산이 같으면 pooled의 결과를, 두 집단의 분산이 다르면 Satterthwaite 결과를 해석한다.</p>
<p>아래의 그림은 각 집단의 값이 정규분포를 따르는지(정규성)을 살펴보기위해 histogram과 Q-Q plot을 통해 자료의 분포를 살펴본 결과이다.</p>
<p><img src="ttest/ex7_3.jpg" /></p>
<p><img src="ttest/ex7_4.jpg" style="width:80.0%" /></p>
</div>
</div>
<div id="대응표본-t-검정" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> 대응표본 <span class="math inline">\(t\)</span>-검정</h2>
<ul>
<li><p>관측값들이 짝을 이루고 있는 표본을 대응표본(paired sample) 이라고 함</p></li>
<li><p>예를 들어 고혈압 환자에 대한 치료제의 임상시험을 한다고 할 때 우리는
치료제가 효과가 있는지에 관심이 있으며, 이것을 조사하기 위해서
<span class="math inline">\(n\)</span>명의 고혈압 환자를 추출하여 동일한 환자에게서 치료제를 투여하기
전과 투여한 후의 혈압을 측정하여 관찰하였다고 하면 투여하기 전의
<span class="math inline">\(n\)</span>개의 관찰값과 투여한 후의 <span class="math inline">\(n\)</span>개의 관찰값은 서로 짝을 이루며
대응되는데, 이러한 표본을 대응표본이라고 함</p></li>
<li><p><span class="math inline">\(n\)</span>개의 짝을 이루는 대응표본의 차이, 즉 투여전과 투여 후의 혈압의
차이를 분석하기 위해서는 관찰값들 각각의 차이 <span class="math inline">\(D_i=X_i-Y_i\)</span>를
계산하여 단일표본으로 생각하면 됨</p></li>
<li><p>모집단의 차이 <span class="math inline">\(\Delta\)</span>에 대한 검정은 검정통계량에 평균 <span class="math inline">\(\bar{D}\)</span>를
사용하며, 이러한 검정법을 대응표본 <span class="math inline">\(t\)</span>-검정(paired sample
<span class="math inline">\(t\)</span>-test)이라고 함</p></li>
<li><p><span class="math inline">\(n\)</span>개의 차이 <span class="math inline">\(D_1,\ldots, D_n(D_i=X_i-Y_i)\)</span>이 정규모집단으로부터의
추출된 확률표본이라 하고 모집단 차이 <span class="math inline">\(\Delta\)</span>에 대한 귀무가설이
<span class="math inline">\(H_0 : \Delta=d_0\)</span>라고 하면 계산된 검정통계량은 다음과 같이
주어지고, 이것은 자유도가 <span class="math inline">\(n-1\)</span>인 <span class="math inline">\(t\)</span>분포를 따름</p>
<p><span class="math display">\[T=\frac{\bar{D}-d_0}{S_d/\sqrt{n}}\sim t_{(n-1)}\]</span> 여기서
<span class="math inline">\(S_d^2=\frac{1}{n-1}\sum_{i=1}^n(D_i-\bar{D})^2\)</span>,
<span class="math inline">\(\bar{D}=\frac{1}{n}\sum_{i=1}^nD_i\)</span>.</p>
<p><img src="ttest/f13.jpg" style="width:90.0%" /></p></li>
<li><p>가설의 형태</p>
<ul>
<li>양측검정 : <span class="math inline">\(H_0 : \Delta=d_0 \quad vs. \quad H_1 : \Delta \ne d_0\)</span></li>
<li>단측(좌측)검정 :
<span class="math inline">\(H_0 : \Delta=d_0 \quad vs. \quad H_1 : \Delta &lt; d_0\)</span></li>
<li>단측(우측)검정 :
<span class="math inline">\(H_0 : \Delta=d_0 \quad vs. \quad H_1 : \Delta &gt; d_0\)</span></li>
</ul></li>
<li><p>검정통계량 <span class="math display">\[T=\frac{\bar{D}-d_0}{S_d/\sqrt{n}}\sim t_{(n-1)}\]</span></p></li>
<li><p>유의수준 <span class="math inline">\(\alpha\)</span>에서 임계값
<span class="math display">\[\pm t_{\alpha/2,(n-1)} \quad \text{또는} \quad \pm t_{\alpha,(n-1)}\]</span></p></li>
<li><p>양측검정에서의 기각역</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if
<span class="math display">\[T \ge t_{\alpha/2,(n-1)} \quad \text{또는} \quad T \le -t_{\alpha/2,(n-1)}\]</span></li>
</ul></li>
<li><p>단측검정에서의 기각역</p>
<ul>
<li>In right-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \ge t_{\alpha,(n-1)}\]</span></li>
<li>In left-tail test, reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[T \le -t_{\alpha,(n-1)}\]</span></li>
</ul></li>
</ul>
<p>예제) 다음 자료는 지난 <span class="math inline">\(20\)</span>일 동안에 한 극장내의 <span class="math inline">\(A\)</span>매표소와 <span class="math inline">\(B\)</span>매표소의 영화 관람권 판매수이다. 두 매표소간의 평균 판매 수에 차이가 있는지 유의수준
<span class="math inline">\(5\%\)</span>에서 검정하라.</p>
<p><img src="ttest/f14.jpg" style="width:90.0%" /></p>
<p>풀이)</p>
<ol style="list-style-type: decimal">
<li><p>귀무가설과 대립가설:
<span class="math inline">\(H_0 : \Delta=0, \hskip5pt vs. \hskip5pt H_1 : \Delta\ne 0\)</span></p></li>
<li><p>유의수준: <span class="math inline">\(\alpha=0.05\)</span></p></li>
<li><p>임계값: <span class="math inline">\(t_{(0.025,19)}=2.093\)</span>, <span class="math inline">\(-t_{(0.025,19)}=-2.093\)</span></p></li>
<li><p>기각역: <span class="math inline">\(T\ge 2.093\)</span> 또는 <span class="math inline">\(T\le -2.093\)</span></p></li>
<li><p>검정통계량값 계산: <span class="math inline">\(d_i=x_i-y_i\)</span>라면 <span class="math inline">\(\bar{d}=0.505\)</span>, <span class="math inline">\(s_d^2=0.378\)</span>,
<span class="math inline">\(n=20\)</span>, <span class="math inline">\(t_0=\frac{0.505}{\sqrt{0.378/20}}=3.6733\)</span></p></li>
<li><p><span class="math inline">\(t_0=3.6733\)</span>은 기각역에 속하므로 유의수준 <span class="math inline">\(\alpha=0.05\)</span>에서 귀무가설
<span class="math inline">\(H_0\)</span>를 기각한다. 따라서 두 매표소의 판매 수에는 차이가 있다고 할 수
있다.</p></li>
<li><p><span class="math inline">\(P\)</span>-값 계산: <span class="math inline">\(P\)</span>-값=<span class="math inline">\(2\times P(T\ge 3.6733)=0.0016\)</span></p></li>
</ol>
<p>따라서 <span class="math inline">\(P\)</span>-값<span class="math inline">\(&lt;\alpha\)</span>이므로 귀무가설 <span class="math inline">\(H_0\)</span>를 기각한다.</p>
<p>예제) 새로운 항우울제의 치료 효과를 증명하기 위한 연구이다. 총 <span class="math inline">\(26\)</span>명의 우울증
환자를 대상으로 항우울제 치료전/후(Pre/Post)의 우울증 점수를 측정하였다.
치료 전과 비교하여 새 항우울제 치료 후 우울증 점수가 유의하게
감소하였는지 검정하라.</p>
<p><img src="ttest/ex8.jpg" /></p>
<div id="with-r-2" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> With R</h3>
<ol style="list-style-type: decimal">
<li>데이터 입력</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="ttest.html#cb17-1" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">38</span>,<span class="dv">26</span>,<span class="dv">25</span>,<span class="dv">32</span>,<span class="dv">28</span>,<span class="dv">34</span>,<span class="dv">27</span>,<span class="dv">33</span>,<span class="dv">32</span>,<span class="dv">18</span>,<span class="dv">25</span>,<span class="dv">29</span>,<span class="dv">27</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">31</span>,<span class="dv">34</span>,<span class="dv">29</span>,<span class="dv">28</span>,<span class="dv">34</span>,<span class="dv">33</span>,<span class="dv">24</span>,<span class="dv">26</span>,<span class="dv">29</span>,<span class="dv">28</span>)</span>
<span id="cb17-2"><a href="ttest.html#cb17-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">24</span>,<span class="dv">22</span>,<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">24</span>,<span class="dv">31</span>,<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">17</span>,<span class="dv">8</span>,<span class="dv">12</span>,<span class="dv">19</span>,<span class="dv">16</span>,<span class="dv">12</span>,<span class="dv">18</span>,<span class="dv">24</span>,<span class="dv">16</span>,<span class="dv">17</span>,<span class="dv">21</span>,<span class="dv">27</span>,<span class="dv">29</span>,<span class="dv">24</span>,<span class="dv">22</span>,<span class="dv">23</span>,<span class="dv">19</span>,<span class="dv">16</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>대응표본 t-검정</li>
</ol>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="ttest.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(post, pre, <span class="at">paired=</span>T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  post and pre
## t = -9.6667, df = 25, p-value = 6.327e-10
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.824189  -7.021964
## sample estimates:
## mean of the differences 
##               -8.923077</code></pre>
<p>결과를 살펴보면 <span class="math inline">\(p\)</span>-value는 6.327e-10으로 유의수준 5%보다 아주 작은 값임을 알 수 있다. 이때 post - pre의 평균은 -8.9로 새 항우울제 치료 후 우울증 점수가 유의하게 감소하였음을 알 수 있다.</p>
<ol start="3" style="list-style-type: decimal">
<li>차이를 통한 일표본 t-검정</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="ttest.html#cb20-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> post<span class="sc">-</span>pre</span>
<span id="cb20-2"><a href="ttest.html#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="ttest.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(d, <span class="at">mu=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  d
## t = -9.6667, df = 25, p-value = 6.327e-10
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -10.824189  -7.021964
## sample estimates:
## mean of x 
## -8.923077</code></pre>
<p>대응표본 t-검정은 차이에 대한 일표본 t-검정과 같고 이에 대한 귀무가설은 전-후 차이의 평균은 0이다 로 나타낼 수 있다. 결과를 살펴보면 대응표본을 통한 검정과 차이에 대한 일표본 검정값이 같음을 알 수 있다.</p>
</div>
<div id="with-sas-2" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> with SAS</h3>
<blockquote>
<p>SAS Code</p>
</blockquote>
<pre><code>data pairttest;
input pre post @@;
cards;
38  24  24  12
26  22  25  18
25  19  28  24
32  18  31  16
28  24  34  17
34  31  29  21
27  19  28  27
33  18  34  29
32  17  33  24
18  8   24  22
25  12  26  23
29  19  29  19
27  16  28  16
;
run;

proc means data=pairttest;
var pre post;
run;

proc ttest data=pairttest;
paired pre*post;
run;
</code></pre>
<ul>
<li>Results</li>
</ul>
<p><img src="ttest/ex10.jpg" /></p>
<p>결과를 살펴보면 <span class="math inline">\(p\)</span>-value는 &lt;.0001로 유의수준 5%보다 아주 작은 값으로 새 항우울제 치료 후 우울증 점수가 유의하게 감소하였음을 알 수 있다.</p>
<!-------------------------------------->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["rmanual.pdf", "rmanual.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
