<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; 네트워크 메타분석 – 메타분석</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-cumulative-sensitivity.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3d841e2d0dac331999ea63b9b6b417ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-network-meta-analysis.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">네트워크 메타분석</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="검색" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">메타분석</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="검색"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">들어가며</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-meta-analysis-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">메타분석 개요</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-effect-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">효과크기 계산</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-fixed-random-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">고정효과모형과 랜덤효과모형</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-moderator-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">조절효과분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-publication-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">출판 비뚤림 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-cumulative-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">누적메타분석과 민감도분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-network-meta-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">네트워크 메타분석</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#네트워크-메타분석의-이해" id="toc-네트워크-메타분석의-이해" class="nav-link active" data-scroll-target="#네트워크-메타분석의-이해"><span class="header-section-number">7.1</span> 네트워크 메타분석의 이해</a>
  <ul class="collapse">
  <li><a href="#네트워크-메타분석의-통계적-접근" id="toc-네트워크-메타분석의-통계적-접근" class="nav-link" data-scroll-target="#네트워크-메타분석의-통계적-접근"><span class="header-section-number">7.1.1</span> 네트워크 메타분석의 통계적 접근</a></li>
  <li><a href="#네트워크-메타분석의-기본-원리" id="toc-네트워크-메타분석의-기본-원리" class="nav-link" data-scroll-target="#네트워크-메타분석의-기본-원리"><span class="header-section-number">7.1.2</span> 네트워크 메타분석의 기본 원리</a></li>
  <li><a href="#네트워크-메타분석의-가정" id="toc-네트워크-메타분석의-가정" class="nav-link" data-scroll-target="#네트워크-메타분석의-가정"><span class="header-section-number">7.1.3</span> 네트워크 메타분석의 가정</a></li>
  </ul></li>
  <li><a href="#prisma-네트워크-메타분석-체크리스트" id="toc-prisma-네트워크-메타분석-체크리스트" class="nav-link" data-scroll-target="#prisma-네트워크-메타분석-체크리스트"><span class="header-section-number">7.2</span> PRISMA 네트워크 메타분석 체크리스트</a>
  <ul class="collapse">
  <li><a href="#네트워크-지형도" id="toc-네트워크-지형도" class="nav-link" data-scroll-target="#네트워크-지형도"><span class="header-section-number">7.2.1</span> 네트워크 지형도</a></li>
  <li><a href="#일관성-검정assessment-of-consistency" id="toc-일관성-검정assessment-of-consistency" class="nav-link" data-scroll-target="#일관성-검정assessment-of-consistency"><span class="header-section-number">7.2.2</span> 일관성 검정(assessment of consistency)</a></li>
  <li><a href="#치료법-간의-비교우위-선정" id="toc-치료법-간의-비교우위-선정" class="nav-link" data-scroll-target="#치료법-간의-비교우위-선정"><span class="header-section-number">7.2.3</span> 치료법 간의 비교우위 선정</a></li>
  </ul></li>
  <li><a href="#이산형-자료-예제" id="toc-이산형-자료-예제" class="nav-link" data-scroll-target="#이산형-자료-예제"><span class="header-section-number">7.3</span> 이산형 자료 예제</a>
  <ul class="collapse">
  <li><a href="#자료의-입력" id="toc-자료의-입력" class="nav-link" data-scroll-target="#자료의-입력"><span class="header-section-number">7.3.1</span> 자료의 입력</a></li>
  <li><a href="#네트워크-plot" id="toc-네트워크-plot" class="nav-link" data-scroll-target="#네트워크-plot"><span class="header-section-number">7.3.2</span> 네트워크 plot</a></li>
  <li><a href="#네트워크-모델" id="toc-네트워크-모델" class="nav-link" data-scroll-target="#네트워크-모델"><span class="header-section-number">7.3.3</span> 네트워크 모델</a></li>
  <li><a href="#mcmc-시물레이션과-진단" id="toc-mcmc-시물레이션과-진단" class="nav-link" data-scroll-target="#mcmc-시물레이션과-진단"><span class="header-section-number">7.3.4</span> MCMC 시물레이션과 진단</a></li>
  <li><a href="#일관성-검정consistency-test" id="toc-일관성-검정consistency-test" class="nav-link" data-scroll-target="#일관성-검정consistency-test"><span class="header-section-number">7.3.5</span> 일관성 검정(consistency test)</a></li>
  <li><a href="#forest-plot" id="toc-forest-plot" class="nav-link" data-scroll-target="#forest-plot"><span class="header-section-number">7.3.6</span> Forest plot</a></li>
  <li><a href="#치료-간-비교우위-선정treatment-ranking" id="toc-치료-간-비교우위-선정treatment-ranking" class="nav-link" data-scroll-target="#치료-간-비교우위-선정treatment-ranking"><span class="header-section-number">7.3.7</span> 치료 간 비교우위 선정(treatment ranking)</a></li>
  </ul></li>
  <li><a href="#연속형-자료-예제" id="toc-연속형-자료-예제" class="nav-link" data-scroll-target="#연속형-자료-예제"><span class="header-section-number">7.4</span> 연속형 자료 예제</a>
  <ul class="collapse">
  <li><a href="#자료의-입력-1" id="toc-자료의-입력-1" class="nav-link" data-scroll-target="#자료의-입력-1"><span class="header-section-number">7.4.1</span> 자료의 입력</a></li>
  <li><a href="#네트워크-plot-1" id="toc-네트워크-plot-1" class="nav-link" data-scroll-target="#네트워크-plot-1"><span class="header-section-number">7.4.2</span> 네트워크 plot</a></li>
  <li><a href="#네트워크-모델-1" id="toc-네트워크-모델-1" class="nav-link" data-scroll-target="#네트워크-모델-1"><span class="header-section-number">7.4.3</span> 네트워크 모델</a></li>
  <li><a href="#mcmc-시물레이션과-진단-1" id="toc-mcmc-시물레이션과-진단-1" class="nav-link" data-scroll-target="#mcmc-시물레이션과-진단-1"><span class="header-section-number">7.4.4</span> MCMC 시물레이션과 진단</a></li>
  <li><a href="#일관성-검정consistency-test-1" id="toc-일관성-검정consistency-test-1" class="nav-link" data-scroll-target="#일관성-검정consistency-test-1"><span class="header-section-number">7.4.5</span> 일관성 검정(consistency test)</a></li>
  <li><a href="#forest-plot-1" id="toc-forest-plot-1" class="nav-link" data-scroll-target="#forest-plot-1"><span class="header-section-number">7.4.6</span> Forest plot</a></li>
  <li><a href="#치료-간-비교우위-선정treatment-randing" id="toc-치료-간-비교우위-선정treatment-randing" class="nav-link" data-scroll-target="#치료-간-비교우위-선정treatment-randing"><span class="header-section-number">7.4.7</span> 치료 간 비교우위 선정(treatment randing)</a></li>
  </ul></li>
  <li><a href="#time-to-event-예제" id="toc-time-to-event-예제" class="nav-link" data-scroll-target="#time-to-event-예제"><span class="header-section-number">7.5</span> Time to event 예제</a>
  <ul class="collapse">
  <li><a href="#자료의-입력-2" id="toc-자료의-입력-2" class="nav-link" data-scroll-target="#자료의-입력-2"><span class="header-section-number">7.5.1</span> 자료의 입력</a></li>
  <li><a href="#네트워크-plot-2" id="toc-네트워크-plot-2" class="nav-link" data-scroll-target="#네트워크-plot-2"><span class="header-section-number">7.5.2</span> 네트워크 plot</a></li>
  <li><a href="#네트워크-모델-2" id="toc-네트워크-모델-2" class="nav-link" data-scroll-target="#네트워크-모델-2"><span class="header-section-number">7.5.3</span> 네트워크 모델</a></li>
  <li><a href="#mcmc-시물레이션과-진단-2" id="toc-mcmc-시물레이션과-진단-2" class="nav-link" data-scroll-target="#mcmc-시물레이션과-진단-2"><span class="header-section-number">7.5.4</span> MCMC 시물레이션과 진단</a></li>
  <li><a href="#일관성-검정consistency-test-2" id="toc-일관성-검정consistency-test-2" class="nav-link" data-scroll-target="#일관성-검정consistency-test-2"><span class="header-section-number">7.5.5</span> 일관성 검정(consistency test)</a></li>
  <li><a href="#forest-plot-2" id="toc-forest-plot-2" class="nav-link" data-scroll-target="#forest-plot-2"><span class="header-section-number">7.5.6</span> Forest plot</a></li>
  <li><a href="#치료-간-비교우위-선정treatment-randing-1" id="toc-치료-간-비교우위-선정treatment-randing-1" class="nav-link" data-scroll-target="#치료-간-비교우위-선정treatment-randing-1"><span class="header-section-number">7.5.7</span> 치료 간 비교우위 선정(treatment randing)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="Chapter7" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">네트워크 메타분석</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="네트워크-메타분석의-이해" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="네트워크-메타분석의-이해"><span class="header-section-number">7.1</span> 네트워크 메타분석의 이해</h2>
<p>네트워크 메타분석(network meta-analysis, NMA)은 다중비교(multiple treatment meta-analysis) 또는 혼합비교(mixed treatment comparison)라고도 불리며, 다수의 치료(intervention 또는 treatment)를 가진 여러 연구들의 효과크기를 종합하는 것이다 (White, 2015).</p>
<p>기존의 일반적인 메타분석(pairwise meta-analysis)에서는 동일한 치료를 실시한 연구들을 모아 치료군과 비교군으로 두 군의 짝을 만든 후 효과크기를 직접 계산하였다. 그러나 네트워크 메타분석에서는 치료그룹별 직접비교 연구가 없거나 치료가 서로 다르다고 하더라도 간접비교(indirect treatment comparison) 방법을 이용하여 치료그룹 간의 효과크기를 계산할 수 있다.</p>
<ul>
<li>관계도</li>
</ul>
<p><img src="ch7/e1.png" class="img-fluid"></p>
<p>International Society for Pharmacoeconomics and Outcomes Research (ISPOR) 에서는 근거가 2개 이상인 치료를 연결하는 2개 이상의 임상연구(randomized clinical trial)가 있는 경우에 네트워크 메타분석이라는 용어를 사용한다. 이때 네트워크가 열려 있어 loop를 구성하지 못하면 간접비교(indirect treatment comparison, ITC)를 제안하고, 네트워크가 닫혀 있어서 loop를 구성하면 혼합비교(mixed treatment comparison, MTC)를 제안하였다. (Jansen et al., 2011)</p>
<section id="네트워크-메타분석의-통계적-접근" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="네트워크-메타분석의-통계적-접근"><span class="header-section-number">7.1.1</span> 네트워크 메타분석의 통계적 접근</h3>
<p>네트워크 메타분석을 실행하는 방법은 크게 베이지안(Bayesian) 방법과 빈도주의적(frequentist) 방법으로 나누어볼 수 있다. 두 통계법의 차이는 통계모형에 접근하는 근본적인 개념의 차이에서 기인하며 표본크기가 클 경우 동일한 결과를 나타낸다.</p>
<p>우선 기존 네트워크 메타분석에서 상대적으로 많이 시행되는 ‘베이지안 방법’은 사전에 알려진 정보(prior probasbility 또는 external information)를 바탕으로 현재의 자료에서 주어진 정보(present data)를 더하여 연구가설이 참(true)일 사후확률(posterior probability)을 산출하는 것이다. 따라서 베이지안 방법은 사전정보에 따라 연구가설이 참일 확률이 변할 수 있는 확률적인 접근이라고 할 수 있다.</p>
<p>반면에 빈도주의적 방법은 일반적인 통계이론에 근거하여 현재 주어진 자료가 무한히 반복되었을 때 연구가설이 기각되거나 받아들여질 유의확률이나 신뢰구간에 기반한다. 따라서 빈도주의적 방법은 외적 정보와 무관하며, 주어진 자료 내에서 연구가설이 참일 확률이 이미 특정되어 있어서 단지 이것이 받아들여지거나 기각될지를 유의수준으로 판단한다.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>베이지안 방법</th>
<th>빈도주의적 방법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>기본개념(basic concept)</td>
<td>베이지안 이론(Bayesian therorem)</td>
<td>자료의 분포(distribution)</td>
</tr>
<tr class="even">
<td>사용되는 정보(information used)</td>
<td>사전확률(prior probability) &amp; 연구자료(present data)</td>
<td>연구자료(present data only)</td>
</tr>
<tr class="odd">
<td>불확실성 측정(uncertainty measurment)</td>
<td>신용구간(credible interval, Crl)</td>
<td>신뢰구간(confidence interval, CI)</td>
</tr>
<tr class="even">
<td>연구가설 검정(hypothesis testing)</td>
<td>연구가설이 참일 확률, 즉 사후확률을 직접 계산함</td>
<td></td>
</tr>
<tr class="odd">
<td>귀무가설을 기각함으로써 연구 가설을 증명</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>다수의 선행연구를 참조하고 다양한 약물의 효과크기를 통해서 실제 현상을 설명하기에는 베이지안 방법이 빈도주의적 방법보다 논리적이고 타당하다고 볼 수 있다. 그러나 베이지안 방법은 연구가설에서 사전확률이 확립되어 있지 않을 경우, 사전확률을 설정하는 문제가 본래 분석하고자 하는 연구가설 검정보다 오히려 더 복잡할 수 있다. 그렇기 때문에 일반 연구자들이 접근하기에는 많은 한계를 지닌다. 최근, 다수의 연구에서 빈도주의적 방법과 베이지안 방법을 적용하여 네트워크 메타분석을 실행한 결과가 다르지 않음을 보여준다.</p>
</section>
<section id="네트워크-메타분석의-기본-원리" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="네트워크-메타분석의-기본-원리"><span class="header-section-number">7.1.2</span> 네트워크 메타분석의 기본 원리</h3>
<section id="간접비교" class="level4" data-number="7.1.2.1">
<h4 data-number="7.1.2.1" class="anchored" data-anchor-id="간접비교"><span class="header-section-number">7.1.2.1</span> 간접비교</h4>
<p>일반적인 메타분석(pairwise meta-analysis)에서는 두 치료그룹 간의 직접비교(direct comparison)에 따른 효과크기(effect size)를 여러 연구에서 종합하여 계산하였다. 그러나 둘 이상의 치료그룹에서 특정 치료간의 직접비교가 없을 경우에는 간접비교를 사용하여 이를 계산할 수 있다. 특히 공통 비교인자 (common comparator)를 통한 간접비교를 보정된 간접비교(adjusted indirect treatment comparison, AITC)라고 하는데, 이는 네트워크 메타분석을 가능하게 해주는 기본적인 원리이다.</p>
<p>예를 들어, 치료(treatment)는 3개(A, B, C)이고 2개의 연구(AB, AC)가 있으며 각각의 효과크기는 d_AB와 d_AC이다. A를 공통비교인자로 설정하여 2개의 직접비교 효과크기를 활용하여 BC의 간접비교(AITC)를 계산한 효과크기와 분산은 다음과 같다.</p>
<p><img src="ch7/f1.jpg" class="img-fluid"></p>
</section>
<section id="혼합비교" class="level4" data-number="7.1.2.2">
<h4 data-number="7.1.2.2" class="anchored" data-anchor-id="혼합비교"><span class="header-section-number">7.1.2.2</span> 혼합비교</h4>
<p>아래 그림과 같이 3개 치료 그룹 간의 직접비교 연구가 있는 경우에는 닫힌 loop를 형성하고 있기 때문에 직접비교와 간접비교(AITC)를 종합한 혼합비교(mixed treatment comparison, MTC)를 계산할 수 있다. 혼합비교는 Lumley(2002)가 2-arm trials에서 활용 가능한 방법을 제시하였고 이를 바탕으로 Higgins et al., (2012)와 White et al., (2012) 등이 multi-arm trials로 발전시켰다. 혼합비교는 연구의 정밀성(precision)을 향상시킬 수 있으며 직접비교만을 활용한 연구보다 신뢰구간(confidence interval)을 더 좁게 나타낼 수 있다.</p>
<p><img src="ch7/f2.jpg" class="img-fluid"></p>
</section>
</section>
<section id="네트워크-메타분석의-가정" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="네트워크-메타분석의-가정"><span class="header-section-number">7.1.3</span> 네트워크 메타분석의 가정</h3>
<p>메타분석은 기본적으로 여러 연구들을 수리적으로 종합하는 통계적 방법론이기 때문에 사전에 여러 가정(assumption)들을 충족해야만 종합효과크기(overall effect size)의 타당성을 보여줄 수 있다. 더욱이 2개 이상의 치료를 연결하는 네트워크 메타분석의 경우에는 보다 엄격한 가정이 요구된다.</p>
<p>네트워크 메타분석의 가정은 크게 임상석 유사성(clinical similarity), 통계적 동질성(statistical non-heterogeneity), 논리적 이행성(transitivity), 그리고 효과크기들의 일관성(consistency)으로 구분할 수 있다. 특히 주요 논문들에서는 임상적 의미가 있는 연구들을 수집하였는지 확인하는 임상적 유사성과 통계적 검정이 가능한 일관성을 중점적으로 다루고 있다.</p>
<p>메타분석은 태생적으로 이질성 논쟁을 피할 수 없다. 따라서 동일 연구디자인 내에서라면 임상적 유사성 검정을 위하여 Cochrane 통계량이나 Higgins 등의 이질성 수치를 활용할 수 있다. 그러나 이것은 비단 네트워크 메타분석에서뿐만 아니라 일반적인 메타분석에서와 동일한 논쟁이므로 크게 차별점이 없다. 더욱이 네트워크 메타분석에서는 여러 치료법과 여러 연구디자인을 아울러야 하므로 결국 이행성을 검정하기 위한 일관성 가정이 초점이 되고 있다. 다시말하면, ‘일관성’이란 직접비교와 간접비교를 수렴하기 위한 특수한 경우의 이질성(special type of heterogeneity)이라고 할 수 있다. 따라서 이를 검정함으로써 네트워크 메타분석 결과의 유의함을 보여주고자 하는 것이다.</p>
<section id="유사성similarity" class="level4" data-number="7.1.3.1">
<h4 data-number="7.1.3.1" class="anchored" data-anchor-id="유사성similarity"><span class="header-section-number">7.1.3.1</span> 유사성(similarity)</h4>
<p>대상 연구들 간의 임상적, 방법론적 유사성을 나타내는 것이다. 일반적으로 PICO (population, Intervention, Comparison, Outcomes)를 통하여 대상연구 선정의 전체적인 흐름을 파악하게 되는데 대상연구들이 연구주제와 부합하며 전반적으로 임상적, 방법론적으로 유사하여야 한다. 예를 들면, 대상연구들 중에서 인구집단(population) 내 동일한 질환군을 대상으로 실시한 연구가 아니라면 유사성을 의심하여야 한다. 그러나 임상적 유사성은 연구의 전반적인 유사성이지 통계적으로 검정할 수 있는 것은 아니다.</p>
</section>
<section id="이행성transitivity" class="level4" data-number="7.1.3.2">
<h4 data-number="7.1.3.2" class="anchored" data-anchor-id="이행성transitivity"><span class="header-section-number">7.1.3.2</span> 이행성(transitivity)</h4>
<p>임상적, 방법론적 유사성이 치료그룹과 연구들 간에 있어서 논리적으로 확장된 개념이라고 할 수 있다. 간단히 설명하자면 만약 세 가지 치료(A, B, C)를 비교한 연구의 효과크기가 <span class="math inline">\(A&gt;B\)</span> 그리고 <span class="math inline">\(B&gt;C\)</span> 라면 <span class="math inline">\(A&gt;C\)</span>가 논리적으로 타당한 것이다. 이러한 논리적 이행성은 네트워크 메타분석 내 모든 경우에서 지켜져야 한다.</p>
<p>앞서 살펴본 유사성과 이행성은 개념적으로 비슷하지만 상호 동일한 것은 아니다. 예를 들어 3개의 연구가 고혈압 환자 중에서 각각 AB는 severe군, AC는 moderate군, 그리고 BC는 mild군을 대상으로 실시되어졌다고 가정해보자. 모든 연구가 고혈압이라는 특정 인구집단이기에 임상적 유사성은 만족할지라도 논리적 이행성 가정은 성립되지 않는다. 왜냐하면 이미 개별연구 인구집단별로 효과크기의 차별이 존재하기 때문이다.</p>
<p><img src="ch7/f21.png" class="img-fluid"></p>
<p><img src="ch7/f22.png" class="img-fluid"></p>
</section>
<section id="일관성consistency" class="level4" data-number="7.1.3.3">
<h4 data-number="7.1.3.3" class="anchored" data-anchor-id="일관성consistency"><span class="header-section-number">7.1.3.3</span> 일관성(consistency)</h4>
<p>기본적으로 일관성은 혼합비교를 구현함에 있어서 직접비교와 간접비교를 통한 효과크기가 동일하다는 가정이다. 예를 들어 관심효과크기가 BC라면 우선 직접비교를 통한 효과크기 <span class="math inline">\(d_{BC}\)</span>와 간접비교를 통한 효과크기 <span class="math inline">\(d_{BC}\)</span>는 통계적으로 유의한 차이를 보이지 않아야 일관성 가정이 충족된다고 볼 수 있다. 또한 일관성 검정은 논리적 이행성 가정을 검정하는 통계적인 방법이라고도 할 수 있다.</p>
<p>Higgins는 multi-arm 네트워크 메타분석에 적용 가능한 비일관성(inconsistency, 즉 일관성을 보이지 않는 여러 경우) 모델에 대한 개념을 다음과 같이 두 가지로 폭넓게 정립하였다. 첫째, 혼합비교를 계산할 때 직접비교와 간접비교의 차이를(difference) 들 수 있는데, 이를 loof inconsistency라고 한다. 둘째 동일하게 관심 효과크기가 BC라면 연구디자인 (BC, ABC)에 따른 (difference)를 들 수 있는데, BC 디자인에서의 직접비교 값인 <span class="math inline">\(d_{BC}\)</span>와 ABC 디자인에서의 직접비교 값인 <span class="math inline">\(d_{BC}\)</span>의 차이를 design inconsistency라고 한다.</p>
</section>
</section>
</section>
<section id="prisma-네트워크-메타분석-체크리스트" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="prisma-네트워크-메타분석-체크리스트"><span class="header-section-number">7.2</span> PRISMA 네트워크 메타분석 체크리스트</h2>
<p>일반적인 메타분석(pairwise meta-analysis)을 확장한 개념인 PRISMA (preferred Reporting Items for Systematic Reviews and Meta-analyses) 네트워크 메타분석 체크리스트는 (Hutton et al., 2015) 기존 메타분석에 더하여 네트워크 메타분석에 추가적으로 요구되는 항목들을 잘 기술하고 있다. 1번 title에서부터 연구에 대한 이해관계를 규정한 27번 funding 항목까지 매우 상세히 설명하고 있어 네트워크 메타분석 연구를 실시하고자 하는 연구자들은 반드시 이를 참조하여야 한다. 본 연구에서는 이들 항목 중 특히 네트워크 메타분석에서 반드시 보고되어야 하는 항목들은 다음과 같다.</p>
<section id="네트워크-지형도" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="네트워크-지형도"><span class="header-section-number">7.2.1</span> 네트워크 지형도</h3>
<p>네트워크 지형도(network geometry)는 네트워크 메타분석에서 비교군 간의 관계를 도식화한 것이다. 네트워크 지형도의 질적 기술(qualitative description)은 일반적으로 네트워크 그래프(map or plot)로, 양적관계(quantitative metrics)는 각 치료별 가중값을 보여주는 기여도 그림(contribution plot)으로 보여주는 것이 일반적이다.</p>
</section>
<section id="일관성-검정assessment-of-consistency" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="일관성-검정assessment-of-consistency"><span class="header-section-number">7.2.2</span> 일관성 검정(assessment of consistency)</h3>
<p>네트워크 메타분석의 기본 가정인 일관성을 검정하는 방법으로 두 가지 방법이 있다. 첫 번째 개별 치료별 접근(local approach)은 Bucher가 제시한 방법을 활용하여 각 치료별로 짝지어서(node-splitting) 직접비교와 간접비교의 차이를 통계적으로 검정하는 것이다. 두 번째 전체 모델별 접근(global approach)은 design by treatment interaction model을 사용하여 각각의 연구디자인별 비일관성 모델의 회귀계수를 계산한 후 Wald test로 전체 모델에 대한 회귀계수들의 선형성을 검정하는 것이다.</p>
</section>
<section id="치료법-간의-비교우위-선정" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="치료법-간의-비교우위-선정"><span class="header-section-number">7.2.3</span> 치료법 간의 비교우위 선정</h3>
<p>네트워크 메타분석의 유용한 장점 중의 하나는 각 치료별 누적확률(cumulative probability)을 활용하여 치료법 간의 비교 우선순위를 산출할 수 있다는 것이다. 일반적으로 SUCRA(surface under the cumulative ranking) 곡선으로 나타내어지며, 각 치료별로 best에서부터 worst까지 확률을 도식화하여 곡선 아래 면적이 넓을수록 우선순위가 높다고 판단할 수 있다.</p>
</section>
</section>
<section id="이산형-자료-예제" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="이산형-자료-예제"><span class="header-section-number">7.3</span> 이산형 자료 예제</h2>
<section id="자료의-입력" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="자료의-입력"><span class="header-section-number">7.3.1</span> 자료의 입력</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bin_nma <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="st">study   d   n   trt</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="st">"Alshryda 2013" 10  80  D</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="st">"Alshryda 2013" 26  81  A</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="st">"Barrachina 2016"   4   36  C</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="st">"Barrachina 2016"   14  37  A</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2000"   9   20  C</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2000"   15  19  A</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2001"   4   18  B</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2001"   8   20  A</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="st">"Claeys 2007"   1   20  B</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="st">"Claeys 2007"   6   20  A</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="st">"Fraval 2017"   1   50  C</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="st">"Fraval 2017"   6   51  A</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="st">"Husted 2003"   2   20  C</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="st">"Husted 2003"   7   20  A</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="st">"Hsu 2015"  2   30  C</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="st">"Hsu 2015"  9   30  A</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="st">"Johansson 2005"    8   47  B</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="st">"Johansson 2005"    23  53  A</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="st">"Kazemi 2010"   7   32  B</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="st">"Kazemi 2010"   15  32  A</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="st">"Lee 2013"  9   34  C</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="st">"Lee 2013"  20  34  A</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="st">"Lemay 2004"    6   20  C</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="st">"Lemay 2004"    13  19  A</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="st">"Martin 2014"   3   25  D</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="st">"Martin 2014"   5   25  A</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="st">"Niskanen 2005" 5   19  C</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="st">"Niskanen 2005" 8   20  A</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="st">"North 2016"    8   70  C</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="st">"North 2016"    12  69  D</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="st">"Rajesparan 2009"   3   36  B</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="st">"Rajesparan 2009"   10  37  A</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="st">"Wang 2016" 9   81  B</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="st">"Wang 2016" 10  38  A</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="st">"Wei 2014"  6   101 B</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="st">"Wei 2014"  26  100 A</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  3   70  B</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  4   70  D</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  0   70  E</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   8   50  B</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   1   50  E</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   19  50  A</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="st">"Yue 2014"  3   52  D</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="st">"Yue 2014"  11  49  A</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="st">'</span>, <span class="at">header=</span>T)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>bin_nma</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             study  d   n trt
1    Alshryda 2013 10  80   D
2    Alshryda 2013 26  81   A
3  Barrachina 2016  4  36   C
4  Barrachina 2016 14  37   A
5      Benoni 2000  9  20   C
6      Benoni 2000 15  19   A
7      Benoni 2001  4  18   B
8      Benoni 2001  8  20   A
9      Claeys 2007  1  20   B
10     Claeys 2007  6  20   A
11     Fraval 2017  1  50   C
12     Fraval 2017  6  51   A
13     Husted 2003  2  20   C
14     Husted 2003  7  20   A
15        Hsu 2015  2  30   C
16        Hsu 2015  9  30   A
17  Johansson 2005  8  47   B
18  Johansson 2005 23  53   A
19     Kazemi 2010  7  32   B
20     Kazemi 2010 15  32   A
21        Lee 2013  9  34   C
22        Lee 2013 20  34   A
23      Lemay 2004  6  20   C
24      Lemay 2004 13  19   A
25     Martin 2014  3  25   D
26     Martin 2014  5  25   A
27   Niskanen 2005  5  19   C
28   Niskanen 2005  8  20   A
29      North 2016  8  70   C
30      North 2016 12  69   D
31 Rajesparan 2009  3  36   B
32 Rajesparan 2009 10  37   A
33       Wang 2016  9  81   B
34       Wang 2016 10  38   A
35        Wei 2014  6 101   B
36        Wei 2014 26 100   A
37        Xie 2016  3  70   B
38        Xie 2016  4  70   D
39        Xie 2016  0  70   E
40         Yi 2016  8  50   B
41         Yi 2016  1  50   E
42         Yi 2016 19  50   A
43        Yue 2014  3  52   D
44        Yue 2014 11  49   A</code></pre>
</div>
</div>
<p>베이지안 네트워크 메타분석을 실행하기 위해 <strong>gemtc</strong> 패키지를 이용한다. 또한 MCMC를 위해 <strong>JAGS</strong>를 이용하므로 <strong>JAGS</strong>(http://mcmc-jags.sourceforge.net/) 프로그램을 별도로 설치해야 한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("gemtc")</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gemtc)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>gemtc</strong> package는 여러 함수를 포함하고 있으며, 그 중 네트워크 분석을 실행하는 <em>mtc.network</em> 함수는 함수의 인수가 특정 변수명이어야 실행 가능하다. 이산형 자료에서는 순서대로 이벤트 수를 나타내는 “responders”와 표본크기인 “sampleSize” 변수명이 일치해야 한다. 따라서 이를 위해 column 명을 변경한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(bin_nma) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"study"</span>, <span class="st">"responders"</span>, <span class="st">"sampleSize"</span>, <span class="st">"treatment"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(bin_nma)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "study"      "responders" "sampleSize" "treatment" </code></pre>
</div>
</div>
<p>다음으로 네트워크 plot에서 treatment를 상세히 보여주고 이를 네트워크 셋업으로 활용하기 위해 treatment 데이터셋을 설정한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>  treatment <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">'</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="st">                          id description</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="st">                          A "Placebo"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="st">                          B "IV(single)"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          C "IV(double)"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          D "Topical"</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="st">                          E "Combination"</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          '</span>, <span class="at">header=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="네트워크-plot" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="네트워크-plot"><span class="header-section-number">7.3.2</span> 네트워크 plot</h3>
<p>데이터셋 bin_nma와 treatment를 이용하여 네트워크 셋업을 시행한다. 이때 함수는 <em>mtc.network</em>를 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>network <span class="ot">&lt;-</span> <span class="fu">mtc.network</span>(<span class="at">data.ab=</span>bin_nma, <span class="at">treatments=</span>treatment, <span class="at">description=</span><span class="st">"Bayesian NMA"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>셋업된 네트워크 정보를 network에 저장하고 <em>plot</em> 함수를 이용해 간단하게 네트워크 plot을 출력한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(network, <span class="at">use.description=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>네트워크 plot은 네트워크를 구성하는 치료그룹 간의 직접비교(direct comparison) 관계를 도식화해서 보여준다. 각 node를 연결하는 엣지(edge)의 굵기는 수행된 연구 수를 의미한다. 네트워크 plot은 네트워크 메타분석 연구에서 치료 간의 질적, 양적 관계를 가늠할 수 있게 해주므로 반드시 제시되어야 한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(network, <span class="at">layout=</span>igraph<span class="sc">::</span>layout.fruchterman.reingold, <span class="at">use.description=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>위의 예제와 같이 <strong>igraph</strong> 패키지를 이용하면 네트워크 plot을 좀 더 다양하게 표현하는 것이 가능하다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">summary</span>(network)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Description
[1] "MTC dataset: Bayesian NMA"

$`Studies per treatment`
 A  B  C  D  E 
19  9  9  5  2 

$`Number of n-arm studies`
2-arm 3-arm 
   19     2 

$`Studies per treatment comparison`
  t1 t2 nr
1  A  B  8
2  A  C  8
3  A  D  3
4  A  E  1
5  B  D  1
6  B  E  2
7  C  D  1
8  D  E  1</code></pre>
</div>
</div>
<p><em>summary</em> 명령어를 실시하면 결과창에서 네트워크 셋업의 전반적인 상황을 볼 수 있다. 각 치료별 2-arm 또는 3-arm 연구의 개수와 치료별 대응개수도 알 수 있다. 즉, 네트워크 plot을 수치적으로 나타낸 결과이다.</p>
</section>
<section id="네트워크-모델" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="네트워크-모델"><span class="header-section-number">7.3.3</span> 네트워크 모델</h3>
<p>네트워크 셋업 후 고정효과모형(fixed effect model) 또는 랜덤효과모형(random effect model)으로 네트워크 모델을 설정한다. 이때 함수 <em>mtc.model</em>을 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>  model_fix <span class="ot">&lt;-</span> <span class="fu">mtc.model</span>(network, <span class="at">linearModel=</span><span class="st">'fixed'</span>, <span class="at">n.chain=</span><span class="dv">4</span>, <span class="at">likelihood=</span><span class="st">'binom'</span>, <span class="at">link=</span><span class="st">'logit'</span>) <span class="co"># Fixed effect model</span></span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>mtc.model</em> 함수에 네트워크 셋업 데이터 network를 불러들여 고정효과모형 또는 랜덤효과모형으로 설정하여 각각 model_fix와 model_ran으로 저장한다. 여기서 n.chain은 MCMC에서 사용할 chain 수를 나타낸다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>  model_ran <span class="ot">&lt;-</span> <span class="fu">mtc.model</span>(network, <span class="at">linearModel=</span><span class="st">'random'</span>, <span class="at">n.chain=</span><span class="dv">4</span>, <span class="at">likelihood=</span><span class="st">'binom'</span>, <span class="at">link=</span><span class="st">'logit'</span>) <span class="co"># Random effect model</span></span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>motc.model</em>에서 효과크기 설정은 likelihood와 link 옵션으로 조절하며, 효과크기 종류와 매칭시켜야 하는 변수명은 다음과 같다.</p>
<ul>
<li>Odds ratio: binom/logit, (responders, sampleSize)</li>
<li>Risk ratio: binom/log (responders, sampleSize)</li>
<li>Hazard ratio: binom/cloglog, (responders, sampleSize)</li>
<li>Hazard ratio: poisson/log, (responders, exposure)</li>
</ul>
</section>
<section id="mcmc-시물레이션과-진단" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="mcmc-시물레이션과-진단"><span class="header-section-number">7.3.4</span> MCMC 시물레이션과 진단</h3>
<section id="mcmc-시뮬레이션-실행" class="level4" data-number="7.3.4.1">
<h4 data-number="7.3.4.1" class="anchored" data-anchor-id="mcmc-시뮬레이션-실행"><span class="header-section-number">7.3.4.1</span> MCMC 시뮬레이션 실행</h4>
<p>네트워크 모델이 설정되면 MCMC 시뮬레이션을 실시한다. 전반적인 순서는 적정 수준의 시뮬레이션 횟수를 설정하여 실행하고 실행한 결과들의 수렴 여부를 확인한다. 먼저 고정효과모형을 중심으로 살펴보자. MCMC 시물레이션은 <em>mtc.run</em> 함수를 사용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### MCMC Simulation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mcmc_fix <span class="ot">&lt;-</span> <span class="fu">mtc.run</span>(model_fix, <span class="at">n.adapt=</span><span class="dv">1000</span>, <span class="at">n.iter=</span><span class="dv">10000</span>, <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 44
   Unobserved stochastic nodes: 25
   Total graph size: 860

Initializing model</code></pre>
</div>
</div>
<p>여기서 n.adapt=1000은 MCMC를 통해 추출된 난수중 초기값에 영향을 받는 처음부터 1000번까지는 버리는다는 의미이다. n.iter=10000은 n.adapt에서 제거한 난수 이후에 생성되는 난수의 수를 의미하며 thin은 10번의 간격으로 생성난 난수를 추출한다는 의미이다. 따라서 총 난수는 1번부터 11000번까지 생성되며, 그중에서 1~1000번까지의 난수는 버리게 되며, 1001번부터 11000까지의 난수 중 1010, 1020, … 과 같은 순으로 난수가 추출된다.</p>
<p>베이지안 분석에서는 사후분포(posterior distribution)를 결정하기 위해 다중연쇄(multi chain)를 고려한 사전분포(prior distribution)을 넣어주는데, 이때 사전분포를 계산하기 위한 사전분포의 사전모수, 즉 초모수(hyperparameter)의 초기값을 다중으로 설정하여 다중연쇄 시뮬레이션을 실시한다. 총 10000개의 난수 중 10번 간격으로 추출하는 것이기 때문에 각 chain별로 1000개씩의 난수를 추출하게 된다. MCMC 수행 결과는 <em>summary</em> 함수를 통해 살펴볼 수 있다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Results on the Log Odds Ratio scale

Iterations = 1010:11000
Thinning interval = 10 
Number of chains = 4 
Sample size per chain = 1000 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

        Mean     SD Naive SE Time-series SE
d.A.B -1.336 0.1918 0.003033       0.003151
d.A.C -1.516 0.2315 0.003660       0.003660
d.A.D -1.130 0.2626 0.004152       0.004187
d.A.E -4.328 1.3071 0.020667       0.020226

2. Quantiles for each variable:

        2.5%    25%    50%     75%   97.5%
d.A.B -1.715 -1.466 -1.334 -1.2014 -0.9753
d.A.C -1.970 -1.667 -1.516 -1.3614 -1.0563
d.A.D -1.649 -1.309 -1.131 -0.9519 -0.6093
d.A.E -7.489 -5.044 -4.109 -3.4082 -2.3528

-- Model fit (residual deviance):

    Dbar       pD      DIC 
31.10365 25.53177 56.63542 

44 data points, ratio 0.7069, I^2 = 0%</code></pre>
</div>
</div>
</section>
<section id="mcmc-시뮬레이션-진단" class="level4" data-number="7.3.4.2">
<h4 data-number="7.3.4.2" class="anchored" data-anchor-id="mcmc-시뮬레이션-진단"><span class="header-section-number">7.3.4.2</span> MCMC 시뮬레이션 진단</h4>
<p>MCMC 시뮬레이션이 잘 수행되었는지 확인하기 위해서 아래 사항들을 복합적으로 확인한다.</p>
<ul>
<li><p>MCMC error : 몬테카를로 오차(Naive SE &amp; Time-series SE)는 작을수록 높은 정밀도를 나타내어 수렴이 잘 되었다고 판단할 수 있다. 시뮬레이션의 전반적인 평가는 MCMC error 가 얼마나 최소화되는가에 달려 있다고 볼 수 있다. 따라서 반복 시뮬레이션 획수를 늘려 표본의 수를 충분히 확보하고 초기값의 영향을 제거하기 위해 burn-in 과정을 거치며 난수 추출간격 thin을 잘 조정해야 한다.</p></li>
<li><p>DIC (deviance information criterion) : <span class="math inline">\(DIC = \bar{D} + pD\)</span>로 표현된다 <span class="math inline">\(\bar{D}\)</span>는 잔차이탈도(residual deviance)의 합이며 <span class="math inline">\(pD\)</span>는 모수 수의 추정값으로 결국 DIC는 모형의 적합도와 복잡성을 동시에 고려한 수치이다. 이 수치가 작을수록 좀 더 나은 모형이라고 할 수 있다.</p></li>
<li><p>trace plot과 density plot : trace plot은 특정한 패턴 없이 각 chain들이 얽혀 있어야 잘 수렴했다고 판단할 수 있다. density plot은 사후분포(사후밀도함수)로서 시뮬레이션 반복횟수에 따라 모양이 크게 다르다면 잘 수렴하지 않았다는 것을 의미한다.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>겔만-루빈(Gelman-Rubin) 통계량과 plot</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Gelman-Rubin Statistics and plot</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gelman.diag</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Potential scale reduction factors:

      Point est. Upper C.I.
d.A.B          1       1.00
d.A.C          1       1.01
d.A.D          1       1.00
d.A.E          1       1.00

Multivariate psrf

1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gelman.plot</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>gelman.diag</em> 함수는 겔만-루빈 통계량을 구해주며, <em>gelman.plot</em>은 겔만-루빈 plot을 그려준다. 시뮬레이션 반복횟수가 커짐에 따라 1에 가깝게 나타나며 변동이 안정화되어야 잘 수렵했다고 할 수 있다.</p>
</section>
</section>
<section id="일관성-검정consistency-test" class="level3" data-number="7.3.5">
<h3 data-number="7.3.5" class="anchored" data-anchor-id="일관성-검정consistency-test"><span class="header-section-number">7.3.5</span> 일관성 검정(consistency test)</h3>
<p>네트워크 메타분석의 가정에서 일관성 검정은 네트워크 메타분석 결과의 적용 가능 여부를 판가름하는 매우 중요한 도구이다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Consistency test</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    node_fix <span class="ot">&lt;-</span> <span class="fu">mtc.nodesplit</span>(network, <span class="at">linearModel=</span><span class="st">'fixed'</span>,   <span class="at">n.adapt=</span><span class="dv">1000</span>, <span class="at">n.iter=</span><span class="dv">10000</span>, <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 43
   Unobserved stochastic nodes: 26
   Total graph size: 937

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 44
   Unobserved stochastic nodes: 26
   Total graph size: 952

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 44
   Unobserved stochastic nodes: 26
   Total graph size: 949

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 43
   Unobserved stochastic nodes: 26
   Total graph size: 935

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 43
   Unobserved stochastic nodes: 26
   Total graph size: 931

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 44
   Unobserved stochastic nodes: 26
   Total graph size: 948

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 43
   Unobserved stochastic nodes: 26
   Total graph size: 931

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 44
   Unobserved stochastic nodes: 25
   Total graph size: 860

Initializing model</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#   plot(node_fix)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">summary</span>(node_fix))</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>mtc.nodesplit</em> 함수에 네트워크 셋입 자료를 넣어서 일관성 검정을 위한 고정효과모형 모델 node_fix를 만든다. 이때 MCMC 시뮬레이션도 같이 시행된다. 치료 간의 변동을 시각적으로 쉽게 파악할 수 있으며 모든 개별 치료 간의 일관성 검정 결과를 쉽게 파악할 수 있다. 전체적으로 통계적 유의차를 보이지 않아 해당 모델은 일관성을 지지하는 것으로 나타난다.</p>
</section>
<section id="forest-plot" class="level3" data-number="7.3.6">
<h3 data-number="7.3.6" class="anchored" data-anchor-id="forest-plot"><span class="header-section-number">7.3.6</span> Forest plot</h3>
<p>네트워크 메타분석을 통해 치료그룹별 효과크기를 한눈에 알아볼 수 있도록 도식화하여 비교한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Forest plot</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">forest</span>(<span class="fu">relative.effect</span>(mcmc_fix,<span class="at">t1=</span><span class="st">"A"</span>), <span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>relative.effect</em> 함수를 통해 치료 그룹간 효과크기를 추출하고 이를 <em>forest</em> 함수를 통해 forest plot을 그린다. <em>relative.effect</em> 함수의 인수중 t1에 “A”를 넣으면 참조치료를 A로 하는 forest plot을 생성한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Forest plot</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">forest</span>(<span class="fu">relative.effect</span>(mcmc_fix,<span class="at">t1=</span><span class="st">"E"</span>), <span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Forest plot을 통해 각 치료별 효과크기를 직관적으로 비교할 수 있다. Placebo에 대비한 모든 치료별 효과크기(OR, 수혈률)가 낮게 나타났으며 <span class="math inline">\(95\%\)</span> 신용구간(credible interval)이 겹치지 않는다는 것을 알 수 있다. 특히 병용치료방법(E, combination)의 경우 placebo뿐만 아니라 정맥1회주사법(B, IV(single)), 정맥2회주사법(C, IV(double)), 국소도포법(D, topical) 등 모든 치료에 대비하여 통계적으로 유의하게 수혈률이 낮음을 알 수 있다. 참조치료를 E로 변경하면 반대로 해석할 수 있다.</p>
</section>
<section id="치료-간-비교우위-선정treatment-ranking" class="level3" data-number="7.3.7">
<h3 data-number="7.3.7" class="anchored" data-anchor-id="치료-간-비교우위-선정treatment-ranking"><span class="header-section-number">7.3.7</span> 치료 간 비교우위 선정(treatment ranking)</h3>
<p>네트워크 메타분석의 가장 중요한 기능 중의 하나는 치료 간 비교우위를 선정할 수 있다는 것이다. 다시 말해 치료별 최우선 순위에서 최하위 순위까지 선택될 누적확률을 계산할 수 있다.</p>
<p><em>rank.probability</em> 함수에 MCMC 최종 모형을 넣고, preferredDirection은 효과크기가 작을수록 우수한 것인지 클수록 우수한 것인지에 따라 ‘-1’ 또는 ‘1’ 중에서 방향을 설정한다. 예제에서는 참조치료 대비 효과크기가 작을수록 우수한 것이기 때문에 ’-1’을 설정한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Treatment ranking</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    rank_fix <span class="ot">&lt;-</span> <span class="fu">rank.probability</span>(mcmc_fix, <span class="at">preferredDirection=</span><span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    rank_fix</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rank probability; preferred direction = -1
     [,1]   [,2]   [,3]    [,4] [,5]
A 0.00000 0.0000 0.0000 0.00000    1
B 0.00025 0.2545 0.5110 0.23425    0
C 0.00125 0.6840 0.2545 0.06025    0
D 0.00000 0.0600 0.2345 0.70550    0
E 0.99850 0.0015 0.0000 0.00000    0</code></pre>
</div>
</div>
<p>결과를 살펴보면 E(combination)이 best 치료일 경우는 99.8%이다. 2순위로 선택될 치료로는 C(IV double)가 68.2%이며, 다음으로는 B(IV single), D(topical), A(placebo)의 순위를 보인다.</p>
<p>치료간 우위를 그래프로 표현하면 다음과 같다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(rank_fix, <span class="at">beside=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="연속형-자료-예제" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="연속형-자료-예제"><span class="header-section-number">7.4</span> 연속형 자료 예제</h2>
<section id="자료의-입력-1" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="자료의-입력-1"><span class="header-section-number">7.4.1</span> 자료의 입력</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>con_nma <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">'</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="st">study   n   m   s   trt</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="st">"Alshryda 2013" 80  1650    188 D</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="st">"Alshryda 2013" 81  1981    1007    A</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="st">"Barrachina 2016"   36  1308    641 C</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="st">"Barrachina 2016"   37  2215    1136    A</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2000"   20  550 275 C</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2000"   19  500 234 A</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2001"   18  759 193 B</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="st">"Benoni 2001"   20  996 267 A</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="st">"Ekbck 2000"    20  1130    400 C</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="st">"Ekbck 2000"    20  1770    523 A</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="st">"Fraval 2017"   50  1084    440 C</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="st">"Fraval 2017"   51  1394    426 A</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="st">"Garneti 2004"  25  1443    809 B</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="st">"Garneti 2004"  25  1340    665 A</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="st">"Johansson 2005"    47  969 434 B</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="st">"Johansson 2005"    53  1324    577 A</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="st">"Lemay 2004"    20  1308    462 C</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="st">"Lemay 2004"    19  1469    405 A</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="st">"Lee 2013"  34  647 216 C</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="st">"Lee 2013"  34  1326    349 A</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="st">"Niskanen 2005" 19  626 206 C</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="st">"Niskanen 2005" 20  790 293 A</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="st">"North 2016"    70  1195    485.9   C</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="st">"North 2016"    69  1442.7  562.7   D</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a><span class="st">"Rajesparan 2009"   36  1372    436 B</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a><span class="st">"Rajesparan 2009"   37  1683    705 A</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="st">"Wei 2014"  101 958.5   422.1   B</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="st">"Wei 2014"  102 963.4   421.3   D</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a><span class="st">"Wei 2014"  100 1364.2  278.6   A</span></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   50  1002.6  366.9   B</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   50  750.6   343.5   E</span></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a><span class="st">"Yi 2016"   50  1221.1  386.3   A</span></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  70  878 210 B</span></span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  70  905.07  237.7   D</span></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a><span class="st">"Xie 2016"  70  670.7   189 E</span></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a><span class="st">"Yamasaki 2004" 20  1350    477 B</span></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a><span class="st">"Yamasaki 2004" 20  1667    401 A</span></span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a><span class="st">"Yue 2014"  52  1050.3  331.7   D</span></span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a><span class="st">"Yue 2014"  49  1255.5  193.5   A</span></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a><span class="st">'</span>, <span class="at">header=</span>T)</span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>con_nma</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             study   n       m      s trt
1    Alshryda 2013  80 1650.00  188.0   D
2    Alshryda 2013  81 1981.00 1007.0   A
3  Barrachina 2016  36 1308.00  641.0   C
4  Barrachina 2016  37 2215.00 1136.0   A
5      Benoni 2000  20  550.00  275.0   C
6      Benoni 2000  19  500.00  234.0   A
7      Benoni 2001  18  759.00  193.0   B
8      Benoni 2001  20  996.00  267.0   A
9       Ekbck 2000  20 1130.00  400.0   C
10      Ekbck 2000  20 1770.00  523.0   A
11     Fraval 2017  50 1084.00  440.0   C
12     Fraval 2017  51 1394.00  426.0   A
13    Garneti 2004  25 1443.00  809.0   B
14    Garneti 2004  25 1340.00  665.0   A
15  Johansson 2005  47  969.00  434.0   B
16  Johansson 2005  53 1324.00  577.0   A
17      Lemay 2004  20 1308.00  462.0   C
18      Lemay 2004  19 1469.00  405.0   A
19        Lee 2013  34  647.00  216.0   C
20        Lee 2013  34 1326.00  349.0   A
21   Niskanen 2005  19  626.00  206.0   C
22   Niskanen 2005  20  790.00  293.0   A
23      North 2016  70 1195.00  485.9   C
24      North 2016  69 1442.70  562.7   D
25 Rajesparan 2009  36 1372.00  436.0   B
26 Rajesparan 2009  37 1683.00  705.0   A
27        Wei 2014 101  958.50  422.1   B
28        Wei 2014 102  963.40  421.3   D
29        Wei 2014 100 1364.20  278.6   A
30         Yi 2016  50 1002.60  366.9   B
31         Yi 2016  50  750.60  343.5   E
32         Yi 2016  50 1221.10  386.3   A
33        Xie 2016  70  878.00  210.0   B
34        Xie 2016  70  905.07  237.7   D
35        Xie 2016  70  670.70  189.0   E
36   Yamasaki 2004  20 1350.00  477.0   B
37   Yamasaki 2004  20 1667.00  401.0   A
38        Yue 2014  52 1050.30  331.7   D
39        Yue 2014  49 1255.50  193.5   A</code></pre>
</div>
</div>
<p>베이지안 네트워크 메타분석을 실행하기 위해 <strong>gemtc</strong> 패키지를 이용한다. 또한 MCMC를 위해 <strong>JAGS</strong>를 이용하므로 <strong>JAGS</strong>(http://mcmc-jags.sourceforge.net/) 프로그램을 별도로 설치해야 한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("gemtc")</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gemtc)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>gemtc</strong> package는 여러 함수를 포함하고 있으며, 그 중 네트워크 분석을 실행하는 <em>mtc.network</em> 함수는 함수의 인수가 특정 변수명이어야 실행 가능하다. 연속형 자료에서는 순서대로 “sampleSize”, “mean”, “std.dev”가 일치해야 한다. 따라서 이를 위해 column 명을 변경한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(con_nma) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"study"</span>, <span class="st">"sampleSize"</span>, <span class="st">"mean"</span>, <span class="st">"std.dev"</span>, <span class="st">"treatment"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(con_nma)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "study"      "sampleSize" "mean"       "std.dev"    "treatment" </code></pre>
</div>
</div>
<p>다음으로 네트워크 plot에서 treatment를 상세히 보여주고 이를 네트워크 셋업으로 활용하기 위해 treatment 데이터셋을 설정한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>  treatment <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">'</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="st">                          id description</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="st">                          A "Treatment A"</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="st">                          B "Treatment B"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          C "Treatment C"</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          D "Treatment D"</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="st">                          E "Treatment E"</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          '</span>, <span class="at">header=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="네트워크-plot-1" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="네트워크-plot-1"><span class="header-section-number">7.4.2</span> 네트워크 plot</h3>
<p>데이터셋 con_nma와 treatment를 이용하여 네트워크 셋업을 시행한다. 이때 함수는 <em>mtc.network</em>를 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>network <span class="ot">&lt;-</span> <span class="fu">mtc.network</span>(<span class="at">data.ab=</span>con_nma, <span class="at">treatments=</span>treatment, <span class="at">description=</span><span class="st">"Bayesian NMA"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>셋업된 네트워크 정보를 network에 저장하고 <em>plot</em> 함수를 이용해 간단하게 네트워크 plot을 출력한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(network, <span class="at">use.description=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>네트워크 plot은 네트워크를 구성하는 치료그룹 간의 직접비교(direct comparison) 관계를 도식화해서 보여준다. 각 node를 연결하는 엣지(edge)의 굵기는 수행된 연구 수를 의미한다. 네트워크 plot은 네트워크 메타분석 연구에서 치료 간의 질적, 양적 관계를 가늠할 수 있게 해주므로 반드시 제시되어야 한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">summary</span>(network)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Description
[1] "MTC dataset: Bayesian NMA"

$`Studies per treatment`
 A  B  C  D  E 
16  8  8  5  2 

$`Number of n-arm studies`
2-arm 3-arm 
   15     3 

$`Studies per treatment comparison`
  t1 t2 nr
1  A  B  7
2  A  C  7
3  A  D  3
4  A  E  1
5  B  D  2
6  B  E  2
7  C  D  1
8  D  E  1</code></pre>
</div>
</div>
<p><em>summary</em> 명령어를 실시하면 결과창에서 네트워크 셋업의 전반적인 상황을 볼 수 있다. 각 치료별 2-arm 또는 3-arm 연구의 개수와 치료별 대응개수도 알 수 있다. 즉, 네트워크 plot을 수치적으로 나타낸 결과이다.</p>
</section>
<section id="네트워크-모델-1" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="네트워크-모델-1"><span class="header-section-number">7.4.3</span> 네트워크 모델</h3>
<p>네트워크 셋업 후 고정효과모형 또는 랜덤효과모형으로 네트워크 모델을 설정한다. 이때 함수 <em>mtc.model</em>을 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>  model_fix <span class="ot">&lt;-</span> <span class="fu">mtc.model</span>(network, <span class="at">linearModel=</span><span class="st">'fixed'</span>, <span class="at">n.chain=</span><span class="dv">4</span>, <span class="at">likelihood=</span><span class="st">'normal'</span>, <span class="at">link=</span><span class="st">'identity'</span>) <span class="co"># Fixed effect model</span></span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>mtc.model</em> 함수에 네트워크 셋업 데이터 network를 불러들여 고정효과모형 또는 랜덤효과모형으로 설정하여 각각 model_fix와 model_ran으로 저장한다. 여기서 n.chain은 MCMC에서 사용할 chain 수를 나타낸다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>  model_ran <span class="ot">&lt;-</span> <span class="fu">mtc.model</span>(network, <span class="at">linearModel=</span><span class="st">'random'</span>, <span class="at">n.chain=</span><span class="dv">4</span>, <span class="at">likelihood=</span><span class="st">'normal'</span>, <span class="at">link=</span><span class="st">'identity'</span>) <span class="co"># Random effect model</span></span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="mcmc-시물레이션과-진단-1" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="mcmc-시물레이션과-진단-1"><span class="header-section-number">7.4.4</span> MCMC 시물레이션과 진단</h3>
<section id="mcmc-시뮬레이션-실행-1" class="level4" data-number="7.4.4.1">
<h4 data-number="7.4.4.1" class="anchored" data-anchor-id="mcmc-시뮬레이션-실행-1"><span class="header-section-number">7.4.4.1</span> MCMC 시뮬레이션 실행</h4>
<p>네트워크 모델이 설정되면 MCMC 시뮬레이션을 실시한다. 전반적인 순서는 적정 수준의 시뮬레이션 횟수를 설정하여 실행하고 실행한 결과들의 수렴 여부를 확인한다. 먼저 고정효과모형을 중심으로 살펴보자. MCMC 시물레이션은 <em>mtc.run</em> 함수를 사용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### MCMC Simulation</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mcmc_fix <span class="ot">&lt;-</span> <span class="fu">mtc.run</span>(model_fix, <span class="at">n.adapt=</span><span class="dv">1000</span>, <span class="at">n.iter=</span><span class="dv">10000</span>, <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 39
   Unobserved stochastic nodes: 22
   Total graph size: 454

Initializing model</code></pre>
</div>
</div>
<p>여기서 n.adapt=1000은 MCMC를 통해 추출된 난수중 초기값에 영향을 받는 처음부터 1000번까지는 버리는다는 의미이다. n.iter=10000은 n.adapt에서 제거한 난수 이후에 생성되는 난수의 수를 의미하며 thin은 10번의 간격으로 생성난 난수를 추출한다는 의미이다. 따라서 총 난수는 1번부터 11000번까지 생성되며, 그중에서 1~1000번까지의 난수는 버리게 되며, 1001번부터 11000까지의 난수 중 1010, 1020, … 과 같은 순으로 난수가 추출된다. MCMC 수행 결과는 <em>summary</em> 함수를 통해 살펴볼 수 있다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Results on the Mean Difference scale

Iterations = 10:10000
Thinning interval = 10 
Number of chains = 4 
Sample size per chain = 1000 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

        Mean    SD Naive SE Time-series SE
d.A.B -302.8 27.76   0.4389         0.4620
d.A.C -361.4 33.71   0.5330         0.5398
d.A.D -276.3 27.66   0.4373         0.4683
d.A.E -511.6 35.31   0.5583         0.5794

2. Quantiles for each variable:

        2.5%    25%    50%    75%  97.5%
d.A.B -357.0 -321.0 -303.1 -283.7 -249.1
d.A.C -425.9 -384.3 -361.4 -339.1 -296.3
d.A.D -330.1 -294.7 -275.8 -257.2 -223.6
d.A.E -581.0 -536.6 -511.3 -488.2 -442.7

-- Model fit (residual deviance):

     Dbar        pD       DIC 
105.48142  21.96559 127.44700 

39 data points, ratio 2.705, I^2 = 64%</code></pre>
</div>
</div>
</section>
<section id="mcmc-시뮬레이션-진단-1" class="level4" data-number="7.4.4.2">
<h4 data-number="7.4.4.2" class="anchored" data-anchor-id="mcmc-시뮬레이션-진단-1"><span class="header-section-number">7.4.4.2</span> MCMC 시뮬레이션 진단</h4>
<ul>
<li>Trace plot</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>특정한 패턴 없이 각 chain들이 얽혀 있어야 잘 수렴했다고 판단할 수 있다. density plot은 사후분포(사후밀도함수)로서 시뮬레이션 반복횟수에 따라 모양이 크게 다르다면 잘 수렴하지 않았다는 것을 의미한다.</p>
<ul>
<li>겔만-루빈(Gelman-Rubin) 통계량과 plot</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Gelman-Rubin Statistics and plot</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gelman.diag</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Potential scale reduction factors:

      Point est. Upper C.I.
d.A.B          1       1.01
d.A.C          1       1.00
d.A.D          1       1.00
d.A.E          1       1.00

Multivariate psrf

1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gelman.plot</span>(mcmc_fix)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>gelman.diag</em> 함수는 겔만-루빈 통계량을 구해주며, <em>gelman.plot</em>은 겔만-루빈 plot을 그려준다. 시뮬레이션 반복횟수가 커짐에 따라 1에 가깝게 나타나며 변동이 안정화되어야 잘 수렵했다고 할 수 있다.</p>
</section>
</section>
<section id="일관성-검정consistency-test-1" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="일관성-검정consistency-test-1"><span class="header-section-number">7.4.5</span> 일관성 검정(consistency test)</h3>
<p>네트워크 메타분석의 가정에서 일관성 검정은 네트워크 메타분석 결과의 적용 가능 여부를 판가름하는 매우 중요한 도구이다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Consistency test</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    node_fix <span class="ot">&lt;-</span> <span class="fu">mtc.nodesplit</span>(network, <span class="at">linearModel=</span><span class="st">'fixed'</span>,   <span class="at">n.adapt=</span><span class="dv">1000</span>, <span class="at">n.iter=</span><span class="dv">10000</span>, <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 37
   Unobserved stochastic nodes: 23
   Total graph size: 527

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 39
   Unobserved stochastic nodes: 23
   Total graph size: 545

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 38
   Unobserved stochastic nodes: 23
   Total graph size: 533

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 38
   Unobserved stochastic nodes: 23
   Total graph size: 536

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 37
   Unobserved stochastic nodes: 23
   Total graph size: 523

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 39
   Unobserved stochastic nodes: 23
   Total graph size: 541

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 38
   Unobserved stochastic nodes: 23
   Total graph size: 532

Initializing model

Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 39
   Unobserved stochastic nodes: 22
   Total graph size: 454

Initializing model</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#   plot(node_fix)</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">summary</span>(node_fix))</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>mtc.nodesplit</em> 함수에 네트워크 셋입 자료를 넣어서 일관성 검정을 위한 고정효과모형 모델 node_fix를 만든다. 이때 MCMC 시뮬레이션도 같이 시행된다. 치료 간의 변동을 시각적으로 쉽게 파악할 수 있으며 모든 개별 치료 간의 일관성 검정 결과를 쉽게 파악할 수 있다. 전체적으로 통계적 유의차를 보이지 않아 해당 모델은 일관성을 지지하는 것으로 나타난다.</p>
</section>
<section id="forest-plot-1" class="level3" data-number="7.4.6">
<h3 data-number="7.4.6" class="anchored" data-anchor-id="forest-plot-1"><span class="header-section-number">7.4.6</span> Forest plot</h3>
<p>네트워크 메타분석을 통해 치료그룹별 효과크기를 한눈에 알아볼 수 있도록 도식화하여 비교한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Forest plot</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">forest</span>(<span class="fu">relative.effect</span>(mcmc_fix,<span class="at">t1=</span><span class="st">"A"</span>), <span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>relative.effect</em> 함수를 통해 치료 그룹간 효과크기를 추출하고 이를 <em>forest</em> 함수를 통해 forest plot을 그린다. <em>relative.effect</em> 함수의 인수중 t1에 “A”를 넣으면 참조치료를 A로 하는 forest plot을 생성한다.</p>
</section>
<section id="치료-간-비교우위-선정treatment-randing" class="level3" data-number="7.4.7">
<h3 data-number="7.4.7" class="anchored" data-anchor-id="치료-간-비교우위-선정treatment-randing"><span class="header-section-number">7.4.7</span> 치료 간 비교우위 선정(treatment randing)</h3>
<p>네트워크 메타분석의 가장 중요한 기능 중의 하나는 치료 간 비교우위를 선정할 수 있다는 것이다. 다시 말해 치료별 최우선 순위에서 최하위 순위까지 선택될 누적확률을 계산할 수 있다.</p>
<p><em>rank.probability</em> 함수에 MCMC 최종 모형을 넣고, preferredDirection은 효과크기가 작을수록 우수한 것인지 클수록 우수한 것인지에 따라 ‘-1’ 또는 ‘1’ 중에서 방향을 설정한다. 예제에서는 참조치료 대비 효과크기가 작을수록 우수한 것이기 때문에 ’-1’을 설정한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">###### Treatment ranking</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    rank_fix <span class="ot">&lt;-</span> <span class="fu">rank.probability</span>(mcmc_fix, <span class="at">preferredDirection=</span><span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    rank_fix</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rank probability; preferred direction = -1
     [,1]    [,2]    [,3]    [,4] [,5]
A 0.00000 0.00000 0.00000 0.00000    1
B 0.00000 0.07950 0.75525 0.16525    0
C 0.00125 0.91075 0.07375 0.01425    0
D 0.00000 0.00850 0.17100 0.82050    0
E 0.99875 0.00125 0.00000 0.00000    0</code></pre>
</div>
</div>
<p>결과를 살펴보면 Treatment E가 best 선택일 경우는 99.9%이다. 2순위로 선택될 치료로는 Treatment C이며, 다음으로는 Treatment B, D, A의 순위를 보인다.</p>
<p>치료간 우위를 그래프로 표현하면 다음과 같다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(rank_fix, <span class="at">beside=</span>T)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="time-to-event-예제" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="time-to-event-예제"><span class="header-section-number">7.5</span> Time to event 예제</h2>
<p>생존자료의 메타분석을 위해 여기서는 <strong>BUGSnet</strong> packages (https://bugsnetsoftware.github.io/)를 이용한다(<strong>meta</strong> package도 이용 가능).</p>
<section id="자료의-입력-2" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="자료의-입력-2"><span class="header-section-number">7.5.1</span> 자료의 입력</h3>
<p><code>r} ##### install.packages("BUGSnet") library(BUGSnet)</code></p>
<p>본 예제에서는 <strong>BUGSnet</strong> packages에 내장된 당뇨 관련 데이터인 <strong>diabetes.sim</strong> 데이터셋을 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(BUGSnet<span class="sc">::</span>diabetes.sim)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Study followup trtnum Treatment diabetes    n  age age_SD  age_type
1 MRC-E      5.8      1  Diuretic       43 1081 60.7  14.26 mean &amp; SD
2 MRC-E      5.8      2   Placebo       34 2213 59.2  13.10 mean &amp; SD
3 MRC-E      5.8      3   blocker       37 1102 60.2  14.00 mean &amp; SD
4  EWPH      4.7      1  Diuretic       29  416 59.0  15.20 mean &amp; SD
5  EWPH      4.7      2   Placebo       20  424 57.0  14.80 mean &amp; SD
6  SHEP      3.0      1  Diuretic      140 1631 63.1  13.20 mean &amp; SD</code></pre>
</div>
</div>
<p>데이터를 <strong>BUGSnet</strong>에 적용하기 위해 <em>data.prep</em> 함수를 이용하여 변형한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>rate2.slr <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">data.prep</span>(<span class="at">arm.data=</span>BUGSnet<span class="sc">::</span>diabetes.sim, <span class="at">varname.t=</span><span class="st">"Treatment"</span>, <span class="at">varname.s=</span><span class="st">"Study"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="네트워크-plot-2" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="네트워크-plot-2"><span class="header-section-number">7.5.2</span> 네트워크 plot</h3>
<p>데이터셋 con_nma와 treatment를 이용하여 네트워크 셋업을 시행한다. 이때 함수는 <em>net.plot</em>를 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>BUGSnet<span class="sc">::</span><span class="fu">net.plot</span>(rate2.slr, <span class="at">node.scale=</span><span class="dv">3</span>, <span class="at">edge.scale=</span><span class="fl">1.5</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>특정노드와 관련된 직접적인 근거(direct evidence)는 <em>falg</em> 옵션을 통해 조절한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>BUGSnet<span class="sc">::</span><span class="fu">net.plot</span>(rate2.slr, <span class="at">node.scale=</span><span class="dv">3</span>, <span class="at">edge.scale=</span><span class="fl">1.5</span>, <span class="at">flag=</span><span class="st">"ARB"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>그림을 살펴보면, ARB와 관련된 5개의 연구에서 4개의 treatment와 연관되어 있음을 붉은 색 엣지로 표시해준다.</p>
<p>네트워크 특성과 관련된 정보는 다음과 같이 확인한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>network.char <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">net.tab</span>(<span class="at">data=</span>rate2.slr, <span class="at">outcome=</span><span class="st">"diabetes"</span>, <span class="at">N=</span><span class="st">"n"</span>, <span class="at">type.outcome=</span><span class="st">"rate2"</span>, <span class="at">time=</span><span class="st">"followup"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Network Characteristics</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>network.char<span class="sc">$</span>network</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   Characteristic                                        Value 
   &lt;chr&gt;                                                 &lt;chr&gt; 
 1 Number of Interventions                               6     
 2 Number of Studies                                     22    
 3 Total Number of Patients in Network                   154176
 4 Total Possible Pairwise Comparisons                   15    
 5 Total Number of Pairwise Comparisons With Direct Data 14    
 6 Is the network connected?                             TRUE  
 7 Number of Two-arm Studies                             18    
 8 Number of Multi-Arms Studies                          4     
 9 Total Number of Events in Network                     10962 
10 Number of Studies With  No Zero Events                22    
11 Number of Studies With At Least One Zero Event        0     
12 Number of Studies with All Zero Events                0     
13 Mean person follow up time                            4.06  </code></pre>
</div>
</div>
<ul>
<li>Intervention Characterisitcs</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>network.char<span class="sc">$</span>intervention</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Treatment n.studies n.events n.patients person.time.fup min.event.rate
1 ACE inhibitor         8     1618      23351          106027    0.007263184
2           ARB         5     1189      14185           57291    0.005102041
3           CCB         9     2791      38809          163469    0.009421001
4      Diuretic         8      973      18699           71931    0.006032042
5       Placebo         9     1686      22982           89692    0.002648924
6       blocker         9     2705      36150          173098    0.005788848
  max.event.rate events.per.person overall.event.rate
1     0.05705935        0.06929039         0.01526026
2     0.03229521        0.08382094         0.02075370
3     0.04168838        0.07191631         0.01707357
4     0.04081633        0.05203487         0.01352685
5     0.06160242        0.07336176         0.01879766
6     0.04548408        0.07482711         0.01562699</code></pre>
</div>
</div>
<ul>
<li>Comparison Characterisitcs</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>network.char<span class="sc">$</span>comparison</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 7
   comparison n.studies n.patients n.outcomes patient_time proportion event.rate
   &lt;chr&gt;          &lt;int&gt;      &lt;int&gt;      &lt;int&gt;        &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
 1 ACE inhib…         3      12597        538       289731     0.0427    0.00186
 2 ACE inhib…         2      16488        759       263808     0.0460    0.00288
 3 ACE inhib…         3      17893       1929       429432     0.108     0.00449
 4 ACE inhib…         3      15158       1022       409266     0.0674    0.00250
 5 ARB vs. C…         1      10161       1535        81288     0.151     0.0189 
 6 ARB vs. D…         1        392          9          784     0.0230    0.0115 
 7 ARB vs. P…         2       9778        573       127114     0.0586    0.00451
 8 ARB vs. b…         1       7999        562        71991     0.0703    0.00781
 9 CCB vs. D…         2      15739        768       220346     0.0488    0.00349
10 CCB vs. P…         1       9711        331        58266     0.0341    0.00568
11 Diuretic …         3       7343        384       198261     0.0523    0.00194
12 blocker v…         5      44974       3361      1933882     0.0747    0.00174
13 blocker v…         2       8752        241       166288     0.0275    0.00145
14 blocker v…         1       3315         71        36465     0.0214    0.00195</code></pre>
</div>
</div>
<ul>
<li>Patient Characteristics</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>BUGSnet<span class="sc">::</span><span class="fu">data.plot</span>(<span class="at">data=</span>rate2.slr, <span class="at">covariate=</span><span class="st">"age"</span>, <span class="at">half.length=</span><span class="st">"age_SD"</span>, <span class="at">by=</span><span class="st">"treatment"</span>, <span class="at">avg.hline=</span>T, <span class="at">text.size=</span><span class="dv">12</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="네트워크-모델-2" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="네트워크-모델-2"><span class="header-section-number">7.5.3</span> 네트워크 모델</h3>
<p><strong>BUGSnet</strong>에서 고정효과모형 또는 랜덤효과모형 설정은 <em>nma.model</em> 함수를 이용한다.</p>
<ul>
<li>고정효과모형</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>  model_fix <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.model</span>(<span class="at">data=</span>rate2.slr,</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">outcome=</span><span class="st">"diabetes"</span>,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">N=</span><span class="st">"n"</span>,</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">reference=</span><span class="st">"Diuretic"</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">family=</span><span class="st">"binomial"</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">link=</span><span class="st">"cloglog"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">time=</span><span class="st">"followup"</span>,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">effects=</span><span class="st">"fixed"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>랜덤효과모형</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>  model_ran <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.model</span>(<span class="at">data=</span>rate2.slr,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">outcome=</span><span class="st">"diabetes"</span>,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">N=</span><span class="st">"n"</span>,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">reference=</span><span class="st">"Diuretic"</span>,</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">family=</span><span class="st">"binomial"</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">link=</span><span class="st">"cloglog"</span>,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">time=</span><span class="st">"followup"</span>,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">effects=</span><span class="st">"random"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="mcmc-시물레이션과-진단-2" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="mcmc-시물레이션과-진단-2"><span class="header-section-number">7.5.4</span> MCMC 시물레이션과 진단</h3>
<section id="mcmc-시뮬레이션-실행-2" class="level4" data-number="7.5.4.1">
<h4 data-number="7.5.4.1" class="anchored" data-anchor-id="mcmc-시뮬레이션-실행-2"><span class="header-section-number">7.5.4.1</span> MCMC 시뮬레이션 실행</h4>
<p>고정효과모형과 랜덤효과모형 실행은 <em>nma.run</em> 함수를 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>mcmc_fix <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.run</span>(model_fix,</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.burnin=</span><span class="dv">1000</span>,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.iter=</span><span class="dv">10000</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.chains=</span><span class="dv">4</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 48
   Unobserved stochastic nodes: 27
   Total graph size: 1077

Initializing model</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>mcmc_ran <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.run</span>(model_ran,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.burnin=</span><span class="dv">1000</span>,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.iter=</span><span class="dv">10000</span>,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.chains=</span><span class="dv">4</span>,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 48
   Unobserved stochastic nodes: 54
   Total graph size: 1161

Initializing model</code></pre>
</div>
</div>
</section>
<section id="mcmc-시뮬레이션-진단-2" class="level4" data-number="7.5.4.2">
<h4 data-number="7.5.4.2" class="anchored" data-anchor-id="mcmc-시뮬레이션-진단-2"><span class="header-section-number">7.5.4.2</span> MCMC 시뮬레이션 진단</h4>
<p>고정효과모형과 랜덤효과모형은 rainbow plot과 DIC를 비교하여 선택한다. Leverage plot에서 보라색선을 넘어가는 연구는 잠재적 이상값(outlier)으로 간주할 수 있고 이들도 인해 모형이 잘 적합되지 않을 수 있음을 시사한다. 이를 위한 함수는 <em>nma.fit</em>이다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>model_fit_fix <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.fit</span>(mcmc_fix, <span class="at">main=</span><span class="st">"Fixed Effects Model"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>model_fit_ran <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.fit</span>(mcmc_ran, <span class="at">main=</span><span class="st">"Random Effects Model"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>결과를 살펴보면 랜덤효과모형이 더 나은 것으로 나타난다. DIC가 91.56으로 고정효과모형의 105.2보다 낮게 나타나며, 고정효과모형에서 잠재적 이상값이 8개가 나타나 모형 적합에 영향을 주는것으로 보인다.</p>
<ul>
<li>Assessment of convergence</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>BUGSnet<span class="sc">::</span><span class="fu">nma.diag</span>(mcmc_ran, <span class="at">plot_prompt=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-51-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$gelman.rubin
$psrf
      Point est. Upper C.I.
d[2]   1.0006443   1.002974
d[3]   1.0018540   1.004641
d[4]   1.0007793   1.001745
d[5]   0.9997727   1.000801
d[6]   0.9995592   1.000315
sigma  1.0034099   1.011283

$mpsrf
[1] 1.003758

attr(,"class")
[1] "gelman.rubin.results"

$geweke
$stats
         Chain 1    Chain 2    Chain 3      Chain 4
d[2]   0.6270877 -2.0247078 -0.3502474  0.738412806
d[3]   1.9728671 -1.6810878 -0.2011249  1.716184726
d[4]   1.0398495 -1.2019541 -0.9697977  0.603186033
d[5]   0.9018891 -1.3811599 -0.8708550  0.444636209
d[6]   1.3664307 -0.8493687 -0.4199778  1.004526399
sigma -1.0154485 -0.1249125 -0.4228015 -0.005972859

$frac1
[1] 0.1

$frac2
[1] 0.5

attr(,"class")
[1] "geweke.results"</code></pre>
</div>
</div>
</section>
</section>
<section id="일관성-검정consistency-test-2" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="일관성-검정consistency-test-2"><span class="header-section-number">7.5.5</span> 일관성 검정(consistency test)</h3>
<p>일관성 검정을 위해 랜덤효과모형과 비일관성모형의 rainbow plot과 DiC를 비교하여 일관성을 측정한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>  model_ran_inconsis <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.model</span>(<span class="at">data=</span>rate2.slr,</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">outcome=</span><span class="st">"diabetes"</span>,</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">N=</span><span class="st">"n"</span>,</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">reference=</span><span class="st">"Diuretic"</span>,</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">family=</span><span class="st">"binomial"</span>,</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">link=</span><span class="st">"cloglog"</span>,</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">time=</span><span class="st">"followup"</span>,</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type=</span><span class="st">"inconsistency"</span>,</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>                         <span class="at">effects=</span><span class="st">"random"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>mcmc_ran_inconsis <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.run</span>(model_ran_inconsis,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.burnin=</span><span class="dv">1000</span>,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.iter=</span><span class="dv">10000</span>,</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n.chains=</span><span class="dv">4</span>,</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">thin=</span><span class="dv">10</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 48
   Unobserved stochastic nodes: 64
   Total graph size: 1069

Initializing model</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>model_fit_ran <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.fit</span>(mcmc_ran, <span class="at">main=</span><span class="st">"Consistency Random Effects Model"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>model_fit_ran_inconsis <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.fit</span>(mcmc_ran_inconsis, <span class="at">main=</span><span class="st">"Inconsistency Random Effects Model"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>두 모형을 비교하면 consistency 모형의 DIC가 조금 더 낮게 나오지만 inconsistency 모형의 outlier가 leverage plot에 조금 더 가까이 나타나는 것으로 보인다. Dres는 inconsistency가 조금 더 낮게 나타나지만 모형의 복잡성(complexity)에 더 높은 비용을 지불하기 때문에 이러한 경우에 consistency 모형이 좀 더 적합한 것으로 간주된다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>BUGSnet<span class="sc">::</span><span class="fu">nma.compare</span>(model_fit_ran, model_fit_ran_inconsis)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>대부분의 점들이 라인 근처에 형성되어 있기때문에 두 모형은 비슷한 것으로 보인다. 이러한 경우에는 좀 더 일관성이 있는 모형을 선호한다.</p>
</section>
<section id="forest-plot-2" class="level3" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="forest-plot-2"><span class="header-section-number">7.5.6</span> Forest plot</h3>
<p>Placebo를 기준으로 forest plot을 그려보면 다음과 같다. 이때 <em>rma.forest</em> 함수를 이용한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>  BUGSnet<span class="sc">::</span><span class="fu">nma.forest</span>(mcmc_ran,</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">central.tdcy=</span><span class="st">"median"</span>,</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">comparator=</span><span class="st">"Placebo"</span>,</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">log.scale=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="치료-간-비교우위-선정treatment-randing-1" class="level3" data-number="7.5.7">
<h3 data-number="7.5.7" class="anchored" data-anchor-id="치료-간-비교우위-선정treatment-randing-1"><span class="header-section-number">7.5.7</span> 치료 간 비교우위 선정(treatment randing)</h3>
<p>각 치료에 대한 순위는 SUCRA plot을 통해 살펴본다. SUCRA plot을 위한 기본 정보는 <em>nma.rank</em> 함수를 이용하고, 결과물중 우선 rankogram을 이용해 ranking probability를 살펴보자.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>sucra.out <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.rank</span>(mcmc_ran, <span class="at">largerbetter=</span><span class="cn">FALSE</span>, <span class="at">sucra.palette=</span><span class="st">"Set1"</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>sucra.out<span class="sc">$</span>rankogram</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>이를 수치적으로 표현하면 다음과 같다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>sucra.out<span class="sc">$</span>ranktable</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
# Groups:   rank [6]
   rank `ACE inhibitor`   ARB blocker   CCB Diuretic Placebo
  &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1     1           23.2  76.3     0     0.05     0       0.5 
2     2           69.3  21.1     0     2        0       7.6 
3     3            6.9   2.38    0.07 26.6      0.03   64.0 
4     4            0.62  0.25    1.4  70.0      0.43   27.3 
5     5            0     0      79.6   1.3     18.6     0.55
6     6            0     0      18.9   0.05    81       0.03</code></pre>
</div>
</div>
<p>Survace under the cumulative ranking curve (SUCRA)는 결과물중 sucraplot에 담겨 있다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>sucra.out<span class="sc">$</span>sucraplot</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>SUCRA plot의 수치적 정보는 다음과 같이 추출한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>sucra.out<span class="sc">$</span>sucratable</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 7
  rank  `ACE inhibitor` ARB    blocker CCB    Diuretic Placebo
  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  
1 1     23.15           76.3   0       0.05   0        0.5    
2 2     92.48           97.38  0       2.05   0        8.1    
3 3     99.38           99.76  0.07    28.63  0.03     72.15  
4 4     100             100.01 1.47    98.66  0.46     99.42  
5 5     100             100.01 81.07   99.96  19.01    99.97  
6 6     100             100.01 99.99   100.01 100.01   100    
7 SUCRA 83              94.69  16.52   45.87  3.9      56.03  </code></pre>
</div>
</div>
<p>네트워크 메타분석의 결과를 요약하는 또 다른 방법은 League table을 산출하는 것이다. League table은 모든 중재간의 상대 효과크기와 95% 신용구간을 포함한다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>league.out <span class="ot">&lt;-</span> BUGSnet<span class="sc">::</span><span class="fu">nma.league</span>(mcmc_ran,</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">central.tdcy=</span><span class="st">"median"</span>,</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">order=</span>sucra.out<span class="sc">$</span>order,</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">log.scale=</span><span class="cn">FALSE</span>,</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">low.colour=</span><span class="st">"springgreen4"</span>,</span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mid.colour=</span><span class="st">"white"</span>,</span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">high.colour=</span><span class="st">"red"</span>,</span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">digits=</span><span class="dv">2</span>)</span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a>league.out<span class="sc">$</span>heatplot</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-network-meta-analysis_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>여기서 hazard ratio의 원 scale을 유지하기 위해 log.scale=FALSE 옵션을 사용한다. 녹색은 treatment가 더 좋은 효과를 의미하고 (추정값이 1보다 작은), 반대로 빨간색은 효과가 나쁨을 의미한다. **는 신용구간이 1을 포함하지 않음을 의미하기 때문에 통계적으로 유의한 차이를 의미한다. 이 결과를 테이블로 추출하면 다음과 같다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>league.out<span class="sc">$</span>table</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              ARB                   ACE inhibitor         Placebo              
ARB           "ARB"                 "1.07 (0.87 to 1.33)" "1.20 (1.00 to 1.45)"
ACE inhibitor "0.93 (0.75 to 1.15)" "ACE inhibitor"       "1.12 (0.96 to 1.29)"
Placebo       "0.83 (0.69 to 1.00)" "0.89 (0.78 to 1.04)" "Placebo"            
CCB           "0.80 (0.65 to 0.95)" "0.85 (0.72 to 0.99)" "0.96 (0.80 to 1.11)"
blocker       "0.67 (0.55 to 0.81)" "0.72 (0.61 to 0.84)" "0.81 (0.68 to 0.95)"
Diuretic      "0.62 (0.49 to 0.77)" "0.67 (0.56 to 0.79)" "0.75 (0.62 to 0.88)"
              CCB                   blocker               Diuretic             
ARB           "1.26 (1.06 to 1.54)" "1.48 (1.23 to 1.82)" "1.60 (1.29 to 2.03)"
ACE inhibitor "1.17 (1.01 to 1.39)" "1.38 (1.19 to 1.63)" "1.49 (1.26 to 1.80)"
Placebo       "1.05 (0.90 to 1.25)" "1.24 (1.05 to 1.47)" "1.34 (1.13 to 1.62)"
CCB           "CCB"                 "1.18 (1.03 to 1.34)" "1.27 (1.07 to 1.53)"
blocker       "0.85 (0.74 to 0.97)" "blocker"             "1.08 (0.91 to 1.31)"
Diuretic      "0.79 (0.65 to 0.93)" "0.93 (0.77 to 1.10)" "Diuretic"           </code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-cumulative-sensitivity.html" class="pagination-link" aria-label="누적메타분석과 민감도분석">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">누적메타분석과 민감도분석</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>