<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 고정효과모형과 랜덤효과모형 | Meta-analysis with R</title>
  <meta name="description" content="This is a manual for meta-analysis with R" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 고정효과모형과 랜덤효과모형 | Meta-analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a manual for meta-analysis with R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 고정효과모형과 랜덤효과모형 | Meta-analysis with R" />
  
  <meta name="twitter:description" content="This is a manual for meta-analysis with R" />
  

<meta name="author" content="Jin Hyun Nam" />


<meta name="date" content="2021-06-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter2.html"/>
<link rel="next" href="applications.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>머리말</a></li>
<li class="chapter" data-level="1" data-path="chapter1.html"><a href="chapter1.html"><i class="fa fa-check"></i><b>1</b> 메타분석 개요</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chapter1.html"><a href="chapter1.html#메타분석-과정"><i class="fa fa-check"></i><b>1.1</b> 메타분석 과정</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="chapter1.html"><a href="chapter1.html#연구주제-선정-및-연구질문"><i class="fa fa-check"></i><b>1.1.1</b> 연구주제 선정 및 연구질문</a></li>
<li class="chapter" data-level="1.1.2" data-path="chapter1.html"><a href="chapter1.html#문헌-검색"><i class="fa fa-check"></i><b>1.1.2</b> 문헌 검색</a></li>
<li class="chapter" data-level="1.1.3" data-path="chapter1.html"><a href="chapter1.html#연구-선정-개별연구의-질-검증-및-코딩"><i class="fa fa-check"></i><b>1.1.3</b> 연구 선정, 개별연구의 질 검증 및 코딩</a></li>
<li class="chapter" data-level="1.1.4" data-path="chapter1.html"><a href="chapter1.html#데이터-분석"><i class="fa fa-check"></i><b>1.1.4</b> 데이터 분석</a></li>
<li class="chapter" data-level="1.1.5" data-path="chapter1.html"><a href="chapter1.html#결과-보고"><i class="fa fa-check"></i><b>1.1.5</b> 결과 보고</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="chapter1.html"><a href="chapter1.html#메타분석-주요-용어"><i class="fa fa-check"></i><b>1.2</b> 메타분석 주요 용어</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="chapter1.html"><a href="chapter1.html#효과크기"><i class="fa fa-check"></i><b>1.2.1</b> 효과크기</a></li>
<li class="chapter" data-level="1.2.2" data-path="chapter1.html"><a href="chapter1.html#통계적-유의성"><i class="fa fa-check"></i><b>1.2.2</b> 통계적 유의성</a></li>
<li class="chapter" data-level="1.2.3" data-path="chapter1.html"><a href="chapter1.html#가중값"><i class="fa fa-check"></i><b>1.2.3</b> 가중값</a></li>
<li class="chapter" data-level="1.2.4" data-path="chapter1.html"><a href="chapter1.html#평균효과크기"><i class="fa fa-check"></i><b>1.2.4</b> 평균효과크기</a></li>
<li class="chapter" data-level="1.2.5" data-path="chapter1.html"><a href="chapter1.html#forest-plot"><i class="fa fa-check"></i><b>1.2.5</b> Forest plot</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chapter1.html"><a href="chapter1.html#일반적인-메타분석-접근법"><i class="fa fa-check"></i><b>1.3</b> 일반적인 메타분석 접근법</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter2.html"><a href="chapter2.html"><i class="fa fa-check"></i><b>2</b> 효과크기 계산</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter2.html"><a href="chapter2.html#연속형-자료의-효과크기-계산"><i class="fa fa-check"></i><b>2.1</b> 연속형 자료의 효과크기 계산</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="chapter2.html"><a href="chapter2.html#평균차mean-difference-md"><i class="fa fa-check"></i><b>2.1.1</b> 평균차(mean difference; MD)</a></li>
<li class="chapter" data-level="2.1.2" data-path="chapter2.html"><a href="chapter2.html#example"><i class="fa fa-check"></i><b>2.1.2</b> Example</a></li>
<li class="chapter" data-level="2.1.3" data-path="chapter2.html"><a href="chapter2.html#표준화-평균차"><i class="fa fa-check"></i><b>2.1.3</b> 표준화 평균차</a></li>
<li class="chapter" data-level="2.1.4" data-path="chapter2.html"><a href="chapter2.html#example-1"><i class="fa fa-check"></i><b>2.1.4</b> Example</a></li>
<li class="chapter" data-level="2.1.5" data-path="chapter2.html"><a href="chapter2.html#두-집단사전-사후검사-전후-비교조사"><i class="fa fa-check"></i><b>2.1.5</b> 두 집단(사전-사후검사) 전후 비교조사</a></li>
<li class="chapter" data-level="2.1.6" data-path="chapter2.html"><a href="chapter2.html#단일집단사전-사후검사"><i class="fa fa-check"></i><b>2.1.6</b> 단일집단(사전-사후검사)</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chapter2.html"><a href="chapter2.html#이분형-자료의-효과크기-계산"><i class="fa fa-check"></i><b>2.2</b> 이분형 자료의 효과크기 계산</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chapter2.html"><a href="chapter2.html#상대위험률relative-risk-rr"><i class="fa fa-check"></i><b>2.2.1</b> 상대위험률(Relative Risk; RR)</a></li>
<li class="chapter" data-level="2.2.2" data-path="chapter2.html"><a href="chapter2.html#example-2"><i class="fa fa-check"></i><b>2.2.2</b> Example</a></li>
<li class="chapter" data-level="2.2.3" data-path="chapter2.html"><a href="chapter2.html#오즈비odds-ratio-or"><i class="fa fa-check"></i><b>2.2.3</b> 오즈비(Odds Ratio; OR)</a></li>
<li class="chapter" data-level="2.2.4" data-path="chapter2.html"><a href="chapter2.html#example-3"><i class="fa fa-check"></i><b>2.2.4</b> Example</a></li>
<li class="chapter" data-level="2.2.5" data-path="chapter2.html"><a href="chapter2.html#위험율-차이risk-difference-rd"><i class="fa fa-check"></i><b>2.2.5</b> 위험율 차이(Risk Difference, RD)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chapter2.html"><a href="chapter2.html#time-to-event-자료의-효과크기-계산"><i class="fa fa-check"></i><b>2.3</b> Time to event 자료의 효과크기 계산</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chapter2.html"><a href="chapter2.html#example-4"><i class="fa fa-check"></i><b>2.3.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapter2.html"><a href="chapter2.html#상관관계-자료의-효과크기-계산"><i class="fa fa-check"></i><b>2.4</b> 상관관계 자료의 효과크기 계산</a></li>
<li class="chapter" data-level="2.5" data-path="chapter2.html"><a href="chapter2.html#효과크기의-상호-전환"><i class="fa fa-check"></i><b>2.5</b> 효과크기의 상호 전환</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter3.html"><a href="chapter3.html"><i class="fa fa-check"></i><b>3</b> 고정효과모형과 랜덤효과모형</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter3.html"><a href="chapter3.html#fixed-vs.-random-effect-model"><i class="fa fa-check"></i><b>3.1</b> Fixed vs. Random effect model</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chapter3.html"><a href="chapter3.html#고정효과모형과-랜덤효과모형의-의미"><i class="fa fa-check"></i><b>3.1.1</b> 고정효과모형과 랜덤효과모형의 의미</a></li>
<li class="chapter" data-level="3.1.2" data-path="chapter3.html"><a href="chapter3.html#고정효과모형과-랜덤효과모형의-적용-과정"><i class="fa fa-check"></i><b>3.1.2</b> 고정효과모형과 랜덤효과모형의 적용 과정</a></li>
<li class="chapter" data-level="3.1.3" data-path="chapter3.html"><a href="chapter3.html#example-5"><i class="fa fa-check"></i><b>3.1.3</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chapter3.html"><a href="chapter3.html#효과크기의-이질성"><i class="fa fa-check"></i><b>3.2</b> 효과크기의 이질성</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="chapter3.html"><a href="chapter3.html#효과크기의-이질성-1"><i class="fa fa-check"></i><b>3.2.1</b> 효과크기의 이질성</a></li>
<li class="chapter" data-level="3.2.2" data-path="chapter3.html"><a href="chapter3.html#이질성-통계량---q-tau2-및-i2"><i class="fa fa-check"></i><b>3.2.2</b> 이질성 통계량 - <span class="math inline">\(Q\)</span>, <span class="math inline">\(\tau^2\)</span> 및 <span class="math inline">\(I^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chapter3.html"><a href="chapter3.html#연속형-자료-예제"><i class="fa fa-check"></i><b>3.3</b> 연속형 자료 예제</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="chapter3.html"><a href="chapter3.html#example-6"><i class="fa fa-check"></i><b>3.3.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chapter3.html"><a href="chapter3.html#이산형-자료-예제"><i class="fa fa-check"></i><b>3.4</b> 이산형 자료 예제</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chapter3.html"><a href="chapter3.html#example-7"><i class="fa fa-check"></i><b>3.4.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chapter3.html"><a href="chapter3.html#time-to-event-예제"><i class="fa fa-check"></i><b>3.5</b> Time to event 예제</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="chapter3.html"><a href="chapter3.html#example-8"><i class="fa fa-check"></i><b>3.5.1</b> Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>4</b> Applications</a>
<ul>
<li class="chapter" data-level="4.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Meta-analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter3" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> 고정효과모형과 랜덤효과모형</h1>
<div id="fixed-vs.-random-effect-model" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Fixed vs. Random effect model</h2>
<div id="고정효과모형과-랜덤효과모형의-의미" class="section level3" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> 고정효과모형과 랜덤효과모형의 의미</h3>
<p>메타분석에서 고정효과모형(fixed effect model)과 랜덤효과모형(random effet model)은 실제 효과크기(true effect size)를 어떻게 가정하느냐에 따라 달라진다. 즉 연구자가 평균효과크기를 계산할 때 두 가지 방법 중 어떤 방법을 선택해서 계산하느냐에 따라 평균효과크기의 추정값이 달라지고 그에 따라 평균효과크기의 정밀성(precision)도 달라진다.</p>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>고정효과모형</th>
<th>랜덤효과모형</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>가정: 모든 연구의 모집단 효과크기는 동일하다. (모집단 효과크기의 동질성)</td>
<td>가정: 각 연구는 대상자, 개입방법, 기간 등이 서로 다르기 때문에 개별 연구의 모집단 효과크기는 서로 다르다. (모집단 효과크기의 이질성)</td>
</tr>
<tr class="even">
<td>목적: 동일한 모집단의 효과, 즉 one true effect (common effect)를 추정한다.</td>
<td>목적: 서로 상이한 모집단의 효과크기 분포의 평균을 추정한다.</td>
</tr>
<tr class="odd">
<td>각 연구의 효과크기 차이는 표본오차(sampling error)에 기인한다.</td>
<td>각 연구의 효과크기 차이는 표본오차와 연구 간 분산(between-study variance)으로 구성된다.</td>
</tr>
<tr class="even">
<td>평균효과크기는 각 연구의 동일한 모집단 효과크기를 추정한 값이다.</td>
<td>평균효과크기는 각 연구의 서로 상이한 모집단 효과크기 분포의 추정 평균값이다.</td>
</tr>
<tr class="odd">
<td>표본크기가 커지면 표준오차는 0에 가까워진다.</td>
<td>표본크기가 크고 동시에 연구의 규모도 커지면 표준오차는 0에 가까워진다.</td>
</tr>
</tbody>
</table>
<p>고정효과모형과 랜덤효과모형을 그림으로 설명하면 다음과 같다.</p>
<p>고정효과모형: 관찰된 효과크기는 실제(true) 하나의 효과 크기 <span class="math inline">\(\theta\)</span>로 부터 발생하고 표본오차(sampling error)에 의해서만 차이가 발생한다고 가정한다. 이를 표현하면 다음과 같다.</p>
<p><span class="math display">\[
\theta_k = \theta + \epsilon_k
\]</span></p>
<p><img src="ch3/f1.jpg" /></p>
<p>랜덤효과모형: 랜덤효과모형은 고정효과모형에서 가정하는 표본오차(<span class="math inline">\(\epsilon_k\)</span>) 외에도 연구 간 발생하는 실제 효과크기의 분포를 고려하고, 때문에 연구 간 실제 효과크기가 서로 다를 수 있음을 가정한다. 이를 <span class="math inline">\(\zeta_k\)</span>로 표현하고 관측된 <span class="math inline">\(\theta_k\)</span>는 다음과 같이 표현된다.</p>
<p><span class="math display">\[
\theta_k=\mu+\epsilon_k +\zeta_k
\]</span></p>
<p><img src="ch3/f2.jpg" /></p>
<p>여기서 circle은 모집단 효과크기이며 square는 관찰된 효과크기를 의미한다.</p>
<p>그림에서 보는 것처럼 고정효과모형은 각 연구 간 관찰된 효과크기는 서로 다르지만 추정하고자 하는 모집단의 효과크기는 동일하다. 즉 연구 간 효과크기가 서로 다른것은 표본오차에 의한 것이다. 반면 랜덤효과모형은 각 연구 간 관찰된 효과크기가 서로 다르며 추정하고자 하는 모집단의 효과크기도 각각 다르다. 이것은 표본오차에 의한 차이, 즉 연구 내 분산(within-study variance) 뿐 아니라 연구 간 분산(between-study variance)이 존재하기 때문이다.</p>
<p>고정효과모형과 랜덤효과모형의 차이점은 다음과 같다.</p>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>고정효과모형</th>
<th>랜덤효과모형</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>각 연구들이 기능적으로 동일(identical)하다.</td>
<td>각 연구들의 표본, 개입방법 등이 서로 다르다.</td>
</tr>
<tr class="even">
<td>효과크기의 동질성(homogeneity of effect)을 가정한다. 따라서 각 연구의 연구 간 분산은 0으로 고정한다.</td>
<td>효과크기의 이질성(heterogenety of effect)을 가정하고 연구 간 분산을 인정한다.</td>
</tr>
<tr class="odd">
<td>각 연구의 가중값은 매우 다르다.</td>
<td>가중값이 보다 균형적이고 표준오차가 크다. 따라서 신뢰구간이 더 길다.</td>
</tr>
<tr class="even">
<td>기능적으로 동일한 연구이며, 연구 결과의 적용을 일반화하기보다는 특정 집단에 한정하고자 하는 경우 사용한다.</td>
<td>각 연구는 연구자들에 의해 독립적으로 이루어진 것이며, 연구 결과를 다른 집단에도 일반화하여 적용하고자 하는 경우에 사용한다.</td>
</tr>
</tbody>
</table>
<ul>
<li>효과크기의 계산 모형(computational model) 선택은, 즉 평균효과크기를 계산할 때 고정효과모형을 선택할 것인가 아니면 랜덤효과모형을 선택할 것인가는 각 연구들이 동일한 모집단의 효과크기를 가정하고 있는지, 그리고 분석의 목적이 무엇인지에 따라 결정되어야 한다.</li>
</ul>
</div>
<div id="고정효과모형과-랜덤효과모형의-적용-과정" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> 고정효과모형과 랜덤효과모형의 적용 과정</h3>
<div id="고정효과모형" class="section level4" number="3.1.2.1">
<h4><span class="header-section-number">3.1.2.1</span> 고정효과모형</h4>
<p>고정효과모형의 적용 과정을 살펴보기 위해 표준화 평균차를 기준으로 살펴보자. 표준화 평균차 <span class="math inline">\(d_i\)</span>와 그 분산은 다음과 같다.</p>
<ul>
<li>표준화 평균차:</li>
</ul>
<p><span class="math display">\[
d_i = \frac{\bar{X_1}-\bar{X_2}}{S_p}
\]</span></p>
<p>여기서 <span class="math inline">\(S_p\)</span>는 합동표준편차를 의미하며, <span class="math inline">\(S_p\)</span>는 다음과 같다.</p>
<p><span class="math display">\[
S_p = \sqrt{\frac{(n_1 -1)S_1^2 + (n_2-1)S_2^2}{n_1+n_2-2}}
\]</span></p>
<p>개별 연구의 표준화 평균차 <span class="math inline">\(d_i\)</span>의 분산은 다음과 같이 정의한다.</p>
<p><span class="math display">\[
Var(d_i)=\frac{1}{n_1}+\frac{1}{n_2}+\frac{d_i^2}{2(n_1+n_2)}=\frac{n_1+n_2}{n_1n_2}+\frac{d_i^2}{2(n_1+n_2)}
\]</span></p>
<ul>
<li>보정된 표준화 평균차 <span class="math inline">\(g_i\)</span></li>
</ul>
<p><span class="math display">\[
g_i = J \times d_i, \,\,\, J=1-\frac{3}{4(n_1+n_2)-9}
\]</span></p>
<p><span class="math inline">\(g_i\)</span>의 분산은 다음과 같다.</p>
<p><span class="math display">\[
Var(g_i)=J^2\times Var(d_i)
\]</span></p>
<p>따라서 보정된 표준화 평균차의 신뢰구간은 다음과 같다.</p>
<p><span class="math display">\[
CI(g_i)=g_i \pm z_{\alpha/2}\times SE(g_i), \quad SE(g_i)=\sqrt{Var(g_i)}
\]</span></p>
<p>고정효과모형의 평균효과크기와 분산은 다음과 같다.</p>
<p>평균효과크기 <span class="math inline">\(M\)</span>:
<span class="math display">\[
M = \frac{\sum_{i=1}^K w_ig_i}{\sum_{i=1}^K w_i}
\]</span></p>
<p>여기서 <span class="math inline">\(w_i=\frac{1}{Var(g_i)}\)</span>이다.</p>
<ul>
<li>평균효과크기 <span class="math inline">\(M\)</span>의 분산과 표준오차:</li>
</ul>
<p><span class="math display">\[Var(M) = \frac{1}{\sum_{i=1}^K w_i}, \quad SE(M)=\sqrt{V_M}\]</span></p>
<p>이때, 귀무가설 <span class="math inline">\(H_0: M=0\)</span> 하에서 검정통계량은</p>
<p><span class="math display">\[Z=\frac{M}{SE(M)}\]</span></p>
<p>이며, 신뢰구간은 다음과 같다.</p>
<p><span class="math display">\[CI=(M-z_{\alpha/2}\times SE(M),\,\,\, M+z_{\alpha/2}\times SE(M))\]</span></p>
</div>
<div id="랜덤효과모형" class="section level4" number="3.1.2.2">
<h4><span class="header-section-number">3.1.2.2</span> 랜덤효과모형</h4>
<p>랜덤효과모형은 고정효과모형과 기본적인 과정에서 차이가 없으며, 다만 평균효과크기를 추정 할 때 적용되는 분산이 달라진다. 랜덤효과모형의 적용 과정을 살펴보기 위해 고정효과모형과 같이 표준화 평균 차를 기준으로 살펴보자. 표준화 평균차 <span class="math inline">\(d_i\)</span>와 분산은 다음과 같다.</p>
<p>표준화된 평균 차이:
<span class="math display">\[
d_i = \frac{\bar{X_1}-\bar{X_2}}{S_p}
\]</span></p>
<p>여기서 <span class="math inline">\(S_p\)</span>는 합동표준편차를 의미하며, <span class="math inline">\(S_p\)</span>는 다음과 같다.</p>
<p><span class="math display">\[
S_p = \sqrt{\frac{(n_1 -1)S_1^2 + (n_2-1)S_2^2}{n_1+n_2-2}}
\]</span></p>
<p>개별 연구의 표준화된 평균 차이 <span class="math inline">\(d_i\)</span>의 분산은 다음과 같이 정의한다.</p>
<p><span class="math display">\[
Var(d_i)=\frac{1}{n_1}+\frac{1}{n_2}+\frac{d_i^2}{2(n_1+n_2)}=\frac{n_1+n_2}{n_1n_2}+\frac{d_i^2}{2(n_1+n_2)}
\]</span></p>
<p>교정된 표준화된 평균 차이</p>
<p><span class="math display">\[
g_i = J \times d, \,\,\, J=1-\frac{3}{4(n_1+n_2)-9}
\]</span></p>
<p><span class="math inline">\(g_i\)</span>의 분산은 다음과 같다.</p>
<p><span class="math display">\[
Var(g_i)=J^2\times Var(d_i)
\]</span></p>
<p>따라서 교정된 표준화된 평균 차이의 신뢰구간은 다음과 같다.</p>
<p><span class="math display">\[
CI(g_i)=g_i \pm z_{\alpha/2}\times SE(g_i), \quad SE(g_i)=\sqrt{Var(g_i)}
\]</span></p>
<p>랜덤효과모형의 평균효과크기와 분산은 다음과 같다.</p>
<ul>
<li>평균효과크기 <span class="math inline">\(M\)</span>:</li>
</ul>
<p><span class="math display">\[
M = \frac{\sum_{i=1}^K w_ig_i}{\sum_{i=1}^K w_i}
\]</span></p>
<p>여기서, <span class="math inline">\(w_i=\frac{1}{Var(g_i)*}\)</span>이며 <span class="math inline">\(Var(g_i)*\)</span>는 <span class="math inline">\(Var(g_i)*=Var(g_i)+\tau^2\)</span>이다.</p>
<p>연구 간 분산을 의미하는 <span class="math inline">\(\tau^2\)</span>은 다음과 같이 정의한다.</p>
<p><span class="math display">\[
\tau^2=\frac{Q-df}{C}, \quad df=K-1
\]</span></p>
<p>여기서, <span class="math inline">\(Q=\sum_{i=1}^K w_ig_i^2 - \frac{(\sum_{i=1}^K w_ig_i)^2}{\sum_{i=1}^Kw_i}\)</span>,
<span class="math inline">\(C=\sum_{i=1}^K w_i - \frac{\sum_{i=1}^K w_i^2}{\sum_{i=1}^K w_i}\)</span>이다.</p>
<p>평균효과크기 <span class="math inline">\(M\)</span>의 분산과 표준오차:</p>
<p><span class="math display">\[Var(M) = \frac{1}{\sum_{i=1}^K w_i}, \quad SE(M)=\sqrt{Var(M)}\]</span></p>
<p>이때, 귀무가설 <span class="math inline">\(H_0: M=0\)</span> 하에서 검정통계량은</p>
<p><span class="math display">\[Z=\frac{M}{SE(M)}\]</span></p>
<p>이며, 신뢰구간은 다음과 같다.</p>
<p><span class="math display">\[CI=(M-z_{\alpha/2}\times SE(M), M+z_{\alpha/2}\times SE(M))\]</span></p>
<p>따라서 고정효과모형과 랜덤효과모형에서 평균효과크기를 계산할때 차이점은 랜덤효과모형의 가중값 산출시 연구 간 분산 <span class="math inline">\(\tau^2\)</span>이 더해지며 이로 인해 가중평균, 분산, 신뢰구간의 크기가 달라지게 된다.</p>
</div>
</div>
<div id="example-5" class="section level3" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Example</h3>
<ul>
<li>A meta-analysis of potential biomarkers associated with severity of coronavirus disease 2019 (COVID-19) (Danwang et al., 2020)</li>
</ul>
<p><img src="ch3/random.png" /></p>
<div id="데이터-입력-5" class="section level4" number="3.1.3.1">
<h4><span class="header-section-number">3.1.3.1</span> 데이터 입력:</h4>
<p>두 집단간 비교연구에서 필요한 값은 각 집단의 표본크기(n1, n2), 평균(m1, m2), 표준편차(s1, s2) 값이다. 여기서는 10개의 개별 연구의 값을 입력한다.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chapter3.html#cb1-1" aria-hidden="true" tabindex="-1"></a>random <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">&#39;</span></span>
<span id="cb1-2"><a href="chapter3.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="st">Study   m1  s1  n1  m2   s2 n2</span></span>
<span id="cb1-3"><a href="chapter3.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="st">Wang,R  0.74    0.3111  25  1.11    0.4 100</span></span>
<span id="cb1-4"><a href="chapter3.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="st">Feng,Y  0.82    0.437   70  1.13    0.5481  352</span></span>
<span id="cb1-5"><a href="chapter3.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="st">Cai,Q   0.98    0.4 58  1.34    0.6148  240</span></span>
<span id="cb1-6"><a href="chapter3.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="st">Wan,S   0.8 0.2963  40  1.2 0.5926  95</span></span>
<span id="cb1-7"><a href="chapter3.html#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="st">Ki,K    0.7 0.3778  25  1.23    0.363   58</span></span>
<span id="cb1-8"><a href="chapter3.html#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="st">Zheng,F 0.85    0.2741  30  1.12    0.4519  131</span></span>
<span id="cb1-9"><a href="chapter3.html#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="st">Guan,W  0.8 0.2963  153 1   0.4444  726</span></span>
<span id="cb1-10"><a href="chapter3.html#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="st">Zhang,J 0.7 0.3704  56  0.8 0.4444  82</span></span>
<span id="cb1-11"><a href="chapter3.html#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="st">Wang,D  0.8 0.2963  36  0.9 0.4444  102</span></span>
<span id="cb1-12"><a href="chapter3.html#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="st">Mao,L   0.9 1.8519  88  1.3 1.6296  126</span></span>
<span id="cb1-13"><a href="chapter3.html#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="st">Qin,C   0.8 0.3704  286 1   0.4444  166</span></span>
<span id="cb1-14"><a href="chapter3.html#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="st">Yun,L   0.78    0.4148  21  1.14    0.4741  271</span></span>
<span id="cb1-15"><a href="chapter3.html#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span>, <span class="at">header=</span>T)</span>
<span id="cb1-16"><a href="chapter3.html#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="chapter3.html#cb1-17" aria-hidden="true" tabindex="-1"></a>random</span></code></pre></div>
<pre><code>##      Study   m1     s1  n1   m2     s2  n2
## 1   Wang,R 0.74 0.3111  25 1.11 0.4000 100
## 2   Feng,Y 0.82 0.4370  70 1.13 0.5481 352
## 3    Cai,Q 0.98 0.4000  58 1.34 0.6148 240
## 4    Wan,S 0.80 0.2963  40 1.20 0.5926  95
## 5     Ki,K 0.70 0.3778  25 1.23 0.3630  58
## 6  Zheng,F 0.85 0.2741  30 1.12 0.4519 131
## 7   Guan,W 0.80 0.2963 153 1.00 0.4444 726
## 8  Zhang,J 0.70 0.3704  56 0.80 0.4444  82
## 9   Wang,D 0.80 0.2963  36 0.90 0.4444 102
## 10   Mao,L 0.90 1.8519  88 1.30 1.6296 126
## 11   Qin,C 0.80 0.3704 286 1.00 0.4444 166
## 12   Yun,L 0.78 0.4148  21 1.14 0.4741 271</code></pre>
</div>
<div id="standardized-mean-difference-1" class="section level4" number="3.1.3.2">
<h4><span class="header-section-number">3.1.3.2</span> Standardized mean difference</h4>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chapter3.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(random)</span>
<span id="cb3-2"><a href="chapter3.html#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="chapter3.html#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="do">### 합동분산추정량</span></span>
<span id="cb3-4"><a href="chapter3.html#cb3-4" aria-hidden="true" tabindex="-1"></a>sp2 <span class="ot">&lt;-</span> ((n1<span class="dv">-1</span>)<span class="sc">*</span>s1<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (n2<span class="dv">-1</span>)<span class="sc">*</span>s2<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n1<span class="sc">+</span>n2<span class="dv">-2</span>)</span>
<span id="cb3-5"><a href="chapter3.html#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="chapter3.html#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="do">### 표준오차</span></span>
<span id="cb3-7"><a href="chapter3.html#cb3-7" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp2)</span>
<span id="cb3-8"><a href="chapter3.html#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="chapter3.html#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="do">### 표준화 평균차</span></span>
<span id="cb3-10"><a href="chapter3.html#cb3-10" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> (m1 <span class="sc">-</span> m2)<span class="sc">/</span>sp</span>
<span id="cb3-11"><a href="chapter3.html#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="chapter3.html#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(random,sp,d)</span></code></pre></div>
<pre><code>##      Study   m1     s1  n1   m2     s2  n2        sp          d
## 1   Wang,R 0.74 0.3111  25 1.11 0.4000 100 0.3842721 -0.9628595
## 2   Feng,Y 0.82 0.4370  70 1.13 0.5481 352 0.5314447 -0.5833157
## 3    Cai,Q 0.98 0.4000  58 1.34 0.6148 240 0.5796580 -0.6210559
## 4    Wan,S 0.80 0.2963  40 1.20 0.5926  95 0.5233954 -0.7642406
## 5     Ki,K 0.70 0.3778  25 1.23 0.3630  58 0.3674473 -1.4423836
## 6  Zheng,F 0.85 0.2741  30 1.12 0.4519 131 0.4250532 -0.6352146
## 7   Guan,W 0.80 0.2963 153 1.00 0.4444 726 0.4224675 -0.4734092
## 8  Zhang,J 0.70 0.3704  56 0.80 0.4444  82 0.4160616 -0.2403490
## 9   Wang,D 0.80 0.2963  36 0.90 0.4444 102 0.4114126 -0.2430650
## 10   Mao,L 0.90 1.8519  88 1.30 1.6296 126 1.7242977 -0.2319785
## 11   Qin,C 0.80 0.3704 286 1.00 0.4444 166 0.3991296 -0.5010904
## 12   Yun,L 0.78 0.4148  21 1.14 0.4741 271 0.4702505 -0.7655495</code></pre>
</div>
<div id="corrected-standardized-mean-difference-1" class="section level4" number="3.1.3.3">
<h4><span class="header-section-number">3.1.3.3</span> Corrected standardized mean difference</h4>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chapter3.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">### d의 분산</span></span>
<span id="cb5-2"><a href="chapter3.html#cb5-2" aria-hidden="true" tabindex="-1"></a>vard <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>n1<span class="sc">+</span><span class="dv">1</span><span class="sc">/</span>n2<span class="sc">+</span>d<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(n1<span class="sc">+</span>n2))</span>
<span id="cb5-3"><a href="chapter3.html#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="chapter3.html#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="do">### D의 표준오차</span></span>
<span id="cb5-5"><a href="chapter3.html#cb5-5" aria-hidden="true" tabindex="-1"></a>sed <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(vard)</span>
<span id="cb5-6"><a href="chapter3.html#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="chapter3.html#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="chapter3.html#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="do">### 보정된 표준화 평균차 Hedges&#39; g</span></span>
<span id="cb5-9"><a href="chapter3.html#cb5-9" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> (<span class="dv">1-3</span><span class="sc">/</span>(<span class="dv">4</span><span class="sc">*</span>(n1<span class="sc">+</span>n2)<span class="sc">-</span><span class="dv">9</span>))</span>
<span id="cb5-10"><a href="chapter3.html#cb5-10" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> d <span class="sc">*</span> J</span>
<span id="cb5-11"><a href="chapter3.html#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="chapter3.html#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="do">### g의 분산과 표준오차</span></span>
<span id="cb5-13"><a href="chapter3.html#cb5-13" aria-hidden="true" tabindex="-1"></a>varg <span class="ot">&lt;-</span> J<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>vard; seg <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(varg)</span>
<span id="cb5-14"><a href="chapter3.html#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="chapter3.html#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="do">### 신뢰 하한 </span></span>
<span id="cb5-16"><a href="chapter3.html#cb5-16" aria-hidden="true" tabindex="-1"></a>lbg <span class="ot">&lt;-</span> g <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>seg</span>
<span id="cb5-17"><a href="chapter3.html#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="chapter3.html#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="do">### 신뢰 상한 </span></span>
<span id="cb5-19"><a href="chapter3.html#cb5-19" aria-hidden="true" tabindex="-1"></a>ubg <span class="ot">&lt;-</span> g <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>seg</span>
<span id="cb5-20"><a href="chapter3.html#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="chapter3.html#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">study=</span>random[,<span class="dv">1</span>],g,varg,lbg,ubg) </span></code></pre></div>
<pre><code>##      study          g        varg        lbg        ubg
## 1   Wang,R -0.9569764 0.053054084 -1.4084242 -0.5055287
## 2   Feng,Y -0.5822734 0.017467184 -0.8413091 -0.3232378
## 3    Cai,Q -0.6194810 0.021943492 -0.9098170 -0.3291449
## 4    Wan,S -0.7599229 0.037264848 -1.1382764 -0.3815694
## 5     Ki,K -1.4289868 0.068484235 -1.9418994 -0.9160742
## 6  Zheng,F -0.6322136 0.041822032 -1.0330348 -0.2313924
## 7   Guan,W -0.4730043 0.008027091 -0.6486053 -0.2974032
## 8  Zhang,J -0.2390211 0.029928110 -0.5780898  0.1000476
## 9   Wang,D -0.2417221 0.037379280 -0.6206561  0.1372119
## 10   Mao,L -0.2311569 0.019288512 -0.5033627  0.0410490
## 11   Qin,C -0.5002548 0.009765704 -0.6939415 -0.3065681
## 12   Yun,L -0.7635679 0.052042157 -1.2106896 -0.3164462</code></pre>
</div>
<div id="가중값-4" class="section level4" number="3.1.3.4">
<h4><span class="header-section-number">3.1.3.4</span> 가중값</h4>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chapter3.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">### w</span></span>
<span id="cb7-2"><a href="chapter3.html#cb7-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>varg</span>
<span id="cb7-3"><a href="chapter3.html#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="chapter3.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="do">### Q</span></span>
<span id="cb7-5"><a href="chapter3.html#cb7-5" aria-hidden="true" tabindex="-1"></a>Q <span class="ot">=</span> <span class="fu">sum</span>(w<span class="sc">*</span>g<span class="sc">^</span><span class="dv">2</span>)<span class="sc">-</span>(<span class="fu">sum</span>(w<span class="sc">*</span>g))<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">sum</span>(w)</span>
<span id="cb7-6"><a href="chapter3.html#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="chapter3.html#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="do">### C</span></span>
<span id="cb7-8"><a href="chapter3.html#cb7-8" aria-hidden="true" tabindex="-1"></a>C <span class="ot">=</span> <span class="fu">sum</span>(w) <span class="sc">-</span> <span class="fu">sum</span>(w<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(w)</span>
<span id="cb7-9"><a href="chapter3.html#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="chapter3.html#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="do">### tau</span></span>
<span id="cb7-11"><a href="chapter3.html#cb7-11" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">dim</span>(random)[<span class="dv">1</span>]<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb7-12"><a href="chapter3.html#cb7-12" aria-hidden="true" tabindex="-1"></a>tau2 <span class="ot">=</span> (Q <span class="sc">-</span> df)<span class="sc">/</span>C</span>
<span id="cb7-13"><a href="chapter3.html#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="chapter3.html#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="do">### 가중값</span></span>
<span id="cb7-15"><a href="chapter3.html#cb7-15" aria-hidden="true" tabindex="-1"></a>wg <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>(varg<span class="sc">+</span>tau2)</span>
<span id="cb7-16"><a href="chapter3.html#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="chapter3.html#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="do">### 가중값 표준화</span></span>
<span id="cb7-18"><a href="chapter3.html#cb7-18" aria-hidden="true" tabindex="-1"></a>wpg <span class="ot">&lt;-</span> wg<span class="sc">/</span><span class="fu">sum</span>(wg)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb7-19"><a href="chapter3.html#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="chapter3.html#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">study=</span>random[,<span class="dv">1</span>],g,varg,wg,wpg)</span></code></pre></div>
<pre><code>##      study          g        varg        wg       wpg
## 1   Wang,R -0.9569764 0.053054084 11.088777  6.070777
## 2   Feng,Y -0.5822734 0.017467184 18.316908 10.027964
## 3    Cai,Q -0.6194810 0.021943492 16.928874  9.268056
## 4    Wan,S -0.7599229 0.037264848 13.442300  7.359261
## 5     Ki,K -1.4289868 0.068484235  9.468673  5.183818
## 6  Zheng,F -0.6322136 0.041822032 12.666370  6.934462
## 7   Guan,W -0.4730043 0.008027091 22.146298 12.124441
## 8  Zhang,J -0.2390211 0.029928110 14.913066  8.164461
## 9   Wang,D -0.2417221 0.037379280 13.421654  7.347958
## 10   Mao,L -0.2311569 0.019288512 17.725564  9.704220
## 11   Qin,C -0.5002548 0.009765704 21.325196 11.674912
## 12   Yun,L -0.7635679 0.052042157 11.214617  6.139670</code></pre>
</div>
<div id="평균효과크기와-분산-신뢰구간-3" class="section level4" number="3.1.3.5">
<h4><span class="header-section-number">3.1.3.5</span> 평균효과크기와 분산, 신뢰구간</h4>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chapter3.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">### 평균효과크기</span></span>
<span id="cb9-2"><a href="chapter3.html#cb9-2" aria-hidden="true" tabindex="-1"></a>Mg <span class="ot">&lt;-</span> <span class="fu">sum</span>(wg<span class="sc">*</span>g)<span class="sc">/</span><span class="fu">sum</span>(wg)</span>
<span id="cb9-3"><a href="chapter3.html#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="chapter3.html#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="do">### 평균효과크기의 분산</span></span>
<span id="cb9-5"><a href="chapter3.html#cb9-5" aria-hidden="true" tabindex="-1"></a>varMg <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">sum</span>(wg)</span>
<span id="cb9-6"><a href="chapter3.html#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="chapter3.html#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="do">### 평균효과크기의 표준오차</span></span>
<span id="cb9-8"><a href="chapter3.html#cb9-8" aria-hidden="true" tabindex="-1"></a>seMg <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(varMg)</span>
<span id="cb9-9"><a href="chapter3.html#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="chapter3.html#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="do">### 평균효과크기의 신뢰구간</span></span>
<span id="cb9-11"><a href="chapter3.html#cb9-11" aria-hidden="true" tabindex="-1"></a>lbg <span class="ot">&lt;-</span> Mg <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>seMg</span>
<span id="cb9-12"><a href="chapter3.html#cb9-12" aria-hidden="true" tabindex="-1"></a>ubg <span class="ot">&lt;-</span> Mg <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>seMg</span>
<span id="cb9-13"><a href="chapter3.html#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="chapter3.html#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(Mg, varMg, seMg, lbg, ubg)</span></code></pre></div>
<pre><code>##           Mg       varMg       seMg        lbg        ubg
## 1 -0.5700837 0.005474703 0.07399124 -0.7151038 -0.4250635</code></pre>
</div>
</div>
</div>
<div id="효과크기의-이질성" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> 효과크기의 이질성</h2>
<div id="효과크기의-이질성-1" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> 효과크기의 이질성</h3>
<p>메타분석의 목표는 단순히 효과크기의 평균을 도출하는데 있지 않고 효과크기의 전체 패턴(pattern of effect sizes)을 이해하는 데 있다. 일반적으로 메타분석을 하게 되면 각 개별 연구로부터 도출된 추정된 모집단의 효과크기는 서로 다르게 나타나게 되는데, 이러한 효과크기간의 차이(differnces in effect sizes)를 효과크기의 이질성(heterogeneity)이라고 부른다. 즉 효과크기의 이질성은 각 연구로부터 나타난 효과크기의 분포(dispersion of effect sizes) 정도를 의미하며, 연구 간 효과크기가 일관되지 않은 정도를 의미한다(inconsistency across studies).</p>
<p>메타분석에서 이질성을 평가하는 것은 매우 중요하다. 실제 효과가 다른 두 개 이상의 연구가 하위 그룹으로 존재하기 때문에 높은 이질성이 발생할 수 있다. 이러한 정보는 연구에 매우 유용하게 쓰일 수 있다. 왜냐하면 이를 통해 효과가 더 낮거나 더 높은 특정 중재나 집단을 찾을 수 있기 때문이다. 통계적 관점에서도 높은 이질성은 문제가 되며, 특히 매우 높은 이질성은 연구에 공통점이 없음을 뜻하고 “실제” 진정한 효과가 없음을 의미 할 수 있다. 즉, 합동 효과를 보고하는 것 자체가 전혀 의미 없을 수도 있다 (Borenstein et al. 2011).</p>
<ul>
<li>연구간 이질성의 예:</li>
</ul>
<p><img src="ch3/hetero.png" />
* A practical guide to meta-analysis (Chung et al., 2006)</p>
<p>메타분석에서 발생하는 효과크기 이질성은 크게 세가지 유형으로 구분된다.</p>
<ol style="list-style-type: decimal">
<li><p>임상적 이질성: 연구의 표본 간 특성 차이로 발생한다. 예를 들어, 한 연구는 노인을 대상으로 한 연구이고 다른 연구는 대부분 아주 어린 연구 참가자를 모집한 경우 연구간 표본 차이로 인한 이질성이 발생한다.</p></li>
<li><p>통계적 이질성: 수집 된 효과크기 자료에서 발생하는 통계적 이질성을 의미한다. 이러한 이질성은 임상적 관점(예: 연구마다 효과가 크게 다르기 때문에 치료가 매우 또는 미미하게 효과가 있는지 알 수 없는 경우) 또는 통계적 관점 (이질성으로 인해 pooled 효과크기의 신뢰도에 대한 문제)에서 중요하게 작용한다.</p></li>
<li><p>기타 다른 이질성(예: 연구 디자인과 관련된 이질성)</p></li>
</ol>
<p>임상적 이질성과 기타 이질성은 개별 연구 검색 시 잘 정의된 중재 유형, 모집단 및 그 결과로 제한함으로써 어느 정도 통제할 수 있다.</p>
</div>
<div id="이질성-통계량---q-tau2-및-i2" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> 이질성 통계량 - <span class="math inline">\(Q\)</span>, <span class="math inline">\(\tau^2\)</span> 및 <span class="math inline">\(I^2\)</span></h3>
<p>각 연구로부터 도출된 결과, 즉 효과크기의 이질성의 정도를 나타내는 통계량(heterogeneity statistics)으로 활용되는 것으로 Cochran’s <span class="math inline">\(Q\)</span>, <span class="math inline">\(\tau^2\)</span>과 <span class="math inline">\(I^2\)</span> 세 가지가 있다. <span class="math inline">\(\tau^2\)</span>과 <span class="math inline">\(I^2\)</span>을 이해하고 계산하기 위해서는 먼저 효과크기의 동질성 검정(test of homogeneity)에 사용되는 <span class="math inline">\(Q\)</span>값과 <span class="math inline">\(df\)</span>를 이해해야 한다.</p>
<p><span class="math inline">\(Q\)</span>값은 메타분석에 있어서 각 효과크기들의 관찰된 분산(observed weighted sum of squares)을 의미하며, 이는 표본분산과 실제 연구 간 분산(true variance)을 모두 포함하는 총분산(total variance)을 의미하며, 다음과 같이 정의한다.</p>
<p><span class="math display">\[
Q=\sum_{i=1}^K w_ig_i^2 - \frac{(\sum_{i=1}^K w_ig_i)^2}{\sum_{i=1}^Kw_i}
\]</span></p>
<p><span class="math inline">\(Q\)</span> 통계량은 효과크기의 동질성(homogeneity)을 검정하는데 사용되지만, 귀무가설을 검정할 뿐이며, 그 분포자체는 <span class="math inline">\(\chi^2\)</span> 분포를 따르기 때문에 자유도(<span class="math inline">\(df\)</span>), 즉 메타분석에 포함된 연구 수(<span class="math inline">\(K\)</span>)에 많은 영향을 받게 된다.</p>
<p>한편, <span class="math inline">\(df\)</span>(자유도)는 각 연구의 모집단의 효과크기가 모두 동일하다고 가정할 때 기대하는 기대분산 값이다. 따라서 총분산-기대분산=실제분산 이므로 <span class="math inline">\(Q-df\)</span>는 실제 연구 간 효과 차이로 인한 분산의 정도를 의미한다. 하지만 이 값은 총분산에서 기대분산을 제외한 값으로 절대값을 나타내는 것은 아니다. 따라서 비교가능성을 위해 표준화한 형태인 <span class="math inline">\(\tau^2\)</span>을 정의한다. 일반적으로 <span class="math inline">\(\tau^2\)</span>이 0보다 크면 연구 간 이질성이 존재하게 되며 0(또는 &lt;0)인 경우에는 연구간 이질성이 없기때문에 고정효과모형과 랜덤효과모형의 결과가 동일하게 나타난다.</p>
<p>효과크기의 이질성을 나타내는 다른 지수로는 Higgin’s &amp; Thompson’s <span class="math inline">\(I^2\)</span>이 있으며 정의는 다음과 같다.</p>
<p><span class="math display">\[
I^2=max(0, \frac{Q-df}{Q}\times 100\%)
\]</span></p>
<p>이는 총분산에 대한 실제분산의 비율을 나타내며, <span class="math inline">\(\tau^2\)</span>과 달리 절대값이 아니라 비율(<span class="math inline">\(\%\)</span>)로 나타난다. 즉, 총분산 대비 실제 연구 간 분산의 비율을 표현한다. 일반적으로 <span class="math inline">\(I^2\)</span>이 <span class="math inline">\(25\%\)</span> 내외이면 이질성이 작은 것으로 해석하며, <span class="math inline">\(50\%\)</span>이면 중간 크기 정도로, 그리고 <span class="math inline">\(70\%\)</span> 이상이면 이질성이 매우 큰 것으로 해석하게 된다. 따라서 <span class="math inline">\(I^2&gt;50\%\)</span>이면 연구 간 이질성이 존재 할 가능성이 크다고 볼 수 있다.</p>
</div>
</div>
<div id="연속형-자료-예제" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> 연속형 자료 예제</h2>
<div id="example-6" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Example</h3>
<ul>
<li>Crucial laboratory parameters in COVID-19 diagnosis and prognosis: An updated meta-analysis (Soraya and Ulhaq, 2020)</li>
</ul>
<p><img src="ch3/heteroc.png" heigth="80%" style="width:80.0%" /></p>
<p>R 실습을 위해 “Crucial laboratory parameters in COVID-19 diagnosis and prognosis: An updated meta-analysis (Soraya and Ulhaq, 2020)” 논문에 명시된 자료를 이용하고 R-package <strong>meta</strong>를 사용한다.</p>
<p>우선 R-package <strong>meta</strong>를 install하고 R에서 사용가능하게 <strong>meta</strong> package를 loading 한다.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chapter3.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;meta&quot;)</span></span>
<span id="cb11-2"><a href="chapter3.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(meta)</span></code></pre></div>
<pre><code>## Loading &#39;meta&#39; package (version 4.18-1).
## Type &#39;help(meta)&#39; for a brief overview.</code></pre>
<div id="자료의-입력" class="section level4" number="3.3.1.1">
<h4><span class="header-section-number">3.3.1.1</span> 자료의 입력</h4>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chapter3.html#cb13-1" aria-hidden="true" tabindex="-1"></a>heteroc <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">&#39;</span></span>
<span id="cb13-2"><a href="chapter3.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="st">Study   m1  s1  n1  m2  s2  n2</span></span>
<span id="cb13-3"><a href="chapter3.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Cao et al(1)&quot;  4.48    2.22    19  4.7 1.55    174</span></span>
<span id="cb13-4"><a href="chapter3.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Cao et al(2)&quot;  11.85   5.35    21  6.57    4.98    107</span></span>
<span id="cb13-5"><a href="chapter3.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Gao et al&quot; 4.26    1.85    15  4.96    1.85    28</span></span>
<span id="cb13-6"><a href="chapter3.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Guan et al&quot;    3.7 2.37    173 4.9 1.62    926</span></span>
<span id="cb13-7"><a href="chapter3.html#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Huang et al&quot;   11.3    4.67    13  5.7 3.33    28</span></span>
<span id="cb13-8"><a href="chapter3.html#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Li et al&quot;  5.5 2.67    25  5.27    1.55    58</span></span>
<span id="cb13-9"><a href="chapter3.html#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Liu et al(1)&quot;  5.7 5.33    7   5.2 2.59    44</span></span>
<span id="cb13-10"><a href="chapter3.html#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Liu et al(2)&quot;  6.08    2.56    11  5.18    1.63    67</span></span>
<span id="cb13-11"><a href="chapter3.html#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Lo et al&quot;  5.57    1.99    4   4.51    1.18    6</span></span>
<span id="cb13-12"><a href="chapter3.html#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Mao et al&quot; 5.4 15.03   88  4.5 9.03    126</span></span>
<span id="cb13-13"><a href="chapter3.html#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Qian et al&quot;    5.23    1.52    9   4.97    1.2 82</span></span>
<span id="cb13-14"><a href="chapter3.html#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Qin et al&quot; 5.6 303 286 4.9 1.77    166</span></span>
<span id="cb13-15"><a href="chapter3.html#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Ruan et al&quot;    10.52   4.76    68  6.76    3.49    82</span></span>
<span id="cb13-16"><a href="chapter3.html#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Song et al&quot;    6.6 5.25    42  4.2 1.85    31</span></span>
<span id="cb13-17"><a href="chapter3.html#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Wang et al(1)&quot; 4.8 7.18    37  4.6 10.66   205</span></span>
<span id="cb13-18"><a href="chapter3.html#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Wang et al(2)&quot; 6.6 4.59    36  4.3 1.55    102</span></span>
<span id="cb13-19"><a href="chapter3.html#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Yang et al&quot;    0.62    0.37    32  0.74    0.4 20</span></span>
<span id="cb13-20"><a href="chapter3.html#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Young et al&quot;   3.4 2.37    6   4.6 3.41    12</span></span>
<span id="cb13-21"><a href="chapter3.html#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Yudong et al&quot;  5.53    3.34    16  5.78    2.76    96</span></span>
<span id="cb13-22"><a href="chapter3.html#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Zhang et al(1)&quot;    5.3 3.7 56  4.5 1.78    82</span></span>
<span id="cb13-23"><a href="chapter3.html#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Zhang et al(2)&quot;    6.2 3.92    55  4.1 2   166</span></span>
<span id="cb13-24"><a href="chapter3.html#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Zhang et al(3)&quot;    6.21    3.22    3   4.28    0.82    9</span></span>
<span id="cb13-25"><a href="chapter3.html#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Zhou et al&quot;    9.8 5.18    54  5.2 2.51    137</span></span>
<span id="cb13-26"><a href="chapter3.html#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Zhu et al&quot; 7.8 4.13    43  6.4 2.92    71</span></span>
<span id="cb13-27"><a href="chapter3.html#cb13-27" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span>, <span class="at">header=</span>T)</span>
<span id="cb13-28"><a href="chapter3.html#cb13-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-29"><a href="chapter3.html#cb13-29" aria-hidden="true" tabindex="-1"></a>heteroc</span></code></pre></div>
<pre><code>##             Study    m1     s1  n1   m2    s2  n2
## 1    Cao et al(1)  4.48   2.22  19 4.70  1.55 174
## 2    Cao et al(2) 11.85   5.35  21 6.57  4.98 107
## 3       Gao et al  4.26   1.85  15 4.96  1.85  28
## 4      Guan et al  3.70   2.37 173 4.90  1.62 926
## 5     Huang et al 11.30   4.67  13 5.70  3.33  28
## 6        Li et al  5.50   2.67  25 5.27  1.55  58
## 7    Liu et al(1)  5.70   5.33   7 5.20  2.59  44
## 8    Liu et al(2)  6.08   2.56  11 5.18  1.63  67
## 9        Lo et al  5.57   1.99   4 4.51  1.18   6
## 10      Mao et al  5.40  15.03  88 4.50  9.03 126
## 11     Qian et al  5.23   1.52   9 4.97  1.20  82
## 12      Qin et al  5.60 303.00 286 4.90  1.77 166
## 13     Ruan et al 10.52   4.76  68 6.76  3.49  82
## 14     Song et al  6.60   5.25  42 4.20  1.85  31
## 15  Wang et al(1)  4.80   7.18  37 4.60 10.66 205
## 16  Wang et al(2)  6.60   4.59  36 4.30  1.55 102
## 17     Yang et al  0.62   0.37  32 0.74  0.40  20
## 18    Young et al  3.40   2.37   6 4.60  3.41  12
## 19   Yudong et al  5.53   3.34  16 5.78  2.76  96
## 20 Zhang et al(1)  5.30   3.70  56 4.50  1.78  82
## 21 Zhang et al(2)  6.20   3.92  55 4.10  2.00 166
## 22 Zhang et al(3)  6.21   3.22   3 4.28  0.82   9
## 23     Zhou et al  9.80   5.18  54 5.20  2.51 137
## 24      Zhu et al  7.80   4.13  43 6.40  2.92  71</code></pre>
</div>
<div id="자료의-분석" class="section level4" number="3.3.1.2">
<h4><span class="header-section-number">3.3.1.2</span> 자료의 분석</h4>
<p>고정효과모형 또는 랜덤효과모형으로 평균효과차이를 구하기 위해서 <em>metacont</em> 함수를 이용한다. <em>metacont</em> 함수는 두 방법의 결과를 동시에 제공 가능하기 때문에 어떤 방법을 사용할지 고민할 필요가 없다. 여기서 효과크기는 standardized mean difference (SMD)로 설정하고 교정된 평균효과크기를 위해 “Hedges” 옵션을 사용한다. 이때 사용되는 자료 값은 각 집단의 표본크기(n1, n2), 평균(m1, m2), 표준편차(s1, s2) 등 이다.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chapter3.html#cb15-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">metacont</span>(n1, m1, s1, n2, m2, s2, <span class="at">data=</span>heteroc,</span>
<span id="cb15-2"><a href="chapter3.html#cb15-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">studlab=</span><span class="fu">paste</span>(Study),</span>
<span id="cb15-3"><a href="chapter3.html#cb15-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-4"><a href="chapter3.html#cb15-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.random =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-5"><a href="chapter3.html#cb15-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">prediction =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-6"><a href="chapter3.html#cb15-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sm=</span><span class="st">&quot;SMD&quot;</span>,</span>
<span id="cb15-7"><a href="chapter3.html#cb15-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method.smd=</span><span class="st">&quot;Hedges&quot;</span>) </span>
<span id="cb15-8"><a href="chapter3.html#cb15-8" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div>
<pre><code>##                    SMD             95%-CI %W(fixed) %W(random)
## Cao et al(1)   -0.1349 [-0.6086;  0.3389]       2.6        4.4
## Cao et al(2)    1.0413 [ 0.5559;  1.5267]       2.5        4.4
## Gao et al      -0.3714 [-1.0039;  0.2611]       1.5        4.0
## Guan et al     -0.6818 [-0.8466; -0.5170]      21.4        5.0
## Huang et al     1.4478 [ 0.7121;  2.1836]       1.1        3.7
## Li et al        0.1168 [-0.3524;  0.5861]       2.6        4.4
## Liu et al(1)    0.1609 [-0.6373;  0.9591]       0.9        3.5
## Liu et al(2)    0.5005 [-0.1422;  1.1432]       1.4        3.9
## Lo et al        0.6239 [-0.6891;  1.9368]       0.3        2.3
## Mao et al       0.0756 [-0.1968;  0.3480]       7.8        4.9
## Qian et al      0.2092 [-0.4797;  0.8982]       1.2        3.8
## Qin et al       0.0029 [-0.1883;  0.1941]      15.9        5.0
## Ruan et al      0.9094 [ 0.5714;  1.2473]       5.1        4.7
## Song et al      0.5699 [ 0.0961;  1.0436]       2.6        4.4
## Wang et al(1)   0.0195 [-0.3306;  0.3696]       4.7        4.7
## Wang et al(2)   0.8521 [ 0.4587;  1.2455]       3.8        4.6
## Yang et al     -0.3097 [-0.8718;  0.2524]       1.8        4.2
## Young et al    -0.3660 [-1.3553;  0.6233]       0.6        3.0
## Yudong et al   -0.0872 [-0.6166;  0.4421]       2.1        4.3
## Zhang et al(1)  0.2920 [-0.0496;  0.6336]       5.0        4.7
## Zhang et al(2)  0.8024 [ 0.4883;  1.1165]       5.9        4.8
## Zhang et al(3)  1.1024 [-0.3107;  2.5155]       0.3        2.1
## Zhou et al      1.3195 [ 0.9773;  1.6616]       5.0        4.7
## Zhu et al       0.4061 [ 0.0236;  0.7886]       4.0        4.6
## 
## Number of studies combined: k = 24
## 
##                         SMD            95%-CI    z p-value
## Fixed effect model   0.1401 [ 0.0638; 0.2163] 3.60  0.0003
## Random effects model 0.3371 [ 0.0720; 0.6023] 2.49  0.0127
## Prediction interval         [-0.9337; 1.6080]             
## 
## Quantifying heterogeneity:
##  tau^2 = 0.3572 [0.1447; 0.6542]; tau = 0.5977 [0.3804; 0.8088]
##  I^2 = 90.3% [86.8%; 92.8%]; H = 3.20 [2.75; 3.73]
## 
## Test of heterogeneity:
##       Q d.f.  p-value
##  236.06   23 &lt; 0.0001
## 
## Details on meta-analytical method:
## - Inverse variance method
## - DerSimonian-Laird estimator for tau^2
## - Jackson method for confidence interval of tau^2 and tau
## - Hedges&#39; g (bias corrected standardised mean difference)</code></pre>
<p>메타분석 결과는 다음과 같은 결과를 포함하고 있다.</p>
<ul>
<li><p>the individual effect sizes for each study, and their weight</p></li>
<li><p>The total number of included studies (k)</p></li>
<li><p>The overall effect (in our case, <span class="math inline">\(g=0.1401\)</span> for mixed model and <span class="math inline">\(g=0.3371\)</span> for random effect model) and its confidence interval and <span class="math inline">\(p-value\)</span></p></li>
<li><p>Measures of between-study heterogeneity, such as <span class="math inline">\(\tau^2\)</span> or <span class="math inline">\(I^2\)</span> and a <span class="math inline">\(Q\)</span>-test of heterogeneity</p>
<ul>
<li><span class="math inline">\(\tau^2=0.3572\)</span></li>
<li><span class="math inline">\(I^2=90.3\% (86.8\%, 92.8\%)\)</span></li>
<li><span class="math inline">\(Q=236.06\,\, (p-value=&lt;0.0001)\)</span></li>
</ul></li>
<li><p>고정효과모형 결과만 산출하고 싶으면 <strong>comb.random = FALSE</strong>로 두고 반대로 랜덤효과모형 결과만 산출하고 싶으면 <strong>comb.fixed = FALSE</strong>로 설정한다.</p></li>
<li><p>효과크기 설정시 평균차는 <strong>sm=“MD”</strong>, 표준화 평균차는 <strong>sm=“SMD”</strong>, 평균비(ratio of means)는 <strong>sm=“ROM”</strong>으로 설정한다.</p></li>
<li><p>표준화 평균차를 보정할때는 기본적으로 <strong>method.smd=“Hedges”</strong>로 설정되어 있고 Cohen’s d는 <strong>method.smd=“Cohen”</strong>, Glass’ delta 방법은 <strong>method.smd=“Glass”</strong>로 설정한다.</p></li>
</ul>
</div>
<div id="forest-plot-1" class="section level4" number="3.3.1.3">
<h4><span class="header-section-number">3.3.1.3</span> Forest plot</h4>
<p>메타분석 결과는 일반적으로 forest plot으로 제공하며 <strong>meta</strong> package에서는 <em>forest</em> 함수를 이용하여 forest plot을 쉽게 추출할 수 있다.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chapter3.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fit)</span></code></pre></div>
<p><img src="meta_files/figure-html/unnamed-chunk-9-1.png" width="1152" /></p>
<p>위의 결과는 논문(Soraya and Ulhaq, 2020)에 수록된 결과와 동일함을 알 수 있다.</p>
<p><img src="ch3/heteroc.png" /></p>
</div>
</div>
</div>
<div id="이산형-자료-예제" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> 이산형 자료 예제</h2>
<div id="example-7" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Example</h3>
<ul>
<li>Multifocal versus monofocal intraocular lenses for age-related cataract patients: a system review and meta-analysis based on randomized controlled trals (Cao et al., 2019) Figure 12.</li>
</ul>
<p><img src="ch3/heterob.png" /></p>
<div id="자료의-입력-1" class="section level4" number="3.4.1.1">
<h4><span class="header-section-number">3.4.1.1</span> 자료의 입력</h4>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter3.html#cb18-1" aria-hidden="true" tabindex="-1"></a>heterob <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">&#39;</span></span>
<span id="cb18-2"><a href="chapter3.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="st">study e1 n1 e2 n2</span></span>
<span id="cb18-3"><a href="chapter3.html#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="st">Kamlesh(2001)   9   20  6   20</span></span>
<span id="cb18-4"><a href="chapter3.html#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="st">Chen(2004)  9   104 5   104</span></span>
<span id="cb18-5"><a href="chapter3.html#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="st">Cillino(2008)   7   47  1   15</span></span>
<span id="cb18-6"><a href="chapter3.html#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="st">Harman(2008)    18  24  7   19</span></span>
<span id="cb18-7"><a href="chapter3.html#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="st">Maxwell(2007)   7   153 3   160</span></span>
<span id="cb18-8"><a href="chapter3.html#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span>, <span class="at">header=</span>T)</span>
<span id="cb18-9"><a href="chapter3.html#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="chapter3.html#cb18-10" aria-hidden="true" tabindex="-1"></a>heterob</span></code></pre></div>
<pre><code>##           study e1  n1 e2  n2
## 1 Kamlesh(2001)  9  20  6  20
## 2    Chen(2004)  9 104  5 104
## 3 Cillino(2008)  7  47  1  15
## 4  Harman(2008) 18  24  7  19
## 5 Maxwell(2007)  7 153  3 160</code></pre>
</div>
<div id="자료의-분석-1" class="section level4" number="3.4.1.2">
<h4><span class="header-section-number">3.4.1.2</span> 자료의 분석</h4>
<p>이산형 자료를 이용한 고정효과모형 또는 랜덤효과모형으로 통합효과크기를 구하기 위해서 <strong>metabin</strong> 함수를 이용한다. 여기서 효과크기는 RR로 선택하고 가중값 계산 방법은 MH방법으로 둔다. 이때 필요한 자료의 형태는 각집단의 표본크기 (n1, n2) 그리고 발생한 이벤트 수(e1, e2)이다.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter3.html#cb20-1" aria-hidden="true" tabindex="-1"></a>fit2<span class="ot">&lt;-</span> <span class="fu">metabin</span>(e1,n1,e2,n2,</span>
<span id="cb20-2"><a href="chapter3.html#cb20-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heterob,</span>
<span id="cb20-3"><a href="chapter3.html#cb20-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">studlab =</span> <span class="fu">paste</span>(study),</span>
<span id="cb20-4"><a href="chapter3.html#cb20-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-5"><a href="chapter3.html#cb20-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.random =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-6"><a href="chapter3.html#cb20-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">prediction =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-7"><a href="chapter3.html#cb20-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sm =</span> <span class="st">&quot;RR&quot;</span>,</span>
<span id="cb20-8"><a href="chapter3.html#cb20-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method=</span><span class="st">&quot;MH&quot;</span>)</span>
<span id="cb20-9"><a href="chapter3.html#cb20-9" aria-hidden="true" tabindex="-1"></a>fit2</span></code></pre></div>
<pre><code>##                   RR            95%-CI %W(fixed) %W(random)
## Kamlesh(2001) 1.5000 [0.6564;  3.4276]      25.8       25.8
## Chen(2004)    1.8000 [0.6243;  5.1897]      21.5       15.7
## Cillino(2008) 2.2340 [0.2984; 16.7245]       6.5        4.4
## Harman(2008)  2.0357 [1.0816;  3.8315]      33.6       44.1
## Maxwell(2007) 2.4401 [0.6426;  9.2651]      12.6        9.9
## 
## Number of studies combined: k = 5
## 
##                          RR           95%-CI    z p-value
## Fixed effect model   1.9108 [1.2374; 2.9506] 2.92  0.0035
## Random effects model 1.8862 [1.2391; 2.8711] 2.96  0.0031
## Prediction interval         [0.9535; 3.7313]             
## 
## Quantifying heterogeneity:
##  tau^2 = 0; tau = 0; I^2 = 0.0% [0.0%; 79.2%]; H = 1.00 [1.00; 2.19]
## 
## Test of heterogeneity:
##     Q d.f. p-value
##  0.53    4  0.9703
## 
## Details on meta-analytical method:
## - Mantel-Haenszel method
## - DerSimonian-Laird estimator for tau^2
## - Mantel-Haenszel estimator used in calculation of Q and tau^2 (like RevMan 5)</code></pre>
<p>메타분석 결과는 다음과 같은 결과를 포함하고 있다.</p>
<ul>
<li><p>the individual effect sizes for each study, and their weight</p></li>
<li><p>The total number of included studies (k)</p></li>
<li><p>The overall effect (in our case,,,, <span class="math inline">\(RR=1.91\)</span> for mixed model and ,,, <span class="math inline">\(RR=1.89\)</span> for random effect model) and its confidence interval and p-value</p></li>
<li><p>Measures of between-study heterogeneity, such as <span class="math inline">\(\tau^2\)</span> or <span class="math inline">\(I^2\)</span> and a <span class="math inline">\(Q\)</span>-test of heterogeneity</p>
<ul>
<li><span class="math inline">\(\tau^2=0\)</span></li>
<li><span class="math inline">\(I^2=0\%\)</span></li>
<li><span class="math inline">\(Q=0.53\,\, (p-value=0.9703)\)</span></li>
</ul></li>
<li><p>고정효과모형 결과만 산출하고 싶으면 <strong>comb.random = FALSE</strong>로 두고 반대로 랜덤효과모형 결과만 산출하고 싶으면 <strong>comb.fixed = FALSE</strong>로 설정한다.</p></li>
<li><p>효과크기 설정시 상대위험률(RR)는 <strong>sm=“RR”</strong>, 오즈비(OR)는 <strong>sm=“OR”</strong>, 비율차(RD)는 <strong>sm=“RD”</strong>, Arcsine difference는 <strong>sm=“ASD”</strong>, Diagnostic 오즈비는 <strong>sm=“DOR”</strong>로 설정한다.</p></li>
<li><p>가중값 산출을 위한 방법으로 method 옵션을 적용하며, <strong>method.smd=“Inverse”</strong>는 역분산법, MH는 <strong>method.smd=“MH”</strong>, Peto 방법은 <strong>method.smd=“Peto”</strong>로 설정한다. 이외에도 <strong>method.smd=“GLMM”</strong> 과 <strong>method.smd=“SSW”</strong> 방법을 설정 가능하다.</p></li>
</ul>
</div>
<div id="forest-plot-2" class="section level4" number="3.4.1.3">
<h4><span class="header-section-number">3.4.1.3</span> Forest plot</h4>
<p>메타분석 결과는 일반적으로 forest plot으로 제공하며 <em>meta</em> package에서는 <em>forest</em> 함수를 이용하여 forest plot을 쉽게 추출할 수 있다. 이때 <strong>layout</strong> 옵션을 통해 출력양식을 조절할 수 있다. Review Manager (RevMan) 형태로 출력을 원하면 <strong>layout=“RevMan5”</strong>로 JAMA 스타일을 원하면 <strong>layout=“JAMA”</strong> 옵션으로 조절한다.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chapter3.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fit2)</span></code></pre></div>
<p><img src="meta_files/figure-html/unnamed-chunk-12-1.png" width="1056" /></p>
<p>위의 결과는 논문(Cao et al., 2019)에 수록된 Figure 12와 동일함을 알 수 있다.</p>
<p><img src="ch3/f5.jpg" /></p>
<p>효과크기의 형태를 Odds ratio로 하고 싶으면 <strong>sm=“OR”</strong>로 설정하고, MH 방법이 아닌 역분산법을 이용하고 싶으면 <strong>method=“Inverse”</strong>로 설정한다.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter3.html#cb23-1" aria-hidden="true" tabindex="-1"></a>fitor<span class="ot">&lt;-</span> <span class="fu">metabin</span>(e1,n1,e2,n2,</span>
<span id="cb23-2"><a href="chapter3.html#cb23-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heterob,</span>
<span id="cb23-3"><a href="chapter3.html#cb23-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">studlab =</span> <span class="fu">paste</span>(study),</span>
<span id="cb23-4"><a href="chapter3.html#cb23-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-5"><a href="chapter3.html#cb23-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.random =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-6"><a href="chapter3.html#cb23-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">prediction =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-7"><a href="chapter3.html#cb23-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sm =</span> <span class="st">&quot;OR&quot;</span>,</span>
<span id="cb23-8"><a href="chapter3.html#cb23-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method=</span><span class="st">&quot;Inverse&quot;</span>)</span>
<span id="cb23-9"><a href="chapter3.html#cb23-9" aria-hidden="true" tabindex="-1"></a>fitor</span></code></pre></div>
<pre><code>##                   OR            95%-CI %W(fixed) %W(random)
## Kamlesh(2001) 1.9091 [0.5202;  7.0069]      21.9       21.9
## Chen(2004)    1.8758 [0.6066;  5.8003]      29.1       29.1
## Cillino(2008) 2.4500 [0.2764; 21.7146]       7.8        7.8
## Harman(2008)  5.1429 [1.3842; 19.1073]      21.5       21.5
## Maxwell(2007) 2.5091 [0.6369;  9.8857]      19.7       19.7
## 
## Number of studies combined: k = 5
## 
##                          OR           95%-CI    z p-value
## Fixed effect model   2.5294 [1.3761; 4.6492] 2.99  0.0028
## Random effects model 2.5294 [1.3761; 4.6492] 2.99  0.0028
## Prediction interval         [0.9414; 6.7963]             
## 
## Quantifying heterogeneity:
##  tau^2 = 0 [0.0000; 0.9771]; tau = 0 [0.0000; 0.9885]
##  I^2 = 0.0% [0.0%; 79.2%]; H = 1.00 [1.00; 2.19]
## 
## Test of heterogeneity:
##     Q d.f. p-value
##  1.57    4  0.8136
## 
## Details on meta-analytical method:
## - Inverse variance method
## - DerSimonian-Laird estimator for tau^2
## - Jackson method for confidence interval of tau^2 and tau</code></pre>
<p>Forest plot에서 <strong>layout</strong> 옵션을 통해 출력양식을 조절할 수 있다. Review Manager (RevMan) 형태로 출력을 원하면 <strong>layout=“RevMan5”</strong> 옵션으로 조절한다.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter3.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fitor, <span class="at">layout=</span><span class="st">&quot;RevMan5&quot;</span>)</span></code></pre></div>
<p><img src="meta_files/figure-html/unnamed-chunk-14-1.png" width="1056" /></p>
</div>
</div>
</div>
<div id="time-to-event-예제" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Time to event 예제</h2>
<div id="example-8" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Example</h3>
<ul>
<li>A meta-analysis of adjusted hazard ratios from 20 observational studies of bilateral versus single internal thoracic artery coronary artery bypass grafting (Takagi et al., 2014)</li>
</ul>
<p><img src="ch3/HR.png" /></p>
<div id="자료의-입력-2" class="section level4" number="3.5.1.1">
<h4><span class="header-section-number">3.5.1.1</span> 자료의 입력</h4>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chapter3.html#cb26-1" aria-hidden="true" tabindex="-1"></a>heteroh <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text=</span><span class="st">&#39;</span></span>
<span id="cb26-2"><a href="chapter3.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="st">study loghr se_loghr</span></span>
<span id="cb26-3"><a href="chapter3.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="st">APPROACH(2011)  -0.1424 0.1166</span></span>
<span id="cb26-4"><a href="chapter3.html#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="st">Bonacchi(2006)  -0.4055 0.6551</span></span>
<span id="cb26-5"><a href="chapter3.html#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="st">Buxton(1998)    -0.3415 0.1256</span></span>
<span id="cb26-6"><a href="chapter3.html#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="st">Carrier_p(2009) -0.0781 0.162</span></span>
<span id="cb26-7"><a href="chapter3.html#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="st">Carrier_n(2009) -0.4368 0.1197</span></span>
<span id="cb26-8"><a href="chapter3.html#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="st">DiMauro(2005)   -0.5306 0.2349</span></span>
<span id="cb26-9"><a href="chapter3.html#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="st">Endo(2001)  -0.0502 0.1787</span></span>
<span id="cb26-10"><a href="chapter3.html#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="st">Glineur(2012)   -0.298  0.1259</span></span>
<span id="cb26-11"><a href="chapter3.html#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="st">Grau(2012)  -0.3955 0.1126</span></span>
<span id="cb26-12"><a href="chapter3.html#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="st">Joo(2012)   -0.0125 0.2648</span></span>
<span id="cb26-13"><a href="chapter3.html#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="st">Kelly(2012) -0.2008 0.1004</span></span>
<span id="cb26-14"><a href="chapter3.html#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="st">Kinoshita(2012) -0.5906 0.2962</span></span>
<span id="cb26-15"><a href="chapter3.html#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="st">Kurlansky(2010) -0.1778 0.0426</span></span>
<span id="cb26-16"><a href="chapter3.html#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="st">Locker_only(2012)   -0.2247 0.1904</span></span>
<span id="cb26-17"><a href="chapter3.html#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="st">Locker_RA(2012) -0.1434 0.2412</span></span>
<span id="cb26-18"><a href="chapter3.html#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="st">Locker_SV(2012) -0.312  0.1276</span></span>
<span id="cb26-19"><a href="chapter3.html#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="st">Lytle(2004) -0.2739 0.0704</span></span>
<span id="cb26-20"><a href="chapter3.html#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="st">Navia(2013) -0.0194 0.343</span></span>
<span id="cb26-21"><a href="chapter3.html#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="st">Parsa(2013) -0.0547 0.067</span></span>
<span id="cb26-22"><a href="chapter3.html#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="st">Pick(1997)  -0.2002 0.2489</span></span>
<span id="cb26-23"><a href="chapter3.html#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="st">Puskas(2012)    -0.4309 0.1546</span></span>
<span id="cb26-24"><a href="chapter3.html#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="st">Stevens(2004)   -0.3081 0.1034</span></span>
<span id="cb26-25"><a href="chapter3.html#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="st">Toumpoulis(2006)    -0.12   0.1281</span></span>
<span id="cb26-26"><a href="chapter3.html#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span>, <span class="at">header=</span>T)</span>
<span id="cb26-27"><a href="chapter3.html#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="chapter3.html#cb26-28" aria-hidden="true" tabindex="-1"></a>heteroh</span></code></pre></div>
<pre><code>##                study   loghr se_loghr
## 1     APPROACH(2011) -0.1424   0.1166
## 2     Bonacchi(2006) -0.4055   0.6551
## 3       Buxton(1998) -0.3415   0.1256
## 4    Carrier_p(2009) -0.0781   0.1620
## 5    Carrier_n(2009) -0.4368   0.1197
## 6      DiMauro(2005) -0.5306   0.2349
## 7         Endo(2001) -0.0502   0.1787
## 8      Glineur(2012) -0.2980   0.1259
## 9         Grau(2012) -0.3955   0.1126
## 10         Joo(2012) -0.0125   0.2648
## 11       Kelly(2012) -0.2008   0.1004
## 12   Kinoshita(2012) -0.5906   0.2962
## 13   Kurlansky(2010) -0.1778   0.0426
## 14 Locker_only(2012) -0.2247   0.1904
## 15   Locker_RA(2012) -0.1434   0.2412
## 16   Locker_SV(2012) -0.3120   0.1276
## 17       Lytle(2004) -0.2739   0.0704
## 18       Navia(2013) -0.0194   0.3430
## 19       Parsa(2013) -0.0547   0.0670
## 20        Pick(1997) -0.2002   0.2489
## 21      Puskas(2012) -0.4309   0.1546
## 22     Stevens(2004) -0.3081   0.1034
## 23  Toumpoulis(2006) -0.1200   0.1281</code></pre>
</div>
<div id="자료의-분석-2" class="section level4" number="3.5.1.2">
<h4><span class="header-section-number">3.5.1.2</span> 자료의 분석</h4>
<p>본 연구에서는 Log(HR)과 SE(log(HR)) 값이 주어 졌을때, 메타분석을 위해 <em>metagen</em> 함수를 이용한다. <em>metagen</em> 함수는 effect size와 SE 값이 주어진 경우 메타분석을 시행하게 해준다. 따라서 Hazard ratio 뿐만 아니라 연속형자료와 비율형 자료 모두 사용 가능하다. 이때 효과크기 유형은 sm 옵션에서 조절하며, <strong>“RD,” “RR,” “OR,” “ASD,” “HR,” “MD,” “SMD,” “ROM”</strong> 등이 가능하다.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chapter3.html#cb28-1" aria-hidden="true" tabindex="-1"></a>fit3<span class="ot">&lt;-</span> <span class="fu">metagen</span>(loghr,se_loghr,</span>
<span id="cb28-2"><a href="chapter3.html#cb28-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heteroh,</span>
<span id="cb28-3"><a href="chapter3.html#cb28-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">studlab =</span> <span class="fu">paste</span>(study),</span>
<span id="cb28-4"><a href="chapter3.html#cb28-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-5"><a href="chapter3.html#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">comb.random =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-6"><a href="chapter3.html#cb28-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">prediction =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-7"><a href="chapter3.html#cb28-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">sm =</span> <span class="st">&quot;HR&quot;</span>)</span>
<span id="cb28-8"><a href="chapter3.html#cb28-8" aria-hidden="true" tabindex="-1"></a>fit3</span></code></pre></div>
<pre><code>##                       HR           95%-CI %W(fixed)
## APPROACH(2011)    0.8673 [0.6901; 1.0899]       3.9
## Bonacchi(2006)    0.6666 [0.1846; 2.4072]       0.1
## Buxton(1998)      0.7107 [0.5556; 0.9091]       3.4
## Carrier_p(2009)   0.9249 [0.6733; 1.2705]       2.0
## Carrier_n(2009)   0.6461 [0.5110; 0.8169]       3.7
## DiMauro(2005)     0.5883 [0.3712; 0.9322]       1.0
## Endo(2001)        0.9510 [0.6700; 1.3499]       1.7
## Glineur(2012)     0.7423 [0.5800; 0.9501]       3.4
## Grau(2012)        0.6733 [0.5400; 0.8396]       4.2
## Joo(2012)         0.9876 [0.5877; 1.6595]       0.8
## Kelly(2012)       0.8181 [0.6719; 0.9960]       5.3
## Kinoshita(2012)   0.5540 [0.3100; 0.9900]       0.6
## Kurlansky(2010)   0.8371 [0.7701; 0.9100]      29.5
## Locker_only(2012) 0.7988 [0.5500; 1.1601]       1.5
## Locker_RA(2012)   0.8664 [0.5400; 1.3901]       0.9
## Locker_SV(2012)   0.7320 [0.5700; 0.9400]       3.3
## Lytle(2004)       0.7604 [0.6624; 0.8729]      10.8
## Navia(2013)       0.9808 [0.5007; 1.9210]       0.5
## Parsa(2013)       0.9468 [0.8303; 1.0796]      11.9
## Pick(1997)        0.8186 [0.5026; 1.3333]       0.9
## Puskas(2012)      0.6499 [0.4800; 0.8800]       2.2
## Stevens(2004)     0.7348 [0.6000; 0.8999]       5.0
## Toumpoulis(2006)  0.8869 [0.6900; 1.1400]       3.3
## 
## Number of studies combined: k = 23
## 
##                         HR           95%-CI     z  p-value
## Fixed effect model  0.8048 [0.7691; 0.8421] -9.38 &lt; 0.0001
## Prediction interval        [0.7174; 0.8858]               
## 
## Quantifying heterogeneity:
##  tau^2 = 0.0018 [0.0000; 0.0166]; tau = 0.0429 [0.0000; 0.1289]
##  I^2 = 12.0% [0.0%; 45.9%]; H = 1.07 [1.00; 1.36]
## 
## Test of heterogeneity:
##      Q d.f. p-value
##  24.99   22  0.2974
## 
## Details on meta-analytical method:
## - Inverse variance method
## - DerSimonian-Laird estimator for tau^2
## - Jackson method for confidence interval of tau^2 and tau</code></pre>
<p>메타분석 결과는 다음과 같은 결과를 포함하고 있다.</p>
<ul>
<li>the individual effect sizes for each study, and their weight</li>
<li>The total number of included studies (k)</li>
<li>The overall effect (in our case,,,, <span class="math inline">\(HR=0.805\)</span> for mixed model) and its confidence interval and p-value</li>
<li>Measures of between-study heterogeneity, such as <span class="math inline">\(\tau^2\)</span> or <span class="math inline">\(I^2\)</span> and a <span class="math inline">\(Q\)</span>-test of heterogeneity
<ul>
<li><span class="math inline">\(\tau^2=0.0018\)</span></li>
<li><span class="math inline">\(I^2=12.0\% (0.0%, 45.9\%)\)</span></li>
<li><span class="math inline">\(Q=24.99\,\, (p-value=0.2974)\)</span></li>
</ul></li>
</ul>
</div>
<div id="forest-plot-3" class="section level4" number="3.5.1.3">
<h4><span class="header-section-number">3.5.1.3</span> Forest plot</h4>
<p>메타분석 결과는 일반적으로 forest plot으로 제공하며 <em>meta</em> package에서는 <em>forest</em> 함수를 이용하여 forest plot을 쉽게 추출할 수 있다.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chapter3.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fit3,<span class="at">layout =</span> <span class="st">&quot;RevMan5&quot;</span>)</span></code></pre></div>
<p><img src="meta_files/figure-html/unnamed-chunk-17-1.png" width="768" /></p>
<p>위의 결과는 논문(Takagi et al., 2014)에 수록된 Figure 1과 동일함을 알 수 있다.</p>
<p><img src="ch3/f6.jpg" /></p>
<p>Forest plot에서 layout 옵션을 “JAMA”로 두면 “<strong>Journal of the American Medical Association</strong> (JAMA)” 에서 추천하는 형태로 출력이 된다.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter3.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(fit3,<span class="at">layout =</span> <span class="st">&quot;JAMA&quot;</span>)</span></code></pre></div>
<p><img src="meta_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["meta.pdf", "meta.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
