<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; 다중선형회귀분석 – Regression Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-chapter4.html" rel="next">
<link href="./02-chapter2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-chapter3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">다중선형회귀분석</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="검색" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="검색"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">목 차</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">서론</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">단순선형회귀분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-chapter3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">다중선형회귀분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">회귀진단 및 보정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">모형비교와 변수선택</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">가변수 회귀모형</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">다중회귀분석 예제</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">일반화 가중회귀모형</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">벌점화 회귀모형</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">부록: 기초 행렬 이론</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#다중선형회귀모형---설명변수가-두-개인-경우" id="toc-다중선형회귀모형---설명변수가-두-개인-경우" class="nav-link active" data-scroll-target="#다중선형회귀모형---설명변수가-두-개인-경우"><span class="header-section-number">3.1</span> 다중선형회귀모형 - 설명변수가 두 개인 경우</a></li>
  <li><a href="#다중선형회귀모형---설명변수가-여러-개인-경우" id="toc-다중선형회귀모형---설명변수가-여러-개인-경우" class="nav-link" data-scroll-target="#다중선형회귀모형---설명변수가-여러-개인-경우"><span class="header-section-number">3.2</span> 다중선형회귀모형 - 설명변수가 여러 개인 경우</a></li>
  <li><a href="#모수-추정" id="toc-모수-추정" class="nav-link" data-scroll-target="#모수-추정"><span class="header-section-number">3.3</span> 모수 추정</a>
  <ul class="collapse">
  <li><a href="#최소제곱법을-이용한-모수추정" id="toc-최소제곱법을-이용한-모수추정" class="nav-link" data-scroll-target="#최소제곱법을-이용한-모수추정"><span class="header-section-number">3.3.1</span> 최소제곱법을 이용한 모수추정</a></li>
  <li><a href="#가능도함수를-이용한-모수-추정" id="toc-가능도함수를-이용한-모수-추정" class="nav-link" data-scroll-target="#가능도함수를-이용한-모수-추정"><span class="header-section-number">3.3.2</span> 가능도함수를 이용한 모수 추정</a></li>
  <li><a href="#추정량의-성질" id="toc-추정량의-성질" class="nav-link" data-scroll-target="#추정량의-성질"><span class="header-section-number">3.3.3</span> 추정량의 성질</a></li>
  </ul></li>
  <li><a href="#회귀모형-추정" id="toc-회귀모형-추정" class="nav-link" data-scroll-target="#회귀모형-추정"><span class="header-section-number">3.4</span> 회귀모형 추정</a>
  <ul class="collapse">
  <li><a href="#회귀계수에-대한-검정" id="toc-회귀계수에-대한-검정" class="nav-link" data-scroll-target="#회귀계수에-대한-검정"><span class="header-section-number">3.4.1</span> 회귀계수에 대한 검정</a></li>
  <li><a href="#회귀계수에-대한-신뢰구간" id="toc-회귀계수에-대한-신뢰구간" class="nav-link" data-scroll-target="#회귀계수에-대한-신뢰구간"><span class="header-section-number">3.4.2</span> 회귀계수에 대한 신뢰구간</a></li>
  </ul></li>
  <li><a href="#모형에-대한-적합도-검정" id="toc-모형에-대한-적합도-검정" class="nav-link" data-scroll-target="#모형에-대한-적합도-검정"><span class="header-section-number">3.5</span> 모형에 대한 적합도 검정</a>
  <ul class="collapse">
  <li><a href="#결정계수" id="toc-결정계수" class="nav-link" data-scroll-target="#결정계수"><span class="header-section-number">3.5.1</span> 결정계수</a></li>
  <li><a href="#회귀계수벡터에-대한-검정" id="toc-회귀계수벡터에-대한-검정" class="nav-link" data-scroll-target="#회귀계수벡터에-대한-검정"><span class="header-section-number">3.5.2</span> 회귀계수벡터에 대한 검정</a></li>
  </ul></li>
  <li><a href="#신뢰구간과-예측구간" id="toc-신뢰구간과-예측구간" class="nav-link" data-scroll-target="#신뢰구간과-예측구간"><span class="header-section-number">3.6</span> 신뢰구간과 예측구간</a>
  <ul class="collapse">
  <li><a href="#반응평균과-반응평균에-대한-신뢰구간" id="toc-반응평균과-반응평균에-대한-신뢰구간" class="nav-link" data-scroll-target="#반응평균과-반응평균에-대한-신뢰구간"><span class="header-section-number">3.6.1</span> 반응평균과 반응평균에 대한 신뢰구간</a></li>
  </ul></li>
  <li><a href="#잔차분석" id="toc-잔차분석" class="nav-link" data-scroll-target="#잔차분석"><span class="header-section-number">3.7</span> 잔차분석</a>
  <ul class="collapse">
  <li><a href="#회귀함수의-선형성" id="toc-회귀함수의-선형성" class="nav-link" data-scroll-target="#회귀함수의-선형성"><span class="header-section-number">3.7.1</span> 회귀함수의 선형성</a></li>
  <li><a href="#오차항의-등분산성과-독립성" id="toc-오차항의-등분산성과-독립성" class="nav-link" data-scroll-target="#오차항의-등분산성과-독립성"><span class="header-section-number">3.7.2</span> 오차항의 등분산성과 독립성</a></li>
  <li><a href="#오차항의-정규성" id="toc-오차항의-정규성" class="nav-link" data-scroll-target="#오차항의-정규성"><span class="header-section-number">3.7.3</span> 오차항의 정규성</a></li>
  </ul></li>
  <li><a href="#r을-이용한-다중회귀분석" id="toc-r을-이용한-다중회귀분석" class="nav-link" data-scroll-target="#r을-이용한-다중회귀분석"><span class="header-section-number">3.8</span> R을 이용한 다중회귀분석</a></li>
  <li><a href="#다항회귀모형" id="toc-다항회귀모형" class="nav-link" data-scroll-target="#다항회귀모형"><span class="header-section-number">3.9</span> 다항회귀모형</a></li>
  <li><a href="#표준화-회귀모형" id="toc-표준화-회귀모형" class="nav-link" data-scroll-target="#표준화-회귀모형"><span class="header-section-number">3.10</span> 표준화 회귀모형</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="chapter3" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">다중선형회귀분석</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>다중선형회귀분석(multiple regression analysis)은 하나의 반응변수를 여러 개의 설명변수로 설명하는 방법이다. 단순선형회귀분석에서는 하나의 설명변수와 반응변수 사이의 관계에 초점을 두지만, 실제 자료에서는 반응변수에 영향을 줄 수 있는 요인이 여러 개인 경우가 대부분이다. 따라서 다중회귀분석에서는 각 설명변수의 효과를 해석할 때 반드시 “다른 변수들이 동일하게 유지될 때”라는 조건을 함께 고려해야 한다.</p>
<p>다중회귀분석의 가장 중요한 특징은 <strong>보정(adjustment)</strong> 이다. 예를 들어 나이와 체중을 이용하여 혈압을 설명한다고 하자. 이때 체중의 회귀계수는 단순히 체중과 혈압의 관계를 의미하는 것이 아니라, 나이가 같은 사람들 사이에서 체중이 한 단위 증가할 때 혈압의 평균이 얼마나 달라지는지를 의미한다. 따라서 다중회귀분석의 회귀계수는 항상 다른 설명변수들이 모형에 함께 포함되어 있다는 점을 고려하여 해석해야 한다.</p>
<section id="다중선형회귀모형---설명변수가-두-개인-경우" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="다중선형회귀모형---설명변수가-두-개인-경우"><span class="header-section-number">3.1</span> 다중선형회귀모형 - 설명변수가 두 개인 경우</h2>
<ul>
<li><p>관측벡터 <span class="math inline">\((X_{11},X_{12},y_1), (X_{21},X_{22},y_2), \cdots, (X_{n1},X_{n2},y_n)\)</span>에 대해 다중선형회귀모형을 생각해 보자.</p></li>
<li><p><span class="math inline">\(X_1, X_2\)</span>는 고정된(fixed) 설명변수이고 <span class="math inline">\(Y\)</span>는 일변량 반응변수인 경우, 설명변수들과 반응변수 간의 선형회귀모형은</p></li>
</ul>
<p><span class="math display">\[
Y=\beta_0+\beta_1X_{1}+\beta_2X_{2}+\epsilon
\]</span></p>
<ul>
<li><p>여기서 회귀모수로 <span class="math inline">\(\beta_0\)</span>는 절편, <span class="math inline">\(\beta_1\)</span>은 <span class="math inline">\(X_1\)</span>과 관련된 회귀계수, <span class="math inline">\(\beta_2\)</span>는 <span class="math inline">\(X_2\)</span>와 관련된 회귀계수, 오차항 <span class="math inline">\(\epsilon \stackrel{iid}{\sim} N(0,\sigma^2)\)</span>을 가정</p></li>
<li><p><span class="math inline">\(n\)</span>개 관측점에 대해 표현하면</p></li>
</ul>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_{1i}+\beta_2X_{2i}+\epsilon_i, \,\,\, i=1,2,\cdots, n
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 여기서 <span class="math inline">\(Cov(\epsilon_i,\epsilon_j)=0, \,\,\, i\ne j\)</span></p>
<ul>
<li>선형회귀모형을 벡터와 행렬로 표현하면</li>
</ul>
<p><span class="math display">\[
\mathbf{Y}=\mathbf{X}\beta +\epsilon
\]</span></p>
<ul>
<li>여기서</li>
</ul>
<p><span class="math display">\[
\mathbf{Y}=\begin{pmatrix} Y_1\\Y_2\\\vdots\\Y_n \end{pmatrix}, \,\,\,
x_i=\begin{pmatrix} 1\\X_{i1}\\X_{i2} \end{pmatrix}, \,\,\,
\mathbf{X}=\begin{pmatrix}x_1'\\\vdots\\x_n' \end{pmatrix}=\begin{pmatrix}1 &amp; X_{11}&amp;X_{12}\\
\vdots &amp;\vdots &amp;\vdots \\ 1&amp;X_{n1}&amp;X_{n2} \end{pmatrix}, \,\,\,
\beta=\begin{pmatrix}\beta_0\\ \beta_1\\ \beta_2 \end{pmatrix}, \,\,\,
\epsilon=\begin{pmatrix} \epsilon_1\\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{pmatrix}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\mathbf{Y}\)</span>와 <span class="math inline">\(\epsilon\)</span>은 <span class="math inline">\(n\times 1\)</span> 벡터, <span class="math inline">\(x_i\)</span>와 <span class="math inline">\(\beta\)</span>는 <span class="math inline">\(3 \times 1\)</span> 벡터이고 <span class="math inline">\(\mathbf{X}\)</span>는 <span class="math inline">\(n\times 3\)</span> 행렬</p></li>
<li><p>회귀계수 추정량을 구하기 위해 오차제곱합을 최소화</p></li>
</ul>
<p><span class="math display">\[
S=\sum_{i=1}^n\epsilon_i^2 =\sum_{i=1}^n (Y_i-\beta_0-\beta_1X_{i1}-\beta_2X_{i2})^2
\]</span></p>
<ul>
<li>각 모수에 대해 편미분하여 <span class="math inline">\(0\)</span>으로 놓으면</li>
</ul>
<p><span class="math display">\[
\begin{align}
\frac{\partial S}{\partial\beta_0}&amp;=2\sum_{i=1}^n(Y_i-\beta_0-\beta_1X_{i1}-\beta_2X_{i2})(-1)=0 \\
\frac{\partial S}{\partial\beta_1}&amp;=2\sum_{i=1}^n(Y_i-\beta_0-\beta_1X_{i1}-\beta_2X_{i2})(-X_{i1})=0 \\
\frac{\partial S}{\partial\beta_2}&amp;=2\sum_{i=1}^n(Y_i-\beta_0-\beta_1X_{i1}-\beta_2X_{i2})(-X_{i2})=0
\end{align}
\]</span></p>
<ul>
<li>정규방정식</li>
</ul>
<p><span class="math display">\[
\begin{align}
n\beta_0+\beta_1\sum_{i=1}^nX_{i1}+\beta_2\sum_{i=1}^nX_{i2}&amp;=\sum_{i=1}^nY_i \\
\beta_0\sum_{i=1}^nX_{i1}+\beta_1\sum_{i=1}^nX_{i1}^2+\beta_2\sum_{i=1}^nX_{i1}X_{i2}&amp;=\sum_{i=1}^n X_{i1}Y_i\\
\beta_0\sum_{i=1}^nX_{i2}+\beta_1\sum_{i=1}^nX_{i1}X_{i2}+\beta_2\sum_{i=1}^nX_{i2}^2&amp;=\sum_{i=1}^n X_{i2}Y_i
\end{align}
\]</span></p>
<ul>
<li>설명변수 개수가 증가함에 따라 동시에 풀어야 할 연립방정식 개수도 증가하기때문에 행렬을 이용하여 간결하고 이해하기 쉽게 표현</li>
</ul>
<p><br></p>
</section>
<section id="다중선형회귀모형---설명변수가-여러-개인-경우" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="다중선형회귀모형---설명변수가-여러-개인-경우"><span class="header-section-number">3.2</span> 다중선형회귀모형 - 설명변수가 여러 개인 경우</h2>
<ul>
<li><p><span class="math inline">\(p\)</span>개 설명변수와 한 개의 반응변수를 포함한 관측벡터 <span class="math inline">\((X_{11},X_{12},\cdots, X_{1p},y_1), (X_{21},X_{22},\cdots, X_{2p},y_2), \cdots, (X_{n1},X_{n2},\cdots, X_{np},y_n)\)</span>에 대해 다중선형회귀모형을 생각해 보자.</p></li>
<li><p><span class="math inline">\(X_1, X_2,\cdots, X_p\)</span>는 <span class="math inline">\(p\)</span>개의 고정된(fixed) 설명변수이고 <span class="math inline">\(Y\)</span>는 일변량 반응변수인 경우, 설명변수들과 반응변수 간의 선형회귀모형은</p></li>
</ul>
<p><span class="math display">\[
Y=\beta_0+\beta_1X_{1}+\cdots +\beta_pX_{p}+\epsilon
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 여기서 회귀모수로 <span class="math inline">\(\beta_0\)</span>는 절편, <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j=1,2,\cdots, p\)</span>는 회귀계수, 오차항 <span class="math inline">\(\epsilon \stackrel{iid}{\sim} N(0,\sigma^2)\)</span>을 가정</p>
<section id="회귀계수의-해석" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="회귀계수의-해석">회귀계수의 해석</h4>
<ul>
<li><span class="math inline">\(X_j\)</span> 이외의 설명변수 값이 고정되었을 때, <span class="math inline">\(X_j\)</span>의 값이 한 단위 증가하면 반응변수 <span class="math inline">\(Y\)</span>는 평균적으로 <span class="math inline">\(\beta_j\)</span> 만큼 변함</li>
</ul>
<p>여기서 “다른 설명변수가 고정되었을 때”라는 표현이 매우 중요하다. 다중회귀분석의 회귀계수는 단순히 두 변수 사이의 관련성을 나타내는 값이 아니라, 모형에 포함된 다른 설명변수들의 영향을 통계적으로 보정한 후의 조건부 평균 변화량을 의미한다. 이를 <strong>부분회귀계수(partial regression coefficient)</strong> 라고도 한다.</p>
<p>예를 들어 다음과 같은 모형을 생각해 보자.</p>
<p><span class="math display">\[
\text{Blood pressure}=\beta_0+\beta_1\text{Age}+\beta_2\text{BMI}+\epsilon
\]</span></p>
<p>이 모형에서 <span class="math inline">\(\beta_2\)</span>는 BMI가 한 단위 증가할 때 혈압이 평균적으로 얼마나 달라지는지를 의미한다. 단, 이 해석은 나이가 동일한 사람들끼리 비교한다는 조건을 포함한다. 따라서 다중회귀분석에서는 회귀계수를 해석할 때 항상 “무엇을 보정한 효과인가?”를 함께 생각해야 한다.</p>
<ul>
<li><span class="math inline">\(n\)</span>개 관측점에 대해 표현하면</li>
</ul>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_{1i}+\cdots+\beta_pX_{pi}+\epsilon_i, \,\,\, i=1,2,\cdots, n
\]</span></p>
<ul>
<li>일반적으로 오차항 <span class="math inline">\(\epsilon_i\)</span>에 대한 가정으로부터</li>
</ul>
<ol type="1">
<li><p><span class="math inline">\(E(\epsilon_i)=0, \,\,\, i=1,2,,\cdots, n\)</span></p></li>
<li><p><span class="math inline">\(Var(\epsilon_i)=\sigma^2, \,\,\, i=1,2,,\cdots, n\)</span></p></li>
<li><p><span class="math inline">\(Cov(\epsilon_i, \epsilon_j)=0, \,\,\, i\ne j\)</span></p></li>
</ol>
<ul>
<li><p>즉, 오차항은 서로 독립이며 평균 <span class="math inline">\(0\)</span>, 분산 <span class="math inline">\(\sigma^2\)</span>인 정규분포 <span class="math inline">\(N(0,\sigma^2)\)</span>을 따른다고 가정함</p></li>
<li><p>오차항 <span class="math inline">\(\epsilon\)</span>이 정규분포를 따르면 <span class="math inline">\(Y\)</span>도 정규분포를 따르게 됨</p></li>
<li><p>따라서, 주어진 <span class="math inline">\(X\)</span>에 대해서 <span class="math inline">\(Y\)</span>의 기대값과 분산은 다음과 같음</p></li>
</ul>
<ol type="1">
<li><p><span class="math inline">\(E(Y_i)=\beta_0+\beta_1X_{1i}+\cdots+\beta_pX_{pi}, \,\,\, i=1,2,,\cdots, n\)</span></p></li>
<li><p><span class="math inline">\(Var(Y_i)=\sigma^2, \,\,\, i=1,2,,\cdots, n\)</span></p></li>
<li><p><span class="math inline">\(Cov(Y_i, Y_j)=0, \,\,\, i\ne j\)</span></p></li>
</ol>
<ul>
<li>모형을 행렬과 벡터로 표현하면</li>
</ul>
<p><span class="math display">\[
\begin{pmatrix} Y_1\\Y_2\\\vdots\\Y_n \end{pmatrix}=\begin{pmatrix}1 &amp; X_{11}&amp;X_{12}&amp;\cdots&amp;X_{1p}\\
1 &amp;X_{21}&amp;X_{22}&amp;\cdots &amp;X_{2p}\\
&amp;\vdots &amp; &amp;\vdots &amp;\\ 1&amp;X_{n1}&amp;X_{n2}&amp;\cdots&amp;X_{np} \end{pmatrix} \begin{pmatrix}\beta_0\\ \beta_1\\ \vdots \\ \beta_p \end{pmatrix}+\begin{pmatrix} \epsilon_1\\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{pmatrix}
\]</span></p>
<ul>
<li>또한</li>
</ul>
<p><span class="math display">\[
\mathbf{Y}=\mathbf{X}\beta+\epsilon
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 여기서 <span class="math inline">\(\mathbf{Y}\)</span>와 <span class="math inline">\(\epsilon\)</span>은 <span class="math inline">\(n\times 1\)</span> 벡터, <span class="math inline">\(\mathbf{X}\)</span>는 <span class="math inline">\(n\times (p+1)\)</span> 행렬이고 <span class="math inline">\(\beta\)</span>는 <span class="math inline">\((p+1) \times 1\)</span> 벡터임</p>
<ul>
<li>회귀분석과정으로 반응관측값 <span class="math inline">\(\mathbf{Y}\)</span>를 설명변수 <span class="math inline">\(X_1\)</span>과 <span class="math inline">\(X_2\)</span>가 만드는 공간으로 투영시켜 반응추정값을 구하는 기하학적 표현</li>
</ul>
<center>
<img src="fig3/f1.png" class="img-fluid" style="width:80.0%">
</center>
<ul>
<li>선형최소제곱법을 이용한 회귀직선 적합</li>
</ul>
<center>
<img src="fig3/f2.png" class="img-fluid" style="width:80.0%">
</center>
<p><br></p>
</section>
</section>
<section id="모수-추정" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="모수-추정"><span class="header-section-number">3.3</span> 모수 추정</h2>
<p>다중회귀모형의 모수 추정은 단순선형회귀분석과 같은 최소제곱법의 원리를 따른다. 차이는 설명변수가 여러 개이므로 회귀계수도 여러 개가 되고, 이를 효율적으로 표현하기 위해 벡터와 행렬을 사용한다는 점이다. 행렬 표기법을 사용하면 회귀계수 추정량을 다음과 같이 간단하게 쓸 수 있다.</p>
<p><span class="math display">\[
\hat{\beta}=(\mathbf{X}'\mathbf{X})^{-1}\mathbf{X}'\mathbf{Y}
\]</span></p>
<section id="최소제곱법을-이용한-모수추정" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="최소제곱법을-이용한-모수추정"><span class="header-section-number">3.3.1</span> 최소제곱법을 이용한 모수추정</h3>
<ul>
<li><p>오차제곱합을 최소화하는 최소제곱법을 이용하여 회귀계수 추정량을 구하는 방법은 표본자료로부터 회귀계수를 추정하는 방법 중 가장 널리 이용되는 방법</p></li>
<li><p>회귀계수 <span class="math inline">\(\beta\)</span>의 추정값 <span class="math inline">\(\hat{\beta}\)</span>을 구하기 위한 오차제곱합</p></li>
</ul>
<p><span class="math display">\[ \begin{align}
S(\beta)&amp;=\sum_{i=1}^n\epsilon_i^2\\
&amp;=\sum_{i=1}^n(Y_i-\beta_0-\beta_1X_{i1}-\cdots - \beta_pX_{ip})^2\\
&amp;=(\mathbf{Y}-\mathbf{X}\beta)'(\mathbf{Y}-\mathbf{X}\beta)
\end{align}
\]</span></p>
<ul>
<li>다중선형회귀모형에서 <span class="math inline">\(\mathbf{X}\)</span>가 완전계수(full rank) <span class="math inline">\(p+1\le n\)</span>일 때, 회귀계수 <span class="math inline">\(\beta\)</span>의 최소제곱추정량(least squares estimator)은</li>
</ul>
<p><span class="math display">\[
\hat{\beta}=\mathbf{(X'X)^{-1}X'Y}
\]</span></p>
<ul>
<li>Proof</li>
</ul>
<p><span class="math display">\[
S(\beta)=\mathbf(Y'Y - Y'X\beta - \beta'X'Y+\beta'X'X\beta)
\]</span></p>
<p><span class="math display">\[
\frac{\partial S}{\partial \beta}= -2\mathbf{X'Y}+2\mathbf{X'X\beta}=0
\]</span></p>
<ul>
<li>Proof hint:</li>
</ul>
<ol type="1">
<li><span class="math inline">\(x, y\)</span>가 <span class="math inline">\(n\)</span>차원 벡터일 때</li>
</ol>
<p><span class="math display">\[
\frac{\partial}{\partial x}(x'y)=\frac{\partial}{\partial x}(y'x)=y
\]</span></p>
<ol start="2" type="1">
<li><span class="math inline">\(x\)</span>가 <span class="math inline">\(n\)</span>차원 벡터이고 <span class="math inline">\(\mathbf{A}\)</span>가 <span class="math inline">\(n\times n\)</span> 행렬일 때때</li>
</ol>
<p><span class="math display">\[
\frac{\partial}{\partial x}(x' \mathbf{A})=\mathbf{A}, \,\,\, \frac{\partial}{\partial x}(\mathbf{A}x)=\mathbf{A'}
\]</span></p>
<ol start="3" type="1">
<li><span class="math inline">\(n\)</span>차원 벡터 <span class="math inline">\(x\)</span>의 이차형식에 대한 미분은</li>
</ol>
<p><span class="math display">\[
\frac{\partial}{\partial x}(x' \mathbf{A}x)=\mathbf{A}x + \mathbf{A'}x = 2\mathbf{A}x, \,\,\, \mathbf{A}: symmetric
\]</span></p>
<ul>
<li><span class="math inline">\(\mathbf{H=X(X'X)^{-1}X'}\)</span> (hat matrix)라고 하면</li>
</ul>
<p><span class="math display">\[ \begin{align}
&amp;\mathbf{\hat{Y}=X\hat{\beta}=HY}\\
&amp;e=\mathbf{Y-\hat{Y}=[I-X(X'X)^{-1}X']Y=(I-H)Y}
\end{align}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\mathbf{X'}e=0\)</span>과 <span class="math inline">\(\mathbf{\hat{Y}'}e=0\)</span>를 만족함</p></li>
<li><p>잔차제곱합</p></li>
</ul>
<p><span class="math display">\[ \begin{align}
S(\beta)&amp;=\sum_{i=1}^n(Y_i-\hat{\beta}_0-\hat{\beta}_1X_{i1}-\cdots - \hat{\beta}_pX_{ip})^2\\
&amp;=e'e\\
&amp;=\mathbf{Y'[I-X(X'X)^{-1}X']Y}\\
&amp;=\mathbf{Y'Y-Y'X\hat{\beta}}
\end{align}
\]</span></p>
<ul>
<li>단순회귀모형에 대해 다변량 추정량을 이용해 회귀계수벡터를 구해보자. 단순선형회귀모형 <span class="math inline">\(\mathbf{Y=X\beta+\epsilon}\)</span></li>
</ul>
<p><span class="math display">\[
\begin{pmatrix} Y_1\\Y_2\\\vdots\\Y_n \end{pmatrix}=\begin{pmatrix}1 &amp; X_{11}\\
1 &amp;X_{21}\\
\vdots &amp;\vdots\\
1&amp; X_{n1}\end{pmatrix} \begin{pmatrix}\beta_0\\ \beta_1 \end{pmatrix}+\begin{pmatrix} \epsilon_1\\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{pmatrix}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 여기서 <span class="math inline">\(\mathbf{Y}\)</span>와 <span class="math inline">\(\epsilon\)</span>은 <span class="math inline">\(n\times 1\)</span> 벡터, <span class="math inline">\(\mathbf{X}\)</span>는 <span class="math inline">\(n\times 2\)</span> 행렬이고 <span class="math inline">\(\beta\)</span>는 <span class="math inline">\(2 \times 1\)</span> 벡터임</p>
<p><span class="math display">\[
\mathbf{(X'X)}=\begin{pmatrix}
n&amp;\sum_{i=1}^nX_i\\
\sum_{i=1}^nX_i &amp; \sum_{i=1}^nX_i^2
\end{pmatrix}, \,\,\,
\mathbf{X'Y}=\begin{pmatrix}
\sum_{i=1}^nY_i\\
\sum_{i=1}^nX_iY_i
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[ \begin{align}
\mathbf(X'X)^{-1}&amp;=\frac{1}{n\sum_{i=1}^nX_i^2-(\sum_{i=1}^nX_i)^2}\begin{pmatrix}\sum_{i=1}^nX_i^2 &amp; -\sum_{i=1}^nX_i\\
-\sum_{i=1}^nX_i &amp; n
\end{pmatrix}\\
&amp;=\frac{1}{\sum_{i=1}^n(X_i-\bar{X})^2}\begin{pmatrix}\frac{1}{n}\sum_{i=1}^nX_i^2 &amp; -\bar{X}\\
-\bar{X} &amp; 1
\end{pmatrix}
\end{align}
\]</span></p>
<ul>
<li>따라서</li>
</ul>
<p><span class="math display">\[\begin{align}
\hat{\beta}=
\begin{pmatrix}
\hat{\beta}_0 \\
\hat{\beta}_1
\end{pmatrix}=\mathbf{(X'X)^{-1}X'Y}&amp;=\frac{1}{\sum_{i=1}^n(X_i-\bar{X})^2}\begin{pmatrix}\frac{1}{n}\sum_{i=1}^nX_i^2 &amp; -\bar{X}\\
-\bar{X} &amp; 1
\end{pmatrix}\begin{pmatrix} \sum_{i=1}^nY_i\\ \sum_{i=1}^nX_iY_i \end{pmatrix}\\
&amp;= \begin{pmatrix} \bar{Y}-\hat{\beta}_1\bar{X}\\
\frac{\sum_{i=1}^nX_iY_i-n\bar{X}\bar{Y}}{\sum_{i=1}^n(X_i-\bar{X})^2}\end{pmatrix}
\end{align}
\]</span></p>
</section>
<section id="가능도함수를-이용한-모수-추정" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="가능도함수를-이용한-모수-추정"><span class="header-section-number">3.3.2</span> 가능도함수를 이용한 모수 추정</h3>
<ul>
<li>오차항이 정규분포를 따른다는 가정하에 관측값에 대한 가능도함수를 벡터와 행렬을 이용하여 표현하면</li>
</ul>
<p><span class="math display">\[
P(\mathbf{Y}|\beta, \sigma^2, \mathbf{X})=(2\pi\sigma^2)^{-n/2}exp(-\frac{\mathbf{(Y-X\beta)'(Y-X\beta)}}{2\sigma^2})
\]</span></p>
<ul>
<li>가능도함수를 log 변환을 하면 모수 <span class="math inline">\(\beta\)</span>에 영향을 받는 부분은 <span class="math inline">\(-\mathbf{(Y-X\beta)'(Y-X\beta)}\)</span> 부분만 남게 됨
<ul>
<li>최대가능도 추정량은 가능도 함수를 최대화 하는 모수 값을 찾기 때문에 결국 -부호를 제거하면 <span class="math inline">\(\mathbf{(Y-X\beta)'(Y-X\beta)}\)</span>를 최소화 하는 모수 추정량을 찾는 문제가 같아짐</li>
<li>따라서 최대가능도 추정량은 최소제곱 추정량과 같음</li>
</ul></li>
</ul>
<p><span class="math display">\[
\hat{\beta}=\mathbf{(X'X)^{-1}X'Y}
\]</span></p>
<ul>
<li>로그 가능도함수를 <span class="math inline">\(\sigma^2\)</span>에 대해 미분하여 얻은 최대가능도 추정량은</li>
</ul>
<p><span class="math display">\[
\begin{align}
\hat{\sigma}_{ML}^2=\frac{\mathbf{(Y-X\hat{\beta})'(Y-X\hat{\beta})}}{n}
\end{align}
\]</span></p>
</section>
<section id="추정량의-성질" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="추정량의-성질"><span class="header-section-number">3.3.3</span> 추정량의 성질</h3>
<ul>
<li>회귀계수의 최소제곱 추정량은 불편성과 최소분산성을 만족하는 우수한 추정량</li>
</ul>
<section id="가우스-마코프-정리" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="가우스-마코프-정리">가우스-마코프 정리</h4>
<ul>
<li>다중선형회귀모형의 오차벡터에 대해 <span class="math inline">\(E(\epsilon)=0\)</span>이고 오차항이 서로 독립이고 등분산인 경우 회귀계수에 대한 최적선형불편추정량(best linear unbiased estimator: BLUE)은 최소제곱추정량임</li>
</ul>
</section>
<section id="증명" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="증명">증명</h4>
<ul>
<li>모수들의 선형조합 <span class="math inline">\(\psi=c'\beta\)</span>는 다음과 같은 선형조합이 존재할 경우에만 추정가능함(estimable):</li>
</ul>
<p><span class="math display">\[
E(a'y)=c'\beta \,\,\, \forall\beta
\]</span></p>
<ul>
<li><p>만약 <span class="math inline">\(\mathbf{X}\)</span>가 완전 행렬계수(full rank)라면 모든 선형조합은 추정가능함</p></li>
<li><p>가우스-마코프 정리는 불편성을 지닌 선형조합들 중 최소제곱 추정량이 최소분산(minimum variance)을 가지고 유일하다고(unique) 설명함</p></li>
<li><p><span class="math inline">\(a'y\)</span>는 <span class="math inline">\(c'\beta\)</span>의 불편추정량이라고 가정하면 모든 <span class="math inline">\(\beta\)</span>에 대해 <span class="math inline">\(E(a'y)=c'\beta\)</span> 이므로</p></li>
</ul>
<p><span class="math display">\[
a'\mathbf{X}\beta=c'\beta
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 가 되므로 <span class="math inline">\(a'\mathbf{X}=c'\)</span>.</p>
<ul>
<li>벡터 <span class="math inline">\(c\)</span>는 <span class="math inline">\(\mathbf{X'}\)</span>의 공간에 있어야함. 즉, <span class="math inline">\(\mathbf{X'X}\)</span>의 공간에 있어야 하므로 <span class="math inline">\(c=\mathbf{X'X}\lambda\)</span>를 만족하는 <span class="math inline">\(\lambda\)</span>가 존재해야 함. 따라서</li>
</ul>
<p><span class="math display">\[
c'\hat{\beta}=\lambda'\mathbf{X'X}\hat{\beta}=\lambda'\mathbf{X}'y
\]</span></p>
<ul>
<li>추정량 <span class="math inline">\(a'y\)</span>의 분산을 구해 보면</li>
</ul>
<p><span class="math display">\[
\begin{align}
Var(a'y)&amp;=Var(a'y-c'\hat{\beta}+c'\hat{\beta})\\
&amp;=Var(a'y-\lambda'\mathbf{X}'y+c'\hat{\beta})\\
&amp;=Var(a'y-\lambda'\mathbf{X}'y)+Var(c'\hat{\beta})+2cov(a'y-\lambda'\mathbf{X}'y,\lambda'\mathbf{X}'y)
\end{align}
\]</span></p>
<ul>
<li>여기서</li>
</ul>
<p><span class="math display">\[
\begin{align}
cov(a'y-\lambda'\mathbf{X}'y,\lambda'\mathbf{X}'y)&amp;=(a'-\lambda'\mathbf{X}')\sigma^2\mathbf{IX}\lambda\\
&amp;=(a'\mathbf{X}-\lambda'\mathbf{X'X})\sigma^2\mathbf{I}\lambda\\
&amp;=(c'-c')\sigma^2\mathbf{I}\lambda\\
&amp;=0
\end{align}
\]</span></p>
<ul>
<li>따라서</li>
</ul>
<p><span class="math display">\[
Var(a'y)=Var(a'y-\lambda'\mathbf{X}'y)+Var(c'\hat{\beta})\ge Var(c'\hat{\beta})
\]</span></p>
<ul>
<li><p>즉, <span class="math inline">\(c'\hat{\beta}\)</span>는 최소분산을 가짐</p></li>
<li><p><span class="math inline">\(c'\hat{\beta}\)</span>의 유일성</p>
<ul>
<li>위 분산 텀에서 <span class="math inline">\(Var(c'\hat{\beta})\)</span>와 같아지려면</li>
</ul></li>
</ul>
<p><span class="math display">\[
Var(a'y-\lambda'\mathbf{X}'y)=0
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; 이어야 하므로 <span class="math inline">\((a'-\lambda'\mathbf{X})=0\)</span>이 되고 <span class="math inline">\(a'y=\lambda'\mathbf{X}'y=c'\hat{\beta}\)</span>가 됨</p>
<ul>
<li>따라서 등호는 <span class="math inline">\(a'y=c'\hat{\beta}\)</span>인 경우에만 성립하므로 등호가 성립되는 경우의 유일한 추정량이 됨</li>
</ul>
</section>
<section id="회귀계수-최소제곱추정량-hatbetamathbfxx-1xy-특성" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="회귀계수-최소제곱추정량-hatbetamathbfxx-1xy-특성">회귀계수 최소제곱추정량 <span class="math inline">\(\hat{\beta}=\mathbf{(X'X)^{-1}X'Y}\)</span> 특성</h4>
<ul>
<li>회귀계수의 불편성</li>
</ul>
<p><span class="math display">\[
E(\hat{\beta})=E[\mathbf{(X'X)^{-1}X'Y}]=\mathbf{(X'X)^{-1}X'}E(\mathbf{Y})=\mathbf{(X'X)^{-1}X'X\beta}=\beta
\]</span></p>
<ul>
<li>회귀계수의 공분산 행렬</li>
</ul>
<p><span class="math display">\[
cov(\hat{\beta})=cov(\mathbf{(X'X)^{-1}X'Y})=\mathbf{(X'X)^{-1}X'}cov(\mathbf{Y})\mathbf{X(X'X)^{-1}}= \sigma^2(\mathbf{X'X})^{-1}
\]</span></p>
<ul>
<li>잔차벡터 <span class="math inline">\(e=\{e_1,\cdots, e_n\}'\)</span>에 대해</li>
</ul>
<p><span class="math display">\[
E(e)=0, \,\,\, Cov(e)=\sigma^2(\mathbf{I-H})
\]</span></p>
<ul>
<li>분산추정량</li>
</ul>
<p><span class="math display">\[
S^2=\frac{e'e}{n-(p+1)}=\frac{\mathbf{Y'[I-X(X'X)^{-1}X']Y}}{n-p-1}=\frac{\mathbf{Y'[I-H]Y}}{n-p-1}
\]</span></p>
<ul>
<li><span class="math inline">\(E(S^2)=\sigma^2\)</span>을 만족하므로 <span class="math inline">\(S^2\)</span>은 <span class="math inline">\(\sigma^2\)</span>의 불편추정량</li>
</ul>
<p><br></p>
</section>
</section>
</section>
<section id="회귀모형-추정" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="회귀모형-추정"><span class="header-section-number">3.4</span> 회귀모형 추정</h2>
<section id="회귀계수에-대한-검정" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="회귀계수에-대한-검정"><span class="header-section-number">3.4.1</span> 회귀계수에 대한 검정</h3>
<ul>
<li><p>회귀모형에 대한 유의성은 각 회귀계수에 대한 유의성 문제와 관련이 있음</p></li>
<li><p>가설</p></li>
</ul>
<p><span class="math display">\[
H_{0j}:\beta_j=0 \,\,\, vs. H_{1j}:\beta_j\ne 0, \,\,\, j=1,2,\cdots,p
\]</span></p>
<ul>
<li>검정통계량</li>
</ul>
<p><span class="math display">\[
t_j=\frac{\hat{\beta}_j}{\hat{Var}(\hat{\beta})}=\frac{\hat{\beta}_j}{s\sqrt{q_{jj}}} \sim t_{n-p-1}
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(q_{jj}\)</span>는 <span class="math inline">\((\mathbf{X'X)^{-1}}\)</span>의 <span class="math inline">\(j\)</span>번째 대각선상 <span class="math inline">\(j=1,2,\ldots, p\)</span>에 놓은 값임</p></li>
<li><p>유의수준 <span class="math inline">\(\alpha\)</span> 검정</p></li>
</ul>
<p><span class="math display">\[
|t_j|\ge t_{n-p-1}(\alpha/2) \,\,\, \text{then reject} \,\,\, H_0
\]</span></p>
<ul>
<li><span class="math inline">\(H_0\)</span>를 기각하는 경우 <span class="math inline">\(\beta_j=0\)</span>이라고 할 수 없으므로 추정된 회귀계수가 회귀모형에 기여함을 알 수 있음</li>
</ul>
</section>
<section id="회귀계수에-대한-신뢰구간" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="회귀계수에-대한-신뢰구간"><span class="header-section-number">3.4.2</span> 회귀계수에 대한 신뢰구간</h3>
<ul>
<li><p>각 회귀계수에 대한 신뢰구간은 <span class="math inline">\(t\)</span>-분포를 이용하여 구함</p></li>
<li><p><span class="math inline">\(\beta_j\)</span>에 대한 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간은</p></li>
</ul>
<p><span class="math display">\[
\hat{\beta}_j\pm t_{n-p-1}(\alpha/2)\sqrt{\hat{Var}(\hat{\beta}_j)}
\]</span></p>
<section id="hatbeta의-분포" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="hatbeta의-분포"><span class="math inline">\(\hat{\beta}\)</span>의 분포</h4>
<ul>
<li><span class="math inline">\(\mathbf{Y=X\beta+\epsilon}\)</span>, <span class="math inline">\(rank(\mathbf{X})=p+1\)</span>이고, <span class="math inline">\(\epsilon\sim N_n(0, \sigma^2I)\)</span>일 때 회귀계수벡터 <span class="math inline">\(\beta\)</span>의 최대우도추정량과 최소제곱추정량은 일치함</li>
</ul>
<p><span class="math display">\[
\hat{\beta}=\mathbf{(X'X)^{-1}X'Y}\sim N_{p+1}(\beta,\sigma^2(\mathbf{X'X})^{-1})
\]</span></p>
<ul>
<li>잔차에 대해서는 <span class="math inline">\(e=\mathbf{Y-X\beta}\)</span>일 때,</li>
</ul>
<p><span class="math display">\[
n\hat{\sigma}^2=e'e \sim \sigma^2 \chi_{n-p-1}^2
\]</span></p>
</section>
<section id="동시신뢰영역" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="동시신뢰영역">동시신뢰영역</h4>
<ul>
<li><span class="math inline">\(\mathbf{Y=X\beta+\epsilon}\)</span>, <span class="math inline">\(rank(\mathbf{X})=p+1\)</span>이고, <span class="math inline">\(\epsilon\sim N_n(0, \sigma^2I)\)</span>일 때 회귀계수벡터 <span class="math inline">\(\beta\)</span>에 대한 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰영역은</li>
</ul>
<p><span class="math display">\[
(\beta-\hat{\beta})'\mathbf{X'X}(\beta-\hat{\beta})\le (p+1)S^2 F_{p+1,n-p-1}(\alpha)
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_j\)</span>에 대한 <span class="math inline">\(100(1-\alpha)\%\)</span> 동시신뢰구간은</li>
</ul>
<p><span class="math display">\[
\hat{\beta}_j\pm \sqrt{\hat{Var}(\hat{\beta}_j)}\times \sqrt{(p+1)F_{p+1,n-p-1}(\alpha)}, \,\,\, j=0, 1, \cdots , p
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(S^2\)</span>은 MSE이고 <span class="math inline">\(\hat{Var}(\hat{\beta}_j)\)</span>는 <span class="math inline">\(S^2(\mathbf{X'X})^{-1}\)</span>의 대각선상에서 <span class="math inline">\(j\)</span>번째 원소</li>
</ul>
<p><br></p>
</section>
</section>
</section>
<section id="모형에-대한-적합도-검정" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="모형에-대한-적합도-검정"><span class="header-section-number">3.5</span> 모형에 대한 적합도 검정</h2>
<ul>
<li>회귀모형을 적합한 후에는 그 모형에 대한 적합성 또는 타당성에 대한 평가를 해야하고 만약 회귀모형에 대한 적합도가 충분하지 않다면 설명력이 높은 적절한 회귀모형을 찾아야 함</li>
</ul>
<section id="결정계수" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="결정계수"><span class="header-section-number">3.5.1</span> 결정계수</h3>
<p>결정계수(<span class="math inline">\(R^2\)</span>)는 회귀모형이 반응변수의 전체 변동 중 어느 정도를 설명하는지를 나타내는 지표이다. 다만 다중회귀분석에서는 설명변수를 추가하면 실제로 의미 없는 변수라 하더라도 <span class="math inline">\(R^2\)</span>가 감소하지 않는다. 따라서 설명변수 개수가 다른 모형을 비교할 때는 단순한 <span class="math inline">\(R^2\)</span>만 보기보다 설명변수 수를 보정한 <strong>수정결정계수(adjusted <span class="math inline">\(R^2\)</span>)</strong> 도 함께 확인하는 것이 좋다.</p>
<p>수정결정계수는 모형에 불필요한 설명변수가 추가될 때 패널티를 주기 때문에, 다중회귀모형의 적합도를 비교할 때 더 신중한 기준으로 사용할 수 있다.</p>
<ul>
<li><p>회귀모형을 적합한 후 전체변동을 회귀모형에 의한 변동과 오차에 의한 변동으로 나누었을 때 회귀모형에 의해 설명되는 부분이 클수록 모형의 적합도가 증가하게 됨</p></li>
<li><p>제곱합 분해</p></li>
</ul>
<p><span class="math display">\[
\begin{align}
\mathbf{(Y-\bar{Y})'(Y-\bar{Y})}&amp;=\mathbf{[(\hat{Y}-\bar{Y})+(Y-\hat{Y})]}'\mathbf{[(\hat{Y}-\bar{Y})+(Y-\hat{Y})]}\\
&amp;=\mathbf{(\hat{Y}-\bar{Y})'(\hat{Y}-\bar{Y})+(Y-\hat{Y})'(Y-\hat{Y})}\\
&amp;=\sum_{i=1}^n(\hat{Y}_i-\bar{Y})^2+\sum_{i=1}^ne_i^2\\
TSS&amp;=SSR+SSE
\end{align}
\]</span></p>
<ul>
<li><p>전체 변동 <span class="math inline">\(SST\)</span>는 회귀제곱합 <span class="math inline">\(SSR\)</span>과 잔차제곱합 <span class="math inline">\(SSE\)</span>로 분해</p></li>
<li><p>결정계수</p></li>
</ul>
<p><span class="math display">\[
R^2=\frac{\sum_{i=1}^n(\hat{Y}_j-\bar{Y})^2}{\sum_{i=1}^n(Y_j-\bar{Y})^2}=1-\frac{\sum_{i=1}^ne_i^2}{\sum_{i=1}^n(Y_j-\bar{Y})^2}
\]</span></p>
<ul>
<li><p>결정계수는 전체 변동 중 적합된 회귀식에 의해 설명되는 비율을 나타냄</p></li>
<li><p>결정계수 <span class="math inline">\(R^2\)</span>는 설명변수 개수가 증가할수록 무조건 증가함</p></li>
<li><p>수정된 결정계수(adjusted <span class="math inline">\(R^2\)</span>)</p></li>
</ul>
<p><span class="math display">\[
R_{adj}^2=1-(1-R^2)(\frac{n-1}{n-p-1})=1-\frac{SSE/(n-p-1)}{TSS/(n-1)}
\]</span></p>
<ul>
<li><p>총변동을 회귀모형에 의한 변동과 오차 요인에 의한 변동으로 분해하여 분산분석을 통해 모형의 유의성에 대해 검정이 가능함</p></li>
<li><p>가설</p>
<ul>
<li><span class="math inline">\(H_0:\mathbf{Y}=\beta_0\mathbf{1}+\epsilon\)</span></li>
<li><span class="math inline">\(H_1:\mathbf{Y=X\beta+\epsilon}\)</span></li>
<li>여기서 <span class="math inline">\(\mathbf{1}=(1,\cdots, 1)'\)</span>로 <span class="math inline">\(n\times 1\)</span> 벡터</li>
</ul></li>
<li><p>검정통계량</p></li>
</ul>
<p><span class="math display">\[
F_{model}=\frac{(TSS-SSE)/p}{SSE/(n-p-1)}\sim F_{p,n-p-1}
\]</span></p>
<ul>
<li>유의수준 <span class="math inline">\(\alpha\)</span> 검정</li>
</ul>
<p><span class="math display">\[
F_{model}\ge F_{p,n-p-1}(\alpha) \,\,\, \text{then reject} \,\,\, H_0
\]</span></p>
<ul>
<li>귀무가설하에서는 설명변수가 반응변수와 관련 없이 상수함수로 주어지는 경우로 이러한 상황에서는 두 변수 간의 관련식을 구할 필요가 없음
<ul>
<li>귀무가설을 기각하지 못하면 추정된 회귀모형이 유의하지 않게 됨</li>
</ul></li>
<li>다중회귀모형 분산분석표</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">요인(source)</th>
<th style="text-align: center;">자유도(df)</th>
<th style="text-align: center;">제곱합(SS)</th>
<th style="text-align: center;">평균제곱합(MS)</th>
<th style="text-align: center;"><span class="math inline">\(F\)</span>-통계량</th>
<th style="text-align: center;">기각값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">모형(model)</td>
<td style="text-align: center;"><span class="math inline">\(p\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SSR\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MSR=SSR/p\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{model}=\frac{MSR}{MSE}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{p,n-p-1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">오차(error)</td>
<td style="text-align: center;"><span class="math inline">\(n-p-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SSE\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MSE=SSE/(n-p-1)\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">총합(total)</td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(TSS\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="회귀계수벡터에-대한-검정" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="회귀계수벡터에-대한-검정"><span class="header-section-number">3.5.2</span> 회귀계수벡터에 대한 검정</h3>
<ul>
<li><p>다중회귀모형에서 반응변수와 설명변수벡터 간의 관계를 나타내는 부분이 회귀계수벡터이며, 이 회귀계수벡터에 대한 유의성이 모형의 유의성을 결정함</p></li>
<li><p>회귀계수벡터 <span class="math inline">\(\beta\)</span>는 다음과 같이 표현 가능</p></li>
</ul>
<p><span class="math display">\[
\beta=\begin{pmatrix}
\beta_0\\
\beta_{\mathbf{X}}
\end{pmatrix}
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(\beta_0\)</span>는 절편을 나타내므로 설명변수와의 관계는 <span class="math inline">\(\beta_{\mathbf{X}}\)</span>에서 나타나며 <span class="math inline">\(\beta_{\mathbf{X}}\)</span>에 대한 유의성 검정이 모형의 유의성 검정과 같게 됨</p></li>
<li><p>위 가설을 회귀계수벡터에 대해 표현하면</p>
<ul>
<li><span class="math inline">\(H_0: \beta_{\mathbf{X}}=0\)</span></li>
<li><span class="math inline">\(H_1: \beta_{\mathbf{X}}\ne 0\)</span></li>
</ul></li>
<li><p>검정통계량</p></li>
</ul>
<p><span class="math display">\[
F=\frac{SSR/p}{SSE/(n-p-1)}\sim F_{p,n-p-1}
\]</span></p>
<ul>
<li>유의수준 <span class="math inline">\(\alpha\)</span> 검정</li>
</ul>
<p><span class="math display">\[
F\ge F_{p,n-p-1}(\alpha) \,\,\, \text{then reject} \,\,\, H_0
\]</span></p>
<p><br></p>
</section>
</section>
<section id="신뢰구간과-예측구간" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="신뢰구간과-예측구간"><span class="header-section-number">3.6</span> 신뢰구간과 예측구간</h2>
<ul>
<li><p>반응변수는 변동이 있는 확률변수이기 때문에 정확한 예측값으로 점추정(point estimation)하기는 쉽지 않음</p></li>
<li><p>보완으로 회귀모형을 기반으로 반응변수를 포함한 예측구간 및 신뢰구간을 계산하여 구간추정(interval estimation)을 할 수 있음</p></li>
</ul>
<section id="반응평균과-반응평균에-대한-신뢰구간" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="반응평균과-반응평균에-대한-신뢰구간"><span class="header-section-number">3.6.1</span> 반응평균과 반응평균에 대한 신뢰구간</h3>
<ul>
<li><p>회귀모형을 적합한 구간 내에 있는 설명변수에서의 반응변수의 예측 문제</p></li>
<li><p>설명변수 <span class="math inline">\(\mathbf{x}*=(X_1*, X_2*, \cdots, X_p*)'\)</span>에서의 종속변수 <span class="math inline">\(Y*=\beta_0+\beta_1X_1*+\beta_2X_2*+\cdots + \beta_pX_p*\)</span>의 반응평균을 구하면</p></li>
</ul>
<p><span class="math display">\[
y*=E(Y*)=\beta_0+\beta_1X_1*+\beta_2X_2*+\cdots + \beta_pX_p*=\mathbf{x}*'\beta
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(\mathbf{x}*=(1,X_1*,X_2*,\cdots ,X_p*)'\)</span></p></li>
<li><p><span class="math inline">\(y*\)</span>의 적합값(fitted value)</p></li>
</ul>
<p><span class="math display">\[
\hat{y}*=\mathbf{x}*'\hat{\beta}
\]</span></p>
<ul>
<li><span class="math inline">\(Y*\)</span>의 불편추정량은 <span class="math inline">\(\hat{y}*\)</span>이고, 분산은</li>
</ul>
<p><span class="math display">\[
Var(\hat{y}*)=\sigma^2\mathbf{x}*'(\mathbf{X'X})^{-1}\mathbf{x}*
\]</span></p>
<ul>
<li>따라서 반응평균에 대한 추정값은</li>
</ul>
<p><span class="math display">\[
\hat{y}*=\mathbf{x}*'\hat{\beta}\sim N(y*,\sigma^2\mathbf{x}*'(\mathbf{X'X})^{-1}\mathbf{x}*)
\]</span></p>
<ul>
<li><span class="math inline">\(\mathbf{x}*'\)</span>에서 반응평균에 대한 추정값 <span class="math inline">\(\hat{y}*\)</span>에 대한 <span class="math inline">\(100(1-\alpha)\%\)</span> 신뢰구간</li>
</ul>
<p><span class="math display">\[
\hat{y}*\pm t_{n-p-1}(\alpha/2)\hat{se}[\hat{y}*]
\]</span></p>
<ul>
<li><span class="math inline">\(\hat{se}[\hat{y}*]\)</span>는 추정값 <span class="math inline">\(\hat{y}*\)</span>의 추정된 표준오차</li>
</ul>
<p><span class="math display">\[
\hat{se}[\hat{y}*]=S\sqrt{\mathbf{x}*'(\mathbf{X'X})^{-1}\mathbf{x}*}
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(S=\sqrt{MSE_{model}}\)</span>이고 <span class="math inline">\(MSE_{model}\)</span>은 적합한 모형에 대한 평균제곱오차</li>
</ul>
<p><br></p>
</section>
</section>
<section id="잔차분석" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="잔차분석"><span class="header-section-number">3.7</span> 잔차분석</h2>
<p>다중회귀분석에서도 모형 적합 후에는 반드시 잔차분석을 수행해야 한다. 회귀계수의 p-value가 유의하더라도 잔차에서 뚜렷한 패턴이 나타나면 모형의 선형성, 등분산성, 독립성, 정규성 가정이 만족되지 않을 수 있다. 잔차분석은 단순히 형식적인 절차가 아니라, 현재 모형이 자료의 구조를 적절히 설명하고 있는지 확인하는 핵심 단계이다.</p>
<p>잔차분석에서 주로 확인할 내용은 다음과 같다.</p>
<ol type="1">
<li>잔차와 적합값의 산점도에서 특정한 곡선 패턴이 있는가?</li>
<li>적합값이 커질수록 잔차의 퍼짐이 커지거나 작아지는가?</li>
<li>잔차의 Q-Q plot이 직선에서 크게 벗어나는가?</li>
<li>일부 관측값이 모형 적합에 과도한 영향을 미치고 있는가?</li>
</ol>
<ul>
<li><p>잔차는 관측값과 추정값의 차이로 정의되며 회귀모형에 의하여 설명되지 않는 변동의 크기를 나타내는 오차에 대한 추정값</p></li>
<li><p>따라서 오차에 대한 가정의 성립여부는 잔차를 검토해 봄으로써 알 수 있음</p></li>
<li><p>다중선형회귀모형에서 오차항에 대한 가정</p></li>
</ul>
<ol type="1">
<li>등분산성</li>
<li>독립성</li>
<li>평균 0인 정규성</li>
</ol>
<section id="회귀함수의-선형성" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="회귀함수의-선형성"><span class="header-section-number">3.7.1</span> 회귀함수의 선형성</h3>
<ul>
<li><p>선형회귀함수가 적합한지 적합하지 않은지에 대한 문제는 자료의 산점도를 그려보거나 선형회귀모형을 적합한 후의 잔차를 각 설명변수 또는 반응변수에 대해 그려봄으로써 추측할 수 있음</p></li>
<li><p>회귀직선의 모형이 타당하고 오차의 등분산성이 성립된다면 설명변수에 대한 잔차 산점도 또는 반응변수에 대한 잔차 산점도에서 잔차는 0을 중심으로 랜덤하게 나타나게 됨</p></li>
<li><p>예를 들어, 산점도에서 이차 곡선이나 삼차 곡선의 형태가 나타난다면 가정된 선형회귀함수는 적절하지 못하다고 볼 수 있음</p></li>
</ul>
</section>
<section id="오차항의-등분산성과-독립성" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="오차항의-등분산성과-독립성"><span class="header-section-number">3.7.2</span> 오차항의 등분산성과 독립성</h3>
<ul>
<li><p>잔차는 회귀직선의 모형이 타당하고 오차의 등분산성이 성립된다면 <span class="math inline">\(Y\)</span>에 대한 잔차산점도 또는 <span class="math inline">\(\hat{Y}\)</span>에 대한 잔차산점도에서 0을 중심으로 완전히 랜덤하게 나타나며 <span class="math inline">\(x\)</span>축 변수에 따라 어떤 경향도 나타나지 않아야 함</p></li>
<li><p>오차항의 독립성은 단순선형회귀모형에서와 마찬가지로 더빈-왓슨 검정을 통해 살펴볼 수 있음</p></li>
</ul>
</section>
<section id="오차항의-정규성" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="오차항의-정규성"><span class="header-section-number">3.7.3</span> 오차항의 정규성</h3>
<ul>
<li><p>오차항의 확률분포가 정규분포에서 많이 벗어나는 경우는 정규성을 가정한 가설 검정 등의 추론을 할 수 없음</p></li>
<li><p>오차항의 정규성을 검토하는 방법으로 잔차들에 대해 정규 <span class="math inline">\(Q-Q\)</span> 그림을 그려 보고, 이들이 <span class="math inline">\(45\)</span>도 직선을 따라 분포하면 정규성을 따른다고 볼 수 있음</p></li>
<li><p>정규성을 만족한다는 귀무가설에 대해 <span class="math inline">\(Shapiro-Wilks\)</span> 검정통계량으로 정규성에 대한 검정을 할 수 있음</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="r을-이용한-다중회귀분석" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="r을-이용한-다중회귀분석"><span class="header-section-number">3.8</span> R을 이용한 다중회귀분석</h2>
<ul>
<li>R에서 lm() 함수를 이용하여 회귀분석 후 생성된 객체에 대해 사용할 수 있는 함수</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">함수 이름</th>
<th style="text-align: center;">함수 설명</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">print()</td>
<td style="text-align: center;">출력</td>
</tr>
<tr class="even">
<td style="text-align: center;">summary()</td>
<td style="text-align: center;">회귀분석 후 기본적인 결과</td>
</tr>
<tr class="odd">
<td style="text-align: center;">coef(), coefficients()</td>
<td style="text-align: center;">추정된 회귀계수값</td>
</tr>
<tr class="even">
<td style="text-align: center;">resid(), residuals()</td>
<td style="text-align: center;">잔차</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fitted()</td>
<td style="text-align: center;">반응변수 추정값</td>
</tr>
<tr class="even">
<td style="text-align: center;">anova()</td>
<td style="text-align: center;">요인에 대한 분산분석결과</td>
</tr>
<tr class="odd">
<td style="text-align: center;">predict()</td>
<td style="text-align: center;">새로운 데이터에 대한 추정</td>
</tr>
<tr class="even">
<td style="text-align: center;">plot()</td>
<td style="text-align: center;">회귀진단 그림</td>
</tr>
<tr class="odd">
<td style="text-align: center;">confint()</td>
<td style="text-align: center;">회귀계수에 대한 신뢰구간</td>
</tr>
<tr class="even">
<td style="text-align: center;">deviance()</td>
<td style="text-align: center;">잔차제곱합</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vcov()</td>
<td style="text-align: center;">추정된 분산-공분산행렬</td>
</tr>
<tr class="even">
<td style="text-align: center;">logLik()</td>
<td style="text-align: center;">정규성 가정하에서 로그-가능도값</td>
</tr>
<tr class="odd">
<td style="text-align: center;">AIC()</td>
<td style="text-align: center;">정보기준값, AIC</td>
</tr>
<tr class="even">
<td style="text-align: center;">step()</td>
<td style="text-align: center;">AIC 기준으로 모형 선택과정</td>
</tr>
</tbody>
</table>
<section id="example" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example">Example</h4>
<ul>
<li>R에 내장되어 있는 환경 데이터 airquality는 New York 도시의 153일 동안 오존, 일조량, 기온과 풍속을 기록한 데이터</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airquality)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6</code></pre>
</div>
</div>
<p><code>airquality</code> 자료에는 결측값이 포함되어 있다. 회귀분석에서는 모형에 포함된 변수 중 결측값이 있는 관측값이 자동으로 제외된다. 그러나 강의와 실습에서는 분석 대상 자료를 명확히 하기 위해 완전관측값만 포함한 분석용 자료를 따로 만드는 것이 좋다.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>aq <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(airquality[, <span class="fu">c</span>(<span class="st">"Ozone"</span>, <span class="st">"Solar.R"</span>, <span class="st">"Wind"</span>, <span class="st">"Temp"</span>)])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aq)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Ozone          Solar.R           Wind            Temp      
 Min.   :  1.0   Min.   :  7.0   Min.   : 2.30   Min.   :57.00  
 1st Qu.: 18.0   1st Qu.:113.5   1st Qu.: 7.40   1st Qu.:71.00  
 Median : 31.0   Median :207.0   Median : 9.70   Median :79.00  
 Mean   : 42.1   Mean   :184.8   Mean   : 9.94   Mean   :77.79  
 3rd Qu.: 62.0   3rd Qu.:255.5   3rd Qu.:11.50   3rd Qu.:84.50  
 Max.   :168.0   Max.   :334.0   Max.   :20.70   Max.   :97.00  </code></pre>
</div>
</div>
<ul>
<li>산점도</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(aq, <span class="at">panel =</span> panel.smooth)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>pairs() 함수는 산점도 행렬을 보여주며, panel=panel.smooth 옵션을 사용하여 평활(smooth)시킨 함수를 추정하여 선으로 표현</p></li>
<li><p>Ozone에 대한 다중회귀모형</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm.a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> aq)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.a)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Ozone ~ Solar.R + Wind + Temp, data = aq)

Residuals:
    Min      1Q  Median      3Q     Max 
-40.485 -14.219  -3.551  10.097  95.619 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -64.34208   23.05472  -2.791  0.00623 ** 
Solar.R       0.05982    0.02319   2.580  0.01124 *  
Wind         -3.33359    0.65441  -5.094 1.52e-06 ***
Temp          1.65209    0.25353   6.516 2.42e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.18 on 107 degrees of freedom
Multiple R-squared:  0.6059,    Adjusted R-squared:  0.5948 
F-statistic: 54.83 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>추정된 회귀계수를 이용하여 Ozone에 대한 추정된 회귀식</li>
</ul>
<p><span class="math display">\[
Ozone=-63.34+0.059Solar.R-3.333Wind+1.652Temp
\]</span></p>
<ul>
<li>모형에 대한 결정계수는 <span class="math inline">\(61\%\)</span>이고, 회귀계수 검정결과 모든 회귀계수는 유의함</li>
</ul>
<p>이 결과를 해석할 때는 각 회귀계수가 다른 변수들을 보정한 후의 효과임을 기억해야 한다. 예를 들어 <code>Wind</code>의 회귀계수는 <code>Solar.R</code>과 <code>Temp</code>가 같은 날들을 비교했을 때 풍속이 한 단위 증가하면 오존 농도의 평균이 어떻게 달라지는지를 의미한다.</p>
<ul>
<li>log(Ozone)에 대한 다중회귀모형</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lm.b <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Ozone) <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> aq)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.b)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Ozone) ~ Solar.R + Wind + Temp, data = aq)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.06193 -0.29970 -0.00231  0.30756  1.23578 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.2621323  0.5535669  -0.474 0.636798    
Solar.R      0.0025152  0.0005567   4.518 1.62e-05 ***
Wind        -0.0615625  0.0157130  -3.918 0.000158 ***
Temp         0.0491711  0.0060875   8.077 1.07e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5086 on 107 degrees of freedom
Multiple R-squared:  0.6644,    Adjusted R-squared:  0.655 
F-statistic: 70.62 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>log(Ozone) 모형에 대한 결정계수는 <span class="math inline">\(66\%\)</span>로, log 변환을 취한 경우가 약간 높음</p></li>
<li><p>유의수준 <span class="math inline">\(5\%\)</span>에서 회귀계수 검정결과 각 회귀계수는 유의함</p></li>
<li><p>잔차 그림</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm.a, <span class="at">which=</span><span class="dv">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm.b, <span class="at">which=</span><span class="dv">1</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(lm.a), <span class="fu">residuals</span>(lm.a), <span class="at">xlab=</span><span class="st">"fitted"</span>, <span class="at">ylab=</span><span class="st">"residual"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(lm.b), <span class="fu">residuals</span>(lm.b), <span class="at">xlab=</span><span class="st">"fitted"</span>, <span class="at">ylab=</span><span class="st">"residual"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Ozone과 log(Ozone)에 대한 잔차 그림을 살펴보면 Ozone 모형은 오차에 대한 가정을 벗어나 보임</p></li>
<li><p>정규성 검정</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(lm.a))</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(lm.a)
W = 0.91709, p-value = 3.618e-06</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(lm.b))</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(lm.b)
W = 0.97749, p-value = 0.05726</code></pre>
</div>
</div>
<ul>
<li><p>잔차에 대한 Shapiro-Wilks 정규성 검정 결과 유의수준 <span class="math inline">\(5\%\)</span>에서 Ozone 모형은 귀무가설을 기각하여 정규성을 만족하지 못함</p></li>
<li><p>독립성 검정</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">requireNamespace</span>(<span class="st">"lmtest"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  lmtest<span class="sc">::</span><span class="fu">dwtest</span>(Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> aq)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  lmtest<span class="sc">::</span><span class="fu">dwtest</span>(<span class="fu">log</span>(Ozone) <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> aq)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Package 'lmtest' is required for Durbin-Watson test."</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  log(Ozone) ~ Solar.R + Wind + Temp
DW = 1.8068, p-value = 0.1334
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<ul>
<li><p>두 모형 모두 독립성을 만족하는 것으로 나타남</p></li>
<li><p>동시 신뢰영역</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">requireNamespace</span>(<span class="st">"ellipse"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(ellipse<span class="sc">::</span><span class="fu">ellipse</span>(lm.b, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>)), <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(<span class="fu">coef</span>(lm.b)[<span class="dv">2</span>], <span class="fu">coef</span>(lm.b)[<span class="dv">3</span>], <span class="at">pch =</span> <span class="dv">18</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">confint</span>(lm.b)[<span class="dv">2</span>, ], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">confint</span>(lm.b)[<span class="dv">3</span>, ], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(ellipse<span class="sc">::</span><span class="fu">ellipse</span>(lm.b, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)), <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(<span class="fu">coef</span>(lm.b)[<span class="dv">2</span>], <span class="fu">coef</span>(lm.b)[<span class="dv">4</span>], <span class="at">pch =</span> <span class="dv">18</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(ellipse<span class="sc">::</span><span class="fu">ellipse</span>(lm.b, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>)), <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(<span class="fu">coef</span>(lm.b)[<span class="dv">3</span>], <span class="fu">coef</span>(lm.b)[<span class="dv">4</span>], <span class="at">pch =</span> <span class="dv">18</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Package 'ellipse' is required for simultaneous confidence region plots."</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="다항회귀모형" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="다항회귀모형"><span class="header-section-number">3.9</span> 다항회귀모형</h2>
<ul>
<li><p>설명변수와 반응변수 사이의 곡선 관계는 다항식(polynomial)을 이용해 표현할 수 있음</p></li>
<li><p>수학적으로 <span class="math inline">\(k\)</span>차 다항식은</p></li>
</ul>
<p><span class="math display">\[
y=c_0+c_1x+c_2x^2+\cdots+c_kx^k
\]</span></p>
<ul>
<li>통계적 모형은</li>
</ul>
<p><span class="math display">\[
Y=\beta_0+\beta_1x+\beta_2x^2+\cdots+\beta_kx^k+\epsilon
\]</span></p>
<section id="example-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example-1">Example</h4>
<ul>
<li>8마리의 실험쥐에 대해 <span class="math inline">\(A\)</span>약의 용량을 달리하여 투여한지 2주 후 몸무게 증가량을 측정하였다.</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">투여량</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">몸무게 증가량</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">6.5</td>
</tr>
</tbody>
</table>
<ul>
<li>이와 같은 데이터에 대해 이차항이 포함된 다항회귀모형을 적합해보자</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">1.2</span>,<span class="fl">1.8</span>,<span class="fl">2.0</span>,<span class="fl">3.8</span>,<span class="fl">4.3</span>,<span class="fl">6.5</span>,<span class="fl">9.0</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>mouse.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span><span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mouse.lm)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + I(x^2))

Residuals:
       1        2        3        4        5        6        7        8 
-0.14167  0.05119  0.28214 -0.24881  0.45833 -0.49643 -0.11310  0.20833 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  1.49643    0.51333   2.915  0.03320 * 
x           -0.53571    0.26172  -2.047  0.09602 . 
I(x^2)       0.18095    0.02839   6.374  0.00141 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3679 on 5 degrees of freedom
Multiple R-squared:  0.988, Adjusted R-squared:  0.9832 
F-statistic: 205.6 on 2 and 5 DF,  p-value: 1.582e-05</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Dose"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Weight gain"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>ord <span class="ot">&lt;-</span> <span class="fu">order</span>(x)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x[ord], <span class="fu">fitted</span>(mouse.lm)[ord], <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>다항회귀분석 결과, 추정회귀식</li>
</ul>
<p><span class="math display">\[
\hat{Y}=1.496-0.536X+0.181X^2
\]</span></p>
<ul>
<li><p><span class="math inline">\(R^2=0.983\)</span>으로 추정된 회귀직선의 설명력이 매우 높음</p></li>
<li><p>일차 회귀계수의 유의성 검정으로</p></li>
</ul>
<p><span class="math display">\[
H_0:\beta_1=0 \,\,\, vs. \,\,\, H_1:\beta_1\ne 0
\]</span></p>
<ul>
<li><p><span class="math inline">\(t\)</span> 통계량은 -2.047으로 <span class="math inline">\(p-value=0.096&lt;0.10\)</span>으로 유의수준 <span class="math inline">\(10\%\)</span>에서 <span class="math inline">\(H_0\)</span>를 기각함(유의수준 <span class="math inline">\(5\%\)</span>에서는 기각하지 못함)</p></li>
<li><p>이차 회귀계수의 유의성 검정으로</p></li>
</ul>
<p><span class="math display">\[
H_0:\beta_2=0 \,\,\, vs. \,\,\, H_1:\beta_2\ne 0
\]</span></p>
<ul>
<li><span class="math inline">\(t\)</span> 통계량은 6.374이며 <span class="math inline">\(p-value=0.00141&lt;0.10\)</span>으로 유의수준 <span class="math inline">\(10\%\)</span>에서 <span class="math inline">\(H_0\)</span>를 기각함(유의수준 <span class="math inline">\(5\%\)</span>에서도 기각함)</li>
</ul>
</section>
<section id="example-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example-2">Example</h4>
<ul>
<li><p>보스턴의 lower status에 따라 주택 가치에 대한 자료이다.</p></li>
<li><p>이와 같은 데이터에 대해 선형회귀모형과 다항회귀모형을 비교해 보자</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">requireNamespace</span>(<span class="st">"MASS"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="st">"Boston"</span>, <span class="at">package =</span> <span class="st">"MASS"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(Boston)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Lower status (%)"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Median house value"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Package 'MASS' is required for the Boston data example."</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">"Boston"</span>)) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> <span class="fu">poly</span>(lstat, <span class="dv">1</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), <span class="at">data =</span> Boston)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(model1)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Lower status (%)"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Median house value"</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  ord <span class="ot">&lt;-</span> <span class="fu">order</span>(Boston<span class="sc">$</span>lstat)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(Boston<span class="sc">$</span>lstat[ord], <span class="fu">fitted</span>(model1)[ord], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">"Boston"</span>)) {</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> <span class="fu">poly</span>(lstat, <span class="dv">3</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), <span class="at">data =</span> Boston)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(model3)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Lower status (%)"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Median house value"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  ord <span class="ot">&lt;-</span> <span class="fu">order</span>(Boston<span class="sc">$</span>lstat)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(Boston<span class="sc">$</span>lstat[ord], <span class="fu">fitted</span>(model3)[ord], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">"Boston"</span>)) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> <span class="fu">poly</span>(lstat, <span class="dv">5</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), <span class="at">data =</span> Boston)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(model5)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Lower status (%)"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Median house value"</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  ord <span class="ot">&lt;-</span> <span class="fu">order</span>(Boston<span class="sc">$</span>lstat)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(Boston<span class="sc">$</span>lstat[ord], <span class="fu">fitted</span>(model5)[ord], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-chapter3_files/figure-html/ch4_9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="표준화-회귀모형" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="표준화-회귀모형"><span class="header-section-number">3.10</span> 표준화 회귀모형</h2>
<ul>
<li><p>회귀계수벡터를 구하기 위해 <span class="math inline">\(\mathbf{(X'X)^{-1}}\)</span> 행렬을 이용하는 데 행렬 계산시 반올림오차 등에 민감함</p></li>
<li><p><span class="math inline">\(\mathbf{(X'X)}\)</span>의 결정식이 0에 가까울 경우는 <span class="math inline">\(\mathbf{X}\)</span>변수들의 상관성이 높은 경우임</p></li>
<li><p>또한 <span class="math inline">\(\mathbf{(X'X)}\)</span>의 값이 단위에 큰 차이가 날 경우는 각 <span class="math inline">\(\mathbf{X}\)</span>변수를 표준화한 후 안정된 <span class="math inline">\(\mathbf{(X'X)}\)</span>를 얻을 수 있음</p></li>
<li><p>이러한 과정을 이용한 회귀모형을 표준화 회귀모형이라 함</p></li>
<li><p>변수에 대한 상관성 변환(correlation transformation)은 각 변수가 동일한 단위를 갖게 할 수 있어 회귀계수를 비교할 경우 장점이 있음</p></li>
</ul>
<p>표준화 회귀계수는 설명변수들의 단위가 서로 다를 때 상대적인 영향력을 비교하는 데 도움이 된다. 그러나 표준화 회귀계수의 크기만으로 변수가 더 중요하다고 단정해서는 안 된다. 변수의 임상적 또는 과학적 의미, 측정 단위, 변수 간 상관성, 연구 목적을 함께 고려해야 한다.</p>
<ul>
<li>다음의 다중선형 회귀모형을 고려하자</li>
</ul>
<p><span class="math display">\[
Y=\beta_0+\beta_1X_1+\beta_2X_2+\cdots +\beta_pX_p+\epsilon
\]</span></p>
<ul>
<li><p>변수 표준화(standardization)는 평균으로 중심화(centering)하고 표준편차로 스케일링(scaling)하여 비례 축소함</p></li>
<li><p>변수 표준화</p></li>
</ul>
<p><span class="math display">\[
Y_i*=\frac{Y_i-\bar{Y}}{S_Y}, \,\,\, X_{ij}*=\frac{X_{ij}-\bar{X}_j}{S_{X_j}}
\]</span></p>
<ul>
<li><span class="math inline">\(n\)</span>개 관측점에 대해 표현하며, 표준화 회귀모형(standardized regression model)은</li>
</ul>
<p><span class="math display">\[
Y_i*=\beta_1*X_{i1}*+\beta_2*X_{i2}*+\cdots +\beta_p
*X_{ip}*+\epsilon_i, \,\,\, i=1,2, \ldots, n
\]</span></p>
<ul>
<li><p>여기서 절편항은 표준화 결과 0이 되어 모형에서 사라짐</p></li>
<li><p>표준화 회귀모형에서의 회귀계수 <span class="math inline">\(\beta*\)</span>와 원래 모형에서의 회귀계수 <span class="math inline">\(\beta\)</span>의 관계는 크기조정 요소(scaling factor)간의 비로 나타남</p></li>
</ul>
<p><span class="math display">\[
\beta_j=\frac{S_Y}{S_{X_j}}\beta_j*
\]</span></p>
<section id="example-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example-3">Example</h4>
<ul>
<li>랜덤 발생 데이터에 대해 회귀모형을 적합하고, 표준화 회귀계수도 살펴보자.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">10</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span>x1<span class="sc">+</span>x2<span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6232 -0.6626  0.0234  0.4180  1.7137 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.78573    0.37533  -2.093   0.0458 *  
x1           4.99930    0.01784 280.239  &lt; 2e-16 ***
x2           1.27435    0.10364  12.296 1.42e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8867 on 27 degrees of freedom
Multiple R-squared:  0.9997,    Adjusted R-squared:  0.9996 
F-statistic: 3.96e+04 on 2 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">scale</span>(y) <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">scale</span>(x1)<span class="sc">+</span><span class="fu">scale</span>(x2))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = scale(y) ~ -1 + scale(x1) + scale(x2))

Residuals:
      Min        1Q    Median        3Q       Max 
-0.035020 -0.014296  0.000505  0.009019  0.036973 

Coefficients:
          Estimate Std. Error t value Pr(&gt;|t|)    
scale(x1) 0.996747   0.003493  285.38  &lt; 2e-16 ***
scale(x2) 0.043733   0.003493   12.52 5.43e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01879 on 28 degrees of freedom
Multiple R-squared:  0.9997,    Adjusted R-squared:  0.9996 
F-statistic: 4.107e+04 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<!-- End -->


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-chapter2.html" class="pagination-link" aria-label="단순선형회귀분석">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">단순선형회귀분석</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-chapter4.html" class="pagination-link" aria-label="회귀진단 및 보정">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">회귀진단 및 보정</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>