<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; 비모수적 생존함수 추정 – Survival Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-Cox.html" rel="next">
<link href="./01-survival.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-nonpara.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">비모수적 생존함수 추정</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survival Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">머리말</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Survival Analysis?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-nonpara.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">비모수적 생존함수 추정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Cox.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Cox 비례위험모형(PH model)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Competing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">경쟁위험(Competing Risks)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">모수적 생존함수 추정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-others.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Other Issues</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#누적한계추정법" id="toc-누적한계추정법" class="nav-link active" data-scroll-target="#누적한계추정법"><span class="header-section-number">2.1</span> 누적한계추정법</a>
  <ul class="collapse">
  <li><a href="#분산-추정량---greenwoods-estimate-of-varhatst" id="toc-분산-추정량---greenwoods-estimate-of-varhatst" class="nav-link" data-scroll-target="#분산-추정량---greenwoods-estimate-of-varhatst"><span class="header-section-number">2.1.1</span> 분산 추정량 - Greenwood’s estimate of <span class="math inline">\(Var(\hat{S}(t))\)</span></a></li>
  <li><a href="#r-예제" id="toc-r-예제" class="nav-link" data-scroll-target="#r-예제"><span class="header-section-number">2.1.2</span> R 예제</a></li>
  <li><a href="#sas-예제" id="toc-sas-예제" class="nav-link" data-scroll-target="#sas-예제"><span class="header-section-number">2.1.3</span> SAS 예제</a></li>
  </ul></li>
  <li><a href="#생명표-방법" id="toc-생명표-방법" class="nav-link" data-scroll-target="#생명표-방법"><span class="header-section-number">2.2</span> 생명표 방법</a>
  <ul class="collapse">
  <li><a href="#sas-예제-1" id="toc-sas-예제-1" class="nav-link" data-scroll-target="#sas-예제-1"><span class="header-section-number">2.2.1</span> SAS 예제</a></li>
  </ul></li>
  <li><a href="#생존분포-비교" id="toc-생존분포-비교" class="nav-link" data-scroll-target="#생존분포-비교"><span class="header-section-number">2.3</span> 생존분포 비교</a>
  <ul class="collapse">
  <li><a href="#comparison-of-survival-curve" id="toc-comparison-of-survival-curve" class="nav-link" data-scroll-target="#comparison-of-survival-curve"><span class="header-section-number">2.3.1</span> Comparison of Survival Curve</a></li>
  <li><a href="#r-예제-1" id="toc-r-예제-1" class="nav-link" data-scroll-target="#r-예제-1"><span class="header-section-number">2.3.2</span> R 예제</a></li>
  <li><a href="#sas-예제-2" id="toc-sas-예제-2" class="nav-link" data-scroll-target="#sas-예제-2"><span class="header-section-number">2.3.3</span> SAS 예제</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="chapter2" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">비모수적 생존함수 추정</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="survival2/f6.png" class="img-fluid"></p>
<p><br></p>
<ul>
<li><p>생존시간의 분포를 특정하지 않는 경우 비모수적 방법(nonparameteric method)으로 생존 함수 추정 가능</p></li>
<li><p>중도절단이 없는 경우, 생존시간 <span class="math inline">\(x_1, \ldots, x_n\)</span>을 순서대로 배열한 것을 <span class="math inline">\(t_1&lt;t_2&lt;\cdots&lt;t_n\)</span>이라 하면 경험적 분포함수 (empirical distribution function)</p></li>
</ul>
<p><span class="math display">\[
            S(t_i) = P(T&gt;t_i)
            = \text{생존시간이 } t_i \text{이상인 관측치수} / \text{총 관측치수}
            = 1- t_i \text{까지의 사망자수} / n
\]</span></p>
<ul>
<li><p>경험적 분포함수를 중단절단자료가 있는 경우로 확장한 방법이 생명표(life table)를 이용한 방법과 누적한계추정법(product-limit method)</p></li>
<li><p>생명표 방법은 시간의 단위로 묶어서 생존함수를 추정하며, 누적한계추정법은 환자 개개인의 생존시간을 관측하여 각 시점에서의 생존함수를 추정</p></li>
</ul>
<p><br></p>
<section id="누적한계추정법" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="누적한계추정법"><span class="header-section-number">2.1</span> 누적한계추정법</h2>
<ul>
<li>생존함수를 추정하는 대표적인 방법 중 하나로 연구자의 이름을 따서 카플란-마이어(Kaplan-Meier) 추정법이라고도 함</li>
</ul>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Notation</p>
</blockquote>
</blockquote>
<ul>
<li><p>Sample of <span class="math inline">\(n_0\)</span> from <span class="math inline">\(F\)</span> <span class="math display">\[
0=t_0&lt;t_1&lt;t_2&lt;\cdots &lt;t_k&lt;t_{k+1}=\infty
\]</span> &nbsp; &nbsp; &nbsp; are failure time (uncensored)</p></li>
<li><p><span class="math inline">\(d_j\)</span> subjects fail at <span class="math inline">\(t_j\)</span></p></li>
</ul>
<p><img src="survival_add/f25.png" class="img-fluid"></p>
<ul>
<li># at risk of failure at time just before <span class="math inline">\(t_j\)</span> <span class="math display">\[
n_j=\sum_{i=j}^k(m_i+d_i)
\]</span></li>
</ul>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Assume</p>
</blockquote>
</blockquote>
<ul>
<li><p>The censoring time <span class="math inline">\(t_{jl}\)</span> tells us only that the corresponding failure time is <span class="math inline">\(&gt;t_{jl}\)</span> (i.e., the contribution to the likelihood of a survival time censored at <span class="math inline">\(t_{jl}\)</span> is <span class="math inline">\(P(T&gt;t_{jl})=S(t_{jl}+0))\)</span></p></li>
<li><p>The likelihood of <span class="math inline">\(S\)</span> (survival function) is</p></li>
</ul>
<p><span class="math display">\[
L(S)=\prod_{j=0}^k \bigg \{[S(t_j)-S(t_j+0)]^{d_{j}}\prod_{l=1}^{m_j}S(t_{jl}+0)\bigg\}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; <span class="math inline">\(S(t_j)-S(t_j+0)\)</span>: the probability of failure at time <span class="math inline">\(t_j\)</span></p>
<p>&nbsp; &nbsp; &nbsp; <span class="math inline">\(S(t_{jl}+0)=Pr(T&gt;t_{jl})\)</span>: the contribution to the likelihood of a survival time censored at <span class="math inline">\(t_{jl}\)</span></p>
<ul>
<li><p>MLE of <span class="math inline">\(S\)</span> is <span class="math inline">\(\hat{S}\)</span> such that <span class="math inline">\(L(\hat{S})\)</span> is max</p></li>
<li><p>The maximum likelihood estimate <span class="math inline">\(\hat{S}\)</span> of <span class="math inline">\(F\)</span> will maximized <span class="math inline">\(L(\hat{S})\)</span></p></li>
<li><p>Clearly we want <span class="math inline">\(S(t_j)-S(t_j+0)&gt;0\)</span> (i.e., jump at <span class="math inline">\(t_j\)</span>) (*) otherwise <span class="math inline">\(L(\hat{S})=0\)</span></p></li>
<li><p>Any <span class="math inline">\(\hat{F}\)</span> satisfies (*), <span class="math inline">\(L(\hat{F})\)</span> is maximized by taking</p></li>
</ul>
<p><span class="math display">\[
\hat{S}(t_{jl}+0)=\hat{S}(t_j+0)=\hat{S}(t_{j+1})
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; jump on only at time <span class="math inline">\(t_{j+1}\)</span> not censored time <span class="math inline">\(\rightarrow \hat{S}(t_{0l})=1\)</span>)</p>
<ul>
<li>MLE <span class="math inline">\(\hat{S}\)</span> is a <strong>discrete survival function</strong> with jump points <span class="math inline">\(t_j\)</span></li>
</ul>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Proof</p>
</blockquote>
</blockquote>
<ul>
<li>Let <span class="math inline">\(\hat{\lambda}\)</span> be the hazard function for <span class="math inline">\(\hat{S}\)</span></li>
</ul>
<p><span class="math display">\[
1-\hat{\lambda}_j = \frac{\hat{S}(t_{j+1})}{\hat{S}(t_{j})}=\frac{\hat{S}(t_j+0)}{\hat{S}(t_{j})}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; <span class="math inline">\(\lambda(t)=Pr(T=t|T\ge t)\)</span></p>
<p><span class="math display">\[
\begin{aligned}
1-\lambda(t)&amp;=1-Pr(T=t|T\ge t)\\
&amp;=Pr(T\ge t+1|T \ge t)\\
&amp;=\frac{S(t+0)}{S(t)}
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\hat{\lambda}_j = \frac{\hat{S}(t_{j})-\hat{S}(t_j+0)}{\hat{S}(t_{j})}=\frac{\hat{f}(t_j)}{\hat{S}(t_{j})}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\hat{S}(t_{j})-\hat{S}(t_j+0)=\hat{\lambda}_j\hat{F}(t_j)=\hat{\lambda}_j\prod_{i&lt;j}(1-\hat{\lambda}_i)\)</span>, <span class="math inline">\(\hat{S}(t_{j+1})=\prod_{i=1}^j(1-\hat{\lambda}_i)\)</span></p></li>
<li><p>Now plug in (*) into <span class="math inline">\(L(\hat{F})\)</span> and expand completely</p></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
L(\hat{S})&amp;=\prod_{j=0}^k \bigg \{[\hat{S}(t_j)-\hat{S}(t_j+0)]^{d_{j}}\prod_{l=1}^{m_j}\hat{S}(t_{jl}+0)\bigg\} \\
&amp;=\prod_{j=0}^k \bigg \{[\hat{S}(t_j)-\hat{S}(t_j+0)]^{d_{j}}[\hat{S}(t_{j}+0)]^{m_j}\bigg\} \\
&amp;=\prod_{j=1}^k \bigg \{[\hat{\lambda}_j\hat{S}(t_j)]^{d_{j}}[(1-\hat{\lambda})\hat{S}(t_{j}+0)]^{m_j}\bigg\} \\
&amp;=\prod_{j=1}^k \bigg \{\hat{\lambda}_j^{d_j}(1-\hat{\lambda})^{m_j}\hat{S}(t_j)^{d_{j}+m_j}\bigg\} \\
&amp;=\prod_{j=1}^k \bigg \{\hat{\lambda}_j^{d_j}(1-\hat{\lambda})^{m_j}\prod_{i=0}^{j-1}(1-\hat{\lambda}_j)^{d_{j}+m_j}\bigg\} \\
&amp; \,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\, \vdots \\
&amp;=\prod_{j=1}^k \hat{\lambda}_j^{d_j}(1-\hat{\lambda})^{n_j - d_j}
\end{aligned}
\]</span></p>
<ul>
<li>What <span class="math inline">\(\hat{\lambda}_j\)</span> that maximizes <span class="math inline">\(L(\hat{F})\)</span> is maximized when</li>
</ul>
<p><span class="math display">\[
\hat{\lambda}_j = \frac{d_j}{n_j}
\]</span></p>
<ul>
<li><p>Maximum likelihood estimate of <span class="math inline">\(S\)</span> is <span class="math inline">\(\hat{S}=\prod_{j, t_j&lt;t}(1-\hat{\lambda}_j)\)</span></p></li>
<li><p><strong>Kaplan-Meier estimator</strong> or Product limit estimator of survival function</p></li>
</ul>
<p><span class="math display">\[
\hat{S}=\prod_{j, t_j&lt;t}(1-\hat{\lambda}_j)=\prod_{j, t_j&lt;t}(1-\frac{d_j}{n_j})
\]</span></p>
<p><img src="survival_add/f26.png" class="img-fluid"></p>
<p><span class="math display">\[
\begin{aligned}
S(t)&amp;=Pr(T\ge t) \\
&amp;= Pr(T\ge t|T\ge t_{j-1})\cdot Pr(T\ge t_{j-1}) \\
&amp;= \frac{n_j-d_j}{n_j}\cdot Pr(T\ge t_{j-1})\\
&amp;= \prod_{j, t_j&lt;t}\bigg(1-\frac{d_j}{n_j}\bigg)
\end{aligned}
\]</span></p>
<ul>
<li>Conditional probability</li>
</ul>
<p><span class="math display">\[
\frac{n_j-d_j}{n_j}=\frac{\#\,\,\, of\,\,\, individuals \,\,\, at\,\,\, risk\,\,\, at\,\,\, time\,\,\, t_{(j)}}{\#\,\,\, of\,\,\, individuals \,\,\, at\,\,\, risk\,\,\, at\,\,\, time\,\,\, t_{(j-1)}}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; We get</p>
<p><span class="math display">\[
d_j \sim bin(n_j, \hat{\lambda}_j)
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; where <span class="math inline">\(\hat{\lambda}_j=\frac{d_j}{n_j}\)</span></p>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Note</p>
</blockquote>
</blockquote>
<ol type="1">
<li>If there is no censoring and no ties in the data (i.e., <span class="math inline">\(n_i=n_{i-1}-d_{i-1}\)</span>)</li>
</ol>
<p><span class="math display">\[
\hat{S}(t)=\frac{\#(t_i\ge t)}{n_0}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; empirical survival function (step function)</p>
<ol start="2" type="1">
<li>Setting - no censoring and no ties (<span class="math inline">\(n_i=n_{i-1}-d_{i-1}\)</span>)</li>
</ol>
<p><span class="math display">\[
\hat{S}(t)=\frac{n_0-d_0}{n_0} \cdot \frac{n_1-d_1}{n_1} \cdot \, \cdots \, \cdot \frac{n_j-d_j}{n_j}=\frac{n_j-d_j}{n_0}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; <span class="math inline">\(\hat{\lambda}_j=\frac{d_j}{n_j}\)</span> is equivalent to</p>
<p><span class="math display">\[
\hat{\lambda}_j=Pr(T=t_j|T\ge t_j)=\frac{\#\,\,\,of\,\,\, failure\,\,\, at\,\,\, t_j}{\#\,\,\,of\,\,\, risk\,\,\, at\,\,\, t_j^-}
\]</span></p>
<ol start="3" type="1">
<li><p>KME is a discrete measure giving mass only to the uncensored observations</p></li>
<li><p>KME is step function</p></li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - It jumps at death times</p>
<p>&nbsp; &nbsp; &nbsp; - No changes at censored observations</p>
<ul>
<li><p>Censoring observations do not contribute to compute <span class="math inline">\(\hat{\lambda}_j\)</span></p></li>
<li><p>For breaking ties</p></li>
</ul>
<ol type="1">
<li><p>If a censored observations is tied with an uncensored observation, we consider the censored observations &gt; the uncensored observations</p></li>
<li><p>If two uncensored observations or two censored observations are tied then we break them arbitrary by an infinitesimal distance</p></li>
</ol>
<p><img src="survival_add/f27.png" class="img-fluid"></p>
<ul>
<li><p>생존시간 또는 중도절단시간 <span class="math inline">\(x_1, \ldots, x_n\)</span>을 순서대로 배열한 것을 <span class="math inline">\(t_1&lt;t_2&lt;\cdots&lt;t_n\)</span>이라 하고 <span class="math inline">\(\delta_i\)</span>를 생존시간 <span class="math inline">\(t_i\)</span>의 중도절단여부를 표현. 이때 중도절단인 경우 <span class="math inline">\(\delta_i=0\)</span>, 그렇지 않은 경우 <span class="math inline">\(\delta_i=1\)</span></p></li>
<li><p>시점 <span class="math inline">\(t_i\)</span>에서 위험에 노출된 인원수, 즉 <span class="math inline">\(t_i\)</span> 바로 직전까지 중도절단되지 않고 생존해 있던 인원수를 <span class="math inline">\(n_i\)</span>라고 하고 사망한 사람의 수를 <span class="math inline">\(d_i\)</span>라고 했을 때 생존함수 <span class="math inline">\(S(t)\)</span>의 누적한계추정량은</p></li>
</ul>
<p><span class="math display">\[
\hat{S}(t)=\prod_{t_i\le t} (1-d_i/n_i)^{\delta_i}
\]</span></p>
<ul>
<li><p>누정한계추정량은 중도절단시간에서는 변하지 않고 사망이 관측되는 시점 <span class="math inline">\(x_i\)</span>에서 <span class="math inline">\((n_i-d_i)/n_i\)</span>를 곱해준 만큼씩 감소하는 계단함수</p></li>
<li><p>중도절단의 효과는 각 단계에서의 크기 <span class="math inline">\(n_i\)</span>의 값에서 나타남</p></li>
<li><p>사망시간과 중도절단시간이 동일한 경우에는 사망이 중도절단보다 먼저 관측되었다고 판단</p></li>
<li><p>마지막 생존시간 <span class="math inline">\(t_n\)</span>이 중도절단된 경우에는 <span class="math inline">\(t_n\)</span> 이상의 기간에 대해서는 누적한계추정값을 정의하지 않음</p></li>
</ul>
<section id="분산-추정량---greenwoods-estimate-of-varhatst" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="분산-추정량---greenwoods-estimate-of-varhatst"><span class="header-section-number">2.1.1</span> 분산 추정량 - Greenwood’s estimate of <span class="math inline">\(Var(\hat{S}(t))\)</span></h3>
<p><span class="math display">\[
\hat{Var}(\hat{S}(t))=\hat{S}^2(t)\sum_{i:t_i\le t} \frac{d_i}{n_i(n_i-d_i)}
\]</span></p>
<section id="delta-delta-method" class="level4" data-number="2.1.1.1">
<h4 data-number="2.1.1.1" class="anchored" data-anchor-id="delta-delta-method"><span class="header-section-number">2.1.1.1</span> Delta (<span class="math inline">\(\delta\)</span>) method</h4>
<ul>
<li><p>Suppose <span class="math inline">\(\hat{\theta}\)</span> is an estimator of <span class="math inline">\(\theta\)</span></p></li>
<li><p><span class="math inline">\(g(\theta)\)</span> is the parameter of interest</p></li>
<li><p>Assume <span class="math inline">\(g(\cdot)\)</span> is a differentiable function</p></li>
<li><p><span class="math inline">\(g(\hat{\theta})\)</span> is an estimator of <span class="math inline">\(g(\theta)\)</span></p></li>
</ul>
<p><span class="math display">\[
g(\hat{\theta})-g(\theta)=g'(\theta)(\hat{\theta}-\theta)+o(|\hat{\theta}-\theta|)
\]</span></p>
<ul>
<li><p>Usually <span class="math inline">\(\sqrt{n}(\hat\theta -\theta) \rightarrow^d N(0, \sigma^2)\)</span></p></li>
<li><p>So <span class="math inline">\(Var(g(\hat{\theta})) \approx (g'(\hat{\theta}))^2Var(\hat{\theta})\)</span></p></li>
</ul>
<p><img src="survival_add/f28.png" class="img-fluid"></p>
</section>
<section id="heuristic-derivation-of-greenwoods-estimate-of-sigma_hatst2" class="level4" data-number="2.1.1.2">
<h4 data-number="2.1.1.2" class="anchored" data-anchor-id="heuristic-derivation-of-greenwoods-estimate-of-sigma_hatst2"><span class="header-section-number">2.1.1.2</span> Heuristic derivation of Greenwood’s estimate of <span class="math inline">\(\sigma_{\hat{S}(t)}^2\)</span></h4>
<ul>
<li>Under some regularity conditions</li>
</ul>
<p><span class="math display">\[
\hat{S}(t)=\prod_{j, t_j&lt;t}(1-\frac{d_j}{n_j})\sim AN(S(t),\sigma_{\hat{S}(t)}^2)
\]</span></p>
</section>
<section id="delta-method" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="delta-method"><span class="math inline">\(\delta\)</span>-method</h4>
<ul>
<li><p>Suppose <span class="math inline">\(T_n \sim AN(\mu, \sigma_n^2)\)</span> with <span class="math inline">\(\sigma_n \rightarrow 0\)</span></p></li>
<li><p>Let <span class="math inline">\(g\)</span> be a real-valued function differentiable at <span class="math inline">\(t=\mu\)</span>, with <span class="math inline">\(g'(\mu)\ne 0\)</span></p></li>
<li><p>Then <span class="math inline">\(g(T_n)\sim AN(g(\mu), [g'(\mu)]^2\sigma_n^2)\)</span></p></li>
</ul>
<p><span class="math display">\[
\hat{S}(t)=\prod_{j, t_j&lt;t}(1-\hat{\lambda}_j)
\]</span></p>
<ul>
<li><span class="math inline">\(log\hat{S}(t)=\sum_{j, t_j&lt;t}log(1-\hat{\lambda}_j)\)</span>: sum is easier to calculate</li>
</ul>
<p><span class="math display">\[
Var(log\hat{S}(t))=\sum_{j, t_j&lt;t}Var(log(1-\hat{\lambda}_j))+cov
\]</span></p>
<ul>
<li><p>If we assume independence then <span class="math inline">\(Cov=0\)</span></p></li>
<li><p><span class="math inline">\(1-\hat{\lambda}_j\sim AN(1-\lambda_j, \frac{\lambda_j(1-\lambda_j)}{n_j})\)</span></p></li>
</ul>
<p><span class="math display">\[
log(1-\hat{\lambda}_j)\sim AN(log(1-\lambda_j),(-\frac{1}{1-\lambda_j})^2 \frac{\lambda_j(1-\lambda_j)}{n_j})
\]</span></p>
<p><span class="math display">\[
i.e., \,\,\, log(1-\hat{\lambda}_j)\sim AN(log(1-\lambda_j),(\frac{\lambda_j}{n_j(1-\lambda_j)})
\]</span></p>
<ul>
<li><span class="math inline">\(Var(log\hat{S}(t))=\sum_{j, t_j&lt;t}\frac{\lambda_j}{n_j(1-\lambda_j)}\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\hat{Var}(log\hat{S}(t))&amp;=\sum_{j, t_j&lt;t}\frac{\hat\lambda_j}{n_j(1-\hat\lambda_j)} \\
&amp;= \sum_{j, t_j&lt;t}\frac{d_j}{n_j(n_j-d_j)}
\end{aligned}
\]</span></p>
<ul>
<li><span class="math inline">\(\hat{S}(t)=e^{log\hat{S}(t)}\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
Var(\hat{S}(t))&amp;=(e^{log{S}(t)})^2\sum_{j, t_j&lt;t}\frac{\lambda_j}{n_j(1-\lambda_j)} \\
&amp;= (S(t))^2\sum_{j, t_j&lt;t}\frac{\lambda_j}{n_j(1-\lambda_j)}
\end{aligned}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\hat{Var}(\hat{S}(t))=(\hat{S}(t))^2\sum_{j, t_j&lt;t}\frac{\hat{\lambda}_j}{n_j(1-\hat{\lambda}_j)}\)</span></p></li>
<li><p>Greenwood’s Formula (Crowley &amp; Breslow 1974, Annals of Staitsitcs)</p></li>
</ul>
<p><span class="math display">\[
\hat{Var}(\hat{S}(t))=(\hat{S}(t))^2\sum_{j, t_j&lt;t}\frac{d_j}{n_j(n_j-d_j)}
\]</span></p>
<ul>
<li><span class="math inline">\(\hat{S}(t)\sim AN(S(t), \hat{Var}(\hat{S}(t))\)</span> so,</li>
</ul>
<p><span class="math display">\[
\frac{\hat{S}(t)-S(t)}{\sqrt{Var(\hat{F}(t))}}\rightarrow^d N(0,1)
\]</span></p>
<ul>
<li><span class="math inline">\(100(1-\alpha)\%\)</span> CI for <span class="math inline">\(S(t)\)</span></li>
</ul>
<p><span class="math display">\[
\hat{S}(t) \pm z_{\alpha/2}\sqrt{\hat{Var}(\hat{S}(t))}
\]</span></p>
<ul>
<li><p>Problem: Bounds may be outside <span class="math inline">\([0,1]\)</span> (<span class="math inline">\(0&lt;\hat{S}(t)&lt;1\)</span>)</p></li>
<li><p>누정한계추정량은 일치성(consistency)과 근사적 정규성(asymptotic normality)을 만족하는 등 표본이 클 때 통계적 성질이 우수함</p></li>
<li><p>자료 표현법</p></li>
</ul>
<p><img src="survival/ex5.jpg" class="img-fluid" style="width:80.0%"></p>
<p><img src="survival/ex6.jpg" class="img-fluid" style="width:80.0%"></p>
<ul>
<li>Example: Kaplan-Meier estimator for the 6 MP data (<span class="math inline">\(n=21\)</span>)</li>
</ul>
<p><img src="survival/ex01.jpg" class="img-fluid"></p>
<ul>
<li>Example</li>
</ul>
<p><img src="survival/ex01.png" class="img-fluid"></p>
</section>
</section>
<section id="r-예제" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="r-예제"><span class="header-section-number">2.1.2</span> R 예제</h3>
<!-- * 필요 패키지 로드 -->
<!-- ```{r, message=F} -->
<!-- library(autoReg) -->
<!-- library(survival) -->
<!-- library(survminer) -->
<!-- library(howto) -->
<!-- library(flextable) -->
<!-- library(ftExtra) -->
<!-- library(tidyverse) -->
<!-- ``` -->
<ul>
<li>autoReg 패키지에 포함되어 있는 anderson 데이터를 사용
<ul>
<li>42명의 백혈병 환자 데이터</li>
<li>time: week 단위</li>
<li>status: 재발은 1, 재발하지 않은 경우(중도절단의 경우)는 0</li>
<li>sex: 성별</li>
<li>logWBC: 백혈구 숫자의 로그값</li>
<li>rx: 치료군은 0, 대조군은 1</li>
</ul></li>
<li>설명의 편의를 위해 이 데이터 중 rx가 0인것만 골라 data라는 데이터 생성</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(autoReg)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">subset</span>(anderson,rx<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time status sex logWBC rx
1   35      0   1   1.45  0
2   34      0   1   1.47  0
3   32      0   1   2.20  0
4   32      0   1   2.53  0
5   25      0   1   1.78  0
6   23      1   1   2.57  0</code></pre>
</div>
</div>
<ul>
<li>생존분석은 다른 분석과는 달리 이벤트가 생기지 않은 모든 예에서 정확한 생존기간을 알 수 없기 때문에 모두 중도절단 자료로 취급함. 즉, 연구 종료 시까지 이벤트가 생기지 않고 종료된 경우나 추적실패(follow-up loss) 또는 중도탈락(drop-out)의 경우도 모두 절단된 데이터를 의미</li>
<li>이 데이터에서 time은 숫자로 되어 있으나 생존분석을 위해 중도절단된 자료에는 숫자에 ‘+’를 붙여 중도절단임을 나타내야 함</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>time</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 35 34 32 32 25 23 22 20 19 17 16 13 11 10 10  9  7  6  6  6  6</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(data,<span class="fu">Surv</span>(time,status))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 35+ 34+ 32+ 32+ 25+ 23  22  20+ 19+ 17+ 16  13  11+ 10+ 10   9+  7   6+  6 
[20]  6   6 </code></pre>
</div>
</div>
<ul>
<li>평균생존시간(<span class="math inline">\(\bar{T}\)</span>)은 중도절단을 고려하지 않고 생존시간의 평균을 계산함
<ul>
<li>중도절단된 자료는 정확한 생존시간을 알 수 없으므로 실제 생존시간은 평균생존시간보다 길어짐</li>
<li>평균위험률(average hazard rate, <span class="math inline">\(\bar{h}\)</span>)은 전체 실패 수를 생존시간의 합계로 나눈 값</li>
</ul></li>
<li>다음은 anderson 데이터에서 치료군(rx)에 따라 평균생존시간과 평균 위험률을 계산한 값임</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>anderson <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(rx) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">T=</span><span class="fu">mean</span>(time),<span class="at">h=</span><span class="fu">sum</span>(status)<span class="sc">/</span><span class="fu">sum</span>(time))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
     rx     T      h
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1     0 17.1  0.0251
2     1  8.67 0.115 </code></pre>
</div>
</div>
<ul>
<li><p>치료군(rx==0)에서 평균생존시간이 더 길고 평균위험률이 더 낮은 것을 알 수 있음</p></li>
<li><p>survfit함수를 쓰면 생존율을 계산해줌</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span>data)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = data)

      n events median 0.95LCL 0.95UCL
[1,] 21      9     23      16      NA</code></pre>
</div>
</div>
<ul>
<li><p>출력결과에서 median survival과 95% 신뢰구간을 알 수 있음</p></li>
<li><p>Median survival time은 생존율이 50%인 시간을 의미하며, 각 시기별 생존율은 다음과 같음</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = data)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    6     21       3    0.857  0.0764        0.720        1.000
    7     17       1    0.807  0.0869        0.653        0.996
   10     15       1    0.753  0.0963        0.586        0.968
   13     12       1    0.690  0.1068        0.510        0.935
   16     11       1    0.627  0.1141        0.439        0.896
   22      7       1    0.538  0.1282        0.337        0.858
   23      6       1    0.448  0.1346        0.249        0.807</code></pre>
</div>
</div>
<ul>
<li>각 시기별로 생존율과 생존율의 95% 신뢰구간을 알 수 있음. 생존율의 95% 신뢰구간은 다음과 같이 계산함</li>
</ul>
<p><span class="math display">\[
\hat{S}(t)\pm 1.96 \times \sqrt{\hat{Var}(\hat{S}(t))}
\]</span></p>
<ul>
<li>Mean survival time</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unclass</span>(<span class="fu">summary</span>(fit))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$n
[1] 21

$time
[1]  6  7 10 13 16 22 23

$n.risk
[1] 21 17 15 12 11  7  6

$n.event
[1] 3 1 1 1 1 1 1

$n.censor
[1] 1 0 2 1 0 3 0

$surv
[1] 0.8571429 0.8067227 0.7529412 0.6901961 0.6274510 0.5378151 0.4481793

$std.err
[1] 0.07636035 0.08693529 0.09634965 0.10681471 0.11405387 0.12823375 0.13459146

$cumhaz
[1] 0.1428571 0.2016807 0.2683473 0.3516807 0.4425898 0.5854469 0.7521136

$std.chaz
[1] 0.08247861 0.10130611 0.12127396 0.14714557 0.17296323 0.22433110 0.27946775

$type
[1] "right"

$logse
[1] TRUE

$conf.int
[1] 0.95

$conf.type
[1] "log"

$lower
[1] 0.7198171 0.6531242 0.5859190 0.5096131 0.4393939 0.3370366 0.2487882

$upper
[1] 1.0000000 0.9964437 0.9675748 0.9347692 0.8959949 0.8582008 0.8073720

$t0
[1] 0

$call
survfit(formula = Surv(time, status) ~ 1, data = data)

$table
  records     n.max   n.start    events     rmean se(rmean)    median   0.95LCL 
21.000000 21.000000 21.000000  9.000000 23.287395  2.827468 23.000000 16.000000 
  0.95UCL 
       NA 

$rmean.endtime
[1] 35</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)<span class="sc">$</span>table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  records     n.max   n.start    events     rmean se(rmean)    median   0.95LCL 
21.000000 21.000000 21.000000  9.000000 23.287395  2.827468 23.000000 16.000000 
  0.95UCL 
       NA </code></pre>
</div>
</div>
<ul>
<li><p>생존율을 계산하는 과정을 설명하기 위해 howto 패키지의 howto() 함수를 사용하여 계산과정을 살펴볼 수 있음</p></li>
<li><p>howto 패키지는 다음과 같이 install 함</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"cardiomoon/howto"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span>data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(howto)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable) <span class="do">## highlight function</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">howto</span>(fit) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">highlight</span>(<span class="at">i=</span><span class="dv">1</span>,<span class="at">j=</span><span class="dv">6</span>,<span class="at">color=</span><span class="st">"yellow"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">highlight</span>(<span class="at">i=</span><span class="dv">2</span>,<span class="at">j=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>),<span class="at">color=</span><span class="st">"yellow"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-aded0598{}.cl-ade749b4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ade749be{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:rgba(255, 255, 0, 1.00);}.cl-ade99610{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ade9961a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ade9c176{width:0.574in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c180{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c181{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c182{width:0.871in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c183{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c18a{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c194{width:0.574in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c195{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c196{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c19e{width:0.871in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c19f{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1a0{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1a8{width:0.574in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1a9{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1aa{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1ab{width:0.871in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1b2{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ade9c1b3{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-aded0598"><thead><tr style="overflow-wrap:break-word;"><th class="cl-ade9c176"><p class="cl-ade99610"><span class="cl-ade749b4">time</span></p></th><th class="cl-ade9c180"><p class="cl-ade99610"><span class="cl-ade749b4">n.risk</span></p></th><th class="cl-ade9c181"><p class="cl-ade99610"><span class="cl-ade749b4">n.event</span></p></th><th class="cl-ade9c182"><p class="cl-ade99610"><span class="cl-ade749b4">n.censor</span></p></th><th class="cl-ade9c183"><p class="cl-ade9961a"><span class="cl-ade749b4"> </span></p></th><th class="cl-ade9c18a"><p class="cl-ade99610"><span class="cl-ade749b4">surv</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">21</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4"></span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749be">1.0000</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">6</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749be">21</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749be">3</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749be">1.0000</span><span class="cl-ade749be">×(18 ÷ 21)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.8571</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">7</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">17</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4">0.8571</span><span class="cl-ade749b4">×(16 ÷ 17)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.8067</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">10</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">15</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">2</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4">0.8067</span><span class="cl-ade749b4">×(14 ÷ 15)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.7529</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">13</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">12</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4">0.7529</span><span class="cl-ade749b4">×(11 ÷ 12)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.6902</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">16</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">11</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4">0.6902</span><span class="cl-ade749b4">×(10 ÷ 11)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.6275</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c194"><p class="cl-ade99610"><span class="cl-ade749b4">22</span></p></td><td class="cl-ade9c195"><p class="cl-ade99610"><span class="cl-ade749b4">7</span></p></td><td class="cl-ade9c196"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c19e"><p class="cl-ade99610"><span class="cl-ade749b4">3</span></p></td><td class="cl-ade9c19f"><p class="cl-ade9961a"><span class="cl-ade749b4">0.6275</span><span class="cl-ade749b4">×(6 ÷ 7)</span></p></td><td class="cl-ade9c1a0"><p class="cl-ade99610"><span class="cl-ade749b4">0.5378</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ade9c1a8"><p class="cl-ade99610"><span class="cl-ade749b4">23</span></p></td><td class="cl-ade9c1a9"><p class="cl-ade99610"><span class="cl-ade749b4">6</span></p></td><td class="cl-ade9c1aa"><p class="cl-ade99610"><span class="cl-ade749b4">1</span></p></td><td class="cl-ade9c1ab"><p class="cl-ade99610"><span class="cl-ade749b4">0</span></p></td><td class="cl-ade9c1b2"><p class="cl-ade9961a"><span class="cl-ade749b4">0.5378</span><span class="cl-ade749b4">×(5 ÷ 6)</span></p></td><td class="cl-ade9c1b3"><p class="cl-ade99610"><span class="cl-ade749b4">0.4482</span></p></td></tr></tbody></table></div>
</div>
</div>
<p><br></p>
<ul>
<li>연구 시작 지점에서 대상환자수(number at risk, n.risk)는 21명이었고 아직 이벤트가 발생하지 않았으므로(n.event=0) 생존율은 21/21=1. 6주째에 3명에게 이벤트가 발생하여 6주째의 n.risk는 21명이고 이 중 이벤트가 발생한 3명을 제외하고 18명이 생존하였음. 따라서 6주째 생존율은 다음과 같음</li>
</ul>
<p><span class="math display">\[
\hat{S}(6)=1 \times \frac{(21-3)}{21} =1\times \frac{18}{21} =0.8571
\]</span></p>
<ul>
<li>7주째의 number at risk는 6주째에 3명 실패(이벤트 발생), 1명 중도절단되어 17명이고 생존율은 <span class="math inline">\(0.8571 \times (16/17)=0.8067\)</span>로 추정</li>
</ul>
<p><span class="math display">\[
\hat{S}(7)=1\times \frac{18}{21}\times \frac{16}{17}
\]</span></p>
<ul>
<li>13주째의 생존율</li>
</ul>
<p><span class="math display">\[
\hat{S}(13)=1\times \frac{18}{21}\times \frac{16}{17} \times \frac{14}{15} \times \frac{11}{12} = 0.6902
\]</span></p>
<ul>
<li>이를 이용하여 생존율 그래프를 그릴 수 있으며, 그래프에서 생존율이 0.5인 시간이 median survival을 의미</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">35</span>), <span class="at">mark.time=</span>T, <span class="at">col=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>median<span class="ot">=</span>fit<span class="sc">$</span>time[<span class="fu">min</span>(<span class="fu">which</span>(fit<span class="sc">$</span>surv<span class="sc">&lt;</span><span class="fl">0.5</span>))]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,median,<span class="fl">0.5</span>,<span class="at">angle=</span><span class="dv">15</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(median,<span class="fl">0.5</span>,median,<span class="dv">0</span>,<span class="at">angle=</span><span class="dv">15</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(median,<span class="fl">0.02</span>,median,<span class="at">pos=</span><span class="dv">1</span>,<span class="at">offset=</span><span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>survminer 패키지의 ggsurvplot()을 이용하면 보다 보기 좋은 그래프를 얻을 수 있음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit,<span class="at">data=</span>data, <span class="at">risk.table=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>앞에서 편의상 치료군만을 대상으로 하였으나, 치료군/대조군 모두에서 생존율을 구하면 다음과 같음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span>rx,<span class="at">data=</span>anderson1)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ rx, data = anderson1)

                rx=Treatment 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    6     21       3    0.857  0.0764        0.720        1.000
    7     17       1    0.807  0.0869        0.653        0.996
   10     15       1    0.753  0.0963        0.586        0.968
   13     12       1    0.690  0.1068        0.510        0.935
   16     11       1    0.627  0.1141        0.439        0.896
   22      7       1    0.538  0.1282        0.337        0.858
   23      6       1    0.448  0.1346        0.249        0.807

                rx=Control 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    1     21       2   0.9048  0.0641      0.78754        1.000
    2     19       2   0.8095  0.0857      0.65785        0.996
    3     17       1   0.7619  0.0929      0.59988        0.968
    4     16       2   0.6667  0.1029      0.49268        0.902
    5     14       2   0.5714  0.1080      0.39455        0.828
    8     12       4   0.3810  0.1060      0.22085        0.657
   11      8       2   0.2857  0.0986      0.14529        0.562
   12      6       2   0.1905  0.0857      0.07887        0.460
   15      4       1   0.1429  0.0764      0.05011        0.407
   17      3       1   0.0952  0.0641      0.02549        0.356
   22      2       1   0.0476  0.0465      0.00703        0.322
   23      1       1   0.0000     NaN           NA           NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="censoring에-대한-논의" class="level4" data-number="2.1.2.1">
<h4 data-number="2.1.2.1" class="anchored" data-anchor-id="censoring에-대한-논의"><span class="header-section-number">2.1.2.1</span> Censoring에 대한 논의</h4>
<ol type="1">
<li>Original data</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Original data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fit1<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span>data)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fit1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = data)

      n events median 0.95LCL 0.95UCL
[1,] 21      9     23      16      NA</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Censoring 제거</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Censoring 제거</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fit2<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span><span class="fu">subset</span>(data,status<span class="sc">==</span><span class="dv">1</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fit2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = subset(data, 
    status == 1))

     n events median 0.95LCL 0.95UCL
[1,] 9      9     10       6      NA</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Time point 9와 10을 censoring에서 event로 변경</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># time=9, 10 에서 censoring을 event로 변경</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> index <span class="ot">&lt;-</span> data<span class="sc">$</span>time <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">10</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>status[index] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>fit3<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span>data2)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>fit3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = data2)

      n events median 0.95LCL 0.95UCL
[1,] 21     11     22      10      NA</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">0</span>,fit1<span class="sc">$</span>time), <span class="fu">c</span>(<span class="dv">1</span>,fit1<span class="sc">$</span>surv), <span class="at">type=</span><span class="st">"s"</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">35</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"Time"</span>, <span class="at">ylab=</span><span class="st">"Survival Probability"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="dv">0</span>,fit2<span class="sc">$</span>time), <span class="fu">c</span>(<span class="dv">1</span>,fit2<span class="sc">$</span>surv), <span class="at">type=</span><span class="st">"s"</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="dv">0</span>,fit3<span class="sc">$</span>time), <span class="fu">c</span>(<span class="dv">1</span>,fit3<span class="sc">$</span>surv), <span class="at">type=</span><span class="st">"s"</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">25</span>,<span class="dv">1</span>,<span class="fu">c</span>(<span class="st">"Original"</span>,<span class="st">"No Censoring"</span>,<span class="st">"Mutation"</span>),<span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sas-예제" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="sas-예제"><span class="header-section-number">2.1.3</span> SAS 예제</h3>
<ul>
<li>Kaplan Meier estimator for the 6 MP data</li>
</ul>
<pre><code>data one;
input time censor @@;
cards;
6 1 6 1 6 1 7 1 10 1 13 1 16 1
22 1 23 1 6 0 9 0 10 0 11 0 17 0
19 0 20 0 25 0 32 0 32 0 34 0 35 0
;
run;

proc sort data=one; by time censor; run;
proc print data=one; run;</code></pre>
<p><img src="survival_add/sas1.png" class="img-fluid"></p>
<pre><code>proc lifetest method=KM plots=(S) graphics outsurv=a;
time time*censor(0);
symbol1 v=none;
run;</code></pre>
<p><img src="survival_add/sas2.png" class="img-fluid"></p>
<p><img src="survival_add/sas3.png" class="img-fluid"></p>
<p><img src="survival_add/sas4.png" class="img-fluid"></p>
<pre><code>proc print data=a; run;</code></pre>
<p><img src="survival_add/sas5.png" class="img-fluid"></p>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Note</p>
</blockquote>
</blockquote>
<p>To get confidence intervals around the survival probabilities, you can do using the OUTSURV=option in the PROC LIFETEST option.</p>
<ul>
<li><p>OUTSURV= Data Set</p>
<ul>
<li>You can specify either the OUTSURV= option in the PROC LIFETEST statement to create an output data set containing the following columns:</li>
</ul></li>
<li><p>any specified BY variables</p></li>
<li><p>any specified STRATA variables, their values coming from either their original values or the midpoints of the stratum intervals if endpoints are used to define strata (semi-infinite intervals are labeled by their finite endpoint)</p></li>
<li><p>STRATUM, a numeric variable that numbers the strata</p></li>
<li><p>the time variable as given in the TIME statement. In the case of the product-limit estimates, it contains the observed failure or censored times. For the life-table estimates, it contains the lower endpoints of the time intervals.</p></li>
<li><p>SURVIVAL, a variable containing the survivor function estimates</p></li>
<li><p>CONFTYPE, a variable containing the name of the transformation applied to the survival time in the computation of confidence intervals (if the OUT= option is specified in the SURVIVAL statement)</p></li>
<li><p>SDF_LCL, a variable containing the lower limits of the pointwise confidence intervals for the survivor function</p></li>
<li><p>SDF_UCL, a variable containing the upper limits of the pointwise confidence intervals for the survivor function If the estimation uses the product-limit method, then the data set also contains</p></li>
<li><p><em>CENSOR</em>, an indicator variable that has a value 1 for a censored observation and a value 0 for an event observation If the estimation uses the life-table method, then the data set also contains</p></li>
<li><p>MIDPOINT, a variable containing the value of the midpoint of the time interval</p></li>
<li><p>PDF, a variable containing the density function estimates</p></li>
<li><p>PDF_LCL, a variable containing the lower endpoint of the PDF confidence interval</p></li>
<li><p>PDF_UCL, a variable containing the upper endpoint of the PDF confidence interval</p></li>
<li><p>HAZARD, a variable containing the hazard estimates</p></li>
<li><p>HAZ_LCL, a variable containing the lower endpoint of the hazard confidence interval</p></li>
<li><p>HAZ_UCL, a variable containing the upper endpoint of the hazard confidence interval</p></li>
<li><p>Each survival function contains an initial observation with the value 1 for the SDF and the value 0 for the time. The output data set contains an observation for each distinct failure time if the product-limit method is used or an observation for each time interval if the life-table method is used. The product-limit survival estimates are defined to be right continuous; that is, the estimates at a given time include the factor for the failure events that occur at that time.</p></li>
<li><p>Labels are assigned to all the variables in the output data set except the BY variable and the STRATA variable.</p></li>
<li><p>Myelomatosis data</p>
<ul>
<li>This data gives survival times for 25 patients diagnosed with myelomatosis. These patients were randomly assigned to two drug treatments as indicated by TREAT variable.</li>
<li>DUR: the time in days from the point of randomization to either death or censoring(which could occur either by loss to follow up or termination of the observation).</li>
<li>STATUS: a value of 1 for those who died and 0 for those who were censored</li>
<li>RENAL: indicator variable for normal (1) versus impaired (0) renal functioning at the time of randomization</li>
</ul></li>
</ul>
<pre><code>
data myel;
   input dur status treat renal;
   cards;
8 1 1 1
180 1 2 0
632 1 2 0 
852 0 1 0
52 1 1 1
2240 0 2 0
220 1 1 0
63 1 1 1
195 1 2 0
76 1 2 0
70 1 2 0
8 1 1 0
13 1 2 1
1990 0 2 0
1976 0 1 0
18 1 2 1
700 1 2 0
1296 0 1 0
1460 0 1 0
210 1 2 0
63 1 1 1
1328 0 1 0
1296 1 2 0
365 0 1 0
23 1 2 1
;
run;

proc sort data=myel; by dur status; run;
proc print data=myel; run;</code></pre>
<p><img src="survival_add/sas6.png" class="img-fluid"></p>
<pre><code>ods graphics on;
proc lifetest data=myel PLOTS=(S,LS,LLS) graphics;
    time dur*status(0);
    symbol1 v=none;
run;
ods graphics off;</code></pre>
<p><img src="survival_add/sas7.png" class="img-fluid"></p>
<p><img src="survival_add/sas8.png" class="img-fluid"></p>
<p><img src="survival_add/sas9.png" class="img-fluid"></p>
<p><img src="survival_add/sas10.png" class="img-fluid"></p>
<p><img src="survival_add/sas11.png" class="img-fluid"></p>
<p><br></p>
</section>
</section>
<section id="생명표-방법" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="생명표-방법"><span class="header-section-number">2.2</span> 생명표 방법</h2>
<ul>
<li><p>환자의 수가 상당히 많을 때에는 그들 개개의 생존시간을 고려하는 대신 생존시간을 몇 개의 구간으로 나누어 생존자료를 요약하는 방법이 필요</p></li>
<li><p>보험통계와 같이 데이터의 수집단계에서부터 생존시간이 1년 단위의 구간별로 나뉘어서 주어지는 경우에도 생명표 방법(life table method)이 주로 사용됨</p></li>
<li><p>생존시간을 <span class="math inline">\(k+1\)</span>개의 구간 <span class="math inline">\([t_{i-1}, t_i), \,\,\, i=1, \ldots, k+1\)</span> 으로 나눔. 이 때 <span class="math inline">\(t_0=0\)</span>이고 <span class="math inline">\(t_{k+1}=\infty\)</span></p></li>
<li><p><span class="math inline">\(i\)</span>번째 구간의 시작지점에서의 생존자수를 <span class="math inline">\(n_i\)</span>, <span class="math inline">\(i\)</span>번째 구간에서의 사망자수를 <span class="math inline">\(d_i\)</span>, <span class="math inline">\(c_i\)</span>는 <span class="math inline">\(i\)</span>번째 구간에서 중도절단된 인원수</p></li>
<li><p>구간 내에서의 생존률 <span class="math inline">\(p_i=P\)</span>(<span class="math inline">\(i\)</span>번째 구간에서 내내 생존<span class="math inline">\(|i\)</span>번째 구간의 시작점에서 생존)<span class="math inline">\(=P(T&gt;t_i|T&gt;t_{i-1})\)</span>, 구간 내 사망률은 <span class="math inline">\(q_i = 1-p_i\)</span></p></li>
</ul>
<p><br></p>
<section id="생명표의-형태" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="생명표의-형태">생명표의 형태</h4>
<p><img src="survival/d3.jpg" class="img-fluid" style="width:90.0%"></p>
<p><br></p>
<ul>
<li><p><span class="math inline">\(i\)</span>번째 구간의 시작시점에서의 인원수(위험그룹인원수) <span class="math inline">\(n_i\)</span>는 <span class="math inline">\(n_i=n_{i-1}-d_{i-1}-c_{i-1}\)</span>이며, 유효인원수(effective sample size) <span class="math inline">\(n_i'\)</span>는 구간에서의 위험그룹인원수에서 중도절단된 인원수의 <span class="math inline">\(1/2\)</span>을 뺀 <span class="math inline">\(n_i'=n_i-c_i/2\)</span></p></li>
<li><p>중도절단이 발생한 경우에는 그룹내내 위험에 노출된 것이 아니라 절반가량 노출되었다고 생각하여 이와 같이 인원수를 조정</p></li>
<li><p><span class="math inline">\(i\)</span>번째 구간에서의 사망률 <span class="math inline">\(q_i\)</span>의 추정값은 <span class="math inline">\(\hat{q}_i=d_i/n_i'\)</span>, 생존률 <span class="math inline">\(p_i\)</span>의 추정값은 <span class="math inline">\(\hat{p}_i=1-\hat{q}_i=1-d_i/n_i'\)</span></p></li>
<li><p>생존함수</p></li>
</ul>
<p><span class="math display">\[
S(t_i)=P(T&gt;t_i)
            =P(T&gt;t_1)P(T&gt;t_2|T&gt;t_1)\cdots P(T&gt;t_i|T&gt;t_{i-1})
            =p_1p_2\cdots p_i
\]</span></p>
<ul>
<li>생존함수 추정 <span class="math display">\[
\hat{S}(t_i)=\prod_{k=1}^i \hat{p}_{k}=\prod_{k=1}^i(1-d_k/n_k')
\]</span></li>
</ul>
<p>이 때 <span class="math inline">\(\hat{S}(0)=1\)</span></p>
<ul>
<li><p>그린우드의 공식 (Greenwood formula) - 분산 추정량 <span class="math display">\[
\hat{Var}(\hat{S}(t_i))=\hat{S}^2(t_i)\sum_{k=1}^i \frac{d_k}{n_k'(n_k'-d_k)}
\]</span></p></li>
<li><p><span class="math inline">\(100(1-\alpha)\%\)</span> CI</p></li>
</ul>
<p><span class="math display">\[
\hat{S}(t_i)\pm z_{1-\alpha/2}\sqrt{\hat{Var}(\hat{S}(t_i))}
\]</span></p>
<ul>
<li>Example - Survival of patients with particular form of malignant disease</li>
</ul>
<p><img src="survival/ex0.jpg" class="img-fluid" style="width:90.0%"></p>
<ul>
<li>Survival curve</li>
</ul>
<p><img src="survival/ex0.png" class="img-fluid" style="width:90.0%"></p>
</section>
<section id="sas-예제-1" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="sas-예제-1"><span class="header-section-number">2.2.1</span> SAS 예제</h3>
<ul>
<li>Survival of patients with particular form of malignant disease</li>
</ul>
<pre><code>data one;
input year failure number @@;
cards;
0.5 1 90
1.5 1 76
2.5 1 51
3.5 1 25    3.5 0 12
4.5 1 20    4.5 0 5
5.5 1 7     5.5 0 9
6.5 1 4     6.5 0 9
7.5 1 1     7.5 0 3
8.5 1 3     8.5 0 5
9.5 1 2     9.5 0 5
10.5 1 21  10.5 0 26
;
run;

proc print data=one; run;</code></pre>
<p><img src="survival_add/sas12.png" class="img-fluid"></p>
<pre><code>proc lifetest method=LT plot=(S)graphics   
      intervals=1,2,3,4,5,6,7,8,9,10;
time year*failure(0);
freq number;
run;</code></pre>
<p><img src="survival_add/sas13.png" class="img-fluid"></p>
<p><img src="survival_add/sas14.png" class="img-fluid"></p>
<p><br></p>
</section>
</section>
<section id="생존분포-비교" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="생존분포-비교"><span class="header-section-number">2.3</span> 생존분포 비교</h2>
<ul>
<li><p>가정</p>
<ul>
<li>첫 번째 그룹의 생존시간 <span class="math inline">\(T_{11}, T_{12}, \ldots, T_{1n_1}\)</span>은 서로 독립이며 동일한 생존함수 <span class="math inline">\(S_1\)</span>을 갖고, 중도절단 시간 <span class="math inline">\(C_{11}, C_{12}, \ldots, C_{1n_1}\)</span>도 서로 독립이며 동일한 분포함수 <span class="math inline">\(G_1\)</span>을 가짐</li>
<li>마찬가지로 두 번째 그룹의 생존시간 <span class="math inline">\(T_{21}, T_{22}, \ldots, T_{2n_2}\)</span>은 서로 독립이며 동일한 생존함수 <span class="math inline">\(S_2\)</span>을 갖고, 중도절단 시간 <span class="math inline">\(C_{21}, C_{22}, \ldots, C_{2n_2}\)</span>도 서로 독립이며 동일한 분포함수 <span class="math inline">\(G_2\)</span>를 가짐</li>
</ul></li>
<li><p>관측값의 형태</p>
<ul>
<li><p>그룹 1: <span class="math inline">\((x_{11},\delta_{11}), (x_{12},\delta_{12}), \ldots, (x_{1n_1},\delta_{1n_1})\)</span></p></li>
<li><p>그룹 2: <span class="math inline">\((x_{21},\delta_{21}), (x_{22},\delta_{22}), \ldots, (x_{2n_1},\delta_{2n_2})\)</span></p>
<p>여기서 <span class="math inline">\(x_{ij}=min(T_{ij},C_{ij})\)</span>이고 <span class="math inline">\(\delta_{ij}\)</span>는 중도절단을 나타내는 가변수(<span class="math inline">\(\delta_{ij}=0\)</span>: 중도절단)</p></li>
</ul></li>
</ul>
<p><br></p>
<section id="특정시점에서의-생존률-비교" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="특정시점에서의-생존률-비교">특정시점에서의 생존률 비교</h4>
<ul>
<li><p>가설 <span class="math display">\[H_0 : S_1(t_k )= S_2(t_k) \,\,\, vs. \,\,\, H_1 : S_1(t_k) \ne S_2(t_k)\]</span></p></li>
<li><p>검정통계량</p>
<p><span class="math display">\[Z=\frac{\hat{S}_1(t_k)-\hat{S}_2(t_k)}{\sqrt{\hat{Var}(\hat{S}_1(t_k))+\hat{Var}(\hat{S}_2(t_k))}} \sim N(0,1)\]</span></p></li>
</ul>
<p><br></p>
</section>
<section id="생존함수의-총괄적-비교" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="생존함수의-총괄적-비교">생존함수의 총괄적 비교</h4>
<ul>
<li><p>가설 <span class="math display">\[H_0 : S_1=S_2 \,\,\, vs. \,\,\, H_1 : S_1 \ne S_2\]</span></p></li>
<li><p>두 생존분포의 비교에 주로 사용되는 기법은 Mantel-Haenszel의 로그 순위 검정법(log-rank test)</p></li>
<li><p><span class="math inline">\(t_1 &lt; t_2 &lt; \cdots &lt; t_k\)</span>를 두 그룹의 자료를 섞었을 때 관측된 사망시간을 순서대로 놓은 것이라고 하면, 모든 <span class="math inline">\(t_i\)</span>에서 다음과 같은 <span class="math inline">\(2\)</span>차원 분할표를 작성함</p></li>
</ul>
<p><img src="survival/lo5.jpg" class="img-fluid" style="width:90.0%"></p>
<p><br></p>
<ul>
<li><p>검정통계량 <span class="math display">\[T=\frac{\left(  \sum_{i=1}^k (d_{1i}-E_{1i})    \right)^2}{\sum_{i=1}^k V_{1i}} \sim \chi(1)\]</span></p>
<p>여기서 <span class="math inline">\(E(d_{1i})=E_{1i}=n_{1i}d_i/n_i\)</span>, <span class="math inline">\(Var(d_{i1})=V_{1i}=\frac{n_{1i}n_{2i}}{n_1-1}\frac{d_i(n_i-d_i)}{n_i^2}\)</span></p></li>
<li><p>로그 순위 통계량은 각 시점에서 동일한 비중을 가짐. 따라서 대안으로 다음과 같은 각 시점의 가중치를 다르게 한 통계량을 고려할 수 있음</p></li>
</ul>
<p><span class="math display">\[T=\frac{\left(  \sum_{i=1}^k w_i(d_{1i}-E_{1i})    \right)^2}{\sum_{i=1}^k w_i^2V_{1i}} \sim \chi(1)\]</span></p>
<ul>
<li><p><span class="math inline">\(w=1\)</span>인 경우 로그 순위 통계량이 됨</p></li>
<li><p><span class="math inline">\(w_i=n_i\)</span>이면 Gehan의 검정통계량이 되며, 이때 가중값은 각 시점에서 위험에 처해 있는 인원수에 비례함</p></li>
<li><p>두 그룹의 위험률의 비가 상수일 때 즉, 교차하지 않을 때 로그 순위 검정법이 선호되며, 그렇지 않은 경우에는 다른 가중치를 주는 방법을 선호</p></li>
<li><p><span class="math inline">\(k(\ge 3)\)</span>개의 그룹이 모두 동일한 생존분포를 가지는지 알아내기 위한 검정법도 존재. 크루스칼-왈리스 검정법을 중도절단자료의 경우로 확장시킨 형태와 유사</p></li>
</ul>
<p><br></p>
</section>
<section id="comparison-of-survival-curve" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="comparison-of-survival-curve"><span class="header-section-number">2.3.1</span> Comparison of Survival Curve</h3>
<ul>
<li>Survival curve: <span class="math inline">\(S_1, \cdots, S_r\)</span></li>
<li>Compare curve <span class="math inline">\(S_1, \cdots, S_r\)</span> at <span class="math inline">\(t=t_0\)</span>, <span class="math inline">\(t\ge 0\)</span></li>
</ul>
<p><span class="math display">\[
H_0: S_1(t_0)=S_2(t_0)=\cdots=S_r(t_0)
\]</span></p>
<section id="comparison-of-two-groups" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="comparison-of-two-groups">Comparison of two groups</h4>
<p><span class="math display">\[
H_0: S_1(t_0)=S_2(t_0) \,\,\, or \,\,\, \lambda_1 (t)=\lambda_2(t) \,\,\, or \,\,\, p_1(t)=p_2(t)
\]</span></p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: the survival times are equally distributed in two groups or there is no difference between survival times of the two group.</p></li>
<li><p>Can be tested using the fact taht <span class="math inline">\(\hat{S}_i(t_0)\)</span> are asymptotically independent with mean <span class="math inline">\(S_i(t_0)\)</span> ans variance <span class="math inline">\(\sigma_{\hat{S}_i(t_0)}^2\)</span>.</p></li>
<li><p>Can use the fact that</p></li>
</ul>
<ol type="1">
<li><p><span class="math inline">\(\sqrt{n}(\hat{S}(t_0)-S(t_0))\sim AN(0, \sigma_{\hat{S}_i(t_0)}^2)\)</span>, <span class="math inline">\(\hat{\sigma}_{\hat{S}_i(t_0)}^2\)</span>: Greenwood’s formula</p></li>
<li><p>There exists <span class="math inline">\(\sigma_{\hat{S}_i(t_0)}^2\)</span> such that <span class="math inline">\(\hat{\sigma}_{\hat{S}_i(t_0)}^2 \rightarrow^p \sigma_{\hat{S}_i(t_0)}^2)\)</span></p></li>
<li><p><span class="math inline">\(\hat{S}_1, \hat{S}_2, \cdots, \hat{F}_r\)</span> are mutually independent.</p></li>
</ol>
<ul>
<li><p>To derive a <span class="math inline">\(\chi^2\)</span> test of <span class="math inline">\(H_0\)</span>, the data are combined.</p></li>
<li><p>Failure times <span class="math inline">\(t_1&lt;t_2&lt;\cdots &lt;t_k\)</span>.</p></li>
</ul>
<p><img src="survival_add2/f1.png" class="img-fluid"></p>
<p><img src="survival_add2/f2.png" class="img-fluid"></p>
<ul>
<li><p>Let <span class="math inline">\(T_i\)</span> be survival time for an individual in population <span class="math inline">\(i\)</span>.</p></li>
<li><p><span class="math inline">\(\lambda_{ij}=P(T_i=t_j|T_i\ge t_j)\)</span>: Hazard of failure at <span class="math inline">\(t_j\)</span> or conditional failure probability at <span class="math inline">\(t_j\)</span>, <span class="math inline">\(i=1, 2, \cdots, r\)</span>: population, , <span class="math inline">\(j=1, 2, \cdots, k\)</span>: failure time.</p></li>
<li><p>Want to test equality of survival functions or</p></li>
</ul>
<p><span class="math display">\[
H_0: \lambda_{1j}=\lambda_{2j}=\cdots =\lambda_{rj}, \,\,\, j=1,2,\cdots,K
\]</span></p>
<ul>
<li>Let <span class="math inline">\(H(t)\)</span> be complete history of failure and censoring of the study up to time <span class="math inline">\(t^-\)</span>.</li>
<li>Conditional on censoring and failure experience up to <span class="math inline">\(t_j\)</span> and under <span class="math inline">\(H_0: \lambda_{1j}=\lambda_{2j}=\cdots =\lambda_{rj}=\lambda_j\)</span>,</li>
</ul>
<p><span class="math display">\[
P(d_{1j},\cdots, d_{rj}|H(t), H_0)= \Pi_{i=1}^r \bigg[\binom{n_{ij}}{d_{ij}}\lambda_j^{d_{ij}}(1-\lambda_j)^{n_{ij}-d_{ij}}  \bigg]=\Pi_{i=1}^r \bigg[\binom{n_{ij}}{d_{ij}}\lambda_j^{d_{j}}(1-\lambda_j)^{n_{j}-d_{j}}  \bigg]
\]</span></p>
<ul>
<li>Conditional distribution <span class="math inline">\(d_j\)</span></li>
</ul>
<p><span class="math display">\[
P(d_j|H(t), H_0) = \binom{n_j}{d_j}\lambda_j^{d_j}(1-\lambda_j)^{n_j-d_j}
\]</span></p>
<ul>
<li>The conditional distribution for <span class="math inline">\(d_{1j},\cdots, d_{rj}\)</span>, given <span class="math inline">\(d_j\)</span> is hyper geometric distribution.</li>
</ul>
<p><span class="math display">\[
P(d_{1j},\cdots, d_{rj}|H(t),H_0,d_j)=\frac{P(d_{1j},\cdots, d_{rj}|H(t),H_0)}{P(d_j|H(t),H_0)}=\frac{\Pi_{i=1}^r \binom{n_{ij}}{d_{ij}}}{\binom{n_{i}}{d_{i}}}
\]</span></p>
</section>
<section id="note" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="note">Note</h4>
<ul>
<li>By conditioning, nuisance parameter <span class="math inline">\(\lambda_j\)</span> can be deleted.</li>
<li>Conditional mean and variance of <span class="math inline">\(d_{ij}\)</span> are well known.</li>
</ul>
<p><span class="math display">\[
E(d_{ij})=n_{ij}\frac{d_j}{n_j}=w_{ij}
\]</span></p>
<p><span class="math display">\[
Var(d_{ij})=d_j(n_j-d_j)n_{ij}(n_j-n_{ij})/(n_j^2(n_j-1))=(v_j)_{il}
\]</span></p>
<p><span class="math display">\[
Cov(d_{ij},d_{lj})=-d_j(n_j-d_j)n_{ij}n_{lj}/(n_j^2(n_j-1))=(v_j)_{il}
\]</span></p>
<p><span class="math display">\[
\underline{v}_j = \begin{bmatrix} d_{1j}-w_{1j}\\
\vdots \\
d_{rj}-w_{rj}
\end{bmatrix}_{r\times 1}
\]</span></p>
<ul>
<li>Assume the <span class="math inline">\(K\)</span> tables are independent then</li>
</ul>
<p><span class="math display">\[
\underline{v}=\sum_{j=1}^K \underline{v}_j= \begin{bmatrix} \sum_{j=1}^Kd_{1j}-\sum_{j=1}^Kw_{1j}\\
\vdots \\
\sum_{j=1}^Kd_{rj}-\sum_{j=1}^Kw_{rj}
\end{bmatrix}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\underline{v}_j\)</span> is not of full rank since we have at least one constraint namely <span class="math inline">\(\sum_{i=1}^r d_{ij}=d_j\)</span> (constraint; given)</p></li>
<li><p><span class="math inline">\(V_j=((V_j){il})_{r\times r}\)</span>: Variance-covariane matrix of <span class="math inline">\(V_j\)</span>, <span class="math inline">\(j=1,\cdots, K\)</span></p></li>
<li><p><span class="math inline">\(V_{r\times r}=\sum_{j=1}^k V_j\)</span>, (Rank=<span class="math inline">\(r-1\)</span>)</p></li>
<li><p>Let <span class="math inline">\(V^{-1}\)</span> be a generalized inverse of <span class="math inline">\(V\)</span>. Then the test statistic <span class="math inline">\(T\)</span> is</p></li>
</ul>
<p><span class="math display">\[
T=v^TV^{-1}v, \,\,\, r(V)=r-1
\]</span></p>
<ul>
<li>Under <span class="math inline">\(H_0\)</span> and some regularity conditions,</li>
</ul>
<p><span class="math display">\[
T \sim Asymptotic \,\,\, \chi_{r-1}^2 \,\,\, distribution \,\,\, under\,\,\ H_0
\]</span></p>
<ul>
<li><p>The test based on <span class="math inline">\(T\)</span> is called the “generalized log-rank test.”</p></li>
<li><p>If <span class="math inline">\(r=2\)</span> (i.e., two groups, rank=1)</p></li>
</ul>
<p><span class="math display">\[
V^{-1}= \begin{bmatrix} [\sum_{j=1}^k \frac{d_j(n_j-d_j)n_{1j}n_{2j}}{n_j^2(n_j-1)}]^{-1} &amp; 0\\
0 &amp; 0
\end{bmatrix}
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; is a generalized inverse of <span class="math inline">\(V\)</span>.</p>
<ul>
<li>Then Mantel-Haenzel statistic or log-rank test statistic is</li>
</ul>
<p><span class="math display">\[
T=\frac{[\sum_{j=1}^k d_{1j}-E(d_{1j})]^2}{\sum_{j=1}^k  Var(d_{1j})}=\frac{[\sum_{j=1}^k (d_{1j}-\frac{n_{1j}d_j}{n_j})]^2}{\sum_{j=1}^k \frac{d_j(n_j-d_j)n_{1j}n_{2j}}{n_j^2(n_j-1)}} \sim \chi_1^2
\]</span></p>
<ul>
<li>Failure and groups are independent given time, survival distributions are equal (access time)</li>
</ul>
</section>
<section id="note-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="note-1">Note</h4>
<ol type="1">
<li><p>로그순위 검정법은 실제로 각 환자들의 구체적인 생존시간 <span class="math inline">\(t_i\)</span>가 직접 계산에 사용되지 않고, 생존시간 또는 절단시간들의 순위(rank order)로부터 알게 되는 <span class="math inline">\(n_{1i}, n_{2i}, d_i, n_i-d_i\)</span>가 계산에 사용됨</p></li>
<li><p>이벤트 발생 지점은 모두 독립이므로 각 이벤트 발생 시점에서의 통계량을 합하여 로그순위 검정통계량을 만듦</p></li>
</ol>
</section>
<section id="wilcoxon-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="wilcoxon-test">Wilcoxon test</h4>
<p><span class="math display">\[
Q=\frac{[\sum_{j=1}^k w_j(d_{1j}-E(d_{1j}))]^2}{\sum_{j=1}^k w_j^2\cdot Var(d_{1j})}
\]</span></p>
<ul>
<li>According to the values given to the weight <span class="math inline">\(w_j\)</span>, one obtain different tests.
<ul>
<li><span class="math inline">\(w_j=1, Q=Q_{MH}\)</span>: Mantel-Haenszel (1959), log-rank test</li>
<li><span class="math inline">\(w_j=n_j, Q=Q_{G}\)</span>: Gehan (1965)</li>
<li><span class="math inline">\(w_j=\sqrt{n_j}, Q=Q_{TW}\)</span>: Tarone and Ware (1977)</li>
</ul></li>
<li><span class="math inline">\(Q_{MH}\)</span> gives constant weight.</li>
<li><span class="math inline">\(Q_G\)</span> tends to weight the early differences more heavily than the last ones.</li>
</ul>
<ol type="1">
<li>log-rank test (<span class="math inline">\(Q_{MH}\)</span>)</li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - gives constant weight to the differences between the two survival experiences at each of the <span class="math inline">\(J\)</span>death times.</p>
<p>&nbsp; &nbsp; &nbsp; - long term effect or is sensitive to differences in later in times.</p>
<p>&nbsp; &nbsp; &nbsp; - is sensitive to exposures with a constant relative risk (proportional hazards effect).</p>
<p>&nbsp; &nbsp; &nbsp; - is closely related to tests for differences between two groups that are performed within the framework of Cox’s proportional hazards model.</p>
<ol start="2" type="1">
<li>Wilcoxon test (<span class="math inline">\(Q_G\)</span>)</li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - tends to weight the early differences more heavily than the late ones.</p>
<p>&nbsp; &nbsp; &nbsp; - powerful in detecting the effects of short-term effect or short term risks.</p>
<p>&nbsp; &nbsp; &nbsp; - less sensitive than the log-rank test to differences between groups that occur at later points in time.</p>
<p>&nbsp; &nbsp; &nbsp; - 각 사망시점에서 두 군의 총 대상자수로 가중하여 합하는 것</p>
<p>&nbsp; &nbsp; &nbsp; - 각 시점에서 두 군의 총 대상자는 <span class="math inline">\(n_j\)</span>이며, 이는 시간이 지남에 따라 줄어듬</p>
<p>&nbsp; &nbsp; &nbsp; - is more powerful than the log-rank test in situations where event times have log-normal distributions with common variance but different means in the two groups.</p>
<ol start="3" type="1">
<li>Tarone and Ware test (<span class="math inline">\(Q_{TW}\)</span>)</li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - Tarone and Ware (1977) argue that Gehan’s weighting scheme may imply some loss of sensitivity when the distribution of censoring times widely differ in the two groups to be compared.</p>
<p>&nbsp; &nbsp; &nbsp; - In trying to overcome this drawback they suggested their own weights which appear to be a compromise between used by <span class="math inline">\(Q_{MN}\)</span> and <span class="math inline">\(Q_G\)</span>.</p>
</section>
<section id="note-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="note-2">Note</h4>
<ol type="1">
<li><span class="math inline">\(\sum_j w_j(d_{1i}-E(d_{1i}))\)</span> is powerless for the case of crossing hazards. (i.e., not particularly good at detecting differences when survival curves cross)</li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - i.e., they are powerful when one risk is greater than the other at all times.</p>
<p>&nbsp; &nbsp; &nbsp; - Otherwise some terms in this term are positive, and some other terms are negative, then they cancel each other out.</p>
<ol start="2" type="1">
<li>Some cancer treatments are thought to have cured patients within a short time of initiation.</li>
</ol>
<p>&nbsp; &nbsp; &nbsp; - Then, instead of all patients having the same hazard, the cure model assumes that an unknown proportion (<span class="math inline">\(1-\pi\)</span>) are still at risk whereas the remaining proportion (<span class="math inline">\(\pi\)</span>) have essentially no risk.</p>
<p>&nbsp; &nbsp; &nbsp; - If the aim of the study to compare the cure proportion <span class="math inline">\(\pi\)</span>’s, then neither the generalized Wilcoxon nor log-rank tests are appropriate.</p>
<p>&nbsp; &nbsp; &nbsp; - Then at a time point <span class="math inline">\(t\)</span> far enough for the curves to leave off, compare the estimated survival rates and compute</p>
<p><span class="math display">\[
Z=\frac{\hat{S}_1(t)-\hat{S}_2(t)}{\sqrt{Var(\hat{S}_1(t))+Var(\hat{S}_2(t))}} \sim N(0,1)
\]</span></p>
<p>&nbsp; &nbsp; &nbsp; - <span class="math inline">\(\hat{S}_i(t)\)</span>: from Kaplan-Meier procedure</p>
</section>
<section id="example" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example">Example</h4>
<p><img src="survival_add2/f3.png" class="img-fluid"></p>
<p><img src="survival_add2/f4.png" class="img-fluid"></p>
<p><img src="survival_add2/f5.png" class="img-fluid"></p>
<p><img src="survival_add2/f6.png" class="img-fluid"></p>
<p><img src="survival_add2/f7.png" class="img-fluid"></p>
<p><img src="survival_add2/f8.png" class="img-fluid"></p>
<p><br></p>
</section>
</section>
<section id="r-예제-1" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="r-예제-1"><span class="header-section-number">2.3.2</span> R 예제</h3>
<section id="두-군-간의-km-생존곡선-비교" class="level4" data-number="2.3.2.1">
<h4 data-number="2.3.2.1" class="anchored" data-anchor-id="두-군-간의-km-생존곡선-비교"><span class="header-section-number">2.3.2.1</span> 두 군 간의 KM 생존곡선 비교</h4>
<ul>
<li><p>로그순위검정(log-rank test)은 2개의 생존곡선이 통계적으로 동등한지를 검정하는 것이며, 2개의 생존곡선을 전체적으로 비교하기 위해 각각의 시간에서 두 군의 기댓값과 관찰값의 차이를 구하여 검정통계량을 계산하는 카이제곱검정의 일종이라고 할 수 있음</p></li>
<li><p>autoReg 패키지의 anderson1 데이터를 예로 검정통계량을 구해보자. 먼저 두 군의 비교를 위해 survfit 함수를 이용</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span>rx,<span class="at">data=</span>anderson1)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ rx, data = anderson1)

                rx=Treatment 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    6     21       3    0.857  0.0764        0.720        1.000
    7     17       1    0.807  0.0869        0.653        0.996
   10     15       1    0.753  0.0963        0.586        0.968
   13     12       1    0.690  0.1068        0.510        0.935
   16     11       1    0.627  0.1141        0.439        0.896
   22      7       1    0.538  0.1282        0.337        0.858
   23      6       1    0.448  0.1346        0.249        0.807

                rx=Control 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    1     21       2   0.9048  0.0641      0.78754        1.000
    2     19       2   0.8095  0.0857      0.65785        0.996
    3     17       1   0.7619  0.0929      0.59988        0.968
    4     16       2   0.6667  0.1029      0.49268        0.902
    5     14       2   0.5714  0.1080      0.39455        0.828
    8     12       4   0.3810  0.1060      0.22085        0.657
   11      8       2   0.2857  0.0986      0.14529        0.562
   12      6       2   0.1905  0.0857      0.07887        0.460
   15      4       1   0.1429  0.0764      0.05011        0.407
   17      3       1   0.0952  0.0641      0.02549        0.356
   22      2       1   0.0476  0.0465      0.00703        0.322
   23      1       1   0.0000     NaN           NA           NA</code></pre>
</div>
</div>
<ul>
<li>결과를 보면 치료군 21명 중 23주째의 생존율은 0.448이고, 대조군의 23주째 생존율은 0이다. 두 군 간 생존곡선은 다음과 같음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit1,<span class="at">data=</span>anderson1,<span class="at">pval=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>그래프에서 보이는 p값이 로그순위검정의 p값으로, 다음과 같은 R 명령어로 구할 수 있음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span>rx,<span class="at">data=</span>anderson1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(time, status) ~ rx, data = anderson1)

              N Observed Expected (O-E)^2/E (O-E)^2/V
rx=Treatment 21        9     19.3      5.46      16.8
rx=Control   21       21     10.7      9.77      16.8

 Chisq= 16.8  on 1 degrees of freedom, p= 4e-05 </code></pre>
</div>
</div>
<ul>
<li>로그순위검정 통계량은 16.8이며 이 통계량은 자유도 1인 카이제곱분포를 따르고 p값은 매우 낮으므로 두 곡선은 동등하지 않다고 할 수 있음</li>
</ul>
<p><br></p>
</section>
<section id="세-군-이상인-경우의-로그순위검정" class="level4" data-number="2.3.2.2">
<h4 data-number="2.3.2.2" class="anchored" data-anchor-id="세-군-이상인-경우의-로그순위검정"><span class="header-section-number">2.3.2.2</span> 세 군 이상인 경우의 로그순위검정</h4>
<ul>
<li><p>세 군 이상인 경우의 로그순위검정도 survdiff() 함수를 시행할 수 있음</p></li>
<li><p>이때 로그순위검정의 귀무가설은 ‘모든 생존곡선이 동등하다’임</p></li>
<li><p>예제로 survival 패키지의 대장암 데이터를 사용하며, stage B/C의 대장암 환자 데이터로 관찰군(Obs)과 Lev, Lev+5FU, 세 군의 생존을 비교함</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cancer,<span class="at">package=</span><span class="st">"survival"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span>rx,<span class="at">data=</span>colon)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(time, status) ~ rx, data = colon)

             N Observed Expected (O-E)^2/E (O-E)^2/V
rx=Obs     630      345      299      7.01     10.40
rx=Lev     620      333      295      4.93      7.26
rx=Lev+5FU 608      242      326     21.61     33.54

 Chisq= 33.6  on 2 degrees of freedom, p= 5e-08 </code></pre>
</div>
</div>
<ul>
<li>통계량은 33.6(자유도 2)으로 매우 적은 p값을 보임</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>fit2<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(time,status)<span class="sc">~</span>rx,<span class="at">data=</span>colon)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit2,<span class="at">data=</span>colon,<span class="at">pval=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="로그순위검정의-대안" class="level4" data-number="2.3.2.3">
<h4 data-number="2.3.2.3" class="anchored" data-anchor-id="로그순위검정의-대안"><span class="header-section-number">2.3.2.3</span> 로그순위검정의 대안</h4>
<ul>
<li><p>로그순위검정의 대안으로 여러 가지 통계적인 방법들이 제안됨</p></li>
<li><p>이 방법들은 통계량을 구할 때 가중치가 주어짐</p></li>
</ul>
<p><span class="math display">\[T=\frac{\left(  \sum_{i=1}^k w_i(d_{1i}-E_{1i})    \right)^2}{\sum_{i=1}^k w_i^2V_{1i}} \sim \chi(1)\]</span></p>
<ul>
<li><p>Wilcoxon, Tarone-Ware, Peto, Flemington-Harrington 검정등이 알려져 있으며, 방법에 따라 초기 실패에 더 가중치를 주기도 함</p></li>
<li><p>가중값에 따른 검정방법</p></li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Test Statistic</th>
<th style="text-align: center;">가중값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Log rank</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Wilcoxon</td>
<td style="text-align: center;"><span class="math inline">\(n_i\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tarone-Ware</td>
<td style="text-align: center;"><span class="math inline">\(\sqrt{n_i}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Peto</td>
<td style="text-align: center;"><span class="math inline">\(s(t_i)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Flemington-Harrington</td>
<td style="text-align: center;"><span class="math inline">\(S(t_i )^p \times (1-S(t_i ))^q\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>pancreatic2 데이터는 췌장암 환자의 생존에 관한 데이터로 asaur 패키지에 포함되어 있음</p></li>
<li><p>데이터에서 pfs는 병기의 진행이 없는 생존(progression free survival)을 나타내며, 병기에 따른 생존곡선을 비교해보고자 함</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(pancreatic2,<span class="at">package=</span><span class="st">"asaur"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(pfs)<span class="sc">~</span>stage,<span class="at">data=</span>pancreatic2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(pfs) ~ stage, data = pancreatic2)

          N Observed Expected (O-E)^2/E (O-E)^2/V
stage=LA  8        8     12.3      1.49      2.25
stage=M  33       33     28.7      0.64      2.25

 Chisq= 2.2  on 1 degrees of freedom, p= 0.1 </code></pre>
</div>
</div>
<ul>
<li>로그순위검정에서 국소진행암(locally advanced, LA)과 전이된 암(metastatic, M)의 pfs 생존곡선이 동등하지 않다는 근거는 없다고 할 수 있음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(pfs)<span class="sc">~</span>stage,<span class="at">data=</span>pancreatic2)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit4, <span class="at">data=</span>pancreatic2, <span class="at">pval=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>이 데이터에서 survdiff( ) 함수에 rho=1로 옵션을 주어 검정하면, Peto의 수정방법으로 검정함</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(pfs)<span class="sc">~</span>stage,<span class="at">data=</span>pancreatic2,<span class="at">rho=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(pfs) ~ stage, data = pancreatic2, rho = 1)

          N Observed Expected (O-E)^2/E (O-E)^2/V
stage=LA  8     2.34     5.88     2.128      4.71
stage=M  33    18.76    15.22     0.822      4.71

 Chisq= 4.7  on 1 degrees of freedom, p= 0.03 </code></pre>
</div>
</div>
<ul>
<li>검정 결과 p값은 0.03으로 유의함
<ul>
<li>이 검정방법은 초기 생존시간에 가중치를 주기 때문에 국소진행암이 초기 생존에 유리한 것으로 판단됨</li>
<li>생존곡선을 그릴 때 ggsurvplot( )함수의 log.rank.weights 인수를 조절하면 이 값을 그래프에 나타낼 수 있음</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit4,<span class="at">data=</span>pancreatic2,<span class="at">pval=</span><span class="cn">TRUE</span>,<span class="at">log.rank.weights=</span><span class="st">"S1"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="층화된-로그순위검정" class="level4" data-number="2.3.2.4">
<h4 data-number="2.3.2.4" class="anchored" data-anchor-id="층화된-로그순위검정"><span class="header-section-number">2.3.2.4</span> 층화된 로그순위검정</h4>
<ul>
<li><p>두 군 간의 생존곡선을 비교할 때, 다른 공변량을 보정해야 할 경우 층화된 비례위험모형을 사용할 수 있으며, 보정할 공변량의 수준이 적을 때는 층화된 로그순위검정을 할 수 있음</p></li>
<li><p>층화된 로그순위검정의 귀무가설은 <span class="math inline">\(H_{0}: h_{0j}(t)=h_{1j(t)} \,\,\,for \,\,\ j=1,2, \cdots ,G\)</span></p></li>
<li><p>이때 두 번째 변수의 각 수준에 대해 스코어 통계량 <span class="math inline">\(U_{0g}\)</span>와 분산 <span class="math inline">\(V_{0g}\)</span>를 계산함</p></li>
<li><p>검정통계량</p></li>
</ul>
<p><span class="math display">\[
\chi^2 = \frac{(\sum_{g=1}^G V_{0g})^2}{\sum_{g=1}^G V_{0g}^2}
\]</span></p>
<ul>
<li><p>치료한 병원, 나이군, 성별 등을 층화할 변수로 사용할 수 있음</p></li>
<li><p>assur 패키지의 pharmcoSmoking은 금연 치료로 패치만을 사용한 군과 복합약물치료를 한 군 간의 재발(다시 흡연)까지 걸린 시간에 관한 데이터</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(pharmacoSmoking,<span class="at">package=</span><span class="st">"asaur"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(ttr,relapse)<span class="sc">~</span>grp,<span class="at">data=</span>pharmacoSmoking)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(ttr, relapse) ~ grp, data = pharmacoSmoking)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
grp=combination 61       37     49.9      3.36      8.03
grp=patchOnly   64       52     39.1      4.29      8.03

 Chisq= 8  on 1 degrees of freedom, p= 0.005 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">=</span><span class="fu">survfit</span>(<span class="fu">Surv</span>(ttr,relapse)<span class="sc">~</span>grp,<span class="at">data=</span>pharmacoSmoking)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit,<span class="at">data=</span>pharmacoSmoking,<span class="at">pval=</span><span class="cn">TRUE</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="fl">0.7</span>,<span class="fl">0.85</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>이때 나이의 영향을 보정하기 위해 ageGroup2를 사용하여 층화된 로그순위검정을 하면 다음과 같음</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(ttr,relapse)<span class="sc">~</span>grp<span class="sc">+</span><span class="fu">strata</span>(ageGroup2),<span class="at">data=</span>pharmacoSmoking)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(ttr, relapse) ~ grp + strata(ageGroup2), 
    data = pharmacoSmoking)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
grp=combination 61       37     49.1      2.99      7.03
grp=patchOnly   64       52     39.9      3.68      7.03

 Chisq= 7  on 1 degrees of freedom, p= 0.008 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>labs<span class="ot">=</span><span class="fu">c</span>(<span class="st">"Comibnation, age 21-49"</span>,<span class="st">"Combination, age 50+"</span>,<span class="st">"patchOnly,</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="st">age 21-49"</span>,<span class="st">"patchOnly,age 50+"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(ttr,relapse)<span class="sc">~</span>grp<span class="sc">+</span><span class="fu">strata</span>(ageGroup2), <span class="at">data=</span>pharmacoSmoking), <span class="at">data=</span>pharmacoSmoking,<span class="at">legend=</span><span class="fu">c</span>(<span class="fl">0.7</span>,<span class="fl">0.85</span>),<span class="at">legend.labs=</span>labs,<span class="at">pval=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-nonpara_files/figure-html/c27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sas-예제-2" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="sas-예제-2"><span class="header-section-number">2.3.3</span> SAS 예제</h3>
<ul>
<li>Example</li>
</ul>
<p><img src="survival_add/sas15.png" class="img-fluid"></p>
<pre><code>data one;
   input time censor group @@;
   cards;
  2 1 1  6 0 1   9 1 1  12 1 1  15 1 1 
  5 1 2  9 1 2  10 0 2  14 1 2  20 0 2
   ;
run;

ods graphics on;
proc lifetest method=KM plots=(s) graphics;
   time time*censor(0);
   strata group;
   symbol1 v=none color=black line=1;
   symbol2 v=none color=black line=2;
run;
ods graphics off;</code></pre>
<p><img src="survival_add/sas16.png" class="img-fluid"></p>
<p><img src="survival_add/sas17.png" class="img-fluid"></p>
<ul>
<li>Log rank test for the 6-MP data</li>
</ul>
<pre><code>data six_mp;
   input time censor group @@;
   cards;
6 1 1  6 1 1  6 1 1  7 1 1  10 1 1  13 1 1  16 1 1
22 1 1  23 1 1  6 0 1  9 0 1  10 0 1  11 0 1  17 0 1
19 0 1  20 0 1  25 0 1  32 0 1  32 0 1  34 0 1  35 0 1
1 1 2  1 1 2  2 1 2  2 1 2  3 1 2  4 1 2  4 1 2  5 1 2   5 1 2    
8 1 2  8 1 2  8 1 2  8 1 2  11 1 2  11 1 2  12 1 2
12 1 2  15 1 2  17 1 2  22 1 2  23 1 2  
;
run;

ods graphics on;
proc lifetest method=KM plots=(s) graphics;
   time time*censor(0);
   strata group;
   symbol1 v=none color=black line=1;
   symbol2 v=none color=black line=2;
run;
ods graphics off;</code></pre>
<p><img src="survival_add/sas18.png" class="img-fluid"></p>
<p><img src="survival_add/sas19.png" class="img-fluid"></p>
<p><br></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-survival.html" class="pagination-link" aria-label="Survival Analysis?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Survival Analysis?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-Cox.html" class="pagination-link" aria-label="Cox 비례위험모형(PH model)">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Cox 비례위험모형(PH model)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>