<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Tidyverse 활용 | Insurance Claims Data Analysis with R</title>
  <meta name="description" content="This is a R manual for analysis of insurance claims data" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Tidyverse 활용 | Insurance Claims Data Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a R manual for analysis of insurance claims data" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Tidyverse 활용 | Insurance Claims Data Analysis with R" />
  
  <meta name="twitter:description" content="This is a R manual for analysis of insurance claims data" />
  

<meta name="author" content="Jin Hyun Nam" />


<meta name="date" content="2021-12-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter9.html"/>
<link rel="next" href="chapter11.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Claims Data Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>머리말</a></li>
<li class="chapter" data-level="1" data-path="chapter1.html"><a href="chapter1.html"><i class="fa fa-check"></i><b>1</b> R이란?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chapter1.html"><a href="chapter1.html#r-설치"><i class="fa fa-check"></i><b>1.1</b> R 설치</a></li>
<li class="chapter" data-level="1.2" data-path="chapter1.html"><a href="chapter1.html#r-프로그램의-구성"><i class="fa fa-check"></i><b>1.2</b> R 프로그램의 구성</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="chapter1.html"><a href="chapter1.html#파일"><i class="fa fa-check"></i><b>1.2.1</b> 파일</a></li>
<li class="chapter" data-level="1.2.2" data-path="chapter1.html"><a href="chapter1.html#편집"><i class="fa fa-check"></i><b>1.2.2</b> 편집</a></li>
<li class="chapter" data-level="1.2.3" data-path="chapter1.html"><a href="chapter1.html#기타"><i class="fa fa-check"></i><b>1.2.3</b> 기타</a></li>
<li class="chapter" data-level="1.2.4" data-path="chapter1.html"><a href="chapter1.html#패키지"><i class="fa fa-check"></i><b>1.2.4</b> 패키지</a></li>
<li class="chapter" data-level="1.2.5" data-path="chapter1.html"><a href="chapter1.html#윈도우즈"><i class="fa fa-check"></i><b>1.2.5</b> 윈도우즈</a></li>
<li class="chapter" data-level="1.2.6" data-path="chapter1.html"><a href="chapter1.html#도움말"><i class="fa fa-check"></i><b>1.2.6</b> 도움말</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chapter1.html"><a href="chapter1.html#r-프로그램-특징"><i class="fa fa-check"></i><b>1.3</b> R 프로그램 특징</a></li>
<li class="chapter" data-level="1.4" data-path="chapter1.html"><a href="chapter1.html#rstudio-설치"><i class="fa fa-check"></i><b>1.4</b> RStudio 설치</a></li>
<li class="chapter" data-level="1.5" data-path="chapter1.html"><a href="chapter1.html#r-패키지-이용"><i class="fa fa-check"></i><b>1.5</b> R 패키지 이용</a></li>
<li class="chapter" data-level="1.6" data-path="chapter1.html"><a href="chapter1.html#r-패키지-관리"><i class="fa fa-check"></i><b>1.6</b> R 패키지 관리</a></li>
<li class="chapter" data-level="1.7" data-path="chapter1.html"><a href="chapter1.html#산술-연산자"><i class="fa fa-check"></i><b>1.7</b> 산술 연산자</a></li>
<li class="chapter" data-level="1.8" data-path="chapter1.html"><a href="chapter1.html#논리-연산자와-비교-연산자"><i class="fa fa-check"></i><b>1.8</b> 논리 연산자와 비교 연산자</a></li>
<li class="chapter" data-level="1.9" data-path="chapter1.html"><a href="chapter1.html#기초-산술-함수"><i class="fa fa-check"></i><b>1.9</b> 기초 산술 함수</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="chapter1.html"><a href="chapter1.html#통계-함수"><i class="fa fa-check"></i><b>1.9.1</b> 통계 함수</a></li>
<li class="chapter" data-level="1.9.2" data-path="chapter1.html"><a href="chapter1.html#로그-및-지수-함수-logarithms-and-exponentials"><i class="fa fa-check"></i><b>1.9.2</b> 로그 및 지수 함수 (Logarithms and Exponentials)</a></li>
<li class="chapter" data-level="1.9.3" data-path="chapter1.html"><a href="chapter1.html#삼각-함수"><i class="fa fa-check"></i><b>1.9.3</b> 삼각 함수</a></li>
<li class="chapter" data-level="1.9.4" data-path="chapter1.html"><a href="chapter1.html#기타-수학-함수"><i class="fa fa-check"></i><b>1.9.4</b> 기타 수학 함수</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="chapter1.html"><a href="chapter1.html#객체의-명명과-할당"><i class="fa fa-check"></i><b>1.10</b> 객체의 명명과 할당</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="chapter1.html"><a href="chapter1.html#객체변수-만들기"><i class="fa fa-check"></i><b>1.10.1</b> 객체(변수) 만들기</a></li>
<li class="chapter" data-level="1.10.2" data-path="chapter1.html"><a href="chapter1.html#객체-목록-보기"><i class="fa fa-check"></i><b>1.10.2</b> 객체 목록 보기</a></li>
<li class="chapter" data-level="1.10.3" data-path="chapter1.html"><a href="chapter1.html#객체변수-지우기"><i class="fa fa-check"></i><b>1.10.3</b> 객체(변수) 지우기</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="chapter1.html"><a href="chapter1.html#데이터-유형"><i class="fa fa-check"></i><b>1.11</b> 데이터 유형</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="chapter1.html"><a href="chapter1.html#데이터의-기본-유형"><i class="fa fa-check"></i><b>1.11.1</b> 데이터의 기본 유형</a></li>
<li class="chapter" data-level="1.11.2" data-path="chapter1.html"><a href="chapter1.html#특수-데이터"><i class="fa fa-check"></i><b>1.11.2</b> 특수 데이터</a></li>
<li class="chapter" data-level="1.11.3" data-path="chapter1.html"><a href="chapter1.html#데이터-유형-함수"><i class="fa fa-check"></i><b>1.11.3</b> 데이터 유형 함수</a></li>
<li class="chapter" data-level="1.11.4" data-path="chapter1.html"><a href="chapter1.html#데이터-유형-변경"><i class="fa fa-check"></i><b>1.11.4</b> 데이터 유형 변경</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="chapter1.html"><a href="chapter1.html#자료의-입력"><i class="fa fa-check"></i><b>1.12</b> 자료의 입력</a>
<ul>
<li class="chapter" data-level="1.12.1" data-path="chapter1.html"><a href="chapter1.html#read.table"><i class="fa fa-check"></i><b>1.12.1</b> read.table()</a></li>
<li class="chapter" data-level="1.12.2" data-path="chapter1.html"><a href="chapter1.html#read.csv"><i class="fa fa-check"></i><b>1.12.2</b> read.csv()</a></li>
<li class="chapter" data-level="1.12.3" data-path="chapter1.html"><a href="chapter1.html#read.delim"><i class="fa fa-check"></i><b>1.12.3</b> read.delim()</a></li>
<li class="chapter" data-level="1.12.4" data-path="chapter1.html"><a href="chapter1.html#read_excel"><i class="fa fa-check"></i><b>1.12.4</b> read_excel()</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="chapter1.html"><a href="chapter1.html#자료의-출력"><i class="fa fa-check"></i><b>1.13</b> 자료의 출력</a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="chapter1.html"><a href="chapter1.html#write.table"><i class="fa fa-check"></i><b>1.13.1</b> write.table()</a></li>
<li class="chapter" data-level="1.13.2" data-path="chapter1.html"><a href="chapter1.html#write_xlsx"><i class="fa fa-check"></i><b>1.13.2</b> write_xlsx()</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="chapter1.html"><a href="chapter1.html#r-manual"><i class="fa fa-check"></i><b>1.14</b> R Manual</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter2.html"><a href="chapter2.html"><i class="fa fa-check"></i><b>2</b> Tidyverse Package</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter2.html"><a href="chapter2.html#filter"><i class="fa fa-check"></i><b>2.1</b> filter()</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="chapter2.html"><a href="chapter2.html#filter---연속형-변수-처리"><i class="fa fa-check"></i><b>2.1.1</b> filter() - 연속형 변수 처리</a></li>
<li class="chapter" data-level="2.1.2" data-path="chapter2.html"><a href="chapter2.html#filter---이산형-변수-처리"><i class="fa fa-check"></i><b>2.1.2</b> filter() - 이산형 변수 처리</a></li>
<li class="chapter" data-level="2.1.3" data-path="chapter2.html"><a href="chapter2.html#filter---문자형-변수-처리"><i class="fa fa-check"></i><b>2.1.3</b> filter() - 문자형 변수 처리</a></li>
<li class="chapter" data-level="2.1.4" data-path="chapter2.html"><a href="chapter2.html#filter---일반적인-변수-처리"><i class="fa fa-check"></i><b>2.1.4</b> filter() - 일반적인 변수 처리</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chapter2.html"><a href="chapter2.html#pipe"><i class="fa fa-check"></i><b>2.2</b> Pipe : %&gt;%</a></li>
<li class="chapter" data-level="2.3" data-path="chapter2.html"><a href="chapter2.html#select"><i class="fa fa-check"></i><b>2.3</b> select()</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chapter2.html"><a href="chapter2.html#select---선택"><i class="fa fa-check"></i><b>2.3.1</b> select() - 선택</a></li>
<li class="chapter" data-level="2.3.2" data-path="chapter2.html"><a href="chapter2.html#select---제거"><i class="fa fa-check"></i><b>2.3.2</b> select() - 제거</a></li>
<li class="chapter" data-level="2.3.3" data-path="chapter2.html"><a href="chapter2.html#filter-와-select-혼합"><i class="fa fa-check"></i><b>2.3.3</b> filter() 와 select() 혼합</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapter2.html"><a href="chapter2.html#group_by와-summarise"><i class="fa fa-check"></i><b>2.4</b> group_by()와 summarise()</a></li>
<li class="chapter" data-level="2.5" data-path="chapter2.html"><a href="chapter2.html#arrange"><i class="fa fa-check"></i><b>2.5</b> arrange()</a></li>
<li class="chapter" data-level="2.6" data-path="chapter2.html"><a href="chapter2.html#결측값-처리"><i class="fa fa-check"></i><b>2.6</b> 결측값 처리</a></li>
<li class="chapter" data-level="2.7" data-path="chapter2.html"><a href="chapter2.html#mutate"><i class="fa fa-check"></i><b>2.7</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter3.html"><a href="chapter3.html"><i class="fa fa-check"></i><b>3</b> 공단표본코호트 데모자료</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter3.html"><a href="chapter3.html#자격-db---자격-및-보험료-테이블"><i class="fa fa-check"></i><b>3.1</b> 자격 DB - 자격 및 보험료 테이블</a></li>
<li class="chapter" data-level="3.2" data-path="chapter3.html"><a href="chapter3.html#사망-db---출생-및-사망테이블"><i class="fa fa-check"></i><b>3.2</b> 사망 DB - 출생 및 사망테이블</a></li>
<li class="chapter" data-level="3.3" data-path="chapter3.html"><a href="chapter3.html#요양기관-db"><i class="fa fa-check"></i><b>3.3</b> 요양기관 DB</a></li>
<li class="chapter" data-level="3.4" data-path="chapter3.html"><a href="chapter3.html#진료-db---20-테이블"><i class="fa fa-check"></i><b>3.4</b> 진료 DB - 20 테이블</a></li>
<li class="chapter" data-level="3.5" data-path="chapter3.html"><a href="chapter3.html#진료-db---30-테이블"><i class="fa fa-check"></i><b>3.5</b> 진료 DB - 30 테이블</a></li>
<li class="chapter" data-level="3.6" data-path="chapter3.html"><a href="chapter3.html#진료-db---40-테이블"><i class="fa fa-check"></i><b>3.6</b> 진료 DB - 40 테이블</a></li>
<li class="chapter" data-level="3.7" data-path="chapter3.html"><a href="chapter3.html#진료-db---60-테이블"><i class="fa fa-check"></i><b>3.7</b> 진료 DB - 60 테이블</a></li>
<li class="chapter" data-level="3.8" data-path="chapter3.html"><a href="chapter3.html#작업공간-저장-및-불러오기"><i class="fa fa-check"></i><b>3.8</b> 작업공간 저장 및 불러오기</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="chapter3.html"><a href="chapter3.html#객체-목록-확인"><i class="fa fa-check"></i><b>3.8.1</b> 객체 목록 확인</a></li>
<li class="chapter" data-level="3.8.2" data-path="chapter3.html"><a href="chapter3.html#작업공간-저장"><i class="fa fa-check"></i><b>3.8.2</b> 작업공간 저장</a></li>
<li class="chapter" data-level="3.8.3" data-path="chapter3.html"><a href="chapter3.html#작업공간-불러오기"><i class="fa fa-check"></i><b>3.8.3</b> 작업공간 불러오기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter4.html"><a href="chapter4.html"><i class="fa fa-check"></i><b>4</b> 데이터프레임의 활용</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter4.html"><a href="chapter4.html#데이터-프레임"><i class="fa fa-check"></i><b>4.1</b> 데이터 프레임</a></li>
<li class="chapter" data-level="4.2" data-path="chapter4.html"><a href="chapter4.html#데이터-프레임-인덱싱"><i class="fa fa-check"></i><b>4.2</b> 데이터 프레임 인덱싱</a></li>
<li class="chapter" data-level="4.3" data-path="chapter4.html"><a href="chapter4.html#공단자료와-필요패키지-불러오기"><i class="fa fa-check"></i><b>4.3</b> 공단자료와 필요패키지 불러오기</a></li>
<li class="chapter" data-level="4.4" data-path="chapter4.html"><a href="chapter4.html#특정-변수만-남기기"><i class="fa fa-check"></i><b>4.4</b> 특정 변수만 남기기</a></li>
<li class="chapter" data-level="4.5" data-path="chapter4.html"><a href="chapter4.html#특정-변수-지우기"><i class="fa fa-check"></i><b>4.5</b> 특정 변수 지우기</a></li>
<li class="chapter" data-level="4.6" data-path="chapter4.html"><a href="chapter4.html#변수-이름-바꾸기"><i class="fa fa-check"></i><b>4.6</b> 변수 이름 바꾸기</a></li>
<li class="chapter" data-level="4.7" data-path="chapter4.html"><a href="chapter4.html#특정-위치의-관찰값-추출"><i class="fa fa-check"></i><b>4.7</b> 특정 위치의 관찰값 추출</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter5.html"><a href="chapter5.html"><i class="fa fa-check"></i><b>5</b> 새로운 변수 생성</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter5.html"><a href="chapter5.html#기존-변수의-값-바꾸기"><i class="fa fa-check"></i><b>5.1</b> 기존 변수의 값 바꾸기</a></li>
<li class="chapter" data-level="5.2" data-path="chapter5.html"><a href="chapter5.html#새로운-변수-만들기"><i class="fa fa-check"></i><b>5.2</b> 새로운 변수 만들기</a></li>
<li class="chapter" data-level="5.3" data-path="chapter5.html"><a href="chapter5.html#round-함수-이용"><i class="fa fa-check"></i><b>5.3</b> Round 함수 이용</a></li>
<li class="chapter" data-level="5.4" data-path="chapter5.html"><a href="chapter5.html#순자를-문자로-문자를-숫자로"><i class="fa fa-check"></i><b>5.4</b> 순자를 문자로, 문자를 숫자로</a></li>
<li class="chapter" data-level="5.5" data-path="chapter5.html"><a href="chapter5.html#substr-함수-이용"><i class="fa fa-check"></i><b>5.5</b> substr 함수 이용</a></li>
<li class="chapter" data-level="5.6" data-path="chapter5.html"><a href="chapter5.html#날짜-함수-이용"><i class="fa fa-check"></i><b>5.6</b> 날짜 함수 이용</a></li>
<li class="chapter" data-level="5.7" data-path="chapter5.html"><a href="chapter5.html#누적합-함수-이용"><i class="fa fa-check"></i><b>5.7</b> 누적합 함수 이용</a></li>
<li class="chapter" data-level="5.8" data-path="chapter5.html"><a href="chapter5.html#lag과-diff-함수-이용"><i class="fa fa-check"></i><b>5.8</b> lag과 diff 함수 이용</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter6.html"><a href="chapter6.html"><i class="fa fa-check"></i><b>6</b> 조건문</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chapter6.html"><a href="chapter6.html#특정-조건을-만족하는-관찰값-선택하기"><i class="fa fa-check"></i><b>6.1</b> 특정 조건을 만족하는 관찰값 선택하기</a></li>
<li class="chapter" data-level="6.2" data-path="chapter6.html"><a href="chapter6.html#특정-조건을-만족하는-관찰값-삭제하기"><i class="fa fa-check"></i><b>6.2</b> 특정 조건을 만족하는 관찰값 삭제하기</a></li>
<li class="chapter" data-level="6.3" data-path="chapter6.html"><a href="chapter6.html#조건문-활용하기"><i class="fa fa-check"></i><b>6.3</b> 조건문 활용하기</a></li>
<li class="chapter" data-level="6.4" data-path="chapter6.html"><a href="chapter6.html#조건문-일반화하기"><i class="fa fa-check"></i><b>6.4</b> 조건문 일반화하기</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapter7.html"><a href="chapter7.html"><i class="fa fa-check"></i><b>7</b> 자료의 정렬</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chapter7.html"><a href="chapter7.html#하나의-변수에-의한-관찰값의-정렬"><i class="fa fa-check"></i><b>7.1</b> 하나의 변수에 의한 관찰값의 정렬</a></li>
<li class="chapter" data-level="7.2" data-path="chapter7.html"><a href="chapter7.html#여러-개의-변수에-의한-관찰값의-정렬"><i class="fa fa-check"></i><b>7.2</b> 여러 개의 변수에 의한 관찰값의 정렬</a></li>
<li class="chapter" data-level="7.3" data-path="chapter7.html"><a href="chapter7.html#처음과-마지막-개체-추출하기"><i class="fa fa-check"></i><b>7.3</b> 처음과 마지막 개체 추출하기</a></li>
<li class="chapter" data-level="7.4" data-path="chapter7.html"><a href="chapter7.html#동일한-관찰값의-제거"><i class="fa fa-check"></i><b>7.4</b> 동일한 관찰값의 제거</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapter8.html"><a href="chapter8.html"><i class="fa fa-check"></i><b>8</b> 반복문</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chapter8.html"><a href="chapter8.html#조건에-의한-반복"><i class="fa fa-check"></i><b>8.1</b> 조건에 의한 반복</a></li>
<li class="chapter" data-level="8.2" data-path="chapter8.html"><a href="chapter8.html#개체에-의한-반복"><i class="fa fa-check"></i><b>8.2</b> 개체에 의한 반복</a></li>
<li class="chapter" data-level="8.3" data-path="chapter8.html"><a href="chapter8.html#다중-반복"><i class="fa fa-check"></i><b>8.3</b> 다중 반복</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapter9.html"><a href="chapter9.html"><i class="fa fa-check"></i><b>9</b> 데이터셋 합치기</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chapter9.html"><a href="chapter9.html#변수-기준-개체-통합"><i class="fa fa-check"></i><b>9.1</b> 변수 기준 개체 통합</a></li>
<li class="chapter" data-level="9.2" data-path="chapter9.html"><a href="chapter9.html#개체-기준-변수-통합"><i class="fa fa-check"></i><b>9.2</b> 개체 기준 변수 통합</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chapter10.html"><a href="chapter10.html"><i class="fa fa-check"></i><b>10</b> Tidyverse 활용</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chapter10.html"><a href="chapter10.html#tidyverse-dplyr-기본-구조"><i class="fa fa-check"></i><b>10.1</b> Tidyverse (dplyr) 기본 구조</a></li>
<li class="chapter" data-level="10.2" data-path="chapter10.html"><a href="chapter10.html#단일-데이터셋-다루기"><i class="fa fa-check"></i><b>10.2</b> 단일 데이터셋 다루기</a></li>
<li class="chapter" data-level="10.3" data-path="chapter10.html"><a href="chapter10.html#여러-데이터셋-다루기"><i class="fa fa-check"></i><b>10.3</b> 여러 데이터셋 다루기</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapter11.html"><a href="chapter11.html"><i class="fa fa-check"></i><b>11</b> 사용자 정의 함수</a></li>
<li class="chapter" data-level="12" data-path="chapter12.html"><a href="chapter12.html"><i class="fa fa-check"></i><b>12</b> 예제1</a>
<ul>
<li class="chapter" data-level="12.1" data-path="chapter12.html"><a href="chapter12.html#연구-설계"><i class="fa fa-check"></i><b>12.1</b> 연구 설계</a></li>
<li class="chapter" data-level="12.2" data-path="chapter12.html"><a href="chapter12.html#프로그램"><i class="fa fa-check"></i><b>12.2</b> 프로그램</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Insurance Claims Data Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter10" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Tidyverse 활용</h1>
<p>공단자료와 필요 패키지 불러오기</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chapter10.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;claim.RData&quot;</span>)</span>
<span id="cb1-2"><a href="chapter10.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="chapter10.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate) <span class="co"># 날짜 함수</span></span></code></pre></div>
<p>structured query language (sql)은 테이블에서 자료를 조회하고 자료를 입력, 수정, 삭제하며 테이블, 뷰, 인덱스를 생성, 삭제하는데 널리 사용되는 표준화된 언어이며, 데이터베이스를 관리하는데 유용하게 사용된다. R 패키지 “Tidyverse”는 sql의 기본기능을 이용하여 R에 맞는 함수로 작성하였으며, 따라서 이로 인해 데이터셋 관리의 편리함을 더하고 있다.</p>
<p>우리는 앞에서 이러한 구조의 명령어를 군데 군데 사용하여 그 사용법을 익혀왔으며, 이 장에서는 요약겸 새로운 기능을 익혀 자연스러움을 더하고자 한다.</p>
<div id="tidyverse-dplyr-기본-구조" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Tidyverse (dplyr) 기본 구조</h2>
<p>기본 구조는 다음과 같다.</p>
<pre><code>새로운 데이터셋 &lt;- 기존 데이터셋 %&gt;% 
  filter() %&gt;% 
  select() %&gt;% 
  mutate() %&gt;% 
  group_by() %&gt;% 
  summarise() %&gt;% 
  arrange()</code></pre>
<p>filter 구문은 데이터셋 구성시 필요한 조건을 지정하며, select 구문은 데이터셋에 선택하고자 하는 변수 혹은 새로 생성하려는 변수를 지정한다. mutate 구문은 새로운 변수 생성시 사용하며, group_by 문에는 그룹화된 데이터셋을 생성 시 그룹화할 기준 변수를 지정한다. group_by/summarise 문은 건강보험청구자료와 같이 한 id에 여러 개의 행이 존재하는 경우 유니크한 id별로 값을 산출해주기 때문에 id별로 계산을 해야 하는 경우에 유용하게 사용된다. arrange 문은 데이터셋을 정렬해서 표현하고 싶을 때 정렬 기준 변수를 지정한다. 이와 같이 Pipe 라인을 통해 여러 가지 명령의 수행이 가능한 옵션들로 구성되어 있으며 상황에 맞게 구성하여 사용한다.</p>
</div>
<div id="단일-데이터셋-다루기" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> 단일 데이터셋 다루기</h2>
<p>단일 데이터셋을 이용하여 데이터셋 생성, 변수 생성, 조건문 적용 등과 관련하여 살펴보자. 먼저 조건문에서와 마찬가지로 t20 데이터셋에서 주상병이 제2형 당뇨(‘E11’)이면서 동시에 내과 진료과목이 기재된 명세서만 추출하여 t20_sql 데이터셋을 생성해보자. 이때 진료과목코드(mcare_subj_cd)의 값이 ‘01’이면 내과를 의미한다. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chapter10.html#cb3-1" aria-hidden="true" tabindex="-1"></a>t20_sql <span class="ot">&lt;-</span> t20 <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="chapter10.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">substr</span>(sick_sym1,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;E11&quot;</span>, mcare_subj_cd<span class="sc">==</span><span class="st">&#39;01&#39;</span>)</span>
<span id="cb3-3"><a href="chapter10.html#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="chapter10.html#cb3-4" aria-hidden="true" tabindex="-1"></a>t20_sql</span></code></pre></div>
<pre><code>## # A tibble: 2,174 x 22
##    rn_indi rn_key        rn_inst mdcare_strt_dt form_cd mcare_subj_cd sick_sym1
##      &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;   &lt;chr&gt;         &lt;chr&gt;    
##  1  819628 2002100385297   99662 20021025       03      01            E11      
##  2  663811 2002090160999  108535 20020929       03      01            E11      
##  3  819628 2002090153862   99662 20020907       03      01            E11      
##  4  490204 2002040486087   36298 20020416       03      01            E11      
##  5  490204 2002020191323   36298 20020214       03      01            E11      
##  6  490204 2002030200247   36298 20020316       03      01            E11      
##  7  490204 2002050098890   36298 20020514       03      01            E11      
##  8  490204 2002070043518   36298 20020715       03      01            E11      
##  9  490204 2002100739596   36298 20021030       03      01            E11      
## 10  490204 2002080663820   36298 20020831       03      01            E11      
## # ... with 2,164 more rows, and 15 more variables: sick_sym2 &lt;chr&gt;,
## #   hsptz_path_type &lt;chr&gt;, ofij_type &lt;chr&gt;, oprtn_yn &lt;chr&gt;,
## #   mdcare_dd_cnt &lt;dbl&gt;, vshsp_dd_cnt &lt;dbl&gt;, tot_prsc_dd_cnt &lt;dbl&gt;,
## #   mcare_rslt_type &lt;chr&gt;, fst_hsptz_dt &lt;chr&gt;, edc_add_rt &lt;dbl&gt;,
## #   spcf_sym_type &lt;chr&gt;, ed_rc_tot_amt &lt;dbl&gt;, edc_sba &lt;dbl&gt;,
## #   edc_insur_brdn_amt &lt;dbl&gt;, std_yyyy &lt;chr&gt;</code></pre>
<p>특정 변수를 추출하고 싶으면 select 문에 변수1, 변수2, … 와 같은 형식으로 지정한다. 위의 예제와 동일한 조건에서 특정변수만 남겨보자. 이때 개인고유번호(rn_indi), 요양개시일자(mdcare_strt_dt), 주상병(sick_sym1), 심결요양급여비용총액(ed_rc_tot_amt)를 남겨서 t20_sql2를 만들어보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chapter10.html#cb5-1" aria-hidden="true" tabindex="-1"></a>t20_sql2 <span class="ot">&lt;-</span> t20 <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="chapter10.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">substr</span>(sick_sym1,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;E11&quot;</span>, mcare_subj_cd<span class="sc">==</span><span class="st">&#39;01&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="chapter10.html#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rn_indi, mdcare_strt_dt, sick_sym1, ed_rc_tot_amt)</span>
<span id="cb5-4"><a href="chapter10.html#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="chapter10.html#cb5-5" aria-hidden="true" tabindex="-1"></a>t20_sql2</span></code></pre></div>
<pre><code>## # A tibble: 2,174 x 4
##    rn_indi mdcare_strt_dt sick_sym1 ed_rc_tot_amt
##      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;             &lt;dbl&gt;
##  1  819628 20021025       E11                9030
##  2  663811 20020929       E11               15200
##  3  819628 20020907       E11               31300
##  4  490204 20020416       E11                8160
##  5  490204 20020214       E11                8400
##  6  490204 20020316       E11                8400
##  7  490204 20020514       E11               16320
##  8  490204 20020715       E11                9030
##  9  490204 20021030       E11                9030
## 10  490204 20020831       E11                9030
## # ... with 2,164 more rows</code></pre>
<p>다음은 t20_sql2를 생성하는 동일한 프로그램에 변수간 계산을 통한 새로운 변수생성을 추가해보자. 이때 새로운 변수는 심결본인부담금(edc_sba)과 심결보험자부담금(edc_insur_brdn_amt)을 합하여 totalcost란 변수명으로 지정하고 t20_sql3 데이터셋을 생성해보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chapter10.html#cb7-1" aria-hidden="true" tabindex="-1"></a>t20_sql3 <span class="ot">&lt;-</span> t20 <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="chapter10.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">substr</span>(sick_sym1,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;E11&quot;</span>, mcare_subj_cd<span class="sc">==</span><span class="st">&#39;01&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="chapter10.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">totalcost=</span>edc_sba<span class="sc">+</span>edc_insur_brdn_amt) <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="chapter10.html#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(rn_indi, mdcare_strt_dt, sick_sym1, ed_rc_tot_amt, totalcost) </span>
<span id="cb7-5"><a href="chapter10.html#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="chapter10.html#cb7-6" aria-hidden="true" tabindex="-1"></a>t20_sql3</span></code></pre></div>
<pre><code>## # A tibble: 2,174 x 5
##    rn_indi mdcare_strt_dt sick_sym1 ed_rc_tot_amt totalcost
##      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;
##  1  819628 20021025       E11                9030      9030
##  2  663811 20020929       E11               15200     15200
##  3  819628 20020907       E11               31300     31300
##  4  490204 20020416       E11                8160      8160
##  5  490204 20020214       E11                8400      8400
##  6  490204 20020316       E11                8400      8400
##  7  490204 20020514       E11               16320     16320
##  8  490204 20020715       E11                9030      9030
##  9  490204 20021030       E11                9030      9030
## 10  490204 20020831       E11                9030      9030
## # ... with 2,164 more rows</code></pre>
<p>결과를 살펴보면 심결본인부담금(edc_sba)과 심결보험자부담금(edc_insur_brdn_amt)을 합한 totalcost는 심결요양급여비용총액(ed_rc_tot_amt)와 같은 값을 가짐을 알 수 있다.</p>
<p>이번에는 group by 구문에 대해서 살펴보자. group by 구문은 그룹화되어 있는 개체들을 하나로 묶어서 결과를 제공해준다. 이때 연산은 행 내에서 진행되는 것이 아닌 그룹 변수 열 내에서 연산이 진행된다. 예를 들어 심결본인부담금(edc_sba)과 심결보험자부담금(edc_insur_brdn_amt)의 합을 계산하면, 특정 개체에서 심결본인부담금+심결보험자부담금의 형태로 행 내에서 열+열의 형태로 계산된다. 이에 반해 group by는 특정 열 내에서 행들의 묶음으로 계산이 진행된다. 예를 들어, 위의 결과에서 개인고유번호별로 즉, 환자별로 심결요양급여비용총액을 계산하고 싶다고 하자. 이때 rn_indi가 ’490204‘인 경우 총 7개의 개체(=명세서)가 존재하여 ’490204‘인 환자에 대해 총 심결요양급여비용총액을 계산하면 심결요양급여비용총액을 나타내는 열 내에서 7개의 행들의 합으로 계산이 나타난다. t20_sql과 같은 조건에서 개인고유번호 별로 심결요양급여비용총액을 합하여 변수 totalcost로 나타내고 t20_sql4로 저장해보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chapter10.html#cb9-1" aria-hidden="true" tabindex="-1"></a>t20_sql4 <span class="ot">&lt;-</span> t20 <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="chapter10.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">substr</span>(sick_sym1,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;E11&quot;</span>, mcare_subj_cd<span class="sc">==</span><span class="st">&#39;01&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="chapter10.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(rn_indi) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="chapter10.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">totalcost=</span><span class="fu">sum</span>(ed_rc_tot_amt))</span>
<span id="cb9-5"><a href="chapter10.html#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="chapter10.html#cb9-6" aria-hidden="true" tabindex="-1"></a>t20_sql4</span></code></pre></div>
<pre><code>## # A tibble: 79 x 2
##    rn_indi totalcost
##      &lt;dbl&gt;     &lt;dbl&gt;
##  1    7386     58860
##  2   13546     15110
##  3   27490     12320
##  4   36714    382460
##  5   39217   1116210
##  6   46952    273200
##  7   72225  10196840
##  8   79207     11710
##  9   80234    727700
## 10   92198   2347590
## # ... with 69 more rows</code></pre>
<p>결과를 살펴보면, 중복되지 않은 개인고유번호에 대해 심결요양급여비용총액을 합하여 totalcost 변수로 표현하고 있는 것을 알 수 있다.</p>
<p>summaise 함수 안에 사용될 수 있는 유용한 함수는 다음과 같다.</p>
<pre><code>* Center: mean(), median()

* Spread: sd(), IQR(), mad()

* Range: min(), max(), quantile()

* Position: first(), last(), nth(),

* Count: n(), n_distinct()

* Logical: any(), all()</code></pre>
</div>
<div id="여러-데이터셋-다루기" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> 여러 데이터셋 다루기</h2>
<p>여러 데이터셋을 합치거나, 다른 데이터셋과 연계하여 특정한 조건의 데이터셋 만을 뽑아내는 것이 가능하다. 이러한 기능은 데이터셋을 합치는 bind_rows()문과 merge()를 섞어놓은 형태이며, 사실상 그보다는 더 많은 형태로 활용할 수 있다. 기능 면에서 데이터셋을 통합하는 방법은 다음과 같이 크게 4가지 형태로 나뉜다. 1) 여러 데이터셋에서 동일한 id만을 매칭시켜 데이터셋을 생성하는 inner join 2) 기준 데이터셋을 왼쪽에 두고 다른 데이터셋에서 동일한 id에 해당하는 개체의 변수값을 통합하는 left join 3) left join과는 반대로 동일한 id에 해당하는 개체의 변수값을 오른쪽 기준 데이터셋으로 통합하는 right join 4) 모든 데이터셋의 개체와 변수를 동일 id를 기준으로 통합하는 outer join으로 나뉜다. 이 중에서 left join과 right join은 기능상 같은 역할을 하며, outer join은 기능상 merge 문을 이용하는 게 편하기 때문에 여기서는 inner join과 left join에 대해서 살펴보도록 하자. 이 외에도 동일한 id만 매칭시켜 데이터를 추출하는 semi_join과 매칭되지 않는 id만으로 구성된 anti_join이 있다.</p>
<p>우선 다른 데이터셋과 동일한 id로 구성된 단일 데이터셋을 생성하는 방법을 살펴보자. 이를 개체 입장에서 표현하면 다음 그림과 같다.</p>
<p><img src="fig/inner_join.png" /></p>
<p>예제를 위해 앞 장에서 사용한 t20_sql 예제를 불러오자. t20 데이터셋에서 주상병이 제2형 당뇨(‘E11’)이면서 동시에 내과 진료과목이 기재된 명세서만 추출하여 t20_sql 데이터셋을 생성하자. 이때 진료과목코드(mcare_subj_cd)의 값이 ‘01’이면 내과를 의미한다. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chapter10.html#cb12-1" aria-hidden="true" tabindex="-1"></a>t20_sql <span class="ot">&lt;-</span> t20 <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="chapter10.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">substr</span>(sick_sym1,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;E11&quot;</span>, mcare_subj_cd<span class="sc">==</span><span class="st">&#39;01&#39;</span>)</span>
<span id="cb12-3"><a href="chapter10.html#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="chapter10.html#cb12-4" aria-hidden="true" tabindex="-1"></a>t20_sql</span></code></pre></div>
<pre><code>## # A tibble: 2,174 x 22
##    rn_indi rn_key        rn_inst mdcare_strt_dt form_cd mcare_subj_cd sick_sym1
##      &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;   &lt;chr&gt;         &lt;chr&gt;    
##  1  819628 2002100385297   99662 20021025       03      01            E11      
##  2  663811 2002090160999  108535 20020929       03      01            E11      
##  3  819628 2002090153862   99662 20020907       03      01            E11      
##  4  490204 2002040486087   36298 20020416       03      01            E11      
##  5  490204 2002020191323   36298 20020214       03      01            E11      
##  6  490204 2002030200247   36298 20020316       03      01            E11      
##  7  490204 2002050098890   36298 20020514       03      01            E11      
##  8  490204 2002070043518   36298 20020715       03      01            E11      
##  9  490204 2002100739596   36298 20021030       03      01            E11      
## 10  490204 2002080663820   36298 20020831       03      01            E11      
## # ... with 2,164 more rows, and 15 more variables: sick_sym2 &lt;chr&gt;,
## #   hsptz_path_type &lt;chr&gt;, ofij_type &lt;chr&gt;, oprtn_yn &lt;chr&gt;,
## #   mdcare_dd_cnt &lt;dbl&gt;, vshsp_dd_cnt &lt;dbl&gt;, tot_prsc_dd_cnt &lt;dbl&gt;,
## #   mcare_rslt_type &lt;chr&gt;, fst_hsptz_dt &lt;chr&gt;, edc_add_rt &lt;dbl&gt;,
## #   spcf_sym_type &lt;chr&gt;, ed_rc_tot_amt &lt;dbl&gt;, edc_sba &lt;dbl&gt;,
## #   edc_insur_brdn_amt &lt;dbl&gt;, std_yyyy &lt;chr&gt;</code></pre>
<p>생성된 데이터셋 t20_sql은 2174개의 개체와 t20 데이터셋에 존재하는 모든 변수로 구성되어 있다. 첫번째 예제는 t20_sql과 동일한 청구고유번호(rn_key)를 가지는 t40 데이터셋을 선택 구성하는 방법이다. 다시 말해서, 기준이 되는 데이터셋을 기본으로 나머지 데이터셋의 구성을 바꾸는 형태이다. 먼저 t40 데이터셋에서 t20_sql 데이터셋에 존재하는 rn_key와 같은 개체만 남기고 변수는 모두 선택하여 t40_sql 데이터셋을 구성하는 방법을 살펴보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="chapter10.html#cb14-1" aria-hidden="true" tabindex="-1"></a>t40_sql <span class="ot">&lt;-</span> t40 <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="chapter10.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(t20_sql, <span class="at">by=</span><span class="st">&quot;rn_key&quot;</span>)</span>
<span id="cb14-3"><a href="chapter10.html#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="chapter10.html#cb14-4" aria-hidden="true" tabindex="-1"></a>t40_sql</span></code></pre></div>
<pre><code>## # A tibble: 7,385 x 8
##    rn_indi rn_key        mdcare_strt_dt form_cd mcex_sick_sym detail_tmsg_subj_~
##      &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;          &lt;chr&gt;   &lt;chr&gt;         &lt;chr&gt;             
##  1  575578 2002111049919 20021125       03      F_            &lt;NA&gt;              
##  2  819628 2002110224101 20021125       03      E11           &lt;NA&gt;              
##  3  575578 2002111049919 20021125       03      K589          &lt;NA&gt;              
##  4  575578 2002111049919 20021125       03      E119          &lt;NA&gt;              
##  5  575578 2002111049919 20021125       03      M069          &lt;NA&gt;              
##  6  575578 2002111049919 20021125       03      K253          &lt;NA&gt;              
##  7  575578 2002090816943 20020923       03      K293          &lt;NA&gt;              
##  8  575578 2002090816943 20020923       03      K589          &lt;NA&gt;              
##  9  575578 2002090816943 20020923       03      E119          &lt;NA&gt;              
## 10  490204 2002020191323 20020214       03      F_            &lt;NA&gt;              
## # ... with 7,375 more rows, and 2 more variables: sick_clsf_type &lt;chr&gt;,
## #   std_yyyy &lt;chr&gt;</code></pre>
<p>결과를 살펴보면, t40 데이터셋의 모든 변수가 포함되어 있다는 것을 알 수 있다. rn_key 값이 ‘2002111049919’인 경우 t40 데이터셋엔 다섯개의 개체가 존재하기 때문에 모두 달라 붙어 구성된다.</p>
<p>반대로 t40 데이터셋을 구성시, t20_sql 데이터셋에 존재하지 않는 명세서로 구성된 데이터를 생각해보자. 이 경우엔 anti_join()을 이용한다.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chapter10.html#cb16-1" aria-hidden="true" tabindex="-1"></a>t40_sql2 <span class="ot">&lt;-</span> t40 <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="chapter10.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(t20_sql, <span class="at">by=</span><span class="st">&quot;rn_key&quot;</span>)</span>
<span id="cb16-3"><a href="chapter10.html#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="chapter10.html#cb16-4" aria-hidden="true" tabindex="-1"></a>t40_sql2</span></code></pre></div>
<pre><code>## # A tibble: 333,211 x 8
##    rn_indi rn_key        mdcare_strt_dt form_cd mcex_sick_sym detail_tmsg_subj_~
##      &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;          &lt;chr&gt;   &lt;chr&gt;         &lt;chr&gt;             
##  1  596535 2002120187152 20021202       03      J209          &lt;NA&gt;              
##  2  615374 2002121012274 20021202       03      J209          &lt;NA&gt;              
##  3 1005547 2002120808216 20021202       03      J209          &lt;NA&gt;              
##  4  226594 2002120381612 20021202       03      J209          &lt;NA&gt;              
##  5  204930 2002120790182 20021202       03      J209          &lt;NA&gt;              
##  6  798943 2002040446183 20020401       03      J209          &lt;NA&gt;              
##  7  920001 2002040802704 20020401       03      J209          &lt;NA&gt;              
##  8  986222 2002120261569 20021203       03      J209          &lt;NA&gt;              
##  9  633007 2002120734373 20021203       03      J209          &lt;NA&gt;              
## 10  886653 2002120868879 20021203       03      J209          &lt;NA&gt;              
## # ... with 333,201 more rows, and 2 more variables: sick_clsf_type &lt;chr&gt;,
## #   std_yyyy &lt;chr&gt;</code></pre>
<p>반면, 동일한 semi_join과 같이 동일한 id로 매칭된 두 데이터셋의 모든 변수를 다 가져 올땐 inner join을 이용하며, 다음과 같이 사용한다.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter10.html#cb18-1" aria-hidden="true" tabindex="-1"></a>t20_sql2 <span class="ot">&lt;-</span> t20_sql <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="chapter10.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(t40, <span class="at">by=</span><span class="st">&quot;rn_key&quot;</span>)</span>
<span id="cb18-3"><a href="chapter10.html#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="chapter10.html#cb18-4" aria-hidden="true" tabindex="-1"></a>t20_sql2</span></code></pre></div>
<pre><code>## # A tibble: 7,385 x 29
##    rn_indi.x rn_key   rn_inst mdcare_strt_dt.x form_cd.x mcare_subj_cd sick_sym1
##        &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;    
##  1    819628 2002100~   99662 20021025         03        01            E11      
##  2    663811 2002090~  108535 20020929         03        01            E11      
##  3    819628 2002090~   99662 20020907         03        01            E11      
##  4    490204 2002040~   36298 20020416         03        01            E11      
##  5    490204 2002040~   36298 20020416         03        01            E11      
##  6    490204 2002020~   36298 20020214         03        01            E11      
##  7    490204 2002020~   36298 20020214         03        01            E11      
##  8    490204 2002020~   36298 20020214         03        01            E11      
##  9    490204 2002020~   36298 20020214         03        01            E11      
## 10    490204 2002030~   36298 20020316         03        01            E11      
## # ... with 7,375 more rows, and 22 more variables: sick_sym2 &lt;chr&gt;,
## #   hsptz_path_type &lt;chr&gt;, ofij_type &lt;chr&gt;, oprtn_yn &lt;chr&gt;,
## #   mdcare_dd_cnt &lt;dbl&gt;, vshsp_dd_cnt &lt;dbl&gt;, tot_prsc_dd_cnt &lt;dbl&gt;,
## #   mcare_rslt_type &lt;chr&gt;, fst_hsptz_dt &lt;chr&gt;, edc_add_rt &lt;dbl&gt;,
## #   spcf_sym_type &lt;chr&gt;, ed_rc_tot_amt &lt;dbl&gt;, edc_sba &lt;dbl&gt;,
## #   edc_insur_brdn_amt &lt;dbl&gt;, std_yyyy.x &lt;chr&gt;, rn_indi.y &lt;dbl&gt;,
## #   mdcare_strt_dt.y &lt;chr&gt;, form_cd.y &lt;chr&gt;, mcex_sick_sym &lt;chr&gt;,
## #   detail_tmsg_subj_cd &lt;chr&gt;, sick_clsf_type &lt;chr&gt;, std_yyyy.y &lt;chr&gt;</code></pre>
<p>특정 변수로 구성된 데이터셋을 생성시킬때는 1) 사전에 두 데이터셋에 필요한 변수만 남기던가, 2) 데이터셋을 통합시킨 후 필요한 변수만 남기던가, 3) 데이터셋 통합시 필요한 변수만 구성하는 방법이 가능하다. 이번에는 t40 데이터셋의 모든 변수가 아니라 필요한 변수만 생성하는 방법을 살펴보자. 예를 들어 t40 데이터셋에서 rn_key와 mcex_sick_sym 변수만 남기고 t20_sql에서 rn_key와 mdcare_strt_dt 변수만 남겨서 t40_sql3를 생성시켜보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter10.html#cb20-1" aria-hidden="true" tabindex="-1"></a>t40_sql3 <span class="ot">&lt;-</span> <span class="fu">select</span>(t20_sql,rn_key, mdcare_strt_dt) <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="chapter10.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(<span class="fu">select</span>(t40,rn_key,mcex_sick_sym), <span class="at">by=</span><span class="st">&quot;rn_key&quot;</span>)</span>
<span id="cb20-3"><a href="chapter10.html#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="chapter10.html#cb20-4" aria-hidden="true" tabindex="-1"></a>t40_sql3</span></code></pre></div>
<pre><code>## # A tibble: 7,385 x 3
##    rn_key        mdcare_strt_dt mcex_sick_sym
##    &lt;chr&gt;         &lt;chr&gt;          &lt;chr&gt;        
##  1 2002100385297 20021025       E11          
##  2 2002090160999 20020929       E11          
##  3 2002090153862 20020907       E11          
##  4 2002040486087 20020416       F_           
##  5 2002040486087 20020416       E11          
##  6 2002020191323 20020214       F_           
##  7 2002020191323 20020214       E11          
##  8 2002020191323 20020214       K293         
##  9 2002020191323 20020214       E105         
## 10 2002030200247 20020316       F_           
## # ... with 7,375 more rows</code></pre>
<p>반면, left join은 기준이 되는 데이터셋을 베이스로 공통적으로 존재하는 변수의 값이 매칭되는 행의 정보를 다른 데이터셋으로부터 끌어와 데이터셋을 구성하는 방법이다. 따라서 원본 데이터셋은 그대로 두고 다만 다른 데이터셋의 변수를 추가하고 싶을 때 left join을 사용하며, 이를 개체 입장에서 표현하면 다음 그림과 같다.</p>
<p><img src="fig/left_join.png" /></p>
<p>위의 예제에서 t20_sql은 t20 데이터셋으로부터 주상병이 ‘E11’이고 진료과목코드가 ‘01’ 즉 내과인 명세서로 구성되어 있다. t30 즉, 원내 처치 데이터셋에서 주성분 코드가 ‘107501ATB’인 약제가 쓰였는지의 여부를 나타내는 변수를 생성해 t20_sql 데이터셋에 변수를 추가해보자. 이를 위한 프로그램은 다음과 같다.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chapter10.html#cb22-1" aria-hidden="true" tabindex="-1"></a>t30_drug <span class="ot">&lt;-</span> t30 <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="chapter10.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">drug=</span><span class="fu">ifelse</span>(mcare_div_cd<span class="sc">==</span><span class="st">&quot;107501ATB&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="chapter10.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(rn_key) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="chapter10.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">drug=</span><span class="fu">max</span>(drug))</span>
<span id="cb22-5"><a href="chapter10.html#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="chapter10.html#cb22-6" aria-hidden="true" tabindex="-1"></a>t30_drug</span></code></pre></div>
<pre><code>## # A tibble: 132,398 x 2
##    rn_key         drug
##    &lt;chr&gt;         &lt;dbl&gt;
##  1 2002010004184     0
##  2 2002010007672     0
##  3 2002010008782     0
##  4 2002010009358     0
##  5 2002010010476     0
##  6 2002010011241     0
##  7 2002010012574     0
##  8 2002010016588     0
##  9 2002010018920     0
## 10 2002010019573     0
## # ... with 132,388 more rows</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chapter10.html#cb24-1" aria-hidden="true" tabindex="-1"></a>t20_sql_drug <span class="ot">&lt;-</span> t20_sql <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="chapter10.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(t30_drug, <span class="at">by=</span><span class="st">&quot;rn_key&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="chapter10.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rn_indi, rn_key, drug)</span>
<span id="cb24-4"><a href="chapter10.html#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="chapter10.html#cb24-5" aria-hidden="true" tabindex="-1"></a>t20_sql_drug</span></code></pre></div>
<pre><code>## # A tibble: 2,174 x 3
##    rn_indi rn_key         drug
##      &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
##  1  819628 2002100385297     0
##  2  663811 2002090160999     0
##  3  819628 2002090153862     0
##  4  490204 2002040486087     0
##  5  490204 2002020191323     0
##  6  490204 2002030200247     0
##  7  490204 2002050098890     0
##  8  490204 2002070043518     0
##  9  490204 2002100739596     0
## 10  490204 2002080663820     0
## # ... with 2,164 more rows</code></pre>
<p>결과를 살펴보면 t20_sql 데이터의 개체가 그대로 있으면서 drug 변수가 새로 생성되었다는 것을 알 수 있다. 이를 위해 먼저 t30 데이터셋으로부터 분류코드(mcare_div_cd) 변수를 이용해 주성분 코드 ‘107501ATB’가 쓰였으면 1 아니면 0의 값을 가지는 drug 변수를 생성하여 t30_drug 데이터셋을 생성하였다. 이 데이터셋를 이용해 청구고유번호별로 drug이 1인지 0인지를 유일하게 나타내는 변수 drug을 다시 생성하였다. 이때 group_by 구문을 이용하였으며, 청구고유번호별 축약은 summarise() 문 내에서 max 함수를 이용하였다. t30 데이터셋은 청구고유번호 내에 모든 처치사항이 들어가 있으므로 중복해서 결과가 나타난다면 이를 하나로 묶어 줄 필요가 있다. 이때 1 또는 0으로 표현되는 변수를 max() 함수로 적용하면 1이 하나라도 있는 청구서는 1, 1이 하나도 없으면 0으로 표현된다. 이렇게 생성된 데이터셋을 t30_drug으로 두고 이후 left join을 이용하여 생성한 drug 변수를 t20_sql 데이터셋에 추가하였다.</p>
<p>위의 결과에서 drug 변수는 1또는 0의 값을 가지고 있다. 1이면 해당 청구서에 주성분 코드 ‘107501ATB’가 쓰였다는 것을 의미하며 0이면 쓰이지 않았다는 것을 의미한다. 이때 가져오는 데이터셋이 기준이 되는 데이터셋보다 개체가 많다 하더라도, 매칭되는 개체에만 정보가 생성되며 만약 가져오는 데이터셋의 개체가 기준이 되는 데이터셋보다 적다면, 매칭될 정보가 부족하기 때문에 그러한 경우에는 결측으로 결과가 표시된다. 또한, left join을 이용할 때도 가져오는 데이터셋에 기준변수가 중복으로 존재한다면 그 정보를 그대로 다 활용하게 된다. 따라서 변수를 붙일 때 기준변수를 기준으로 유일한 값을 생성하지 않는다면 데이터셋이 결합할 때 merge() 문과 마찬가지로 중복 정보가 발생할 수 있으니 조심해야 한다.</p>
<!-------- End ------------>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter9.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter11.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["rmanual.pdf", "rmanual.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
